{"kind":"symbol","abstract":[{"type":"text","text":"Raw data group DG2."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg2encodedidentificationfeaturesface"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg2encodedidentificationfeaturesface"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg2EncodedIdentificationFeaturesFace","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"metadata":{"roleHeading":"Instance Property","platforms":[{"beta":false,"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dg2EncodedIdentificationFeaturesFace","kind":"identifier"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg2EncodedIdentificationFeaturesFace","title":"dg2EncodedIdentificationFeaturesFace","role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","title":"Lds1eMrtdApplication","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"title":"Lds1ElementaryFile","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication/dg2EncodedIdentificationFeaturesFace":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg2EncodedIdentificationFeaturesFace","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg2encodedidentificationfeaturesface","kind":"symbol","title":"dg2EncodedIdentificationFeaturesFace","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"}],"type":"topic","abstract":[{"text":"Raw data group DG2.","type":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Result of NFC reading."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"dg2EncodedIdentificationFeaturesFace","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"DOTNLds1ElementaryFile"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg2EncodedIdentificationFeaturesFace\/title","value":"dg2EncodedIdentificationFeaturesFace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg2EncodedIdentificationFeaturesFace\/fragments","op":"replace","value":[{"text":"dg2EncodedIdentificationFeaturesFace","kind":"identifier"}]},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}