{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg3additionalidentificationfeaturefingers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg3additionalidentificationfeaturefingers"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg3AdditionalIdentificationFeatureFingers"},"abstract":[{"type":"text","text":"Raw data group DG3."}],"metadata":{"title":"dg3AdditionalIdentificationFeatureFingers","navigatorTitle":[{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg3AdditionalIdentificationFeatureFingers"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","kind":"symbol","title":"Lds1ElementaryFile","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","title":"Lds1eMrtdApplication","abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg3AdditionalIdentificationFeatureFingers":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg3additionalidentificationfeaturefingers","role":"symbol","type":"topic","title":"dg3AdditionalIdentificationFeatureFingers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg3AdditionalIdentificationFeatureFingers","abstract":[{"text":"Raw data group DG3.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dg3AdditionalIdentificationFeatureFingers","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","text":"DOTNLds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle"},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle"},{"value":"dg3AdditionalIdentificationFeatureFingers","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg3AdditionalIdentificationFeatureFingers\/title"},{"value":[{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg3AdditionalIdentificationFeatureFingers\/fragments"}]}]}