{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg7DisplayedSignatureOrUsualMark"},"variants":[{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg7displayedsignatureorusualmark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg7displayedsignatureorusualmark"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"metadata":{"platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"13.0","unavailable":false}],"title":"dg7DisplayedSignatureOrUsualMark","navigatorTitle":[{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg7DisplayedSignatureOrUsualMark","roleHeading":"Instance Property","role":"symbol"},"abstract":[{"text":"Raw data group DG7.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg7DisplayedSignatureOrUsualMark":{"title":"dg7DisplayedSignatureOrUsualMark","navigatorTitle":[{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg7DisplayedSignatureOrUsualMark","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg7DisplayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg7displayedsignatureorusualmark","abstract":[{"text":"Raw data group DG7.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"title":"TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"role":"symbol","title":"Lds1eMrtdApplication","type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"title":"Lds1ElementaryFile","url":"\/documentation\/dotnfc\/lds1elementaryfile","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"dg7DisplayedSignatureOrUsualMark","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":" * ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg7DisplayedSignatureOrUsualMark\/title","value":"dg7DisplayedSignatureOrUsualMark"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg7DisplayedSignatureOrUsualMark\/fragments","op":"replace","value":[{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}]}]}]}