{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8DataFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"dg8DataFeatures","navigatorTitle":[{"text":"dg8DataFeatures","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg8DataFeatures","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8DataFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"Raw data group DG8."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg8datafeatures"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg8datafeatures"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg8DataFeatures","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","type":"topic","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"role":"symbol","title":"Lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg8DataFeatures":{"type":"topic","title":"dg8DataFeatures","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg8DataFeatures","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8DataFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg8datafeatures","abstract":[{"type":"text","text":"Raw data group DG8."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dg8DataFeatures"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dg8DataFeatures"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dg8DataFeatures","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg8DataFeatures"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","op":"replace","value":"DOTNLds1eMrtdApplication"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","op":"replace","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle","op":"replace","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle","op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg8DataFeatures\/title","op":"replace","value":"dg8DataFeatures"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg8DataFeatures\/fragments","op":"replace","value":[{"text":"dg8DataFeatures","kind":"identifier"}]}]}]}