{"abstract":[{"type":"text","text":"Check whether "},{"code":"DotSdk","type":"codeVoice"},{"text":" library is active.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/islibraryactive(libraryid:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/isLibraryActive(libraryId:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)isLibraryActiveWithLibraryId:","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLibraryActive"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"title":"isLibraryActive(libraryId:)","role":"symbol","symbolKind":"method"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdk","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid","title":"DotLibraryId","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/isLibraryActive(libraryId:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/isLibraryActive(libraryId:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"isLibraryActive(libraryId:)","url":"\/documentation\/dotfacelite\/dotsdk\/islibraryactive(libraryid:)","abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"isLibraryActiveWithLibraryId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":") ","kind":"text"},{"text":"libraryId","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"value":"isLibraryActiveWithLibraryId:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1isLibraryActive(libraryId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1isLibraryActive(libraryId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"op":"replace"}]}]}