{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreset\/photo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreset\/photo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/photo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Outputs low resolution video frames and enables high resolution photo capture. Exact resolution differs between devices."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"title":"CameraPreset.photo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotDocument@E@DOTDCameraPreset@DOTDCameraPresetPhoto","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/photo":{"role":"symbol","title":"CameraPreset.photo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"abstract":[{"type":"text","text":"Outputs low resolution video frames and enables high resolution photo capture. Exact resolution differs between devices."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/photo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}],"url":"\/documentation\/dotdocument\/camerapreset\/photo"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset":{"role":"symbol","title":"CameraPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}],"url":"\/documentation\/dotdocument\/camerapreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDCameraPresetPhoto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1photo\/title","value":"DOTDCameraPresetPhoto"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1photo\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}