{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC12InitializingC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"title":"FingersAutoCaptureUiState.Initializing","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Initializing"}],"symbolKind":"class","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/hash"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingersAutoCaptureUiStateInitializing) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"This state is active right after the component is created for a short period of time.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Initializing state."}],"references":{"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing/isEqual(_:)":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/isEqual(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/isequal(_:)","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Initializing","kind":"identifier"}],"title":"FingersAutoCaptureUiState.Initializing","navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing","kind":"symbol","abstract":[{"type":"text","text":"Initializing state."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"kind":"symbol","title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing/description":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/description","kind":"symbol","abstract":[]},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing/hash":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hash","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/hash","kind":"symbol","abstract":[]},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureUiState","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}