{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lds1eMrtdApplication","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1eMrtdApplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile(im)initWithLds1eMrtdApplication:","platforms":[{"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iOS","deprecated":false}],"symbolKind":"init","navigatorTitle":[{"text":"initWithLds1eMrtdApplication:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol","title":"init(lds1eMrtdApplication:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lds1eMrtdApplication","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","kind":"typeIdentifier","text":"Lds1eMrtdApplication"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/init(lds1eMrtdApplication:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/init(lds1emrtdapplication:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/init(lds1emrtdapplication:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"role":"symbol","type":"topic","title":"TravelDocument","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication","kind":"symbol","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"role":"symbol","title":"Lds1eMrtdApplication","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}]},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","url":"\/documentation\/dotnfc\/ldsmasterfile","title":"LdsMasterFile","abstract":[{"text":"Raw represenation of the whole content stored in the NFC chip of the travel document.","type":"text"}],"navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LdsMasterFile","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile/init(lds1eMrtdApplication:)":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/init(lds1emrtdapplication:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lds1eMrtdApplication"},{"kind":"text","text":": "},{"text":"Lds1eMrtdApplication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithLds1eMrtdApplication:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"init(lds1eMrtdApplication:)","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/init(lds1eMrtdApplication:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithLds1eMrtdApplication:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLds1eMrtdApplication:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithLds1eMrtdApplication:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTNLds1eMrtdApplication","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"lds1eMrtdApplication","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","op":"replace","value":"DOTNLds1eMrtdApplication"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","op":"replace","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"op":"replace","value":"DOTNLdsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}]},{"value":"initWithLds1eMrtdApplication:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1init(lds1eMrtdApplication:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1init(lds1eMrtdApplication:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLds1eMrtdApplication:"}]}]}]}