{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/getLibrary(libraryId:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"title":"getLibrary(libraryId:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"?","kind":"text"}],"externalID":"s:6DotNfc0A3SdkC10getLibrary9libraryIdAA0aE0_pSgAA0aeG0O_tF"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/getlibrary(libraryid:)"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk":{"type":"topic","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdk","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"title":"DotSdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibraryId","title":"DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"url":"\/documentation\/dotnfc\/dotlibraryid"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/getLibrary(libraryId:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/getLibrary(libraryId:)","kind":"symbol","url":"\/documentation\/dotnfc\/dotsdk\/getlibrary(libraryid:)","title":"getLibrary(libraryId:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary"},{"text":"?","kind":"text"}],"abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"kind":"symbol","role":"symbol","abstract":[],"title":"DotLibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"url":"\/documentation\/dotnfc\/dotlibrary"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}