{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"corners","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/corners"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/corners","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corners","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}],"role":"symbol","externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC7cornersSayAA07WrappeddeF6CornerCGvp","modules":[{"name":"DotFaceCore"}],"title":"corners","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"Array of corners which will be used for eye gaze liveness. Minimum allowed size of the array is equal to ","type":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/minValidSamplesCount","type":"reference","isActive":true},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"role":"symbol","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"code":"EyeGazeLivenessCorner","type":"codeVoice"},{"type":"text","text":"."}],"title":"WrappedEyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedEyeGazeLivenessCorner"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"title":"EyeGazeLivenessViewController","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"EyeGazeLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","type":"topic","abstract":[{"text":"Configuration options for the eye gaze liveness process.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/minValidSamplesCount":{"abstract":[{"type":"text","text":"Minimum number of valid samples (images) required to finish the process. Allowed value is from interval  [4, 7].  Default value is "},{"code":"4","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minValidSamplesCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/minvalidsamplescount","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/minValidSamplesCount","kind":"symbol","title":"minValidSamplesCount"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/corners":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"corners","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/corners","role":"symbol","abstract":[{"type":"text","text":"Array of corners which will be used for eye gaze liveness. Minimum allowed size of the array is equal to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/minValidSamplesCount"},{"type":"text","text":"."}],"title":"corners","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/corners","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFWrappedEyeGazeLivenessCorner","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController","op":"replace"},{"value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}