{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":" = Defaults.faceSizeRatioInterval, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"transitionDurationMillis"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = Defaults.transitionDurationMillis, ","kind":"text"},{"text":"transitionType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","text":"TransitionType"},{"kind":"text","text":" = Defaults.transitionType, "},{"text":"corners","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner"},{"text":"], ","kind":"text"},{"text":"minValidSamplesCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.minValidSamplesCount, "},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil, ","kind":"text"},{"text":"objectImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" = Defaults.objectImageSize, ","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"typeIdentifier"},{"kind":"text","text":" = .init()) "},{"kind":"keyword","text":"throws"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":", "},{"text":"transitionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"transitionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionType","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidSamplesCount"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"objectImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"symbolKind":"init","title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:)","externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC12sessionToken21faceSizeRatioInterval14isTorchEnabled12cameraFacing24transitionDurationMillis0U4Type7corners20minValidSamplesCount11objectImage011objectImageM05queryAESSSg_AA0O6DoubleCSbAA06CameraT0OSiAE010TransitionX0OSayAA07WrappeddeF6CornerCGSiSo7UIImageCSgSo6CGSizeVAA0B14DetectionQueryCtKcfc","role":"symbol","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"title":"WrappedEyeGazeLivenessCorner","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedEyeGazeLivenessCorner"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:)":{"title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:)","abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"text":"transitionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"transitionType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","kind":"typeIdentifier","text":"TransitionType"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner"},{"text":"], ","kind":"text"},{"text":"minValidSamplesCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectImage"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"text":"objectImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:)","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/TransitionType-swift.enum":{"title":"EyeGazeLivenessViewController.Configuration.TransitionType","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.enum","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TransitionType"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionType"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","title":"IntervalDouble","type":"topic","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","title":"EyeGazeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"type":"topic","title":"FaceDetectionQuery","navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","kind":"symbol","title":"EyeGazeLivenessViewController.Configuration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","type":"topic","kind":"symbol","title":"CameraFacing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFWrappedEyeGazeLivenessCorner","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}],"op":"replace"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}