{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(common:camera:facelibrarycomponent:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:)"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(common:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Initializer","platforms":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","text":"FaceLibraryComponentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transitionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","text":"TransitionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidSamplesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"objectImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","symbolKind":"init","externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC6common6camera20faceLibraryComponent24transitionDurationMillis0O4Type7corners20minValidSamplesCount11objectImage0xY4SizeAE0aC006CommonI0C_0A7Capture06CameraI0CAA0bmnI0CSiAE010TransitionR0OSayAA07WrappeddeF6CornerCGSiSo7UIImageCSgSo6CGSizeVtKcfc","title":"init(common:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:)","modules":[{"name":"DotFaceCore"}]},"abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":" = .init(facing: .front), ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"text":" = try! .init(\n                faceSizeRatioInterval: Defaults.faceSizeRatioInterval,\n                query: .init()\n            ), ","kind":"text"},{"text":"transitionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = Defaults.transitionDurationMillis, ","kind":"text"},{"text":"transitionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionType","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"text":" = Defaults.transitionType, ","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"], ","kind":"text"},{"text":"minValidSamplesCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = Defaults.minValidSamplesCount, ","kind":"text"},{"text":"objectImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil, ","kind":"text"},{"text":"objectImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" = Defaults.objectImageSize) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"role":"symbol","title":"FaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","navigatorTitle":[{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration for face library components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","deprecated":true,"type":"topic","title":"EyeGazeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI Eye Gaze Liveness component.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"deprecated":true,"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","type":"topic","title":"EyeGazeLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/TransitionType-swift.enum":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.enum","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"title":"EyeGazeLivenessViewController.Configuration.TransitionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionType"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionType"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"title":"WrappedEyeGazeLivenessCorner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/init(common:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":", ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"text":", ","kind":"text"},{"text":"transitionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"transitionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionType","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"], ","kind":"text"},{"text":"minValidSamplesCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"objectImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"objectImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"deprecated":true,"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(common:camera:facelibrarycomponent:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:)","title":"init(common:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:)","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(common:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:)"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"kind":"symbol","title":"CameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","op":"replace","value":"DOTFFaceLibraryComponentConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","op":"replace","value":"DOTFEyeGazeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","op":"replace","value":"DOTFWrappedEyeGazeLivenessCorner"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]}]}]}