{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat","text":"WrappedFloat"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxdevicepitchangle"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Maximal pitch angle of the device."},{"type":"text","text":" "},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat"},{"kind":"text","text":"?"}],"title":"maxDevicePitchAngle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceLite0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC19maxDevicePitchAngleAA12WrappedFloatCSgvp","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/maxDevicePitchAngle":{"role":"symbol","title":"maxDevicePitchAngle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maximal pitch angle of the device."},{"type":"text","text":" "},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxdevicepitchangle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat":{"role":"symbol","title":"WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"url":"\/documentation\/dotfacelite\/wrappedfloat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureConfiguration\/title","value":"DOTFLFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}