{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/imageformat\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"title":"hashValue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DOTImageFormat","symbolKind":"property","extendedModule":"Swift","modules":[{"name":"DotFingersCore","relatedModules":["Swift"]}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/hashValue","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat":{"kind":"symbol","title":"ImageFormat","url":"\/documentation\/dotfingerscore\/imageformat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/hashValue":{"type":"topic","kind":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hashValue","url":"\/documentation\/dotfingerscore\/imageformat\/hashvalue","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/hashValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/title"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/navigatorTitle"}]}]}