{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)"]}],"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detection17expressionNeutral20backgroundUniformity15eyeGazeLiveness07passiveN012verificationAeA0ac15DetectionModuleE0C_AA0ac10ExpressionirE0CSgAA0ac10BackgroundkrE0CSgAA0ac3EyemnrE0CSgAA0ac7PassivenrE0CSgAA0ac12VerificationrE0CSgtcfc","title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"expressionNeutral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"verification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"?)","kind":"text"}]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"kind":"symbol","role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}]},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","title":"DotFacePassiveLivenessModuleConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face passive liveness module."}],"role":"symbol","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"title":"DotFaceEyeGazeLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Face library configuration."}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLibraryConfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection module configuration."}],"role":"symbol","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration":{"kind":"symbol","role":"symbol","title":"DotFaceBackgroundUniformityModuleConfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceVerificationModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"expressionNeutral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"verification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face expression neutral module."}],"url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotFacePassiveLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle"},{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle"},{"value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"},{"value":"DotFaceVerificationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/navigatorTitle"},{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}