{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/origin"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"origin","kind":"identifier"}],"extendedModule":"DotCore","role":"symbol","title":"origin","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)origin","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"symbolKind":"property","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"origin"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier","text":"PointInt","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/rectangleint\/origin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangleint\/origin"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/RectangleInt":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","url":"\/documentation\/dotdocument\/rectangleint","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"type":"topic","kind":"symbol","role":"symbol","title":"RectangleInt"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/origin":{"navigatorTitle":[{"text":"origin","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangleint\/origin","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/origin","title":"origin","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/PointInt":{"kind":"symbol","title":"PointInt","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotdocument\/pointint","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"origin","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"origin","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt","text":"DOTPointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"},{"kind":"text","text":" * "},{"kind":"identifier","text":"origin"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/title","value":"DOTRectangleInt","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1origin\/title","value":"origin","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1origin\/fragments","value":[{"text":"origin","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/title","value":"DOTPointInt","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/fragments","value":[{"text":"DOTPointInt","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/navigatorTitle","value":[{"text":"DOTPointInt","kind":"identifier"}],"op":"replace"}]}]}