{"metadata":{"role":"symbol","externalID":"c:@CM@DotDocument@objc(cs)DOTPointDouble(cm)fromCgPoint:","modules":[{"name":"DotDocument"}],"extendedModule":"DotDocument","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble"}],"title":"from(cgPoint:)","roleHeading":"Type Method"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/from(cgPoint:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointdouble\/from(cgpoint:)"]},{"paths":["\/documentation\/dotdocument\/pointdouble\/from(cgpoint:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/from(cgPoint:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":") -> ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/pointdouble\/from(cgpoint:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/from(cgPoint:)","role":"symbol","title":"from(cgPoint:)","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"type":"topic","title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fromCgPoint:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTPointDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},{"kind":"text","text":" *) "},{"text":"fromCgPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") "},{"text":"cgPoint","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"fromCgPoint:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1from(cgPoint:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1from(cgPoint:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments"}]}]}