{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper\/traveldocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper\/traveldocumenttype"]}],"metadata":{"role":"symbol","title":"travelDocumentType","symbolKind":"property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper(py)travelDocumentType","roleHeading":"Instance Property","navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","kind":"typeIdentifier","text":"TravelDocumentType"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/travelDocumentType"},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper/travelDocumentType":{"title":"travelDocumentType","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/travelDocumentType","url":"\/documentation\/dotnfc\/traveldocumenttypewrapper\/traveldocumenttype","role":"symbol","navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","kind":"typeIdentifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"kind":"symbol","title":"TravelDocumentType","url":"\/documentation\/dotnfc\/traveldocumenttype","type":"topic","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotnfc\/traveldocumenttypewrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"TravelDocumentType"},{"text":" for Objective-C support.","type":"text"}],"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"kind":"symbol","title":"TravelDocumentTypeWrapper","role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"travelDocumentType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"travelDocumentType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","text":"DOTTravelDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1travelDocumentType\/title","value":"travelDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1travelDocumentType\/fragments","value":[{"kind":"identifier","text":"travelDocumentType"}],"op":"replace"},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title","op":"replace"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments","op":"replace"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/navigatorTitle","op":"replace"},{"value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/title","op":"replace"},{"value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/fragments","op":"replace"},{"value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}