{"sections":[],"metadata":{"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC12cameraFacing0A6Camera0lK0Ovp","symbolKind":"property","title":"cameraFacing","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"code":".front","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","role":"symbol","type":"topic","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the MagnifEye liveness process.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"MagnifEyeLivenessViewController.Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/cameraFacing":{"role":"symbol","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraFacing","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerafacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing"}],"title":"cameraFacing","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"kind":"symbol","type":"topic","title":"CameraFacing","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacelite\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"}]}]}