{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camera"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Default is:"}],"type":"paragraph"},{"syntax":null,"code":[".init(cameraFacing: .front)"],"type":"codeListing"}],"kind":"content"}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"camera","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"roleHeading":"Instance Property","platforms":[],"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC6camera0A7Capture06CameraI0Cvp","modules":[{"name":"DotFaceLite"}]},"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/camera","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/camera":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camera","title":"camera","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/camera","deprecated":true,"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","title":"MagnifEyeLivenessViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"role":"symbol","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","role":"symbol","url":"\/documentation\/dotfacelite\/cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"title":"MagnifEyeLivenessViewController","deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTFLMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace"}]}]}