{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"code":".fit","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"metadata":{"title":"cameraPreviewScaleType","externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC22cameraPreviewScaleType0A6Camera0nklM0Ovp","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"modules":[{"name":"DotFaceLite"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraPreviewScaleType","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerapreviewscaletype"]}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","type":"topic","title":"MagnifEyeLivenessViewController.Configuration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/cameraPreviewScaleType":{"title":"cameraPreviewScaleType","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerapreviewscaletype","abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraPreviewScaleType","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","type":"topic","title":"MagnifEyeLivenessViewController","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"kind":"symbol","type":"topic","title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}