{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Common configuration for all UI components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"type":"text","text":"."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/common"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/common","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"CommonConfiguration"}],"platforms":[{"deprecated":true,"beta":false,"unavailable":false,"message":"Use MultiRangeLivenessViewController instead."}],"title":"common","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC6common0A4Core06CommonI0Cvp","roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"type":"text","text":"Common configuration for all components."}],"url":"\/documentation\/dotfacelite\/commonconfiguration","title":"CommonConfiguration","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/common":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/common","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/common","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"}],"deprecated":true,"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"code":".init()","type":"codeVoice"},{"type":"text","text":"."}],"title":"common"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","deprecated":true,"title":"MagnifEyeLivenessViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}