{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC12sessionToken23isDetectionLayerVisible0L12TorchEnabled0l12VideoCaptureQ012cameraFacing0T16PreviewScaleTypeAESSSg_S3b0A6Camera0yU0OAM0yvwX0Otcfc","title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","symbolKind":"init"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = Defaults.isVideoCaptureEnabled, "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":" = Defaults.cameraPreviewScaleType)","kind":"text"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"kind":"symbol","type":"topic","title":"CameraFacing","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacelite\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)":{"role":"symbol","abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","role":"symbol","type":"topic","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"type":"topic","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the MagnifEye liveness process.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"MagnifEyeLivenessViewController.Configuration"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}