{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose"]]},"metadata":{"roleHeading":"Instance Property","title":"roll","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HeadPoseAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"roll","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose(py)roll","role":"symbol"},"abstract":[{"text":"Head pose roll.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/roll"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HeadPoseAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/headpose\/roll"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/headpose\/roll"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headpose","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"type":"topic","title":"HeadPose","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/headposeattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","title":"HeadPoseAttribute","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose/roll":{"title":"roll","navigatorTitle":[{"text":"roll","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headpose\/roll","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/roll","kind":"symbol","role":"symbol","abstract":[{"text":"Head pose roll.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roll","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"roll","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"roll"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFHeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"roll","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle"},{"op":"replace","value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"op":"replace","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle"},{"op":"replace","value":"roll","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1roll\/title"},{"op":"replace","value":[{"text":"roll","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1roll\/fragments"}]}]}