{"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC04baseH023isDetectionLayerVisible11placeholderAeA04BasebdefG0CADC_Sb0aB7Commons11PlaceholderCtcfc","roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","text":"Configuration","preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","text":"Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"kind":"text","text":" = .Visible())"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","type":"topic","title":"BaseFaceAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Face Auto Capture component."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","type":"topic","title":"BaseFaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","role":"symbol","type":"topic","title":"Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholder","abstract":[{"text":"Placeholder.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/init(baseConfiguration:isDetectionLayerVisible:placeholder:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"text":".","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Placeholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"value":"DOTPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title"},{"value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments"},{"value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle"},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle"}]}]}