{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"ImageParameters"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/imageparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/imageparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/imageParameters","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image parameters calculated in the area defined by the placeholder (Document Auto Capture UI component) or"},{"type":"text","text":" "},{"type":"text","text":"by the "},{"type":"codeVoice","code":"DocumentAutoCaptureControllerConfiguration.imageParametersNormalizedRectangle"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}],"title":"imageParameters","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(py)imageParameters","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"imageParameters"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParameters":{"role":"symbol","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotdocument\/imageparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection":{"role":"symbol","title":"DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/imageParameters":{"role":"symbol","title":"imageParameters","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}],"abstract":[{"type":"text","text":"Image parameters calculated in the area defined by the placeholder (Document Auto Capture UI component) or"},{"type":"text","text":" "},{"type":"text","text":"by the "},{"type":"codeVoice","code":"DocumentAutoCaptureControllerConfiguration.imageParametersNormalizedRectangle"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/imageParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageParameters"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection\/imageparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageParameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageParameters"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"DOTDImageParameters"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageParameters"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTDImageParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1imageParameters\/title","value":"imageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1imageParameters\/fragments","value":[{"kind":"identifier","text":"imageParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}