{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone","text":"MachineReadableZone"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/machinereadablezone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/machineReadableZone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Result of MRZ reading."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?"}],"title":"machineReadableZone","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(py)machineReadableZone","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"role":"symbol","title":"MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection":{"role":"symbol","title":"DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/machineReadableZone":{"role":"symbol","title":"machineReadableZone","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Result of MRZ reading."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/machineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection\/machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"machineReadableZone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"machineReadableZone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone","text":"DOTDMachineReadableZone"},{"kind":"text","text":" * "},{"kind":"identifier","text":"machineReadableZone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTDMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDMachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1machineReadableZone\/title","value":"machineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1machineReadableZone\/fragments","value":[{"kind":"identifier","text":"machineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}