{"metadata":{"title":"travelDocumentType","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(py)travelDocumentType"},"kind":"symbol","abstract":[{"text":"Resolved travel document type.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/traveldocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/traveldocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/travelDocumentType","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"text":" for Objective-C support.","type":"text"}],"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"kind":"symbol","title":"TravelDocumentTypeWrapper","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"url":"\/documentation\/dotdocument\/documentautocapturedetection","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"title":"DocumentAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection/travelDocumentType":{"kind":"symbol","title":"travelDocumentType","navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/travelDocumentType","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection\/traveldocumenttype","abstract":[{"text":"Resolved travel document type.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"travelDocumentType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"travelDocumentType"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper","text":"DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace","value":"DOTTravelDocumentTypeWrapper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/navigatorTitle","op":"replace","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","op":"replace","value":"DOTDDocumentAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1travelDocumentType\/title","op":"replace","value":"travelDocumentType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1travelDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"travelDocumentType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}