{"abstract":[{"type":"text","text":"Bottom edge."}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/bottom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/bottom"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"bottom","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"bottom"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)bottom","role":"symbol","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/bottom"},"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble/bottom":{"role":"symbol","abstract":[{"type":"text","text":"Bottom edge."}],"title":"bottom","url":"\/documentation\/dotdocument\/rectangledouble\/bottom","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/bottom","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bottom"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottom"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1bottom\/title","op":"replace","value":"bottom"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1bottom\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottom"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}