{"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)height","navigatorTitle":[{"kind":"identifier","text":"height"}],"roleHeading":"Instance Property","title":"height","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/rectangledouble\/height"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/rectangledouble\/height"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/height"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble/height":{"role":"symbol","abstract":[],"title":"height","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/height","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/rectangledouble\/height","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotDocument","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"height"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1height\/title","value":"height"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1height\/fragments","value":[{"kind":"identifier","text":"height"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}