{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"extendedModule":"DotCore","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"symbolKind":"method","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(im)rebasedWithParentRectangle:","roleHeading":"Instance Method","title":"rebased(parentRectangle:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/rebased(parentRectangle:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble/rebased(parentRectangle:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/rebased(parentRectangle:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"url":"\/documentation\/dotdocument\/rectangledouble\/rebased(parentrectangle:)","title":"rebased(parentRectangle:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"rebasedWithParentRectangle:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":" *) ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":" *) ","kind":"text"},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","op":"replace"},{"value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1rebased(parentRectangle:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1rebased(parentRectangle:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}