{"kind":"symbol","metadata":{"title":"dateOfBirth","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZonePassword(py)dateOfBirth","roleHeading":"Instance Property","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfBirth"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Date of birth from Machine Readable Zone."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/dateofbirth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/dateofbirth"]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","title":"NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"type":"topic","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/dateOfBirth":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfBirth","role":"symbol","title":"dateOfBirth","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/dateofbirth","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Date of birth from Machine Readable Zone."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dateOfBirth","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"},{"value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfBirth\/title","op":"replace","value":"dateOfBirth"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfBirth\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}]}]}]}