{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration"]]},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification"]}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"title":"DotFaceLibraryConfiguration.Modules","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"symbolKind":"class","role":"symbol"},"abstract":[{"text":"Face library module configuration.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFaceLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/verification":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/verification","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"?","kind":"text"}],"title":"verification","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/backgroundUniformity":{"role":"symbol","title":"backgroundUniformity","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/passiveLiveness":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"title":"passiveLiveness","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detection","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"title":"eyeGazeLiveness","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/expressionNeutral":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"expressionNeutral","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/detection":{"kind":"symbol","title":"detection","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"}]}]}