{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.property"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Module configuration."}],"metadata":{"title":"modules","navigatorTitle":[{"text":"modules","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(py)modules","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/modules-swift.property"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/modules-swift.property":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.property","abstract":[{"type":"text","text":"Module configuration."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"title":"modules","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/modules-swift.property"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"role":"symbol","title":"DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"modules","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","text":"DotFaceLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration~1modules-swift.property\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","value":[{"text":"modules","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}