{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class\/BaseDefaults"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class\/basedefaults"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"]]},"metadata":{"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDefaults","kind":"identifier"}],"title":"FingersAutoCaptureViewController.Configuration.BaseDefaults","externalID":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC12BaseDefaultsa","modules":[{"name":"DotFingersCore"}],"roleHeading":"Type Alias","role":"symbol","navigatorTitle":[{"text":"BaseDefaults","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDefaults","kind":"identifier"},{"text":" = ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults","text":"Defaults","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureViewController","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"navigatorTitle":[{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI Fingers Auto Capture component."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class","title":"FingersAutoCaptureViewController.Configuration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/Defaults":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/defaults","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults","title":"BaseFingersAutoCaptureViewController.Configuration.Defaults","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing fingers images with customizable UI.","type":"text"}],"title":"BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class/BaseDefaults":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class\/BaseDefaults","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDefaults","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureViewController.Configuration.BaseDefaults","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"BaseDefaults"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class\/basedefaults"}},"variantOverrides":[{"patch":[{"value":"DOTFGFingersAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title"},{"value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle"},{"value":"DOTFGBaseFingersAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}