{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/previewscaletype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/previewscaletype"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/previewScaleType","interfaceLanguage":"swift"},"abstract":[{"text":"Preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"previewScaleType"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)previewScaleType","title":"previewScaleType","symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/previewScaleType":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"previewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/previewScaleType","url":"\/documentation\/dotfacecore\/cameraconfiguration\/previewscaletype","title":"previewScaleType","abstract":[{"type":"text","text":"Preview scale type. Default is "},{"type":"codeVoice","code":".fit"},{"type":"text","text":"."}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","type":"topic","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"url":"\/documentation\/dotfacecore\/camerapreviewscaletype","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"previewScaleType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"previewScaleType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1previewScaleType\/title","value":"previewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1previewScaleType\/fragments","value":[{"kind":"identifier","text":"previewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]}]}]}