{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/description","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"description","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/description"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"AutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/description":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/description","kind":"symbol","title":"description"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1description\/fragments"}]}]}