{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/hash"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/hash"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC4IdleC4hashSivp","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"title":"hash","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle":{"abstract":[{"type":"text","text":"Idle state."}],"navigatorTitle":[{"kind":"identifier","text":"Idle"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Idle"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle","title":"FaceAutoCaptureUiState.Idle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle/hash":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/hash","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/hash","title":"hash","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate","title":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","op":"replace","value":"DOTFFaceAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceAutoCaptureUiState","kind":"identifier"}]}]}]}