{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/helpAnchor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/templatematcher\/error\/helpanchor"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"metadata":{"title":"helpAnchor","modules":[{"name":"DotFaceCore","relatedModules":["Foundation"]}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"10.10","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:11DotFaceCore15TemplateMatcherC5ErrorO","roleHeading":"Instance Property","extendedModule":"Foundation","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/LocalizedError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateMatcher"}],"abstract":[{"type":"text","text":"Stateless class which can match templates."}],"title":"TemplateMatcher","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/LocalizedError-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/LocalizedError-Implementations","abstract":[],"type":"topic","title":"LocalizedError Implementations","url":"\/documentation\/dotfacecore\/templatematcher\/error\/localizederror-implementations","kind":"article","role":"collectionGroup"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"Matching errors."}],"url":"\/documentation\/dotfacecore\/templatematcher\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","type":"topic","title":"TemplateMatcher.Error","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/helpAnchor":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/helpAnchor","title":"helpAnchor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacecore\/templatematcher\/error\/helpanchor","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","op":"replace","value":"DOTFTemplateMatcher"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/navigatorTitle","op":"replace","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]}]}]}