{"kind":"symbol","metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"generateWithCount:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessCornersGenerator(im)generateWithCount:","title":"generate(count:)","required":true,"modules":[{"name":"DotFaceCore"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> [","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator\/generate(count:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator\/generate(count:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator\/generate(count:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCornersGenerator":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}],"title":"EyeGazeLivenessCornersGenerator","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator","abstract":[{"type":"text","text":"Generates corners for the eye gaze liveness process."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCornersGenerator/generate(count:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator\/generate(count:)","title":"generate(count:)","url":"\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator\/generate(count:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"generateWithCount:"}],"required":true},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"title":"WrappedEyeGazeLivenessCorner","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"code":"EyeGazeLivenessCorner","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"generateWithCount:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateWithCount:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateWithCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFEyeGazeLivenessCornersGenerator","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/title"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/fragments"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/navigatorTitle"},{"value":"generateWithCount:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator~1generate(count:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"generateWithCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator~1generate(count:)\/fragments"},{"value":"DOTFWrappedEyeGazeLivenessCorner","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title"},{"value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments"},{"value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}