{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration\/init"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration\/init","interfaceLanguage":"occ"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersTransformationModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration","type":"topic","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration","kind":"symbol","title":"DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersTransformationModuleConfiguration/init":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration\/init","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration\/init","kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle"}]}]}