{"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"evaluateLeftEye","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery(py)evaluateLeftEye","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateLeftEye","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"evaluateLeftEye","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateLeftEye","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Left eye evaluation flag."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/evaluatelefteye"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/evaluatelefteye"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateLeftEye","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"kind":"symbol","title":"EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpressionQuery"}],"type":"topic","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.15.0"}],"title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/evaluateLeftEye":{"title":"evaluateLeftEye","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/eyesexpressionquery\/evaluatelefteye","abstract":[{"type":"text","text":"Left eye evaluation flag."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateLeftEye","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"evaluateLeftEye"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateLeftEye"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"evaluateLeftEye","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"evaluateLeftEye","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateLeftEye"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTFEyesExpressionQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateLeftEye\/title","value":"evaluateLeftEye","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateLeftEye\/fragments","value":[{"text":"evaluateLeftEye","kind":"identifier"}]}]}]}