{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateRightEye"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/evaluaterighteye"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/evaluaterighteye"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateRightEye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"title":"evaluateRightEye","navigatorTitle":[{"kind":"identifier","text":"evaluateRightEye"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery(py)evaluateRightEye","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateRightEye"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","abstract":[{"type":"text","text":"Right eye evaluation flag."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery/evaluateRightEye":{"url":"\/documentation\/dotfacecore\/eyesexpressionquery\/evaluaterighteye","abstract":[{"text":"Right eye evaluation flag.","type":"text"}],"title":"evaluateRightEye","navigatorTitle":[{"text":"evaluateRightEye","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateRightEye","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateRightEye"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpressionQuery"}],"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/eyesexpressionquery","title":"EyesExpressionQuery"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"evaluateRightEye"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"evaluateRightEye"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateRightEye"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateRightEye\/title","value":"evaluateRightEye"},{"op":"replace","value":[{"kind":"identifier","text":"evaluateRightEye"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateRightEye\/fragments"},{"value":"DOTFEyesExpressionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace"}]}]}