{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init(evaluateRightEye:evaluateLeftEye:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"evaluateRightEye","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"evaluateLeftEye","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery"]]},"metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery(im)initWithEvaluateRightEye:evaluateLeftEye:","title":"init(evaluateRightEye:evaluateLeftEye:)","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithEvaluateRightEye:evaluateLeftEye:"}],"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"evaluateRightEye","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateLeftEye","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/init(evaluaterighteye:evaluatelefteye:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyesexpressionquery\/init(evaluaterighteye:evaluatelefteye:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/init(evaluateRightEye:evaluateLeftEye:)":{"abstract":[],"title":"init(evaluateRightEye:evaluateLeftEye:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init(evaluateRightEye:evaluateLeftEye:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"evaluateRightEye","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateLeftEye","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery\/init(evaluaterighteye:evaluatelefteye:)","role":"symbol","navigatorTitle":[{"text":"initWithEvaluateRightEye:evaluateLeftEye:","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","kind":"symbol","title":"EyesExpressionQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithEvaluateRightEye:evaluateLeftEye:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithEvaluateRightEye:evaluateLeftEye:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEvaluateRightEye:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluateRightEye"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateLeftEye:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluateLeftEye"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init(evaluateRightEye:evaluateLeftEye:)\/title","op":"replace","value":"initWithEvaluateRightEye:evaluateLeftEye:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init(evaluateRightEye:evaluateLeftEye:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvaluateRightEye:evaluateLeftEye:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace","value":"DOTFEyesExpressionQuery"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}