{"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/init()"]}],"metadata":{"title":"init()","externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator(im)init","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init()"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/init()","kind":"symbol","title":"init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init()","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"abstract":[{"text":"Validate size of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","kind":"symbol","type":"topic","title":"SizeTooSmallValidator"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"init","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init()\/fragments"},{"op":"replace","value":"DOTDSizeTooSmallValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}