{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"init(common:camera:challengeSequence:isDetectionLayerVisible:)","symbolKind":"init","externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC6common6camera17challengeSequence23isDetectionLayerVisibleAE0A4Core06CommonI0C_0A7Capture06CameraI0CSay0aB7Commons0deF13ChallengeItemO7WrappedCGSbtKcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challengeSequence"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","role":"symbol"},"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/init(common:camera:challengesequence:isdetectionlayervisible:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(common:camera:challengeSequence:isDetectionLayerVisible:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"},{"kind":"text","text":" = .init(facing: .front), "},{"kind":"externalParam","text":"challengeSequence"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"title":"MultiRangeLivenessViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"title":"MultiRangeLivenessChallengeItem","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"url":"\/documentation\/dotfacelite\/commonconfiguration","type":"topic","abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","role":"symbol","title":"CommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped":{"title":"MultiRangeLivenessChallengeItem.Wrapped","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","role":"symbol","type":"topic","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"text":".","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","url":"\/documentation\/dotfacelite\/cameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/init(common:camera:challengeSequence:isDetectionLayerVisible:)":{"kind":"symbol","abstract":[{"text":"Create the Multi-Range Liveness configuration.","type":"text"}],"title":"init(common:camera:challengeSequence:isDetectionLayerVisible:)","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/init(common:camera:challengesequence:isdetectionlayervisible:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(common:camera:challengeSequence:isDetectionLayerVisible:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"challengeSequence","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"role":"symbol","title":"MultiRangeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]}]}]}