{"kind":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/initwithcommon:camera:autocapture:facelibrarycomponent:qualityattributethresholds:capturemode:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:"}],"title":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"DOTAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"autoCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","text":"DOTFFaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLibraryComponent"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"captureMode"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"abstract":[{"type":"text","text":"Configuration for face library components."}],"type":"topic","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","title":"FaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","abstract":[{"type":"text","text":"Common configuration for all components."}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/autocaptureconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","title":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"text":"Capture mode.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/capturemode","title":"CaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration/initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:"}],"url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/initwithcommon:camera:autocapture:facelibrarycomponent:qualityattributethresholds:capturemode:","title":"initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:","abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"type":"topic","role":"symbol","title":"CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","fragments":[{"text":"DOTFBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic","role":"symbol","title":"DOTFBaseFaceAutoCaptureConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTFFaceAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}