{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","externalID":"s:7DotCore0A3SdkC5ErrorO19failedToLoadLibraryyAeA0aH2IdO_tcAEmF","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"},{"text":")","kind":"text"}],"roleHeading":"Case","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadlibrary(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","url":"\/documentation\/dotdocument\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/failedToLoadLibrary(libraryId:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","role":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadlibrary(libraryid:)","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotSdk":{"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","type":"topic","url":"\/documentation\/dotdocument\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"title":"DotSdk","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdk\/error","title":"DotSdk.Error","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}