{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/init(minconfidencethreshold:)"]},{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/init(minconfidencethreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init(minConfidenceThreshold:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(minConfidenceThreshold:)","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentNotDetectedValidator(im)initWithMinConfidenceThreshold:error:","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init"},"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/init(minConfidenceThreshold:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","title":"init(minConfidenceThreshold:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init(minConfidenceThreshold:)","navigatorTitle":[{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/init(minconfidencethreshold:)"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","title":"DocumentNotDetectedValidator","abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentNotDetectedValidator"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithMinConfidenceThreshold:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinConfidenceThreshold:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minConfidenceThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithMinConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init(minConfidenceThreshold:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init(minConfidenceThreshold:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"value":"DOTDDocumentNotDetectedValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}