{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError","doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/s5ErrorP","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/s8SendableP","doc:\/\/DotFingersCore\/s16SendableMetatypeP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/intervalfloat\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"s:7DotCore13IntervalFloatC5ErrorO","title":"IntervalFloat.Error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/invalidBounds"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/errorMessage","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/internalError"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/DotSdkError-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/Error-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/error-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/Error-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkError":{"kind":"symbol","title":"DotSdkError","url":"\/documentation\/dotfingerscore\/dotsdkerror","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error":{"role":"symbol","title":"IntervalFloat.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error","kind":"symbol"},"doc://DotFingersCore/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/errorMessage":{"title":"errorMessage","kind":"symbol","url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/errormessage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/errorMessage"},"doc://DotFingersCore/s16SendableMetatypeP":{"identifier":"doc:\/\/DotFingersCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/DotSdkError-Implementations":{"role":"collectionGroup","title":"DotSdkError Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/dotsdkerror-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/DotSdkError-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/localizederror-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/LocalizedError-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/internalError":{"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/internalerror","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"title":"internalError","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/internalError"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/equatable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/Equatable-Implementations","kind":"article"},"doc://DotFingersCore/s5ErrorP":{"identifier":"doc:\/\/DotFingersCore\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/invalidBounds":{"type":"topic","kind":"symbol","title":"IntervalFloat.Error.invalidBounds","url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/invalidbounds","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidBounds","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/invalidBounds"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/s8SendableP":{"identifier":"doc:\/\/DotFingersCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat":{"role":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfingerscore\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/fragments"},{"op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/navigatorTitle"}]}]}