{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/bottomleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/bottomleft"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomLeft"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition(py)bottomLeft","role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"symbolKind":"property","title":"bottomLeft","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Bottom left corner point.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","abstract":[{"text":"Position of the palm in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/detectionposition","title":"DetectionPosition","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotpalmcore\/pointdouble","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","title":"PointDouble"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","kind":"symbol","role":"symbol","title":"PalmAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/bottomLeft":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomLeft","abstract":[{"type":"text","text":"Bottom left corner point."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"title":"bottomLeft","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition\/bottomleft"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","type":"topic","title":"PalmAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bottomLeft"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bottomLeft","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"bottomLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPDetectionPosition","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"value":"bottomLeft","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomLeft\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomLeft\/fragments","value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}]}]}