{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultAngleThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/defaultAngleThreshold"},"abstract":[{"type":"text","text":"Default pitch angle in degrees."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/defaultanglethreshold"]},{"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/defaultanglethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultAngleThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLDevicePitchTooHighValidator(cpy)defaultAngleThreshold","roleHeading":"Type Property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"defaultAngleThreshold","kind":"identifier"}],"title":"defaultAngleThreshold"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","kind":"symbol","title":"DevicePitchTooHighValidator","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Validate maximum pitch angle of the device."}],"navigatorTitle":[{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevicePitchTooHighValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/defaultAngleThreshold":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultAngleThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/defaultAngleThreshold","navigatorTitle":[{"text":"defaultAngleThreshold","kind":"identifier"}],"abstract":[{"type":"text","text":"Default pitch angle in degrees."}],"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/defaultanglethreshold","title":"defaultAngleThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"defaultAngleThreshold","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"defaultAngleThreshold","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"defaultAngleThreshold","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title","value":"DOTFLDevicePitchTooHighValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLDevicePitchTooHighValidator"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1defaultAngleThreshold\/title","value":"defaultAngleThreshold"},{"op":"replace","value":[{"kind":"identifier","text":"defaultAngleThreshold"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1defaultAngleThreshold\/fragments"}]}]}