{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"init(detection:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAeA0ac15DetectionModuleE0C_tcfc"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration","title":"DotPalmLibraryConfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"title":"init(detection:)","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmDetectionModuleConfiguration":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration","abstract":[{"type":"text","text":"Palm detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacecore\/dotpalmdetectionmoduleconfiguration","title":"DotPalmDetectionModuleConfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/Modules-swift.class":{"type":"topic","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class","kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]}]}]}