{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lineIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"startIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"endIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lineIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"endIndex"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(im)initWithLineIndex:startIndex:endIndex:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithLineIndex:startIndex:endIndex:"}],"role":"symbol","title":"init(lineIndex:startIndex:endIndex:)","symbolKind":"init","modules":[{"name":"DotDocument"}]},"variants":[{"paths":["\/documentation\/dotdocument\/mrzstringposition\/init(lineindex:startindex:endindex:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzstringposition\/init(lineindex:startindex:endindex:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)"},"references":{"doc://DotDocument/documentation/DotDocument/MrzStringPosition/init(lineIndex:startIndex:endIndex:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lineIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startIndex"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"endIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/mrzstringposition\/init(lineindex:startindex:endindex:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)","kind":"symbol","role":"symbol","title":"init(lineIndex:startIndex:endIndex:)","type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithLineIndex:startIndex:endIndex:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"kind":"symbol","title":"MrzReader"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotdocument\/mrzstringposition","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"title":"MrzStringPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotDocument","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithLineIndex:startIndex:endIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLineIndex:startIndex:endIndex:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithLineIndex:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"lineIndex","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"startIndex:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startIndex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"endIndex:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"endIndex"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"initWithLineIndex:startIndex:endIndex:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLineIndex:startIndex:endIndex:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"}]}]}