{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/lineIndex","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(py)lineIndex","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"roleHeading":"Instance Property","symbolKind":"property","title":"lineIndex","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"lineIndex"}]},"variants":[{"paths":["\/documentation\/dotdocument\/mrzstringposition\/lineindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzstringposition\/lineindex"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"An index of the line in MRZ."}],"references":{"doc://DotDocument/documentation/DotDocument/MrzStringPosition/lineIndex":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/lineIndex","role":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/lineindex","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"lineIndex","abstract":[{"type":"text","text":"An index of the line in MRZ."}],"navigatorTitle":[{"text":"lineIndex","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","title":"MrzStringPosition","url":"\/documentation\/dotdocument\/mrzstringposition"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"lineIndex","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"lineIndex"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineIndex"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"lineIndex","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1lineIndex\/title"},{"op":"replace","value":[{"kind":"identifier","text":"lineIndex"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1lineIndex\/fragments"},{"op":"replace","value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}