{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgra"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgra","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"title":"ImageFormat.rawBgra","modules":[{"name":"DotDocument"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"]]},"abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 4 bytes of color image pixel:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0th byte: BB - blue"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"1st byte: GG - green"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2nd byte: RR - red"}]}]},{"content":[{"inlineContent":[{"text":"3rd byte: 0  - alpha","type":"text"}],"type":"paragraph"}]}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/ImageFormat/rawBgra":{"title":"ImageFormat.rawBgra","type":"topic","url":"\/documentation\/dotdocument\/imageformat\/rawbgra","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgra","abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"type":"topic","title":"ImageFormat","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","url":"\/documentation\/dotdocument\/imageformat"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTImageFormatRawBgra","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTImageFormatRawBgra","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgra\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgra\/fragments","op":"replace"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}