{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/sod"]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/sod"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/sod"},"metadata":{"title":"Lds1ElementaryFileId.sod","role":"symbol","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdSod","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sod"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdSod"}]},"abstract":[{"type":"text","text":"The security document."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sod","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId/sod":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/sod","abstract":[{"type":"text","text":"The security document."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/sod","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdSod"}],"title":"Lds1ElementaryFileId.sod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sod","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"title":"Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdSod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdSod"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNLds1ElementaryFileIdSod","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTNLds1ElementaryFileIdSod","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1sod\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1sod\/fragments","op":"replace","value":[{"text":"DOTNLds1ElementaryFileIdSod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"}]}]}