{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/isEqual(_:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(im)isEqual:","title":"isEqual(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/commonconfiguration\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/commonconfiguration\/isequal(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/CommonConfiguration/isEqual(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/isEqual(_:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/commonconfiguration\/isequal(_:)"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"url":"\/documentation\/dotdocument\/commonconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isEqual:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1isEqual(_:)\/fragments","op":"replace"},{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","op":"replace"}]}]}