{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration"]]},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration(im)init","role":"symbol","title":"init","symbolKind":"method","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration\/init"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"type":"topic","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol","title":"DotPalmDetectionModuleConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration/init":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration\/init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration\/init","title":"init"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}