{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palmar"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/palmar","interfaceLanguage":"swift"},"abstract":[{"text":"Palmar orientation.","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:@M@DotPalmCore@E@DOTPHandOrientation@DOTPHandOrientationPalmar","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"DOTPHandOrientationPalmar","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"palmar","kind":"identifier"}],"title":"HandOrientation.palmar","roleHeading":"Case","role":"symbol","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/handorientation\/palmar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/handorientation\/palmar"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HandOrientation"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","url":"\/documentation\/dotpalmcore\/handorientation","role":"symbol","title":"HandOrientation","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/palmar":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/handorientation\/palmar","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/palmar","abstract":[{"text":"Palmar orientation.","type":"text"}],"title":"HandOrientation.palmar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmar"}],"navigatorTitle":[{"kind":"identifier","text":"DOTPHandOrientationPalmar"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPHandOrientationPalmar","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTPHandOrientationPalmar","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTPHandOrientationPalmar"}]}]}},{"value":"DOTPHandOrientation","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","value":[{"kind":"identifier","text":"DOTPHandOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1palmar\/title","value":"DOTPHandOrientationPalmar"},{"op":"replace","value":[{"text":"DOTPHandOrientationPalmar","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1palmar\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}