{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handorientation\/rawrepresentable-implementations"]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"collectionGroup","title":"RawRepresentable Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/hashValue"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/hash(into:)"],"anchor":"Instance-Methods"}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/hash(into:)":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/hash(into:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"url":"\/documentation\/dotpalmcore\/handorientation\/hash(into:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/hashValue":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/hashValue","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"title":"hashValue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"url":"\/documentation\/dotpalmcore\/handorientation\/hashvalue","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandOrientation","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"title":"HandOrientation","type":"topic","url":"\/documentation\/dotpalmcore\/handorientation","abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}]}},"variantOverrides":[{"patch":[{"value":"DOTPHandOrientation","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title"},{"value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments"},{"value":[{"text":"DOTPHandOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}