{"metadata":{"externalID":"s:11DotDocument7BarcodeC17DetectionPositionC10bottomLeft0A4Core11PointDoubleCvp","role":"symbol","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"roleHeading":"Instance Property","title":"bottomLeft"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/bottomleft"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"text":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Bottom left corner point.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomLeft","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/Barcode":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","abstract":[{"text":"Result of barcode detection process.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"title":"Barcode","url":"\/documentation\/dotdocument\/barcode"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"title":"Barcode.DetectionPosition","url":"\/documentation\/dotdocument\/barcode\/detectionposition"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/bottomLeft":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/barcode\/detectionposition\/bottomleft","role":"symbol","abstract":[{"type":"text","text":"Bottom left corner point."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomLeft","title":"bottomLeft"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"url":"\/documentation\/dotdocument\/pointdouble","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"symbol","role":"symbol","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","value":"DOTDBarcode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"text":"DOTPointDouble","kind":"identifier"}]}]}]}