{"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","kind":"typeIdentifier","text":"DetectionPosition"}],"externalID":"s:11DotDocument7BarcodeC17DetectionPositionC8mirroredAEyF","title":"mirrored()","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/mirrored()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"references":{"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/mirrored()":{"type":"topic","title":"mirrored()","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","kind":"typeIdentifier","text":"DetectionPosition"}],"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/mirrored()","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition","role":"symbol","title":"Barcode.DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode":{"title":"Barcode","navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcode","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","abstract":[{"text":"Result of barcode detection process.","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","value":"DOTDBarcode","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace"}]}]}