{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/points"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"s:11DotDocument7BarcodeC17DetectionPositionC6pointsSay0A4Core11PointDoubleCGvp","title":"points","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/points","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/barcode\/detectionposition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"title":"Barcode.DetectionPosition","abstract":[{"type":"text","text":"Position of the barcode in the image."}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/points":{"role":"symbol","url":"\/documentation\/dotdocument\/barcode\/detectionposition\/points","type":"topic","title":"points","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/points","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"abstract":[],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","url":"\/documentation\/dotdocument\/pointdouble"},"doc://DotDocument/documentation/DotDocument/Barcode":{"navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"title":"Barcode","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Result of barcode detection process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","url":"\/documentation\/dotdocument\/barcode"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","value":"DOTDBarcode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]}]}]}