{"kind":"symbol","metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)description","modules":[{"name":"DotNfc"}],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/description"]},{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/description"},"references":{"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/description":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/description","title":"description","url":"\/documentation\/dotnfc\/td1machinereadablezone\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"type":"topic","role":"symbol","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","url":"\/documentation\/dotnfc\/td1machinereadablezone","title":"Td1MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1description\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]}]}]}