{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/verifyisactive()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/verifyisactive()"]}],"metadata":{"title":"verifyIsActive()","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary(im)verifyIsActiveAndReturnError:","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"abstract":[{"text":"Verify that library is initialized.","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary","title":"DotFaceLiteLibrary","navigatorTitle":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":" library initialization."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary/verifyIsActive()":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/verifyIsActive()","kind":"symbol","type":"topic","title":"verifyIsActive()","role":"symbol","abstract":[{"text":"Verify that library is initialized.","type":"text"}],"navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/verifyisactive()"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"verifyIsActiveAndReturnError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title","op":"replace","value":"DotFaceLiteLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1verifyIsActive()\/title","op":"replace","value":"verifyIsActiveAndReturnError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1verifyIsActive()\/fragments"}]}]}