{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","title":"DotLibraryId.document"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"text":" identifier.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/document","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/document":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/document","abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"text":" identifier.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"}],"title":"DotLibraryId.document","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid\/document"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotLibraryIdDocument","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}]}},{"value":"DotLibraryIdDocument","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1document\/title","op":"replace"},{"op":"replace","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1document\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}