{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = Defaults.minValidFramesInRowToStartCandidateSelection, ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.candidateSelectionDurationMillis, "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble"},{"text":"? = nil, ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]},{"parameters":[{"name":"sessionToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation."}]}]},{"name":"minValidFramesInRowToStartCandidateSelection","content":[{"inlineContent":[{"text":"Minimum number of valid frames in a row to start candidate selection.","type":"text"}],"type":"paragraph"}]},{"name":"candidateSelectionDurationMillis","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Duration of candidate selection phase."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Normalized rectangle in the input image used for face detection."}]}],"name":"detectionNormalizedRectangle"},{"name":"validators","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of validators which will be used to validate input image."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Throws an error when validator dependencies are missing."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/init(sessiontoken:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(sessionToken:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"init","title":"init(sessionToken:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator","text":"FaceAutoCaptureDetectionValidator"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC12sessionToken44minValidFramesInRowToStartCandidateSelection09candidateR14DurationMillis28detectionNormalizedRectangle10validatorsAESSSg_S2iAA0X6DoubleCSgSayAA0bdE18DetectionValidator_pGtKcfc"},"abstract":[{"text":"Create face auto capture controller configuration.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/init(sessionToken:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)":{"kind":"symbol","title":"init(sessionToken:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validators"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(sessionToken:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/init(sessiontoken:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","title":"FaceAutoCaptureController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble":{"url":"\/documentation\/dotfacelite\/rectangledouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"title":"RectangleDouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"role":"symbol","title":"FaceAutoCaptureDetectionValidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"role":"symbol","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"kind":"symbol","type":"topic","title":"FaceAutoCaptureController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class"}},"variantOverrides":[{"patch":[{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"op":"replace","value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}