{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","text":"DOTCameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","text":"DOTFFaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLibraryComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:isdetectionlayervisible:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"}],"symbolKind":"method","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration(im)initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","title":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"},"kind":"symbol","abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","fragments":[{"text":"DOTFSmileLivenessConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","type":"topic","title":"DOTFSmileLivenessConfiguration","abstract":[{"text":"Configuration options for the UI Smile Liveness component.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","fragments":[{"kind":"text","text":"- "},{"text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:isdetectionlayervisible:","type":"topic","title":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"url":"\/documentation\/dotfacecore\/commonconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","type":"topic","title":"FaceLibraryComponentConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for face library components."}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle"},{"value":"DOTFFaceLibraryComponentConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle"}]}]}