{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/Equatable-Implementations"},"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"anchor":"Operators","generated":true,"title":"Operators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId"]]},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"DotDocument"}],"title":"Equatable Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"article","references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"kind":"symbol","title":"DotPalmModuleId","abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotpalmmoduleid","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/!=(_:_:)":{"abstract":[],"role":"symbol","type":"topic","title":"!=(_:_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/!=(_:_:)","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}]}]}