{"abstract":[{"type":"text","text":"Deinitialize library."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/deinitialize()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/deinitialize()"]},{"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary(im)deinitializeAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"title":"deinitialize()","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/deinitialize()":{"abstract":[{"text":"Deinitialize library.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/deinitialize()","title":"deinitialize()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/deinitialize()"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary":{"url":"\/documentation\/dotfacelite\/dotfacelitelibrary","type":"topic","title":"DotFaceLiteLibrary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibrary"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":" library initialization."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"text":"version: 8.9.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"deinitializeAndReturnError:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"deinitializeAndReturnError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title","value":"DotFaceLiteLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]}]}]}