{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample\/image"]}],"sections":[],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerSample(py)image","symbolKind":"property","fragments":[{"text":"image","kind":"identifier"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property","title":"image"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample\/image","interfaceLanguage":"occ"},"abstract":[{"text":"Sample image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample"]]},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample/image":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample\/image","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample\/image","abstract":[{"text":"Sample image.","type":"text"}],"fragments":[{"kind":"identifier","text":"image"}],"type":"topic","kind":"symbol","role":"symbol","title":"image"},"doc://DotDocument/documentation/DotDocument/Image":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"symbol","title":"Image","type":"topic","url":"\/documentation\/dotdocument\/image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample":{"type":"topic","kind":"symbol","title":"DOTDDocumentAutoCaptureControllerSample","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","fragments":[{"text":"DOTDDocumentAutoCaptureControllerSample","kind":"identifier"}],"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"}]}]}