{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/baseConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","text":"Configuration","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(py)baseConfiguration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"baseConfiguration","modules":[{"name":"DotPalmCore"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Current configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/baseconfiguration"]},{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"type":"topic","title":"BasePalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration":{"url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"title":"DOTPBasePalmAutoCaptureConfiguration","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration","fragments":[{"text":"DOTPBasePalmAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/baseConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/baseConfiguration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/baseconfiguration","title":"baseConfiguration","role":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"kind":"symbol","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","type":"topic","role":"symbol","title":"BasePalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"baseConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"baseConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration","text":"DOTPBasePalmAutoCaptureConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"baseConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1baseConfiguration\/title"},{"value":[{"text":"baseConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1baseConfiguration\/fragments"},{"value":"DOTPBasePalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle"}]}]}