{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/start()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"title":"start()","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(im)start","symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"abstract":[{"text":"Start the palm auto capture process.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/start()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/start()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","title":"BasePalmAutoCaptureViewController"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/start()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Start the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/start()","title":"start()","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/start()","navigatorTitle":[{"kind":"identifier","text":"start"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"start"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"start","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1start()\/title","op":"replace","value":"start"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1start()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}