{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","role":"symbol","extendedModule":"DotPalmCore","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"title":"viewDidDisappear(_:)","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:@CM@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(im)viewDidDisappear:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdiddisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdiddisappear(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidDisappear(_:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewDidDisappear(_:)":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdiddisappear(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidDisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","title":"BasePalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","abstract":[{"text":"version: 9.4.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"viewDidDisappear:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidDisappear(_:)\/fragments","op":"replace"},{"value":"DOTPBasePalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace"}]}]}