{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/passiveLiveness","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"code":"minConfidence","type":"codeVoice"},{"type":"text","text":" value is 0.15."}]},{"type":"paragraph","inlineContent":[{"code":"sizeInterval","type":"codeVoice"},{"type":"text","text":" value is [0.16, 0.2]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minSharpness"},{"text":" value is 0.2832.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pitchAngleInterval"},{"type":"text","text":" value is [-15, 15]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"yawAngleInterval"},{"text":" value is [-20, 20].","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"brightnessInterval","type":"codeVoice"},{"text":" value is [0.11, 0.75].","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"contrastInterval","type":"codeVoice"},{"type":"text","text":" value is [0.25, 0.8]."}]},{"type":"paragraph","inlineContent":[{"code":"minUniqueIntensityLevels","type":"codeVoice"},{"text":" value is 0.525.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"maxDevicePitchAngle"},{"type":"text","text":" value is 30."}]},{"type":"paragraph","inlineContent":[{"code":"minEdgeDistanceToImageShorterSideRatioThreshold","type":"codeVoice"},{"type":"text","text":" value is 0.05"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Type Property","title":"passiveLiveness","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"externalID":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7PresetsC15passiveLivenessAC7BuilderCvpZ","role":"symbol"},"abstract":[{"text":"Builder for ","type":"text"},{"type":"codeVoice","code":"FaceAutoCaptureQualityAttributeThresholds"},{"text":" recommended for passive liveness evaluation.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Presets/passiveLiveness":{"title":"passiveLiveness","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/passiveLiveness","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets\/passiveliveness","abstract":[{"text":"Builder for ","type":"text"},{"code":"FaceAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":" recommended for passive liveness evaluation.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"title":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Presets":{"abstract":[{"text":"Presets for the quality attributes thresholds of the face auto capture result.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Presets","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets","title":"FaceAutoCaptureQualityAttributeThresholds.Presets","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Presets","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder":{"title":"FaceAutoCaptureQualityAttributeThresholds.Builder","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","role":"symbol","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}