{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder"}],"symbolKind":"property","roleHeading":"Type Property","title":"standard","externalID":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7PresetsC8standardAC7BuilderCvpZ"},"abstract":[{"text":"Builder for ","type":"text"},{"code":"FaceAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":" recommended for standard use cases, for example matching.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"},{"text":".","kind":"text"},{"text":"Builder","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"code":"minConfidence","type":"codeVoice"},{"text":" value is 0.15.","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"sizeInterval","type":"codeVoice"},{"text":" value is [0.16, 0.2].","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"minSharpness","type":"codeVoice"},{"text":" value is 0.2832.","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"maxDevicePitchAngle","type":"codeVoice"},{"text":" value is 30.","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"minEdgeDistanceToImageShorterSideRatioThreshold","type":"codeVoice"},{"text":" value is 0.05","type":"text"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets\/standard"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/standard","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","title":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder":{"title":"FaceAutoCaptureQualityAttributeThresholds.Builder","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Builder","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Builder"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Presets/standard":{"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets\/standard","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/standard","kind":"symbol","title":"standard","type":"topic","role":"symbol","abstract":[{"text":"Builder for ","type":"text"},{"code":"FaceAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":" recommended for standard use cases, for example matching.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Presets":{"navigatorTitle":[{"text":"Presets","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the face auto capture result."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Presets","kind":"identifier"}],"title":"FaceAutoCaptureQualityAttributeThresholds.Presets","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}