{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection"},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","roleHeading":"Instance Property","title":"detection","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Face library configuration."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Modules-swift.class":{"title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Modules-swift.class/detection":{"role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class\/detection","type":"topic","title":"detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}