{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral"]}],"metadata":{"role":"symbol","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC17expressionNeutralAA0ac10Expressionh6ModuleE0CSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"expressionNeutral","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLibraryConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","kind":"symbol","abstract":[{"text":"Face library configuration.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Modules-swift.class/expressionNeutral":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"expressionNeutral"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceExpressionNeutralModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"title":"DotFaceExpressionNeutralModuleConfiguration","kind":"symbol","abstract":[{"text":"Face expression neutral module.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class","title":"DotFaceLibraryConfiguration.Modules","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class","type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]}]}]}