{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"title":"DotDocumentModuleId.barcode","symbolKind":"case","navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/barcode","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId":{"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid","title":"DotDocumentModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/barcode":{"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/barcode","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/barcode","title":"DotDocumentModuleId.barcode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"role":"symbol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotDocumentModuleIdBarcode","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/title"},{"op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/fragments"},{"op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/navigatorTitle"},{"op":"replace","value":"DotDocumentModuleIdBarcode","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId~1barcode\/title"},{"op":"replace","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId~1barcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}