{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"description","externalID":"s:7DotCore0A16DocumentModuleIdO11descriptionSSvp","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/description"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/description":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/description","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId","title":"DotDocumentModuleId","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/fragments","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/navigatorTitle","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace"}]}]}