{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary\/deinitialize()"]}],"metadata":{"title":"deinitialize()","externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)deinitializeAndReturnError:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"roleHeading":"Instance Method","role":"symbol","required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"modules":[{"name":"DotPalmCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/deinitialize()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary/deinitialize()":{"required":true,"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotlibrary\/deinitialize()","type":"topic","kind":"symbol","abstract":[],"title":"deinitialize()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/deinitialize()"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"role":"symbol","abstract":[],"title":"DotLibrary","type":"topic","url":"\/documentation\/dotpalmcore\/dotlibrary","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]}]}]}