{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/id"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary\/id"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary(py)id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}],"roleHeading":"Instance Property","symbolKind":"property","title":"id","role":"symbol","modules":[{"name":"DotPalmCore"}],"required":true},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary/id":{"required":true,"navigatorTitle":[{"text":"id","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/id","abstract":[],"url":"\/documentation\/dotpalmcore\/dotlibrary\/id","title":"id","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"title":"DotLibrary","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotlibrary"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","title":"DotLibraryId","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","role":"symbol","url":"\/documentation\/dotpalmcore\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"id"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}]}]}},{"value":"id","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1id\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace"},{"value":"DotLibraryId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}