{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary\/initialize(license:)"]}],"metadata":{"externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)initializeWithLicense:error:","required":true,"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"initialize(license:)","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/initialize(license:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"role":"symbol","title":"DotSdkLicenseProxyProtocol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","abstract":[],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotlibrary","kind":"symbol","abstract":[],"role":"symbol","title":"DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary/initialize(license:)":{"required":true,"abstract":[],"url":"\/documentation\/dotpalmcore\/dotlibrary\/initialize(license:)","type":"topic","role":"symbol","title":"initialize(license:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary\/initialize(license:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithLicense:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithLicense:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<DotSdkLicenseProxyProtocol>","preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace"},{"value":"initializeWithLicense:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1initialize(license:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary~1initialize(license:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}]}]}]}