{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"},"abstract":[{"type":"text","text":"Position of the barcode in the image."}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomRight","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/points","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topRight"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/isEqual(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/mirrored()","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/rebased(parentRectangle:)"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/from(rectangle:)"]}],"metadata":{"symbolKind":"class","extendedModule":"DotDocument","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument7BarcodeC17DetectionPositionC","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"title":"Barcode.DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDBarcodeDetectionPosition) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/detectionposition"]}],"references":{"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/topLeft":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/topleft","abstract":[{"text":"Top left corner point.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topLeft","title":"topLeft","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/from(rectangle:)":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/from(rectangle:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/from(rectangle:)","abstract":[],"title":"from(rectangle:)","type":"topic","role":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/bottomRight":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/bottomright","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomRight","abstract":[{"type":"text","text":"Bottom right corner point."}],"title":"bottomRight","type":"topic","role":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/isEqual(_:)":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/isequal(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/isEqual(_:)","abstract":[],"title":"isEqual(_:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode":{"role":"symbol","abstract":[{"type":"text","text":"Result of barcode detection process."}],"navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"type":"topic","url":"\/documentation\/dotdocument\/barcode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","kind":"symbol","title":"Barcode"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/rebased(parentRectangle:)":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/rebased(parentrectangle:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/rebased(parentRectangle:)","abstract":[],"title":"rebased(parentRectangle:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/points":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/points","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/points","title":"points","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/topRight":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/topright","abstract":[{"type":"text","text":"Top right corner point."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topRight","title":"topRight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/hash":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/hash","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/hash","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/description":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/description","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/mirrored()":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/mirrored()","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/mirrored()","title":"mirrored()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/init(topLeft:topRight:bottomRight:bottomLeft:)":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"title":"Barcode.DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/bottomLeft":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/bottomleft","abstract":[{"type":"text","text":"Bottom left corner point."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomLeft","title":"bottomLeft","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDBarcode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title"},{"op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle"}]}]}