{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagefactory\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/10Foundation14LocalizedErrorP","doc:\/\/com.innovatrics.dot.face.core\/s5ErrorP","doc:\/\/com.innovatrics.dot.face.core\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/maxFaceSizeRatioTooBig","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioBelowZero","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooBig","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooSmall(requiredMin:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/errorDescription-7um5s"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/Error-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/LocalizedError-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"FaceImageFactory.Error","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:11DotFaceCore0B12ImageFactoryC5ErrorO","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/errorDescription-7um5s":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/errorDescription-7um5s","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/errordescription-7um5s"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error":{"role":"symbol","title":"FaceImageFactory.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/faceimagefactory\/error"},"doc://com.innovatrics.dot.face.core/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s5ErrorP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/maxFaceSizeRatioTooBig":{"role":"symbol","title":"FaceImageFactory.Error.maxFaceSizeRatioTooBig","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFaceSizeRatioTooBig"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/maxFaceSizeRatioTooBig","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/maxfacesizeratiotoobig"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/minFaceSizeRatioBelowZero":{"role":"symbol","title":"FaceImageFactory.Error.minFaceSizeRatioBelowZero","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioBelowZero"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioBelowZero","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/minfacesizeratiobelowzero"},"doc://com.innovatrics.dot.face.core/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.innovatrics.dot.face.core\/10Foundation14LocalizedErrorP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/localizederror-implementations"},"doc://com.innovatrics.dot.face.core/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s8SendableP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/minFaceSizeRatioTooBig":{"role":"symbol","title":"FaceImageFactory.Error.minFaceSizeRatioTooBig","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioTooBig"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooBig","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/minfacesizeratiotoobig"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory":{"role":"symbol","title":"FaceImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageFactory"}],"abstract":[{"type":"text","text":"Factory which creates face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceImageFactory"}],"url":"\/documentation\/dotfacecore\/faceimagefactory"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/error-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/minFaceSizeRatioTooSmall(requiredMin:)":{"role":"symbol","title":"FaceImageFactory.Error.minFaceSizeRatioTooSmall(requiredMin:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioTooSmall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requiredMin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooSmall(requiredMin:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/minfacesizeratiotoosmall(requiredmin:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageFactory\/title","value":"DOTFFaceImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFaceDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}