{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory\/create(bgraRawImage:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"]]},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/ciimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/ciimagefactory\/create(bgrarawimage:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"bgraRawImage"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:","modules":[{"name":"DotFaceLite"}],"title":"create(bgraRawImage:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"kind":"text","text":") -> "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"roleHeading":"Type Method","symbolKind":"method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"title":"BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory/create(bgraRawImage:)":{"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"url":"\/documentation\/dotfacelite\/ciimagefactory\/create(bgrarawimage:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory\/create(bgraRawImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.14.0"}],"title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory":{"title":"CIImageFactory","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfacelite\/ciimagefactory","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"createWithBgraRawImage:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory~1create(bgraRawImage:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace"}]}]}