{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/optionalData"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/optionaldata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/optionaldata"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"metadata":{"navigatorTitle":[{"text":"optionalData","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)optionalData","roleHeading":"Instance Property","title":"optionalData","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionalData","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":"]"}],"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionalData"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","title":"Td1MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/optionalData":{"title":"optionalData","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"optionalData","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/optionalData","url":"\/documentation\/dotnfc\/td1machinereadablezone\/optionaldata","type":"topic","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"type":"topic","url":"\/documentation\/dotnfc\/mrzelement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"optionalData","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"optionalData","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTMrzElement *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"optionalData","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1optionalData\/title","op":"replace","value":"optionalData"},{"value":[{"text":"optionalData","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1optionalData\/fragments","op":"replace"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}