{"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg12","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Case","title":"Lds1ElementaryFileId.dg12","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg12","kind":"identifier"}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg12","kind":"identifier"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg12","platforms":[{"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false}],"symbolKind":"case"},"abstract":[{"type":"text","text":"File identifier for data group 12. Data group 12 contains additional document details."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg12"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg12"]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg12"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"kind":"symbol","title":"Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","type":"topic","role":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId/dg12":{"abstract":[{"text":"File identifier for data group 12. Data group 12 contains additional document details.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg12","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg12","title":"Lds1ElementaryFileId.dg12","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg12"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg12"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 8.2.0"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg12","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg12"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"DOTNLds1ElementaryFileIdDg12","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg12","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg12\/title"},{"value":[{"text":"DOTNLds1ElementaryFileIdDg12","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg12\/fragments"}]}]}