{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorityCertificatesNotProvided"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus\/authoritycertificatesnotprovided"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus\/authoritycertificatesnotprovided"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/authorityCertificatesNotProvided","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authority certificates were not provided for Passive Authentication of the travel document."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}],"role":"symbol","title":"PassiveAuthenticationStatus.authorityCertificatesNotProvided","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorityCertificatesNotProvided"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTNPassiveAuthenticationStatus@DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/authorityCertificatesNotProvided":{"role":"symbol","title":"PassiveAuthenticationStatus.authorityCertificatesNotProvided","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorityCertificatesNotProvided"}],"abstract":[{"type":"text","text":"Authority certificates were not provided for Passive Authentication of the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/authorityCertificatesNotProvided","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/authoritycertificatesnotprovided"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus":{"role":"symbol","title":"PassiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1authorityCertificatesNotProvided\/title","value":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1authorityCertificatesNotProvided\/fragments","value":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/title","value":"DOTNPassiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}