{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/commonconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/commonconfiguration"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCommonConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","metadata":{"title":"CommonConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"roleHeading":"Class"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration"},"abstract":[{"type":"text","text":"Common configuration for all components."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/init(sessionToken:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/sessionToken"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/description":{"title":"description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/commonconfiguration\/description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/description"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/hash":{"role":"symbol","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/hash","type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/commonconfiguration\/hash"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/isEqual(_:)","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/commonconfiguration\/isequal(_:)"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/init(sessionToken:)":{"type":"topic","abstract":[],"title":"init(sessionToken:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/init(sessionToken:)","navigatorTitle":[{"text":"initWithSessionToken:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/commonconfiguration\/init(sessiontoken:)"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"url":"\/documentation\/dotpalmcore\/commonconfiguration","type":"topic","title":"CommonConfiguration","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Common configuration for all components."}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/sessionToken":{"abstract":[{"text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/commonconfiguration\/sessiontoken","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/sessionToken","kind":"symbol","navigatorTitle":[{"text":"sessionToken","kind":"identifier"}],"role":"symbol","type":"topic","title":"sessionToken","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/sessionToken"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/init(sessionToken:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCommonConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1init(sessionToken:)\/title","value":"initWithSessionToken:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1init(sessionToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1sessionToken\/title","value":"sessionToken","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1sessionToken\/fragments","value":[{"text":"sessionToken","kind":"identifier"}],"op":"replace"}]}]}