{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration"},"abstract":[{"type":"text","text":"Face detection module configuration."}],"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast"],"title":"Classes","generated":true,"anchor":"Classes"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast"],"title":"Inherited By","type":"inheritedBy"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"title":"DotFaceDetectionModuleConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},"references":{"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Fast":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/fast","title":"DotFaceDetectionModuleConfiguration.Fast","navigatorTitle":[{"kind":"identifier","text":"Fast"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face detection fast module."}]},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfigurationBalanced":{"fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfigurationbalanced","title":"DotFaceDetectionModuleConfigurationBalanced","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face detection balanced module."}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"abstract":[{"text":"Face detection module configuration.","type":"text"}],"title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfigurationFast":{"title":"DotFaceDetectionModuleConfigurationFast","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfigurationfast","abstract":[{"type":"text","text":"Face detection fast module."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationFast","fragments":[{"text":"DotFaceDetectionModuleConfigurationFast","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Balanced":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/balanced","title":"DotFaceDetectionModuleConfiguration.Balanced","navigatorTitle":[{"kind":"identifier","text":"Balanced"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Face detection balanced module.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFaceDetectionModuleConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationFast"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}