{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fit","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"type":"text","text":" "},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/fit"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType"]]},"metadata":{"symbolKind":"case","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFit","modules":[{"name":"DotDocument"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}],"title":"CameraPreviewScaleType.fit","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"type":"topic","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","url":"\/documentation\/dotdocument\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType/fit":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/fit","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fit","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/fit","abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"title":"CameraPreviewScaleType.fit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraPreviewScaleTypeFit"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace"},{"value":"DOTCameraPreviewScaleTypeFit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType~1fit\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType~1fit\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]}]}]}