{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage\/init(bytesPointer:size:)","interfaceLanguage":"swift"},"abstract":[{"text":"Do not use this, use ","type":"text"},{"code":"BgrRawImageFactory","type":"codeVoice"},{"type":"text","text":" to create "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage\/init(bytespointer:size:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage\/init(bytespointer:size:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(im)initWithBytesPointer:size:","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"modules":[{"name":"DotFaceCore"}],"title":"init(bytesPointer:size:)","role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"role":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","type":"topic","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"title":"ImageSize","url":"\/documentation\/dotfacecore\/imagesize"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage/init(bytesPointer:size:)":{"url":"\/documentation\/dotfacecore\/bgrrawimage\/init(bytespointer:size:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgrRawImageFactory"},{"type":"text","text":" to create "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage\/init(bytesPointer:size:)","type":"topic","title":"init(bytesPointer:size:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithBytesPointer:size:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBytesPointer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"DOTImageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"},{"value":"initWithBytesPointer:size:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage~1init(bytesPointer:size:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage~1init(bytesPointer:size:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBytesPointer:size:","kind":"identifier"}]}]}]}