{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(py)faceDetectionConfidenceThreshold","title":"faceDetectionConfidenceThreshold","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold"},"abstract":[{"type":"text","text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"text":". Default value is ","type":"text"},{"code":"0.06","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold"]},{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"title":"DotFaceLibraryConfiguration","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"navigatorTitle":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"abstract":[{"type":"text","text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"text":". Default value is ","type":"text"},{"type":"codeVoice","code":"0.06"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","title":"faceDetectionConfidenceThreshold","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"faceDetectionConfidenceThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"faceDetectionConfidenceThreshold","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title"},{"op":"replace","value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}