{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/modules-swift.property"},"abstract":[{"type":"text","text":"Module configuration."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","text":"Modules"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.property"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(py)modules","navigatorTitle":[{"text":"modules","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"modules","symbolKind":"property"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/modules-swift.property":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.property","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Module configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/modules-swift.property","role":"symbol","navigatorTitle":[{"text":"modules","kind":"identifier"}],"title":"modules"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"title":"DotFaceLibraryConfiguration","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"title":"DotFaceLibraryConfiguration.Modules","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modules"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceLibraryConfigurationModules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1modules-swift.property\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","value":[{"text":"modules","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}]}