{"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/Equatable-Implementations"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","title":"DotFaceModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/!=(_:_:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/!=(_:_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/!=(_:_:)","role":"symbol","title":"!=(_:_:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}