{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator"]]},"abstract":[{"text":"Current maximal accepted brightness.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/threshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/threshold"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/threshold","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"property","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator(py)threshold","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"threshold"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/threshold":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/threshold","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/threshold","kind":"symbol","title":"threshold","abstract":[{"type":"text","text":"Current maximal accepted brightness."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threshold"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"abstract":[{"text":"Validate maximum brightness of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"type":"topic","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"threshold","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"threshold","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1threshold\/title","op":"replace","value":"threshold"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}]},{"op":"replace","value":"DOTDBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments"},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}]}]}