{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"format"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage(py)format","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"format","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Format of the stored image"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/format"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/image\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/image\/format"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfingerscore\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat","title":"ImageFormat","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image/format":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"format"}],"url":"\/documentation\/dotfingerscore\/image\/format","abstract":[{"type":"text","text":"Format of the stored image"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/format","title":"format","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"format"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"format"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat","text":"DOTImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1format\/title","value":"format"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1format\/fragments","value":[{"kind":"identifier","text":"format"}]}]}]}