{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/common"]}],"abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"text","text":".init()"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/common"},"metadata":{"navigatorTitle":[{"text":"common","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration(py)common","modules":[{"name":"DotFaceLite"}],"title":"common","role":"symbol","fragments":[{"text":"common","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"common"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration/common":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/common","type":"topic","abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"kind":"symbol","title":"common","role":"symbol","fragments":[{"text":"common","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/common"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"role":"symbol","title":"DOTFLMultiRangeLivenessConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","fragments":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"kind":"symbol","type":"topic","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol","title":"CommonConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","url":"\/documentation\/dotfacelite\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]}]}]}