{"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minFingerCountThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(minFingerCountThreshold:minConfidenceThreshold:)","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerCountTooLowValidator(im)initWithMinFingerCountThreshold:minConfidenceThreshold:error:","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"text":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"minFingerCountThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = FingersNotDetectedValidator.defaultMinConfidenceThreshold) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/init(minFingerCountThreshold:minConfidenceThreshold:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init(minfingercountthreshold:minconfidencethreshold:)"]},{"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init(minfingercountthreshold:minconfidencethreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"navigatorTitle":[{"text":"FingerCountTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","title":"FingerCountTooLowValidator","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator/init(minFingerCountThreshold:minConfidenceThreshold:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minFingerCountThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init(minfingercountthreshold:minconfidencethreshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/init(minFingerCountThreshold:minConfidenceThreshold:)","title":"init(minFingerCountThreshold:minConfidenceThreshold:)","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinFingerCountThreshold:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minFingerCountThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","value":"DOTFGFingerCountTooLowValidator"},{"value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle"},{"value":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1init(minFingerCountThreshold:minConfidenceThreshold:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinFingerCountThreshold:minConfidenceThreshold:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1init(minFingerCountThreshold:minConfidenceThreshold:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}