{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/minConfidenceThreshold"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerCountTooLowValidator(py)minConfidenceThreshold","title":"minConfidenceThreshold","navigatorTitle":[{"kind":"identifier","text":"minConfidenceThreshold"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Minimum detection confidence threshold."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minconfidencethreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minconfidencethreshold"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"navigatorTitle":[{"text":"FingerCountTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","title":"FingerCountTooLowValidator","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator/minConfidenceThreshold":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/minConfidenceThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"minConfidenceThreshold","abstract":[{"type":"text","text":"Minimum detection confidence threshold."}],"navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minconfidencethreshold"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"minConfidenceThreshold","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"minConfidenceThreshold","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidenceThreshold"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","value":"DOTFGFingerCountTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1minConfidenceThreshold\/title","value":"minConfidenceThreshold","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1minConfidenceThreshold\/fragments","value":[{"text":"minConfidenceThreshold","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}