{"variants":[{"paths":["\/documentation\/dotfacecore\/template\/version"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/template\/version"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplate(py)version","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"version","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"version","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"version"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Template version."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/version","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Template":{"url":"\/documentation\/dotfacecore\/template","type":"topic","abstract":[{"type":"text","text":"Face template."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","kind":"symbol","title":"Template","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"navigatorTitle":[{"text":"Template","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Template/version":{"url":"\/documentation\/dotfacecore\/template\/version","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"version","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Template version."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"version"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/version"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"version","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"version"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFTemplate"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFTemplate"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1version\/title","op":"replace","value":"version"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1version\/fragments","op":"replace","value":[{"kind":"identifier","text":"version"}]}]}]}