{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/identifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/identifier"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/identifier","interfaceLanguage":"swift"},"metadata":{"title":"identifier","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooHighValidator(py)identifier","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]]},"kind":"symbol","sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","abstract":[{"text":"version: 8.3.1","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooHighValidator":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooHighValidator/identifier":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/identifier","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator\/identifier","title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"identifier"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"value":"DOTFLBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments"},{"value":"identifier","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1identifier\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}],"op":"replace"}]}]}