{"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC04baseH023isDetectionLayerVisible11placeholderAeA04BasebdefG0CADC_SbAA11PlaceholderCtcfc","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","symbolKind":"init"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","kind":"typeIdentifier","text":"Placeholder"},{"kind":"text","text":" = .Visible())"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)"]}],"kind":"symbol","abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"title":"PalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","role":"symbol","abstract":[{"text":"Configuration options for the UI Palm Auto Capture component.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","role":"symbol","title":"Placeholder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","url":"\/documentation\/dotpalmcore\/placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"kind":"symbol","abstract":[{"text":"Placeholder.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"type":"topic","role":"symbol","title":"BasePalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/init(baseConfiguration:isDetectionLayerVisible:placeholder:)":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder","text":"Placeholder"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"title":"PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","role":"symbol","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","title":"BasePalmAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTPPlaceholder","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","op":"replace"},{"value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"DOTPBasePalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}