{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentdetectordocument\/initwithdetectionposition:confidence:widthtoheightratio:imageparameters:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDetectionPosition:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier","text":"DOTDDetectionPosition"},{"kind":"text","text":" *) "},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confidence"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"widthToHeightRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters:"},{"kind":"text","text":"("},{"text":"DOTDImageParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageParameters"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"title":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","navigatorTitle":[{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument(im)initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","kind":"identifier"}]},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument/initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:":{"kind":"symbol","title":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","fragments":[{"kind":"text","text":"- "},{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument\/initwithdetectionposition:confidence:widthtoheightratio:imageparameters:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/initWithDetectionPosition:confidence:widthToHeightRatio:imageParameters:","type":"topic"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"title":"ImageParameters","url":"\/documentation\/dotdocument\/imageparameters","role":"symbol","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"Position of the document card in the image.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","url":"\/documentation\/dotdocument\/detectionposition","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","type":"topic","abstract":[{"text":"Result of the document detection process.","type":"text"}],"title":"DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","role":"symbol","fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDImageParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"text":"DOTDImageParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","op":"replace","value":"DOTDDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]}]}]}