{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"}],"title":"cameraPreviewScaleType","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceLite30MagnifEyeLivenessConfigurationC8DefaultsV22cameraPreviewScaleTypeAA06CamerajkL0OvpZ","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/Defaults"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessConfiguration/Defaults/cameraPreviewScaleType":{"role":"symbol","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/Defaults\/cameraPreviewScaleType","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/defaults\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessConfiguration/Defaults":{"role":"symbol","title":"MagnifEyeLivenessConfiguration.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/defaults"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessConfiguration":{"role":"symbol","title":"MagnifEyeLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessConfiguration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.0.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration\/title","value":"DOTFLMagnifEyeLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}