{"abstract":[{"type":"text","text":"Process an input image or video frame and update the state."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult"}]}]},{"parameters":[{"name":"bgraRawImage","content":[{"inlineContent":[{"type":"text","text":"Input image."}],"type":"paragraph"}]},{"name":"timestampMillis","content":[{"inlineContent":[{"type":"text","text":"Input image timestamp."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The result of processing of the input image.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"If you call this method after the document auto capture process has finished, it will throw an error.","type":"text"}]}],"type":"aside","style":"note"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:timestampMillis:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","platforms":[],"title":"process(bgraRawImage:timestampMillis:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureController(im)processWithBgraRawImage:timestampMillis:error:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC"}]},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use process(sample:) instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:timestampmillis:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:timestampmillis:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/process(bgraRawImage:timestampMillis:)":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:timestampmillis:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"process","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:timestampMillis:)","abstract":[{"text":"Process an input image or video frame and update the state.","type":"text"}],"kind":"symbol","title":"process(bgraRawImage:timestampMillis:)","navigatorTitle":[{"kind":"identifier","text":"processWithBgraRawImage:timestampMillis:error:"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"type":"topic","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult":{"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","title":"DocumentAutoCaptureController.ProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the document auto capture process.","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult":{"type":"topic","title":"DOTDDocumentAutoCaptureControllerProcessingResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerProcessingResult"}],"abstract":[{"text":"The result returned from the processing of one image during the document auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"type":"topic","title":"BgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"processWithBgraRawImage:timestampMillis:error:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","text":"DOTDDocumentAutoCaptureControllerProcessingResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerProcessingResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"processWithBgraRawImage:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"text":"timestampMillis:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"processWithBgraRawImage:timestampMillis:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace"}]}]}