{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotlibraryid\/fingers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotlibraryid\/fingers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/fingers"},"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFingers","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"title":"DotLibraryId.fingers"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","url":"\/documentation\/dotnfc\/dotlibraryid","title":"DotLibraryId","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/fingers":{"navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/fingers","url":"\/documentation\/dotnfc\/dotlibraryid\/fingers","title":"DotLibraryId.fingers","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdFingers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1fingers\/title","value":"DotLibraryIdFingers"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1fingers\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}