{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentCode","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone(py)documentCode","role":"symbol","title":"documentCode","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"}],"modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/documentcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/documentcode"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone/documentCode":{"url":"\/documentation\/dotnfc\/td1machinereadablezone\/documentcode","role":"symbol","kind":"symbol","title":"documentCode","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentCode","navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone":{"url":"\/documentation\/dotnfc\/td1machinereadablezone","role":"symbol","kind":"symbol","title":"Td1MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/mrzelement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentCode","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"documentCode"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTMrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"documentCode"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentCode\/title","value":"documentCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentCode\/fragments","value":[{"text":"documentCode","kind":"identifier"}]},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}]}]}