{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"style","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC","text":"Style"}],"navigatorTitle":[{"kind":"identifier","text":"style"}],"role":"symbol","platforms":[{"deprecated":true,"message":"Use MultiRangeLivenessViewController instead.","beta":false,"unavailable":false}],"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController(py)style","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Style-swift.class","kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Current style."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/style-swift.property","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"UI Eye Gaze Liveness component."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"type":"topic","title":"EyeGazeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/style-swift.property":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/style-swift.property","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Current style."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/style-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC","kind":"typeIdentifier"}],"type":"topic","title":"style","navigatorTitle":[{"text":"style","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessStyle":{"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessstyle","abstract":[{"type":"text","text":"Customization options for the eye gaze liveness user interface."}],"title":"DOTFEyeGazeLivenessStyle","fragments":[{"text":"DOTFEyeGazeLivenessStyle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessStyle","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Style-swift.class":{"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Customization options for the eye gaze liveness user interface."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/style-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"title":"EyeGazeLivenessViewController.Style","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Style-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":true,"beta":false,"unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"style"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"style"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFEyeGazeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"style"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/deprecationSummary","op":"replace","value":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","op":"replace","value":"DOTFEyeGazeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1style-swift.property\/title","op":"replace","value":"style"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1style-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"style"}]}]}]}