{"sections":[],"metadata":{"navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"roleHeading":"Instance Property","title":"cgPoint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"extendedModule":"DotCore","symbolKind":"property","externalID":"c:@CM@DotCore@objc(cs)DOTPointInt(py)cgPoint","modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointint\/cgpoint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/pointint\/cgpoint"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/cgPoint"},"references":{"doc://DotDocument/documentation/DotDocument/PointInt":{"type":"topic","kind":"symbol","title":"PointInt","url":"\/documentation\/dotdocument\/pointint","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"},"doc://DotDocument/documentation/DotDocument/PointInt/cgPoint":{"url":"\/documentation\/dotdocument\/pointint\/cgpoint","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/cgPoint","navigatorTitle":[{"kind":"identifier","text":"cgPoint"}],"abstract":[],"title":"cgPoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cgPoint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cgPoint","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/title","value":"DOTPointInt"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/fragments","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/navigatorTitle","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1cgPoint\/title","value":"cgPoint"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1cgPoint\/fragments","value":[{"text":"cgPoint","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}