{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/from(cgPoint:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"DotCore","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"roleHeading":"Type Method","title":"from(cgPoint:)","externalID":"c:@CM@DotCore@objc(cs)DOTPointInt(cm)fromCgPoint:","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier","text":"PointInt"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointint\/from(cgpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/pointint\/from(cgpoint:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt","text":"PointInt","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/PointInt":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"url":"\/documentation\/dotdocument\/pointint","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt","title":"PointInt"},"doc://DotDocument/documentation/DotDocument/PointInt/from(cgPoint:)":{"navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/from(cgPoint:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/pointint\/from(cgpoint:)","title":"from(cgPoint:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"fromCgPoint:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt","text":"DOTPointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromCgPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgPoint"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1from(cgPoint:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]}]}]}