{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(document:traveldocumenttype:mrzrecognitionresult:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(document:traveldocumenttype:mrzrecognitionresult:)"]}],"metadata":{"symbolKind":"init","title":"init(document:travelDocumentType:mrzRecognitionResult:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mrzRecognitionResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(im)initWithDocument:travelDocumentType:mrzRecognitionResult:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:travelDocumentType:mrzRecognitionResult:"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentDetector","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","text":"Document"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"mrzRecognitionResult"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","kind":"typeIdentifier","text":"MrzRecognitionResult"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(document:travelDocumentType:mrzRecognitionResult:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters/init(document:travelDocumentType:mrzRecognitionResult:)":{"title":"init(document:travelDocumentType:mrzRecognitionResult:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(document:travelDocumentType:mrzRecognitionResult:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mrzRecognitionResult"},{"text":": ","kind":"text"},{"text":"MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:travelDocumentType:mrzRecognitionResult:"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(document:traveldocumenttype:mrzrecognitionresult:)","abstract":[],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorDocument":{"type":"topic","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"abstract":[{"text":"Result of the document detection process.","type":"text"}],"title":"DOTDDocumentDetectorDocument","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Document":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Document"}],"navigatorTitle":[{"kind":"identifier","text":"Document"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","title":"DocumentDetector.Document","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","url":"\/documentation\/dotdocument\/documentdetector\/document"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"kind":"symbol","title":"DocumentAutoCaptureFrameParameters","role":"symbol","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","role":"symbol","url":"\/documentation\/dotdocument\/documentdetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","role":"symbol","title":"TravelDocumentTypeWrapper","type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"text":" for Objective-C support.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzRecognitionResult":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","url":"\/documentation\/dotdocument\/mrzrecognitionresult","navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzRecognitionResult"}],"kind":"symbol","abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"type":"topic","title":"MrzRecognitionResult"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocument:travelDocumentType:mrzRecognitionResult:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocument:travelDocumentType:mrzRecognitionResult:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDocument:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","kind":"typeIdentifier","text":"DOTDDocumentDetectorDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"text":" ","kind":"text"},{"text":"travelDocumentType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"travelDocumentType","kind":"internalParam"},{"kind":"text","text":" "},{"text":"mrzRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","kind":"typeIdentifier","text":"DOTDMrzRecognitionResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"mrzRecognitionResult"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(document:travelDocumentType:mrzRecognitionResult:)\/title","op":"replace","value":"initWithDocument:travelDocumentType:mrzRecognitionResult:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(document:travelDocumentType:mrzRecognitionResult:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:travelDocumentType:mrzRecognitionResult:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace"},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace","value":"DOTTravelDocumentTypeWrapper"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"op":"replace"},{"value":"DOTDMrzRecognitionResult","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzRecognitionResult\/title"},{"op":"replace","value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzRecognitionResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}