{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Current configuration."}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/configuration-swift.property","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(py)configuration","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"platforms":[],"roleHeading":"Instance Property","title":"configuration","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.property"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the face simple capture process.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"deprecated":true,"kind":"symbol","title":"FaceSimpleCaptureViewController.Configuration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceSimpleCaptureConfiguration":{"url":"\/documentation\/dotfacecore\/dotffacesimplecaptureconfiguration","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration","role":"symbol","title":"DOTFFaceSimpleCaptureConfiguration","type":"topic","fragments":[{"text":"DOTFFaceSimpleCaptureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"deprecated":true,"kind":"symbol","title":"FaceSimpleCaptureViewController"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/configuration-swift.property":{"type":"topic","abstract":[{"text":"Current configuration.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/configuration-swift.property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"kind":"symbol","deprecated":true,"title":"configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.property","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration","text":"DOTFFaceSimpleCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1configuration-swift.property\/title"},{"value":[{"kind":"identifier","text":"configuration"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1configuration-swift.property\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}