{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"abstract":[{"type":"text","text":"Start the face simple capture process."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/start()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/start()"]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(im)start","title":"start()","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"start","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/start()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"deprecated":true,"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","role":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","title":"FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/start()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/start()","kind":"symbol","abstract":[{"type":"text","text":"Start the face simple capture process."}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/start()","deprecated":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"()"}],"title":"start()","navigatorTitle":[{"kind":"identifier","text":"start"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"start"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"start"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFFaceSimpleCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1start()\/title","op":"replace","value":"start"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}