{"metadata":{"role":"symbol","title":"DocumentImageQuality","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentImageQuality"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DocumentImageQuality","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"},"kind":"symbol","abstract":[{"text":"Document image quality.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/init(brightness:sharpness:hotspotsScore:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/brightness","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hotspotsScore","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/sharpness"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentImageQuality) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentImageQuality"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentimagequality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentimagequality"]}],"references":{"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/brightness":{"abstract":[{"type":"text","text":"Brightness value in range [0, 1.0]."}],"role":"symbol","url":"\/documentation\/dotdocument\/documentimagequality\/brightness","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"brightness"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/brightness","title":"brightness"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/hotspotsScore":{"abstract":[{"text":"Hotspots score value in range [0, 1.0].","type":"text"}],"url":"\/documentation\/dotdocument\/documentimagequality\/hotspotsscore","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hotspotsScore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hotspotsScore","kind":"symbol","type":"topic","title":"hotspotsScore"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/sharpness":{"navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"url":"\/documentation\/dotdocument\/documentimagequality\/sharpness","kind":"symbol","abstract":[{"text":"Sharpness value in range [0, 1.0].","type":"text"}],"title":"sharpness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/sharpness","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/isEqual(_:)":{"role":"symbol","url":"\/documentation\/dotdocument\/documentimagequality\/isequal(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/isEqual(_:)","title":"isEqual(_:)","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotdocument\/documentimagequality\/hash","kind":"symbol","abstract":[],"title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hash","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"navigatorTitle":[{"kind":"identifier","text":"DocumentImageQuality"}],"url":"\/documentation\/dotdocument\/documentimagequality","kind":"symbol","abstract":[{"text":"Document image quality.","type":"text"}],"title":"DocumentImageQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentImageQuality"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/init(brightness:sharpness:hotspotsScore:)":{"title":"init(brightness:sharpness:hotspotsScore:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithBrightness:sharpness:hotspotsScore:"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/init(brightness:sharpness:hotspotsScore:)","url":"\/documentation\/dotdocument\/documentimagequality\/init(brightness:sharpness:hotspotsscore:)"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/description":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/documentimagequality\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/description","title":"description"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDDocumentImageQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}]},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/brightness","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hotspotsScore","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/sharpness"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/init(brightness:sharpness:hotspotsScore:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentImageQuality"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"brightness","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1brightness\/title","op":"replace"},{"value":[{"kind":"identifier","text":"brightness"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1brightness\/fragments","op":"replace"},{"value":"hotspotsScore","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hotspotsScore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hotspotsScore"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hotspotsScore\/fragments","op":"replace"},{"value":"sharpness","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1sharpness\/title","op":"replace"},{"value":[{"kind":"identifier","text":"sharpness"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1sharpness\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1isEqual(_:)\/fragments","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hash\/fragments","op":"replace"},{"value":"DOTDDocumentImageQuality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle","op":"replace"},{"value":"initWithBrightness:sharpness:hotspotsScore:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1init(brightness:sharpness:hotspotsScore:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrightness:sharpness:hotspotsScore:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1init(brightness:sharpness:hotspotsScore:)\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1description\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}