{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"DotDocumentModuleId","modules":[{"name":"DotDocument"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@M@DotCore@E@DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/barcode"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/description"],"generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/RawRepresentable-Implementations":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/rawrepresentable-implementations","kind":"article","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/init(rawValue:)":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/init(rawvalue:)","kind":"symbol","abstract":[],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/init(rawValue:)","type":"topic","role":"symbol"},"doc://DotDocument/SY":{"identifier":"doc:\/\/DotDocument\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/Equatable-Implementations":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/equatable-implementations","kind":"article","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/Equatable-Implementations","type":"topic","role":"collectionGroup"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"role":"symbol","title":"DotDocumentModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotdocument\/dotdocumentmoduleid","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/description":{"abstract":[],"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/description","kind":"symbol","type":"topic","title":"description"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/barcode":{"role":"symbol","title":"DotDocumentModuleId.barcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/barcode","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/barcode","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/barcode"],"generated":true,"anchor":"Enumeration-Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId~1barcode\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId~1barcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}