{"abstract":[{"text":"Face detection module configuration.","type":"text"}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"roleHeading":"Class","title":"DotFaceDetectionModuleConfiguration"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast"],"generated":true,"anchor":"Classes"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfigurationBalanced":{"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfigurationbalanced","kind":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","abstract":[{"type":"text","text":"Face detection balanced module."}],"fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfigurationFast":{"role":"symbol","title":"DotFaceDetectionModuleConfigurationFast","fragments":[{"text":"DotFaceDetectionModuleConfigurationFast","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationFast","kind":"symbol","abstract":[{"text":"Face detection fast module.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfigurationfast","type":"topic"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Fast":{"navigatorTitle":[{"kind":"identifier","text":"Fast"}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/fast","kind":"symbol","title":"DotFaceDetectionModuleConfiguration.Fast","abstract":[{"text":"Face detection fast module.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Balanced":{"title":"DotFaceDetectionModuleConfiguration.Balanced","abstract":[{"type":"text","text":"Face detection balanced module."}],"navigatorTitle":[{"kind":"identifier","text":"Balanced"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"abstract":[{"type":"text","text":"Face detection module configuration."}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","kind":"symbol","type":"topic","title":"DotFaceDetectionModuleConfiguration"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationFast"],"title":"Inherited By"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}]}]}