{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImage","navigatorTitle":[{"text":"Image","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotDocument"}],"title":"Image","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"Converting images","generated":true,"anchor":"Converting-images","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/image"]},{"paths":["\/documentation\/dotdocument\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/init(format:bytes:size:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/bytes","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/format","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/size"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/Image/bytes":{"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"url":"\/documentation\/dotdocument\/image\/bytes","kind":"symbol","title":"bytes","abstract":[{"type":"text","text":"Raw image data."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/bytes","type":"topic","role":"symbol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Image/init(format:bytes:size:)":{"abstract":[],"title":"init(format:bytes:size:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/init(format:bytes:size:)","type":"topic","url":"\/documentation\/dotdocument\/image\/init(format:bytes:size:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier","text":"ImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":")"}]},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Image/format":{"abstract":[{"type":"text","text":"Format of the stored image"}],"title":"format","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/format","navigatorTitle":[{"kind":"identifier","text":"format"}],"type":"topic","url":"\/documentation\/dotdocument\/image\/format","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier","text":"ImageFormat"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/Image/size":{"kind":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"title":"size","type":"topic","abstract":[{"type":"text","text":"Image size."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/size","url":"\/documentation\/dotdocument\/image\/size"},"doc://DotDocument/documentation/DotDocument/ImageFactory":{"abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/imagefactory","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","title":"ImageFactory"},"doc://DotDocument/documentation/DotDocument/Image":{"abstract":[],"url":"\/documentation\/dotdocument\/image","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"symbol","type":"topic","title":"Image"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Image/description":{"abstract":[],"url":"\/documentation\/dotdocument\/image\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/description","kind":"symbol","type":"topic","title":"description"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/CGImageFactory":{"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dotdocument\/cgimagefactory","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","title":"CGImageFactory"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/CIImageFactory":{"role":"symbol","title":"CIImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotdocument\/ciimagefactory","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/bytes","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/format","doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/size"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Converting images","generated":true,"anchor":"Converting-images","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory"]}]},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImage"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1bytes\/title","op":"replace","value":"bytes"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1bytes\/fragments","op":"replace","value":[{"kind":"identifier","text":"bytes"}]},{"value":"format","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1format\/title"},{"value":[{"kind":"identifier","text":"format"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1format\/fragments"},{"value":"size","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1size\/title"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1size\/fragments"},{"value":"DOTImageFactory","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1description\/fragments"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/navigatorTitle"},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/navigatorTitle"}]}]}