{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"Logs failed operations and other errors."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/error"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/error","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelError","title":"LoggerLogLevel.error","roleHeading":"Case","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"url":"\/documentation\/dotnfc\/loggerloglevel","type":"topic","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Available log levels."}],"title":"LoggerLogLevel","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/error":{"title":"LoggerLogLevel.error","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"url":"\/documentation\/dotnfc\/loggerloglevel\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1error\/title","op":"replace","value":"DOTLoggerLogLevelError"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1error\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]}]}]}