{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDQualityAttributeThresholdsBuilder) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/build()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/maxHotspotsScore(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minConfidence(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minSharpness(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minSize(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds.Builder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"Builder"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/minSize(_:)":{"role":"symbol","title":"minSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minSize(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/minsize(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/init()","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/init()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/minConfidence(_:)":{"role":"symbol","title":"minConfidence(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidence"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minConfidence(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/minconfidence(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/build()","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/build()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/maxHotspotsScore(_:)":{"role":"symbol","title":"maxHotspotsScore(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHotspotsScore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/maxHotspotsScore(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/maxhotspotsscore(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds.Builder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/brightnessInterval(_:)":{"role":"symbol","title":"brightnessInterval(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/brightnessinterval(_:)"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/minSharpness(_:)":{"role":"symbol","title":"minSharpness(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/minSharpness(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/minsharpness(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}