{"abstract":[{"type":"text","text":"Raw data group DG14."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dg14SecurityOptions","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg14securityoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg14securityoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg14SecurityOptions"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"dg14SecurityOptions","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg14SecurityOptions","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg14SecurityOptions"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"role":"symbol","platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false}],"title":"dg14SecurityOptions"},"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","title":"Lds1eMrtdApplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"title":"TravelDocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg14SecurityOptions":{"title":"dg14SecurityOptions","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg14SecurityOptions","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg14SecurityOptions","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg14securityoptions","kind":"symbol","abstract":[{"type":"text","text":"Raw data group DG14."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dg14SecurityOptions"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","url":"\/documentation\/dotnfc\/lds1elementaryfile","title":"Lds1ElementaryFile","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"dg14SecurityOptions","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"dg14SecurityOptions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":" * ","kind":"text"},{"text":"dg14SecurityOptions","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg14SecurityOptions\/title","value":"dg14SecurityOptions"},{"value":[{"text":"dg14SecurityOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg14SecurityOptions\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}