{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"barcode","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode","role":"symbol","title":"barcode","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","navigatorTitle":[{"text":"barcode","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules\/barcode"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfigurationModules/barcode":{"fragments":[{"kind":"identifier","text":"barcode"}],"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules\/barcode","kind":"symbol","role":"symbol","title":"barcode","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules\/barcode"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration","kind":"symbol","role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules","kind":"symbol","role":"symbol","title":"DotDocumentLibraryConfigurationModules","abstract":[{"type":"text","text":"Document library module configuration."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]}]}]}