{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/captureMode","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"captureMode","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"}],"externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC11captureMode0aE00eJ0Ovp","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/capturemode"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"code":".autoCapture","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier","text":"CaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/captureMode":{"kind":"symbol","title":"captureMode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/captureMode","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/capturemode","abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"type":"codeVoice","code":".autoCapture"},{"text":".","type":"text"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"role":"symbol","url":"\/documentation\/dotfacecore\/capturemode","title":"CaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCaptureMode","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"}]}]}