{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/devicetiltangles"]}],"metadata":{"externalID":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC16deviceTiltAngles0aE00iJ0CSgvp","title":"deviceTiltAngles","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/deviceTiltAngles","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"type":"topic","title":"FaceAutoCaptureController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"title":"TiltAngles","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","url":"\/documentation\/dotfacelite\/tiltangles","abstract":[{"text":"Tilt angles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}],"kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Sample":{"title":"FaceAutoCaptureController.Sample","navigatorTitle":[{"text":"Sample","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the face auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Sample","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Sample/deviceTiltAngles":{"title":"deviceTiltAngles","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/deviceTiltAngles","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/devicetiltangles","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceTiltAngles"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace","value":"DOTFLFaceAutoCaptureController"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","op":"replace"}]}]}