{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/init(image:timestampMillis:deviceTiltAngles:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/init(image:timestampmillis:devicetiltangles:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(image:timestampMillis:deviceTiltAngles:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC5image15timestampMillis16deviceTiltAnglesAE0A4Core5ImageC_Si0aE00lM0CSgtcfc","role":"symbol","symbolKind":"init"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TiltAngles"}],"type":"topic","title":"TiltAngles","url":"\/documentation\/dotfacelite\/tiltangles","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Sample":{"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the face auto capture process."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample","title":"FaceAutoCaptureController.Sample","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sample"}],"navigatorTitle":[{"kind":"identifier","text":"Sample"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Sample/init(image:timestampMillis:deviceTiltAngles:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","role":"symbol","title":"init(image:timestampMillis:deviceTiltAngles:)","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/init(image:timestampmillis:devicetiltangles:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/init(image:timestampMillis:deviceTiltAngles:)"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","title":"Image","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/image","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/navigatorTitle","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}]}]}