{"metadata":{"title":"from(cgRect:)","roleHeading":"Type Method","extendedModule":"DotCore","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(cm)fromCgRect:","symbolKind":"method","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc","relatedModules":["DotCore"]}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/from(cgrect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/from(cgrect:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/from(cgRect:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/RectangleDouble/from(cgRect:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/from(cgRect:)","title":"from(cgRect:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/rectangledouble\/from(cgrect:)","abstract":[],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","url":"\/documentation\/dotnfc\/rectangledouble","type":"topic","title":"RectangleDouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"fromCgRect:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"fromCgRect:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"text":"fromCgRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgRect"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1from(cgRect:)\/title","op":"replace","value":"fromCgRect:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1from(cgRect:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromCgRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}