{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator\/dependencyIdentifiers"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator"]]},"metadata":{"title":"dependencyIdentifiers","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentNotDetectedValidator(py)dependencyIdentifiers","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/dependencyidentifiers"]}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator/dependencyIdentifiers":{"type":"topic","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/dependencyidentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator\/dependencyIdentifiers","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator":{"type":"topic","abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"title":"DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"dependencyIdentifiers","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}]}]}