{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/detectionposition\/lengthofedgescalculatorprotocol-implementations"]},{"paths":["\/documentation\/dotdocument\/detectionposition\/lengthofedgescalculatorprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/LengthOfEdgesCalculatorProtocol-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition"]]},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/points"]}],"kind":"article","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"LengthOfEdgesCalculatorProtocol Implementations","modules":[{"name":"DotDocument"}],"role":"collectionGroup"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition","role":"symbol","title":"DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"Position of the document card in the image.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"url":"\/documentation\/dotdocument\/documentdetector","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition/points":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/points","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"points","abstract":[],"navigatorTitle":[{"text":"points","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition\/points"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/points"],"generated":true,"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1points\/title","value":"points"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1points\/fragments","op":"replace","value":[{"text":"points","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}