{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/dorsal","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handorientation\/dorsal"]},{"paths":["\/documentation\/dotpalmcore\/handorientation\/dorsal"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation"]]},"abstract":[{"text":"Dorsal orientation.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dorsal","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"HandOrientation.dorsal","navigatorTitle":[{"kind":"identifier","text":"DOTPHandOrientationDorsal"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dorsal","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotPalmCore@E@DOTPHandOrientation@DOTPHandOrientationDorsal","symbolKind":"case"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/dorsal":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/dorsal","navigatorTitle":[{"text":"DOTPHandOrientationDorsal","kind":"identifier"}],"title":"HandOrientation.dorsal","abstract":[{"text":"Dorsal orientation.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dorsal"}],"type":"topic","url":"\/documentation\/dotpalmcore\/handorientation\/dorsal","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/handorientation","title":"HandOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandOrientation","kind":"identifier"}],"navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represents the orientation of a hand when detecting palm.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTPHandOrientationDorsal"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTPHandOrientationDorsal","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTPHandOrientationDorsal","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1dorsal\/title","op":"replace","value":"DOTPHandOrientationDorsal"},{"value":[{"kind":"identifier","text":"DOTPHandOrientationDorsal"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1dorsal\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","value":"DOTPHandOrientation"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","value":[{"text":"DOTPHandOrientation","kind":"identifier"}]},{"value":[{"text":"DOTPHandOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle"}]}]}