{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current frame parameters."}]}],"name":"palmAutoCaptureFrameParameters"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for the failed validation and "},{"code":"true","type":"codeVoice"},{"type":"text","text":" for the successful validation."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"role":"symbol","required":true,"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator(im)validateWithPalmAutoCaptureFrameParameters:","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"validate(palmAutoCaptureFrameParameters:)","modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"]]},"abstract":[{"type":"text","text":"Validate current frame parameters."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/validate(palmAutoCaptureFrameParameters:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/validate(palmautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/validate(palmautocaptureframeparameters:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"title":"PalmAutoCaptureFrameParameters","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"abstract":[{"text":"Information from the detection process about the detected palm.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParametersValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","type":"topic","title":"PalmAutoCaptureFrameParametersValidator","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator/validate(palmAutoCaptureFrameParameters:)":{"kind":"symbol","required":true,"role":"symbol","abstract":[{"text":"Validate current frame parameters.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/validate(palmAutoCaptureFrameParameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/validate(palmautocaptureframeparameters:)","title":"validate(palmAutoCaptureFrameParameters:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"DOTPPalmAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current frame parameters."}]}],"name":"palmAutoCaptureFrameParameters"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for the failed validation and "},{"code":"true","type":"codeVoice"},{"type":"text","text":" for the successful validation."}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","op":"replace","value":"DOTPPalmAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title","op":"replace","value":"DOTPPalmAutoCaptureFrameParametersValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1validate(palmAutoCaptureFrameParameters:)\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}]}]}]}