{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(py)delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"symbolKind":"property","roleHeading":"Instance Property","title":"delegate"},"variants":[{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate","text":"PalmAutoCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"abstract":[{"text":"Set this delegate to handle the palm auto capture events.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","kind":"symbol","title":"BasePalmAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"title":"PalmAutoCaptureViewControllerDelegate","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the palm auto capture events."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/delegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/delegate","type":"topic","abstract":[{"type":"text","text":"Set this delegate to handle the palm auto capture events."}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/delegate","title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate","text":"id<DOTPPalmAutoCaptureViewControllerDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","value":"DOTPBasePalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1delegate\/fragments","op":"replace"}]}]}