{"abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","interfaceLanguage":"occ"},"sections":[],"metadata":{"navigatorTitle":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiStateRunning","title":"DOTFFaceAutoCaptureUiStateRunning","role":"symbol","fragments":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/phase","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/preview","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/result"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/isEqual:"],"title":"Instance Methods","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"],"kind":"relationships","title":"Inherits From"}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DOTFFaceAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/result":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/result","fragments":[{"kind":"identifier","text":"result"}],"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/result","title":"result"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/initwithpreview:phase:detection:result:","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","title":"initWithPreview:phase:detection:result:","navigatorTitle":[{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/preview":{"abstract":[{"type":"text","text":"Preview information."}],"fragments":[{"kind":"identifier","text":"preview"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/preview","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/preview","type":"topic","kind":"symbol","title":"preview","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","type":"topic","title":"FaceAutoCaptureUiState","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/isEqual:":{"type":"topic","title":"isEqual:","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/isEqual:","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","fragments":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFFaceAutoCaptureUiStateRunning","type":"topic","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/description":{"kind":"symbol","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/description","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/description","fragments":[{"kind":"identifier","text":"description"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/detection":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/detection","role":"symbol","title":"detection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"fragments":[{"kind":"identifier","text":"detection"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/detection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/hash":{"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/hash","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/hash","title":"hash","fragments":[{"kind":"identifier","text":"hash"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/phase":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/phase","abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/phase","title":"phase","kind":"symbol","fragments":[{"kind":"identifier","text":"phase"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments"},{"value":[{"text":"DOTFFaceAutoCaptureUiState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}