{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase"},"abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"topicSections":[{"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped"],"generated":true},{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/candidateSelection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/preCandidateSelection"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/init(rawValue:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/description"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFaceAutoCapturePhase) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturephase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocapturephase"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/s12CaseIterableP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"FaceAutoCapturePhase"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/preCandidateSelection":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturephase\/precandidateselection","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}],"title":"FaceAutoCapturePhase.preCandidateSelection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/preCandidateSelection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"title":"FaceAutoCapturePhase","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturephase","abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Wrapped":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"title":"FaceAutoCapturePhase.Wrapped","url":"\/documentation\/dotfacecore\/faceautocapturephase\/wrapped","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Equatable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturephase\/equatable-implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/candidateSelection":{"title":"FaceAutoCapturePhase.candidateSelection","abstract":[{"type":"text","text":"Candidate selection is running."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/candidateSelection","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/candidateselection"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/description":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturephase\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/description","role":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/init(rawValue:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturephase\/init(rawvalue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/init(rawValue:)","role":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotFaceCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s12CaseIterableP","title":"Swift.CaseIterable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFaceAutoCapturePhase","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/candidateSelection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/preCandidateSelection"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFaceAutoCapturePhase"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1preCandidateSelection\/title","op":"replace","value":"DOTFaceAutoCapturePhasePreCandidateSelection"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1preCandidateSelection\/fragments","op":"replace","value":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title","op":"replace","value":"DOTFaceAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments","op":"replace","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1candidateSelection\/title","op":"replace","value":"DOTFaceAutoCapturePhaseCandidateSelection"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1candidateSelection\/fragments","op":"replace","value":[{"text":"DOTFaceAutoCapturePhaseCandidateSelection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}