{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"title":"recoverySuggestion","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","platforms":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"8.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"8.0","deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"8.0","deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"introducedAt":"10.10","deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"9.0","deprecated":false},{"name":"watchOS","beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false}],"extendedModule":"Foundation","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/recoverysuggestion"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/recoverySuggestion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"title":"CardAccessNumberPassword","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/recoverySuggestion":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/recoverySuggestion","type":"topic","role":"symbol","abstract":[],"kind":"symbol","title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/recoverysuggestion"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"title":"CardAccessNumberPassword.Error","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}