{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"cameraFacing","symbolKind":"property","role":"symbol","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC12cameraFacing0A6Camera0kJ0Ovp","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/camerafacing"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","title":"CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","kind":"symbol","title":"FaceAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/cameraFacing":{"kind":"symbol","type":"topic","title":"cameraFacing","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/camerafacing","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"}]}]}