{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/height"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangleint\/height"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangleint\/height"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)height","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"extendedModule":"DotCore","navigatorTitle":[{"text":"height","kind":"identifier"}],"role":"symbol","title":"height","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/RectangleInt":{"navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"type":"topic","title":"RectangleInt","role":"symbol","url":"\/documentation\/dotnfc\/rectangleint","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/RectangleInt/height":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/rectangleint\/height","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/height"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"height"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"height"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title","op":"replace","value":"DOTRectangleInt"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1height\/title","op":"replace","value":"height"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1height\/fragments","op":"replace","value":[{"kind":"identifier","text":"height"}]}]}]}