{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController","text":"DocumentAutoCaptureController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DotDocument@objc(cs)DOTDocumentAutoCaptureViewController(im)documentAutoCaptureControllerCandidateSelectionStarted:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/DocumentAutoCaptureControllerDelegate-Implementations"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/documentAutoCaptureControllerCandidateSelectionStarted(_:)":{"role":"symbol","title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollercandidateselectionstarted(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/DocumentAutoCaptureControllerDelegate-Implementations":{"role":"collectionGroup","title":"DocumentAutoCaptureControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/DocumentAutoCaptureControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollerdelegate-implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController","text":"DOTDocumentAutoCaptureController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}