{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/failedToLoadSystemConstants","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"DotSdk.Error.failedToLoadSystemConstants","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"role":"symbol","externalID":"s:7DotCore0A3SdkC5ErrorO27failedToLoadSystemConstantsyA2EmF","symbolKind":"case"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/error\/failedtoloadsystemconstants"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotpalmcore\/dotsdk\/error","abstract":[],"title":"DotSdk.Error","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error/failedToLoadSystemConstants":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/failedToLoadSystemConstants","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/error\/failedtoloadsystemconstants","title":"DotSdk.Error.failedToLoadSystemConstants","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}