{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype"]}],"sections":[],"kind":"symbol","metadata":{"externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC22cameraPreviewScaleTypeAA06CameraijK0Ovp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"role":"symbol","symbolKind":"property","title":"cameraPreviewScaleType","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"type":"topic","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/cameraPreviewScaleType":{"abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType","type":"topic","title":"cameraPreviewScaleType","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]}]}]}