{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:placeholdertype:)"]}],"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"text":"validationMode","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode","kind":"typeIdentifier"},{"text":" = Defaults.validationMode, ","kind":"text"},{"text":"mrzValidation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","kind":"typeIdentifier","text":"MrzValidation","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation"},{"text":" = Defaults.mrzValidation, ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"text":"placeholderType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier","text":"PlaceholderType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType"},{"kind":"text","text":" = Defaults.placeholderType)"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds14validationMode13mrzValidation23isDetectionLayerVisible0Q12TorchEnabled12cameraFacing0W16PreviewScaleType15placeholderTypeAESSSg_AE07QualitykL0CAA0pN0OAA03MrzP0OS2bAA06CameraX0OAA06CamerayZ4TypeOAA15PlaceholderTypeOtcfc","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":", ","kind":"text"},{"text":"validationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"placeholderType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","text":"PlaceholderType"},{"text":")","kind":"text"}],"modules":[{"name":"DotDocument"}],"title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","url":"\/documentation\/dotdocument\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/PlaceholderType":{"url":"\/documentation\/dotdocument\/placeholdertype","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"PlaceholderType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","type":"topic","title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"validationMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mrzValidation"},{"text":": ","kind":"text"},{"text":"MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"placeholderType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"text":")","kind":"text"}],"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:placeholdertype:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"title":"ValidationMode","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation":{"role":"symbol","title":"MrzValidation","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzvalidation","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","title":"CameraFacing","url":"\/documentation\/dotdocument\/camerafacing","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType","op":"replace"},{"op":"replace","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title","op":"replace","value":"DOTDValidationMode"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/title","op":"replace","value":"DOTDMrzValidation"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}