{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"text":"validationMode","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.validationMode, "},{"text":"mrzValidation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","text":"MrzValidation"},{"text":" = Defaults.mrzValidation, ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isVideoCaptureEnabled, ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","text":"PlaceholderType"},{"kind":"text","text":" = Defaults.placeholderType)"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:)"]}],"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"init","role":"symbol","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds14validationMode13mrzValidation23isDetectionLayerVisible0Q12TorchEnabled0q5VideodV012cameraFacing0X16PreviewScaleType15placeholderTypeAESSSg_AE07QualitykL0CAA0pN0OAA03MrzP0OS3b0A6Camera06CameraY0OAW06CameraZ9ScaleTypeOAA15PlaceholderTypeOtcfc","title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"validationMode"},{"text":": ","kind":"text"},{"text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"title":"DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"role":"symbol","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)","title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:)","type":"topic","kind":"symbol","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier","text":"ValidationMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mrzValidation"},{"kind":"text","text":": "},{"text":"MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderType"},{"kind":"text","text":": "},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation","role":"symbol","kind":"symbol","title":"MrzValidation","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/validationmode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}],"title":"ValidationMode","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholdertype","abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"type":"topic","title":"PlaceholderType","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype","title":"CameraPreviewScaleType","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"kind":"symbol","title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityAttributeThresholds"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","type":"topic","navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","type":"topic","url":"\/documentation\/dotdocument\/camerafacing","title":"CameraFacing","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}]},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}