{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Specify MRZ validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/mrzvalidation"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/mrzValidation","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC13mrzValidationAA03MrzI0Ovp","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"symbolKind":"property","title":"mrzValidation","roleHeading":"Instance Property","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/mrzValidation":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/mrzvalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/mrzValidation","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"text":"MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"abstract":[{"type":"text","text":"Specify MRZ validation. Default is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"kind":"symbol","title":"mrzValidation","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"type":"topic","title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.1"}],"type":"topic","title":"DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"title":"MrzValidation","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","type":"topic","kind":"symbol","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]}},"variantOverrides":[{"patch":[{"value":"DOTDMrzValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}