{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"placeholderType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","text":"PlaceholderType"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/placeholdertype"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Specify the type of placeholder used in document auto-capture UI. Default is ","type":"text"},{"type":"codeVoice","code":".cornersOnly"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/placeholderType","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"placeholderType","roleHeading":"Instance Property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC15placeholderTypeAA011PlaceholderI0Ovp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"placeholderType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","text":"PlaceholderType"}],"modules":[{"name":"DotDocument"}],"symbolKind":"property"},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PlaceholderType":{"url":"\/documentation\/dotdocument\/placeholdertype","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"PlaceholderType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/placeholderType":{"role":"symbol","title":"placeholderType","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/placeholdertype","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/placeholderType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"}],"abstract":[{"type":"text","text":"Specify the type of placeholder used in document auto-capture UI. Default is "},{"type":"codeVoice","code":".cornersOnly"},{"text":".","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]}},"variantOverrides":[{"patch":[{"value":"DOTDPlaceholderType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/title"},{"value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/fragments","op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}