{"metadata":{"modules":[{"name":"DotNfc"}],"title":"init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(im)initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","kind":"typeIdentifier","text":"AuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"text":": ","kind":"text"},{"text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encodedIdentificationFeaturesFace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayedSignatureOrUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalPersonalDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"additionalDocumentDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","kind":"typeIdentifier","text":"OptionalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"debugInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","kind":"typeIdentifier","text":"DebugInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-25bwr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-25bwr"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"ldsVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accessControlProtocolUsed","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","text":"AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ldsMasterFile","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encodedIdentificationFeaturesFace","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayedSignatureOrUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalPersonalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalDocumentDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"optionalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"debugInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","text":"DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"kind":"symbol","role":"symbol","title":"AccessControlProtocol","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","type":"topic","abstract":[{"type":"text","text":"Access Control protocol."}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"title":"TravelDocument","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}]},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"title":"EncodedIdentificationFeaturesFace","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"url":"\/documentation\/dotnfc\/debuginfo","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"DebugInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"kind":"symbol","role":"symbol","title":"MachineReadableZoneInformation","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"kind":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"role":"symbol","title":"AdditionalDocumentDetails"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"kind":"symbol","url":"\/documentation\/dotnfc\/ldsmasterfile","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LdsMasterFile","kind":"identifier"}],"navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}],"role":"symbol","title":"LdsMasterFile"},"doc://DotNfc/documentation/DotNfc/TravelDocument/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)":{"abstract":[],"title":"init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ldsVersion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accessControlProtocolUsed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"AuthenticationStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ldsMasterFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"LdsMasterFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"MachineReadableZoneInformation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encodedIdentificationFeaturesFace","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","text":"EncodedIdentificationFeaturesFace","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayedSignatureOrUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalPersonalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"additionalDocumentDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"optionalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"debugInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:"}],"role":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-25bwr"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"kind":"symbol","role":"symbol","title":"OptionalDetails","type":"topic","url":"\/documentation\/dotnfc\/optionaldetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionalDetails","kind":"identifier"}],"navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/authenticationstatus","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"role":"symbol","title":"AuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"title":"AdditionalPersonalDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"title":"DisplayedSignatureOrUsualMark","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLdsVersion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"ldsVersion","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessControlProtocolUsed:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"typeIdentifier","text":"DOTNAccessControlProtocol"},{"kind":"text","text":") "},{"kind":"internalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationStatus:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","kind":"typeIdentifier","text":"DOTNAuthenticationStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"authenticationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"ldsMasterFile:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","kind":"typeIdentifier","text":"DOTNLdsMasterFile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ldsMasterFile"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZoneInformation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","kind":"typeIdentifier","text":"DOTNMachineReadableZoneInformation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","kind":"typeIdentifier","text":"DOTNEncodedIdentificationFeaturesFace"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMark:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"typeIdentifier","text":"DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalPersonalDetails:"},{"kind":"text","text":"("},{"text":"DOTNAdditionalPersonalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"additionalPersonalDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocumentDetails:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"typeIdentifier","text":"DOTNAdditionalDocumentDetails"},{"text":" *) ","kind":"text"},{"text":"additionalDocumentDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"optionalDetails:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","kind":"typeIdentifier","text":"DOTNOptionalDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"optionalDetails"},{"kind":"text","text":" "},{"text":"debugInfo:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTNDebugInfo","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo"},{"kind":"text","text":" *) "},{"text":"debugInfo","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle","op":"replace"},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","op":"replace"},{"value":"DOTNEncodedIdentificationFeaturesFace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","op":"replace"},{"value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/navigatorTitle","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/navigatorTitle","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/navigatorTitle","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)\/title","value":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/navigatorTitle","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title","value":"DOTNAuthenticationStatus","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/navigatorTitle","value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}],"op":"replace"}]}]}