{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Error-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","modules":[{"name":"DotPalmCore"}],"roleHeading":"API Collection","title":"Error Implementations"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error"]]},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/localizedDescription"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","title":"AutoCaptureConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","title":"AutoCaptureConfiguration.Error","type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error","abstract":[],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/localizedDescription":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/localizedDescription","kind":"symbol","abstract":[],"type":"topic","title":"localizedDescription","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}