{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO39invalidCandidateSelectionDurationMillisyA2EmF","modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Case","symbolKind":"case"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","kind":"symbol","abstract":[],"title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","kind":"symbol","type":"topic","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error","abstract":[],"title":"AutoCaptureConfiguration.Error","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}