{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Error-Implementations"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/localizedDescription","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Error.localizedDescription","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"extendedModule":"Swift","symbolKind":"property","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0","name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.10","name":"macOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"9.0","name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0","name":"watchOS"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"DotPalmCore"}],"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","title":"localizedDescription"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/localizedDescription":{"type":"topic","title":"localizedDescription","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/localizeddescription","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/localizedDescription","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/Error-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Error-Implementations","type":"topic","abstract":[],"kind":"article","title":"Error Implementations","role":"collectionGroup","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/error-implementations"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","title":"AutoCaptureConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}