{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(multiRangeLivenessLiteViewControllerNoCameraPermission:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","abstract":[{"text":"Tells the delegate that you have no permission for camera usage.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessLiteViewControllerNoCameraPermission:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"title":"multiRangeLivenessViewControllerNoCameraPermission(_:)","required":true,"role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceLite"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","type":"topic","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"title":"MultiRangeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","role":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerNoCameraPermission(_:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)","kind":"symbol","abstract":[{"text":"Tells the delegate that you have no permission for camera usage.","type":"text"}],"title":"multiRangeLivenessViewControllerNoCameraPermission(_:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","title":"MultiRangeLivenessViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"multiRangeLivenessLiteViewControllerNoCameraPermission:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerNoCameraPermission:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/title","value":"multiRangeLivenessLiteViewControllerNoCameraPermission:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerNoCameraPermission:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]}]}]}