{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","role":"symbol","title":"init(value:isValid:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:isValid:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit(im)initWithValue:isValid:","symbolKind":"init","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit"]]},"variants":[{"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/init(value:isvalid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/init(value:isvalid:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit\/init(value:isValid:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"title":"MrzCheckDigit","url":"\/documentation\/dotdocument\/mrzcheckdigit","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit/init(value:isValid:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isValid"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(value:isValid:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit\/init(value:isValid:)","url":"\/documentation\/dotdocument\/mrzcheckdigit\/init(value:isvalid:)","navigatorTitle":[{"kind":"identifier","text":"initWithValue:isValid:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithValue:isValid:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithValue:isValid:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit~1init(value:isValid:)\/title","value":"initWithValue:isValid:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit~1init(value:isValid:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:isValid:","kind":"identifier"}]}]}]}