{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"title":"dependencyIdentifiers","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooHighValidator(py)dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":">"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"title":"BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator/dependencyIdentifiers":{"role":"symbol","title":"dependencyIdentifiers","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/dependencyIdentifiers","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator\/dependencyidentifiers","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","op":"replace","value":"DOTFLBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]}]}]}