{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"SmileLivenessViewController.Style","symbolKind":"class","extendedModule":"DotFaceCore","modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"sections":[],"seeAlsoSections":[{"anchor":"Style-and-configuration","generated":true,"title":"Style and configuration","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFSmileLivenessStyle) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class"]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:placeholderOverlayColor:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/backgroundColor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/detectionLayerColor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionBackgroundColor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionFont","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionTextColor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/placeholderColor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/placeholderOverlayColor"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/placeholderOverlayColor":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/placeholderOverlayColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderOverlayColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"kind":"symbol","abstract":[{"type":"text","text":"Placeholder overlay color, semi-transparent color is recommended."}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/placeholderoverlaycolor","title":"placeholderOverlayColor"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","kind":"symbol","role":"symbol","title":"SmileLivenessViewController.Configuration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the UI Smile Liveness component."}]},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"type":"topic","kind":"symbol","abstract":[{"text":"UI Smile Liveness component.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class":{"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class","title":"SmileLivenessViewController.Style","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/instructionBackgroundColor":{"abstract":[{"text":"Instruction background color.","type":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/instructionbackgroundcolor","title":"instructionBackgroundColor","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/placeholderColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"text":"Placeholder color.","type":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/placeholdercolor","role":"symbol","kind":"symbol","title":"placeholderColor","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/placeholderColor"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/instructionFont":{"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/instructionfont","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionFont","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"}],"title":"instructionFont","abstract":[{"type":"text","text":"Instruction label font."}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/instructionTextColor":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/instructionTextColor","title":"instructionTextColor","type":"topic","abstract":[{"type":"text","text":"Instruction label text color."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/instructiontextcolor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/backgroundColor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/backgroundColor","abstract":[{"text":"Background color of top level view.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/backgroundcolor","title":"backgroundColor"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:placeholderOverlayColor:)":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/init(backgroundcolor:instructionfont:instructiontextcolor:instructionbackgroundcolor:placeholdercolor:detectionlayercolor:placeholderoverlaycolor:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"instructionFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":", ","kind":"text"},{"text":"instructionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"placeholderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"detectionLayerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"placeholderOverlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"title":"init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:placeholderOverlayColor:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:placeholderOverlayColor:)","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/detectionLayerColor":{"title":"detectionLayerColor","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/detectionLayerColor","abstract":[{"type":"text","text":"Detection layer color."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/detectionlayercolor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionLayerColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/init()":{"kind":"symbol","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/init()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/init()","abstract":[],"type":"topic"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}