{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Pre-candidate selection is running.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase\/precandidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase\/precandidateselection"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"]]},"sections":[],"metadata":{"title":"FingersAutoCapturePhase.preCandidateSelection","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase@DOTFGFingersAutoCapturePhasePreCandidateSelection","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/preCandidateSelection","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/preCandidateSelection":{"title":"FingersAutoCapturePhase.preCandidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"abstract":[{"text":"Pre-candidate selection is running.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/precandidateselection","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/preCandidateSelection"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"text":"Phase of the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePhase","kind":"identifier"}],"title":"FingersAutoCapturePhase","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGFingersAutoCapturePhasePreCandidateSelection","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhasePreCandidateSelection"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFGFingersAutoCapturePhasePreCandidateSelection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1preCandidateSelection\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1preCandidateSelection\/fragments","op":"replace"},{"value":"DOTFGFingersAutoCapturePhase","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","op":"replace"}]}]}