{"metadata":{"navigatorTitle":[{"text":"brightness","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"brightness","role":"symbol","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality(py)brightness"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/brightness"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmimagequality\/brightness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmimagequality\/brightness"]}],"kind":"symbol","abstract":[{"text":"Brightness value in range [0, 1.0].","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmimagequality","navigatorTitle":[{"kind":"identifier","text":"PalmImageQuality"}],"title":"PalmImageQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","abstract":[{"text":"Palm image quality.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/brightness":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmimagequality\/brightness","abstract":[{"text":"Brightness value in range [0, 1.0].","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/brightness","title":"brightness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"brightness"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"brightness","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"brightness"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPPalmImageQuality","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmImageQuality"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmImageQuality"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/navigatorTitle","op":"replace"},{"value":"brightness","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1brightness\/title","op":"replace"},{"value":[{"kind":"identifier","text":"brightness"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1brightness\/fragments","op":"replace"}]}]}