{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholder\/visible\/init(type:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"typeIdentifier"},{"text":" = .cornersOnly)","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/init(type:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"text":")","kind":"text"}],"role":"symbol","title":"init(type:)","externalID":"s:11DotDocument11PlaceholderC7VisibleC4typeAeA0C4TypeO_tcfc","symbolKind":"init","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"]]},"references":{"doc://DotDocument/documentation/DotDocument/Placeholder/Visible/init(type:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/placeholder\/visible\/init(type:)","type":"topic","role":"symbol","title":"init(type:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/init(type:)"},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible":{"kind":"symbol","abstract":[{"type":"text","text":"Visible placeholder."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotdocument\/placeholder\/visible","navigatorTitle":[{"kind":"identifier","text":"Visible"}],"type":"topic","role":"symbol","title":"Placeholder.Visible","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"title":"PlaceholderType","type":"topic","url":"\/documentation\/dotdocument\/placeholdertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"text":"Type of placeholder.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Placeholder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"role":"symbol","kind":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotdocument\/placeholder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments"},{"value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle","op":"replace"},{"op":"replace","value":"DOTDPlaceholder","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title"},{"op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments"},{"op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle"}]}]}