{"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument11PlaceholderC7VisibleC7isEqualySbypSgF","roleHeading":"Instance Method","role":"symbol","title":"isEqual(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"variants":[{"paths":["\/documentation\/dotdocument\/placeholder\/visible\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/isEqual(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"]]},"references":{"doc://DotDocument/documentation/DotDocument/Placeholder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"role":"symbol","kind":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotdocument\/placeholder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible":{"kind":"symbol","abstract":[{"type":"text","text":"Visible placeholder."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotdocument\/placeholder\/visible","navigatorTitle":[{"kind":"identifier","text":"Visible"}],"type":"topic","role":"symbol","title":"Placeholder.Visible","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible/isEqual(_:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotdocument\/placeholder\/visible\/isequal(_:)","type":"topic","role":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/isEqual(_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title","value":"DOTDPlaceholder","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}