{"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg10"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Case","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"iOS"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg10","role":"symbol","title":"Lds1ElementaryFileId.dg10","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg10","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg10","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg10"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"File identifier for data group 10. Data group 10 contains substance features."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg10"]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg10"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"role":"symbol","title":"Lds1ElementaryFileId","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg10":{"kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg10","type":"topic","role":"symbol","abstract":[{"type":"text","text":"File identifier for data group 10. Data group 10 contains substance features."}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg10"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg10","title":"Lds1ElementaryFileId.dg10","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dg10","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg10"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg10"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTNLds1ElementaryFileIdDg10","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"DOTNLds1ElementaryFileId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg10\/title","value":"DOTNLds1ElementaryFileIdDg10","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg10"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg10\/fragments"}]}]}