{"metadata":{"role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(phase:)","externalID":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC5phaseAeC_tcfc"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped\/init(phase:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/wrapped\/init(phase:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"url":"\/documentation\/dotfacelite\/faceautocapturephase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","role":"symbol","title":"FaceAutoCapturePhase","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/Wrapped":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturephase\/wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"abstract":[],"role":"symbol","title":"FaceAutoCapturePhase.Wrapped"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/Wrapped/init(phase:)":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped\/init(phase:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturephase\/wrapped\/init(phase:)","title":"init(phase:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFaceAutoCapturePhase","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments","op":"replace"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle","op":"replace"}]}]}