{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Sample","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC6SampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ProcessingResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"sample","content":[{"inlineContent":[{"type":"text","text":"Input sample. Terminates if "},{"type":"codeVoice","code":"sample.image"},{"type":"text","text":" property is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of processing of the input sample."}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if you call this method after the palm auto capture process has finished."}]}],"style":"note","name":"Throws","type":"aside"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/process(sample:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureController(im)processWithSample:error:","role":"symbol","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"title":"process(sample:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Sample","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC6SampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC"}],"navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Process an input sample and update the state."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/process(sample:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/process(sample:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/process(sample:)":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/process(sample:)","abstract":[{"type":"text","text":"Process an input sample and update the state."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/process(sample:)","navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"title":"process(sample:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC6SampleC","text":"Sample","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Sample":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sample"}],"navigatorTitle":[{"kind":"identifier","text":"Sample"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/sample","kind":"symbol","title":"PalmAutoCaptureController.Sample"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","role":"symbol","kind":"symbol","title":"DOTPPalmAutoCaptureControllerProcessingResult","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerProcessingResult"}],"abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"title":"PalmAutoCaptureController.ProcessingResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","title":"PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample":{"title":"DOTPPalmAutoCaptureControllerSample","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","role":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureControllerSample","kind":"identifier"}],"type":"topic","abstract":[{"text":"The data sample captured at specific time which serves as an input for the palm auto capture process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"processWithSample:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithSample:error:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"DOTPPalmAutoCaptureControllerProcessingResult","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerProcessingResult"},{"text":" *) ","kind":"text"},{"text":"processWithSample:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCaptureControllerSample","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerSample"},{"text":" *) ","kind":"text"},{"text":"sample","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input sample. Terminates if "},{"code":"sample.image","type":"codeVoice"},{"type":"text","text":" property is not in "},{"code":".rawBgra","type":"codeVoice"},{"type":"text","text":" format."}],"type":"paragraph"}],"name":"sample"},{"content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}],"name":"error"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The result of processing of the input sample."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1process(sample:)\/title","value":"processWithSample:error:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1process(sample:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithSample:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}