{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/10Foundation14LocalizedErrorP","doc:\/\/com.innovatrics.dot.face.lite\/s5ErrorP","doc:\/\/com.innovatrics.dot.face.lite\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/missingValidatorDependencies(currentValidator:missingValidators:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/errorDescription-21vr7"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/Error-Implementations","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/LocalizedError-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"FaceAutoCaptureControllerConfiguration.Error","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:11DotFaceLite0B34AutoCaptureControllerConfigurationC5ErrorO","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.lite/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/10Foundation14LocalizedErrorP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error\/error-implementations"},"doc://com.innovatrics.dot.face.lite/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s8SendableP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error/errorDescription-21vr7":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/errorDescription-21vr7","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error\/errordescription-21vr7"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error"},"doc://com.innovatrics.dot.face.lite/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s5ErrorP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error\/localizederror-implementations"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error/missingValidatorDependencies(currentValidator:missingValidators:)":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration.Error.missingValidatorDependencies(currentValidator:missingValidators:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingValidatorDependencies"},{"kind":"text","text":"("},{"kind":"externalParam","text":"currentValidator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"missingValidators"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error\/missingValidatorDependencies(currentValidator:missingValidators:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error\/missingvalidatordependencies(currentvalidator:missingvalidators:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/title","value":"DOTFLFaceAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}