{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.minValidFramesInRowToStartCandidateSelection, "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.candidateSelectionDurationMillis, "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator","text":"FaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"minValidFramesInRowToStartCandidateSelection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection."}]}]},{"name":"candidateSelectionDurationMillis","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Duration of candidate selection phase."}]}]},{"name":"detectionNormalizedRectangle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Normalized rectangle in the input image used for face detection."}]}]},{"name":"validators","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of validators which will be used to validate input image."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error when validator dependencies are missing."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/init(minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/init(minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"title":"init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration(im)initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"role":"symbol","title":"FaceAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 6.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)":{"role":"symbol","title":"init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/init(minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionNormalizedRectangle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<DOTFLFaceAutoCaptureDetectionValidator>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"validators"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","value":"DOTFLFaceAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/title","value":"DOTFLFaceAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)\/title","value":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}