{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/none","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/requirePresenceAndValidity"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/description"],"generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"abstract":[{"type":"text","text":"Mode of barcode validation."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","metadata":{"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"externalID":"c:@M@DotDocument@E@DOTDBarcodeValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"roleHeading":"Enumeration","role":"symbol","title":"BarcodeValidation","modules":[{"name":"DotDocument"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDBarcodeValidation) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently only PDF417 barcodes are supported."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotdocument\/barcodevalidation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcodevalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/BarcodeValidation/init(rawValue:)":{"abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/init(rawValue:)"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/description":{"abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","title":"description","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/description"},"doc://DotDocument/SY":{"identifier":"doc:\/\/DotDocument\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/requirePresenceAndValidity":{"abstract":[{"text":"A barcode must be present and valid.","type":"text"}],"url":"\/documentation\/dotdocument\/barcodevalidation\/requirepresenceandvalidity","navigatorTitle":[{"text":"DOTDBarcodeValidationRequirePresenceAndValidity","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requirePresenceAndValidity"}],"type":"topic","kind":"symbol","title":"BarcodeValidation.requirePresenceAndValidity","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/requirePresenceAndValidity"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/RawRepresentable-Implementations"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/equatable-implementations","type":"topic","kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/Equatable-Implementations"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"url":"\/documentation\/dotdocument\/barcodevalidation","abstract":[{"text":"Mode of barcode validation.","type":"text"}],"title":"BarcodeValidation","role":"symbol","kind":"symbol"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/none":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/none","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDBarcodeValidationNone"}],"url":"\/documentation\/dotdocument\/barcodevalidation\/none","abstract":[{"text":"Barcode presence is not required.","type":"text"}],"title":"BarcodeValidation.none","role":"symbol","kind":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDBarcodeValidation","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/none","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/requirePresenceAndValidity"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDBarcodeValidation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDBarcodeValidationRequirePresenceAndValidity","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1requirePresenceAndValidity\/title"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidationRequirePresenceAndValidity"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1requirePresenceAndValidity\/fragments"},{"value":"DOTDBarcodeValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle"},{"value":"DOTDBarcodeValidationNone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1none\/title"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidationNone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}