{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/s12CaseIterableP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped"],"generated":true,"title":"Classes"},{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/candidateSelection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/preCandidateSelection"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/description"],"generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturephase"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturephase"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Phase of the document auto capture process."}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","externalID":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"modules":[{"name":"DotDocument"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"identifier"}],"symbolKind":"enum","title":"DocumentAutoCapturePhase","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentAutoCapturePhase) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/preCandidateSelection":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/preCandidateSelection","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"preCandidateSelection","kind":"identifier"}],"navigatorTitle":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/precandidateselection","abstract":[{"text":"Pre-candidate selection is running.","type":"text"}],"title":"DocumentAutoCapturePhase.preCandidateSelection","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/RawRepresentable-Implementations","abstract":[],"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/documentautocapturephase\/rawrepresentable-implementations"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/init(rawValue:)","abstract":[],"kind":"symbol","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/init(rawvalue:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Equatable-Implementations","abstract":[],"kind":"article","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/documentautocapturephase\/equatable-implementations"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/candidateSelection":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePhaseCandidateSelection"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/candidateselection","abstract":[{"text":"Candidate selection is running.","type":"text"}],"title":"DocumentAutoCapturePhase.candidateSelection","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/candidateSelection"},"doc://DotDocument/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/Wrapped":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped","navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"abstract":[],"kind":"symbol","title":"DocumentAutoCapturePhase.Wrapped","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/wrapped"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"abstract":[{"type":"text","text":"Phase of the document auto capture process."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturephase","title":"DocumentAutoCapturePhase","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"role":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/description":{"abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturephase\/description","type":"topic","kind":"symbol","title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/description"},"doc://DotDocument/SY":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SY","title":"Swift.RawRepresentable"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTDDocumentAutoCapturePhase"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/candidateSelection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/preCandidateSelection"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCapturePhase"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1preCandidateSelection\/title","op":"replace","value":"DOTDDocumentAutoCapturePhasePreCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1preCandidateSelection\/fragments","value":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1candidateSelection\/title","value":"DOTDDocumentAutoCapturePhaseCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1candidateSelection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePhaseCandidateSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","value":"DOTDDocumentAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}