{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"},"metadata":{"symbolKind":"class","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"roleHeading":"Class","title":"MrzNameElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"},"variants":[{"paths":["\/documentation\/dotdocument\/mrznameelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznameelement"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzNameElement) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"seeAlsoSections":[{"generated":true,"anchor":"MRZ-reading-output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/primaryIdentifier","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/secondaryIdentifier"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/isEqual(_:)"],"generated":true,"title":"Instance Methods"}],"sections":[],"references":{"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"url":"\/documentation\/dotdocument\/mrzstringposition","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"type":"topic","kind":"symbol","title":"MrzStringPosition","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"type":"topic","kind":"symbol","title":"MrzNameElement","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/secondaryIdentifier":{"kind":"symbol","url":"\/documentation\/dotdocument\/mrznameelement\/secondaryidentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/secondaryIdentifier","type":"topic","role":"symbol","navigatorTitle":[{"text":"secondaryIdentifier","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}],"title":"secondaryIdentifier","abstract":[{"type":"text","text":"Secondary identifier usually represents given names."}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/init(primaryIdentifier:secondaryIdentifier:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"secondaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrznameelement\/init(primaryidentifier:secondaryidentifier:)","abstract":[],"title":"init(primaryIdentifier:secondaryIdentifier:)","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"title":"Td2MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"type":"topic","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"title":"MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"title":"MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"title":"Td3MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/isEqual(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/isEqual(_:)","type":"topic","url":"\/documentation\/dotdocument\/mrznameelement\/isequal(_:)","title":"isEqual(_:)","kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzNameElement/hash":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/hash","type":"topic","url":"\/documentation\/dotdocument\/mrznameelement\/hash","title":"hash","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"url":"\/documentation\/dotdocument\/mrzelement","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"type":"topic","kind":"symbol","title":"MrzElement","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/primaryIdentifier":{"abstract":[{"type":"text","text":"Primary identifier usually represents surname."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/primaryIdentifier","navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"title":"primaryIdentifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/mrznameelement\/primaryidentifier"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"abstract":[{"text":"A ","type":"text"},{"code":"MrzElement","type":"codeVoice"},{"text":" with check digit and checksum validitity information.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"type":"topic","kind":"symbol","title":"MrzElementWithCheckDigit","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"title":"Td1MachineReadableZone","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/description":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/description","type":"topic","url":"\/documentation\/dotdocument\/mrznameelement\/description","title":"description","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"title":"MrzDate","role":"symbol","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTMrzNameElement"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/primaryIdentifier","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/secondaryIdentifier"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/isEqual(_:)"],"generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"MRZ-reading-output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"generated":true,"title":"MRZ reading output"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTMrzNameElement","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","op":"replace","value":"DOTMrzStringPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","op":"replace","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1secondaryIdentifier\/title","op":"replace","value":"secondaryIdentifier"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1secondaryIdentifier\/fragments","op":"replace","value":[{"text":"secondaryIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/title","op":"replace","value":"initWithPrimaryIdentifier:secondaryIdentifier:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace","value":"DOTTd2MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/navigatorTitle","op":"replace","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/navigatorTitle","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace","value":"DOTTd3MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/navigatorTitle","op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace","value":"DOTMrzElement"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1primaryIdentifier\/title","op":"replace","value":"primaryIdentifier"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1primaryIdentifier\/fragments","op":"replace","value":[{"text":"primaryIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","op":"replace","value":"DOTTd1MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/navigatorTitle","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace","value":[{"text":"DOTMrzDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzDate","kind":"identifier"}]}]}]}