{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible"]]},"abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"text","text":".cornersOnly"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","text":"DOTDPlaceholderType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdplaceholdervisible\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"type"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDPlaceholderVisible(py)type","fragments":[{"text":"type","kind":"identifier"}],"title":"type","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible\/type"},"references":{"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderVisible":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible","abstract":[{"type":"text","text":"Visible placeholder."}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotdplaceholdervisible","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDPlaceholderVisible"}],"type":"topic","title":"DOTDPlaceholderVisible"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","type":"topic","abstract":[{"text":"Type of placeholder.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/placeholdertype","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","role":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderVisible/type":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible\/type","kind":"symbol","title":"type","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"text","text":".cornersOnly"},{"type":"text","text":"."}],"fragments":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/dotdocument\/dotdplaceholdervisible\/type","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}