{"metadata":{"title":"faceLite","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries(py)faceLite","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"faceLite"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLiteLibraryConfiguration"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries"]]},"sections":[],"abstract":[{"type":"text","text":"Face Lite library configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/faceLite"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/libraries\/facelite"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/libraries\/facelite"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Libraries/faceLite":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/libraries\/facelite","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/faceLite","abstract":[{"text":"Face Lite library configuration.","type":"text"}],"role":"symbol","title":"faceLite","type":"topic","navigatorTitle":[{"text":"faceLite","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"abstract":[{"type":"text","text":"Container for library configurations."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"kind":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"title":"Libraries","role":"symbol","url":"\/documentation\/dotfacecore\/libraries","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLiteLibraryConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLiteLibraryConfiguration","url":"\/documentation\/dotfacecore\/dotfacelitelibraryconfiguration","abstract":[{"text":"Face Lite library configuration.","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceLiteLibraryConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"faceLite"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"faceLite"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1faceLite\/title","op":"replace","value":"faceLite"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1faceLite\/fragments","op":"replace","value":[{"text":"faceLite","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title","op":"replace","value":"Libraries"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLiteLibraryConfiguration\/title","op":"replace","value":"DotFaceLiteLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLiteLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]}]}]}