{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/barcode","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"title":"DotDocumentModuleId.barcode","externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/barcode":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/barcode","navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"title":"DotDocumentModuleId.barcode","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/barcode"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotDocumentModuleIdBarcode","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title","op":"replace"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments","op":"replace"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle","op":"replace"},{"value":"DotDocumentModuleIdBarcode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId~1barcode\/title","op":"replace"},{"value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId~1barcode\/fragments","op":"replace"}]}]}