{"sections":[],"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/!=(_:_:)"],"generated":true,"title":"Operators"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"]]},"kind":"article","metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotDocument"}],"role":"collectionGroup"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/!=(_:_:)":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","title":"!=(_:_:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/!=(_:_:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]}]}]}