{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)hash","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"title":"hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/hash","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagesize\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imagesize\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/imagesize"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 8.8.0","type":"text"}],"type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/hash":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/hash","abstract":[],"url":"\/documentation\/dotfacelite\/imagesize\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","title":"hash"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"hash","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1hash\/title","value":"hash"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1hash\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}