{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/recoverySuggestion"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/intervaldouble\/error\/recoverysuggestion"]}],"metadata":{"extendedModule":"Foundation","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.10"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"recoverySuggestion","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite","relatedModules":["Foundation"]}],"symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error","title":"IntervalDouble.Error","url":"\/documentation\/dotfacelite\/intervaldouble\/error","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble":{"url":"\/documentation\/dotfacelite\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","title":"IntervalDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/Error/recoverySuggestion":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"title":"recoverySuggestion","type":"topic","url":"\/documentation\/dotfacelite\/intervaldouble\/error\/recoverysuggestion","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/recoverySuggestion","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}]}]}