{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"machineReadableZone","navigatorTitle":[{"text":"machineReadableZone","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult(py)machineReadableZone"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/machineReadableZone"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/machinereadablezone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/machinereadablezone"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","abstract":[{"text":"Parsed MRZ.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/machineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}],"title":"machineReadableZone","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/machineReadableZone","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parsed MRZ."}],"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzRecognitionResult","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","navigatorTitle":[{"text":"MrzRecognitionResult","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"url":"\/documentation\/dotdocument\/mrzrecognitionresult","title":"MrzRecognitionResult","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"url":"\/documentation\/dotdocument\/machinereadablezone","kind":"symbol","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","title":"MachineReadableZone","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"machineReadableZone"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"machineReadableZone","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTMachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTMachineReadableZone"},{"text":" * ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"machineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1machineReadableZone\/title"},{"value":[{"kind":"identifier","text":"machineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1machineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title","value":"DOTDMrzRecognitionResult","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments","value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/navigatorTitle","value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace"}]}]}