{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityattributeid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityattributeid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/backgroundUniformity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"title":"QualityAttributeId.backgroundUniformity","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCore@E@DOTQualityAttributeId@DOTQualityAttributeIdBackgroundUniformity","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/backgroundUniformity":{"role":"symbol","title":"QualityAttributeId.backgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/backgroundUniformity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/backgrounduniformity"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTQualityAttributeIdBackgroundUniformity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1backgroundUniformity\/title","value":"DOTQualityAttributeIdBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1backgroundUniformity\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}