{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible\/initWithType:"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotplaceholdervisible\/initwithtype:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholderVisible(im)initWithType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"title":"initWithType:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","text":"DOTPlaceholderType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderVisible":{"abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible","role":"symbol","title":"DOTPlaceholderVisible","type":"topic","fragments":[{"text":"DOTPlaceholderVisible","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotplaceholdervisible"},"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderVisible/initWithType:":{"title":"initWithType:","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible\/initWithType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotplaceholdervisible\/initwithtype:"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"abstract":[{"text":"Type of placeholder.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholdertype","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PlaceholderType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}