{"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"class","title":"DotSdkConfiguration","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotsdkconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/libraries","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/licenseBytes","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/transactionCountingToken"]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"references":{"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)","navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","title":"init(licenseBytes:libraries:transactionCountingToken:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}]},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"kind":"symbol","title":"DotSdkConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/licenseBytes":{"role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/licensebytes","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/licenseBytes","title":"licenseBytes","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"abstract":[{"text":"License data.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/libraries":{"role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/libraries","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/libraries","title":"libraries","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"libraries","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"libraries"}],"abstract":[{"text":"List of ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" libraries to use."}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/transactionCountingToken":{"role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/transactioncountingtoken","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/transactionCountingToken","title":"transactionCountingToken","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"transactionCountingToken","kind":"identifier"}],"abstract":[{"type":"text","text":"Transaction counting token."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"DotSdkConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdkConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/libraries","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/licenseBytes","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/transactionCountingToken"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"]}]},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/title","value":"DotSdkConfiguration","op":"replace"},{"value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/fragments"},{"value":"licenseBytes","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1licenseBytes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1licenseBytes\/fragments"},{"value":"libraries","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1libraries\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1libraries\/fragments","value":[{"kind":"identifier","text":"libraries"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1transactionCountingToken\/title","op":"replace","value":"transactionCountingToken"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1transactionCountingToken\/fragments","value":[{"text":"transactionCountingToken","kind":"identifier"}]}]}]}