{"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/init(sharpness:brightness:hotspotsScore:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/brightness","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/hotspotsScore","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/sharpness"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters"},"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparameters"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDImageParameters","roleHeading":"Class","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"title":"ImageParameters"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDImageParameters) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/ImageParameters/sharpness":{"kind":"symbol","abstract":[{"type":"text","text":"Overall sharpness of the document in range [0, 1.0]. Where 0 means low sharpness and 1.0 means high sharpness."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sharpness","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/sharpness","url":"\/documentation\/dotdocument\/imageparameters\/sharpness","navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"title":"sharpness","type":"topic"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/ImageParameters/hotspotsScore":{"kind":"symbol","abstract":[{"type":"text","text":"Overall hotspots score of the document in range [0, 1.0]. Where 0 means low hotspots occurrence and 1.0 means high hotspots occurrence."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"hotspotsScore","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/hotspotsScore","url":"\/documentation\/dotdocument\/imageparameters\/hotspotsscore","navigatorTitle":[{"kind":"identifier","text":"hotspotsScore"}],"title":"hotspotsScore","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/ImageParameters/description":{"title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/imageparameters\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/ImageParameters/init(sharpness:brightness:hotspotsScore:)":{"kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"code":"ImageParameters","type":"codeVoice"},{"text":" with normalized values in range [0, 1.0].","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"hotspotsScore","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/init(sharpness:brightness:hotspotsScore:)","url":"\/documentation\/dotdocument\/imageparameters\/init(sharpness:brightness:hotspotsscore:)","navigatorTitle":[{"text":"initWithSharpness:brightness:hotspotsScore:","kind":"identifier"}],"title":"init(sharpness:brightness:hotspotsScore:)","type":"topic"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"title":"ImageParameters","url":"\/documentation\/dotdocument\/imageparameters","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImageParameters/brightness":{"kind":"symbol","abstract":[{"type":"text","text":"Overall brightness of the document in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/brightness","url":"\/documentation\/dotdocument\/imageparameters\/brightness","navigatorTitle":[{"text":"brightness","kind":"identifier"}],"title":"brightness","type":"topic"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTDImageParameters","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTDImageParameters","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDImageParameters"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/brightness","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/hotspotsScore","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/sharpness"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/init(sharpness:brightness:hotspotsScore:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTDImageParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"sharpness","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1sharpness\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1sharpness\/fragments","op":"replace","value":[{"kind":"identifier","text":"sharpness"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1hotspotsScore\/title","value":"hotspotsScore"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1hotspotsScore\/fragments","value":[{"kind":"identifier","text":"hotspotsScore"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1description\/title","op":"replace","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1description\/fragments","op":"replace"},{"value":"initWithSharpness:brightness:hotspotsScore:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1init(sharpness:brightness:hotspotsScore:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1init(sharpness:brightness:hotspotsScore:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSharpness:brightness:hotspotsScore:"}]},{"value":"DOTDImageParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"text":"DOTDImageParameters","kind":"identifier"}]},{"value":"brightness","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1brightness\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1brightness\/fragments","value":[{"kind":"identifier","text":"brightness"}],"op":"replace"}]}]}