{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","text":"MrzValidation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/defaults\/mrzvalidation"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults\/mrzValidation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"title":"mrzValidation","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:11DotDocument0B24AutoCaptureConfigurationC8DefaultsV13mrzValidationAA03MrzH0OvpZ","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Defaults/mrzValidation":{"role":"symbol","title":"mrzValidation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults\/mrzValidation","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/defaults\/mrzvalidation"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Defaults":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/defaults"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation":{"role":"symbol","title":"MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}