{"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"cameraPreviewScaleType","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"}],"externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV22cameraPreviewScaleType0A6Camera0nklM0OvpZ","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","text":"CameraPreviewScaleType"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.12.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/Defaults":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/defaults","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Defaults","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration.Defaults","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/Defaults/cameraPreviewScaleType":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}],"title":"cameraPreviewScaleType","abstract":[],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","title":"PalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"}]}]}