{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateContrast","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"evaluateContrast","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateContrast","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","role":"symbol","title":"evaluateContrast","roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(py)evaluateContrast","modules":[{"name":"DotFaceCore"}]},"abstract":[{"text":"Contrast evaluation flag.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateContrast"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatecontrast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatecontrast"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"title":"FaceImageQualityQuery","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateContrast":{"title":"evaluateContrast","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateContrast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatecontrast","type":"topic","navigatorTitle":[{"text":"evaluateContrast","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Contrast evaluation flag."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateContrast"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"evaluateContrast","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"evaluateContrast","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateContrast"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle"},{"op":"replace","value":"evaluateContrast","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateContrast\/title"},{"op":"replace","value":[{"text":"evaluateContrast","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateContrast\/fragments"}]}]}