{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator"]}],"abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"seeAlsoSections":[{"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","type":"conformsTo"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"DocumentDoesNotFitPlaceholderValidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDoesNotFitPlaceholderValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"modules":[{"name":"DotDocument"}]},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/maxPenaltyThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/placeholderNormalizedRectangle"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/defaultMaxPenaltyThreshold"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentDoesNotFitPlaceholderValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","type":"topic","abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"title":"DocumentDoesNotFitPlaceholderValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentOutOfBoundsValidator":{"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","type":"topic","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"title":"DocumentOutOfBoundsValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotValidValidator":{"title":"MrzNotValidValidator","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","type":"topic"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/maxPenaltyThreshold":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/maxpenaltythreshold","role":"symbol","abstract":[{"type":"text","text":"Current maximal penalty threshold. Penalty value is low when detected document is well aligned with placeholder and vice versa."}],"navigatorTitle":[{"text":"maxPenaltyThreshold","kind":"identifier"}],"title":"maxPenaltyThreshold","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/maxPenaltyThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"maxPenaltyThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/identifier":{"title":"identifier","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/identifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/identifier","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","title":"DocumentNotDetectedValidator","type":"topic","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/validate(documentAutoCaptureFrameParameters:)":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/validate(documentautocaptureframeparameters:)","abstract":[{"type":"text","text":"Validate position of the detected document relative to the placeholder."}],"title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/dependencyIdentifiers":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/dependencyidentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"kind":"symbol","type":"topic","title":"dependencyIdentifiers","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/dependencyIdentifiers","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","type":"topic","abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"title":"DocumentAutoCaptureDetectionValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)":{"abstract":[{"text":"Initialize with custom penalty threshold and normalized placeholder rectangle.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/init(placeholdernormalizedrectangle:maxpenaltythreshold:)","title":"init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"placeholderNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"maxPenaltyThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/defaultMaxPenaltyThreshold":{"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/defaultmaxpenaltythreshold","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/defaultMaxPenaltyThreshold","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMaxPenaltyThreshold"}],"type":"topic","abstract":[{"text":"Default threshold is 0.035.","type":"text"}],"title":"defaultMaxPenaltyThreshold","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultMaxPenaltyThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/placeholderNormalizedRectangle":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/placeholderNormalizedRectangle","role":"symbol","title":"placeholderNormalizedRectangle","abstract":[{"text":"Placeholder normalized rectangle.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderNormalizedRectangle"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"placeholderNormalizedRectangle"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/placeholdernormalizedrectangle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/maxPenaltyThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/placeholderNormalizedRectangle"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/validate(documentAutoCaptureFrameParameters:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/defaultMaxPenaltyThreshold"],"title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"type":"conformsTo"}]},{"value":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator"]}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","value":"DOTDDocumentOutOfBoundsValidator","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotValidValidator\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1maxPenaltyThreshold\/title","op":"replace","value":"maxPenaltyThreshold"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1maxPenaltyThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxPenaltyThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}]},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1init(placeholderNormalizedRectangle:maxPenaltyThreshold:)\/title","value":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1init(placeholderNormalizedRectangle:maxPenaltyThreshold:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1defaultMaxPenaltyThreshold\/title","value":"defaultMaxPenaltyThreshold"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1defaultMaxPenaltyThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMaxPenaltyThreshold"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"value":"placeholderNormalizedRectangle","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1placeholderNormalizedRectangle\/title"},{"value":[{"text":"placeholderNormalizedRectangle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1placeholderNormalizedRectangle\/fragments","op":"replace"}]}]}