{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDValidationMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotDocument"}],"title":"ValidationMode","roleHeading":"Enumeration","externalID":"c:@M@DotDocument@E@DOTDValidationMode","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationMode","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/validationmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/validationmode"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/standard","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/strict"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/description"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/RawRepresentable-Implementations"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotdocument\/validationmode\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/validationmode","title":"ValidationMode","role":"symbol","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/init(rawValue:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","url":"\/documentation\/dotdocument\/validationmode\/init(rawvalue:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotdocument\/validationmode\/equatable-implementations","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/strict":{"kind":"symbol","abstract":[{"type":"text","text":"Document must be clearly visible, sharp enough and well aligned with the placeholder."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"strict","kind":"identifier"}],"url":"\/documentation\/dotdocument\/validationmode\/strict","title":"ValidationMode.strict","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/strict","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStrict"}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/standard":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStandard"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/standard","title":"ValidationMode.standard","url":"\/documentation\/dotdocument\/validationmode\/standard","abstract":[{"type":"text","text":"Document must be clearly visible and sharp enough."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"standard"}]},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode/description":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/validationmode\/description","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/description","title":"description"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/SY":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DOTDValidationMode","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/standard","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode\/strict"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDValidationMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"DOTDValidationMode","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode~1strict\/title","value":"DOTDValidationModeStrict"},{"value":[{"text":"DOTDValidationModeStrict","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode~1strict\/fragments"},{"value":"DOTDValidationModeStandard","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode~1standard\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode~1standard\/fragments","value":[{"text":"DOTDValidationModeStandard","kind":"identifier"}],"op":"replace"}]}]}