{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg15ActiveAuthenticationPublicKeyInfo","interfaceLanguage":"swift"},"abstract":[{"text":"Raw data group DG15.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"title":"dg15ActiveAuthenticationPublicKeyInfo","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg15ActiveAuthenticationPublicKeyInfo","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg15activeauthenticationpublickeyinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg15activeauthenticationpublickeyinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"title":"Lds1eMrtdApplication","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"type":"topic","role":"symbol","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"title":"Lds1ElementaryFile","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","kind":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication/dg15ActiveAuthenticationPublicKeyInfo":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg15ActiveAuthenticationPublicKeyInfo","navigatorTitle":[{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"}],"abstract":[{"text":"Raw data group DG15.","type":"text"}],"title":"dg15ActiveAuthenticationPublicKeyInfo","kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg15activeauthenticationpublickeyinfo","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 8.2.0"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dg15ActiveAuthenticationPublicKeyInfo","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNLds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg15ActiveAuthenticationPublicKeyInfo\/title","value":"dg15ActiveAuthenticationPublicKeyInfo"},{"op":"replace","value":[{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg15ActiveAuthenticationPublicKeyInfo\/fragments"}]}]}