{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Raw data group DG5."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg5DisplayedPortrait"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg5displayedportrait"]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg5displayedportrait"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg5DisplayedPortrait","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dg5DisplayedPortrait"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg5DisplayedPortrait","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dg5DisplayedPortrait","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"role":"symbol","platforms":[{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false}],"title":"dg5DisplayedPortrait","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","kind":"symbol","title":"TravelDocument","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"title":"Lds1ElementaryFile","type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfile","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg5DisplayedPortrait":{"navigatorTitle":[{"kind":"identifier","text":"dg5DisplayedPortrait"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dg5DisplayedPortrait","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg5DisplayedPortrait","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg5displayedportrait","kind":"symbol","title":"dg5DisplayedPortrait","abstract":[{"type":"text","text":"Raw data group DG5."}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.10.0"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}],"title":"Lds1eMrtdApplication","type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"dg5DisplayedPortrait"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dg5DisplayedPortrait"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg5DisplayedPortrait"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"value":"DOTNLds1ElementaryFile","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"value":"dg5DisplayedPortrait","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg5DisplayedPortrait\/title","op":"replace"},{"value":[{"kind":"identifier","text":"dg5DisplayedPortrait"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg5DisplayedPortrait\/fragments"},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}]}]}]}