{"abstract":[{"text":"Face keypoints.","type":"text"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceKeypoints","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints","kind":"typeIdentifier"}],"title":"faceKeypoints","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B8DetectorC0B0C13faceKeypointsAA0bF0Cvp","role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"faceKeypoints","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/facekeypoints"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/faceKeypoints","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"url":"\/documentation\/dotfacecore\/facedetector\/face","role":"symbol","navigatorTitle":[{"text":"Face","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/faceKeypoints":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceKeypoints"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints"}],"abstract":[{"text":"Face keypoints.","type":"text"}],"type":"topic","title":"faceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/faceKeypoints","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face\/facekeypoints"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"url":"\/documentation\/dotfacecore\/facekeypoints","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"title":"FaceKeypoints"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTFFaceKeypoints","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace","value":"DOTFFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}