{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller"]}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","seeAlsoSections":[{"title":"Non-UI components","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDDocumentAutoCaptureController) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","title":"DocumentAutoCaptureController","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureController","modules":[{"name":"DotDocument"}]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"],"title":"Configuration"},{"title":"Document auto capture process","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"title":"Validators"},{"title":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/init(configuration:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/configuration-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:timestampMillis:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(sample:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Phase"],"title":"Enumerations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"references":{"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected document.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"title":"DocumentOutOfBoundsValidator","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","type":"topic","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","kind":"symbol","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","type":"topic","abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"title":"HotspotsScoreTooHighValidator","role":"symbol","navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"title":"DocumentAutoCaptureResult","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","type":"topic","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"title":"MrzNotValidValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/process(sample:)":{"title":"process(sample:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Process an input sample and update the state."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(sample:)","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/process(sample:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"text":"Sample","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC6SampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC"}],"navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample","navigatorTitle":[{"kind":"identifier","text":"Sample"}],"title":"DocumentAutoCaptureController.Sample","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","type":"topic","abstract":[{"type":"text","text":"Validate size of the detected document."}],"title":"SizeTooSmallValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"url":"\/documentation\/dotdocument\/imageperspectivewarper","title":"ImagePerspectiveWarper","abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Phase":{"type":"topic","role":"symbol","title":"DocumentAutoCaptureController.Phase","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Phase","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/phase","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Phase"}],"abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Phase"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","type":"topic","abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"title":"DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error","type":"topic","title":"DocumentAutoCaptureController.Error","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","type":"topic","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"title":"DocumentNotDetectedValidator","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"title":"DocumentDoesNotFitPlaceholderValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"type":"topic","title":"DocumentAutoCaptureController.Configuration","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/configuration-swift.property":{"title":"configuration","kind":"symbol","type":"topic","abstract":[{"text":"Current configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/configuration-swift.property","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","type":"topic","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","title":"DocumentAutoCaptureController.ProcessingResult","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"role":"symbol","abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/ImageParametersAnalyzer":{"title":"ImageParametersAnalyzer","navigatorTitle":[{"kind":"identifier","text":"ImageParametersAnalyzer"}],"role":"symbol","abstract":[{"text":"Stateless class which can analyze image parameters.","type":"text"}],"url":"\/documentation\/dotdocument\/imageparametersanalyzer","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParametersAnalyzer","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"type":"topic","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"title":"DocumentAutoCaptureDetection","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","title":"DocumentAutoCaptureFrameParameters"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/process(bgraRawImage:timestampMillis:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC"}],"role":"symbol","title":"process(bgraRawImage:timestampMillis:)","navigatorTitle":[{"kind":"identifier","text":"processWithBgraRawImage:timestampMillis:error:"}],"type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Process an input image or video frame and update the state."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:timestampMillis:)","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:timestampmillis:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/init(configuration:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(configuration:)","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Create new instance of "},{"type":"codeVoice","code":"DocumentAutoCaptureController"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/init(configuration:)","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/init(configuration:)"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","type":"topic","abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"title":"SharpnessTooLowValidator","role":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Document auto capture process","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]},{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/configuration-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/init(configuration:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:timestampMillis:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(sample:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"],"title":"Non-UI components","generated":true}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments"},{"value":"DOTDDocumentOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}]},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}]},{"op":"replace","value":"DOTDDocumentAutoCaptureResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments"},{"op":"replace","value":"DOTDMrzNotValidValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments"},{"value":"processWithSample:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(sample:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(sample:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator"},{"value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"value":"DOTDDocumentAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments"},{"value":"DOTDDocumentNotDetectedValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments"},{"op":"replace","value":"configuration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1configuration-swift.property\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1configuration-swift.property\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","value":"DOTDImageParametersAnalyzer","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/title","op":"replace","value":"processWithBgraRawImage:timestampMillis:error:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"processWithBgraRawImage:timestampMillis:error:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1init(configuration:)\/title","value":"initWithConfiguration:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1init(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:","kind":"identifier"}]},{"value":"DOTDSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}