{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/transformation"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/description"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId"},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotFingersModuleId","modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"DotFingersModuleId","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/description":{"kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/description","role":"symbol","title":"description"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/transformation":{"title":"DotFingersModuleId.transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/transformation","navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/transformation","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}]},"doc://DotPalmCore/SY":{"identifier":"doc:\/\/DotPalmCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/equatable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/init(rawValue:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/init(rawValue:)","role":"symbol","title":"init(rawValue:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId":{"role":"symbol","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersmoduleid","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"kind":"symbol","title":"DotFingersModuleId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/detection":{"kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/detection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/detection","role":"symbol","title":"DotFingersModuleId.detection","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DotFingersModuleId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/transformation"],"generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersModuleId"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFingersModuleIdTransformation","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1transformation\/title"},{"value":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1transformation\/fragments"},{"value":"DotFingersModuleId","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/title"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace"},{"value":"DotFingersModuleIdDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1detection\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1detection\/fragments","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"op":"replace"}]}]}