{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder"},"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPlaceholder) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/placeholder"]}],"abstract":[{"text":"Placeholder.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible"],"type":"inheritedBy"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"kind":"symbol","metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","title":"Placeholder","role":"symbol","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}]},"references":{"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Visible":{"title":"Placeholder.Visible","kind":"symbol","type":"topic","abstract":[{"text":"Visible placeholder.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/placeholder\/visible","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderHidden":{"role":"symbol","fragments":[{"text":"DOTPPlaceholderHidden","kind":"identifier"}],"abstract":[{"type":"text","text":"Hidden placeholder."}],"url":"\/documentation\/dotpalmcore\/dotpplaceholderhidden","kind":"symbol","title":"DOTPPlaceholderHidden","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderHidden","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholder/init":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholder\/init","role":"symbol","abstract":[],"title":"init","url":"\/documentation\/dotpalmcore\/dotpplaceholder\/init","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Hidden":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden","role":"symbol","abstract":[{"text":"Hidden placeholder.","type":"text"}],"title":"Placeholder.Hidden","url":"\/documentation\/dotpalmcore\/placeholder\/hidden","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"navigatorTitle":[{"text":"Hidden","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"kind":"symbol","abstract":[{"text":"Placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","url":"\/documentation\/dotpalmcore\/placeholder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible":{"abstract":[{"text":"Visible placeholder.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible","kind":"symbol","title":"DOTPPlaceholderVisible","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible","fragments":[{"kind":"identifier","text":"DOTPPlaceholderVisible"}]},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTPPlaceholder","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholder\/init"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderHidden","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPlaceholder"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","value":"DOTPPlaceholder","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"op":"replace"}]}]}