{"variants":[{"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(bgrRawImage:)"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithBgrRawImage:","modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","symbolKind":"method","title":"create(bgrRawImage:)","role":"symbol","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory"]]},"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" object."}]}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory/create(bgrRawImage:)":{"url":"\/documentation\/dotdocument\/bgrarawimagefactory\/create(bgrrawimage:)","title":"create(bgrRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"kind":"symbol","type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(bgrRawImage:)"},"doc://DotDocument/documentation/DotDocument/BgrRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","url":"\/documentation\/dotdocument\/bgrrawimage","type":"topic"},"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"title":"BgraRawImageFactory","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"url":"\/documentation\/dotdocument\/bgrarawimagefactory","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWithBgrRawImage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithBgrRawImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","kind":"typeIdentifier","text":"DOTBgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"bgrRawImage"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" instance."}],"type":"paragraph"}]}},{"value":"createWithBgrRawImage:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(bgrRawImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(bgrRawImage:)\/fragments"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/fragments"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/navigatorTitle"},{"value":"DOTBgraRawImageFactory","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/fragments"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/navigatorTitle"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/navigatorTitle","op":"replace"}]}]}