{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNDataAuthenticationStatusProtocol) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/passiveAuthentication"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations"]}],"metadata":{"role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"externalID":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"title":"DataAuthenticationStatus.AuthenticationProtocol","modules":[{"name":"DotNfc"}],"symbolKind":"enum"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Protocol for authentication of the data.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/passiveAuthentication":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/passiveauthentication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/passiveAuthentication","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveAuthentication"}],"type":"topic","title":"DataAuthenticationStatus.AuthenticationProtocol.passiveAuthentication","abstract":[{"text":"Passive Authentication protocol.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/Equatable-Implementations":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/equatable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"role":"collectionGroup"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/SY":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY","title":"Swift.RawRepresentable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum","abstract":[{"type":"text","text":"Protocol for authentication of the data."}],"type":"topic","title":"DataAuthenticationStatus.AuthenticationProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","kind":"symbol","navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationProtocol","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus","abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","title":"DataAuthenticationStatus","type":"topic","navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/init(rawValue:)","abstract":[],"role":"symbol","title":"init(rawValue:)","type":"topic","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/init(rawvalue:)"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/RawRepresentable-Implementations":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/rawrepresentable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/description","abstract":[],"role":"symbol","type":"topic","title":"description","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/description"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace","value":"DOTNDataAuthenticationStatus"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}