{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationProtocol"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","kind":"typeIdentifier","text":"AuthenticationProtocol","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/init(status:authenticationProtocol:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/init(status:authenticationprotocol:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/init(status:authenticationprotocol:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:authenticationProtocol:"}],"title":"init(status:authenticationProtocol:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationProtocol","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"},{"kind":"text","text":")"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus(im)initWithStatus:authenticationProtocol:"},"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/init(status:authenticationProtocol:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:authenticationProtocol:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/init(status:authenticationProtocol:)","kind":"symbol","title":"init(status:authenticationProtocol:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationProtocol","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/init(status:authenticationprotocol:)"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus","title":"DataAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum","role":"symbol","kind":"symbol","title":"DataAuthenticationStatus.AuthenticationProtocol","abstract":[{"text":"Protocol for authentication of the data.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusStatus":{"type":"topic","fragments":[{"text":"DOTNDataAuthenticationStatusStatus","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Authentication status of the data."}],"title":"DOTNDataAuthenticationStatusStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus","url":"\/documentation\/dotnfc\/dotndataauthenticationstatusstatus","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusProtocol":{"url":"\/documentation\/dotnfc\/dotndataauthenticationstatusprotocol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","fragments":[{"kind":"identifier","text":"DOTNDataAuthenticationStatusProtocol"}],"title":"DOTNDataAuthenticationStatusProtocol","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Protocol for authentication of the data."}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","title":"DataAuthenticationStatus.Status","type":"topic","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum","abstract":[{"text":"Authentication status of the data.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"navigatorTitle":[{"kind":"identifier","text":"Status"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithStatus:authenticationProtocol:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatus:authenticationProtocol:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTNDataAuthenticationStatusStatus","text":"DOTNDataAuthenticationStatusStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"authenticationProtocol:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","text":"DOTNDataAuthenticationStatusProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNDataAuthenticationStatusProtocol"},{"text":") ","kind":"text"},{"text":"authenticationProtocol","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithStatus:authenticationProtocol:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1init(status:authenticationProtocol:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatus:authenticationProtocol:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1init(status:authenticationProtocol:)\/fragments","op":"replace"},{"value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace"},{"value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace"},{"value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle","op":"replace"}]}]}