{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerallcornersused(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerallcornersused(_:)"]}],"sections":[],"metadata":{"title":"eyeGazeLivenessViewControllerAllCornersUsed(_:)","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewControllerAllCornersUsed:","symbolKind":"method","required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerAllCornersUsed","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerAllCornersUsed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"abstract":[{"text":"Tells the delegate that the eye gaze liveness cannot continue because all corners were used and not enough valid samples were captured.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This callback is called after the component has stopped."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerAllCornersUsed(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerAllCornersUsed(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness cannot continue because all corners were used and not enough valid samples were captured."},{"type":"text","text":" "},{"type":"text","text":"This callback is called after the component has stopped."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerallcornersused(_:)","required":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerAllCornersUsed(_:)","kind":"symbol","title":"eyeGazeLivenessViewControllerAllCornersUsed(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed:"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","navigatorTitle":[{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"title":"EyeGazeLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this delegate to handle the eye gaze liveness events.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"title":"EyeGazeLivenessViewController","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"eyeGazeLivenessViewControllerAllCornersUsed:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"eyeGazeLivenessViewControllerAllCornersUsed:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerAllCornersUsed(_:)\/title","value":"eyeGazeLivenessViewControllerAllCornersUsed:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewControllerAllCornersUsed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerAllCornersUsed(_:)\/fragments"},{"op":"replace","value":"DOTFEyeGazeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]}]}]}