{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState","text":"EyeGazeLivenessState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:statechanged:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:statechanged:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:stateChanged:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness state has changed."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewController:stateChanged:"}],"role":"symbol","title":"eyeGazeLivenessViewController(_:stateChanged:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessState","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewController:stateChanged:","required":true,"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState":{"role":"symbol","title":"EyeGazeLivenessState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessState"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"role":"symbol","title":"EyeGazeLivenessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewController(_:stateChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewController:stateChanged:"}],"role":"symbol","title":"eyeGazeLivenessViewController(_:stateChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessState","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness state has changed."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:stateChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:statechanged:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"eyeGazeLivenessViewController:stateChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewController:stateChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"eyeGazeLivenessViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateChanged:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState","text":"DOTFEyeGazeLivenessState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/title","value":"DOTFEyeGazeLivenessState"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title","value":"DOTFEyeGazeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:stateChanged:)\/title","value":"eyeGazeLivenessViewController:stateChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:stateChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewController:stateChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}