{"metadata":{"modules":[{"name":"DotFaceCore"}],"required":true,"role":"symbol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewController:finished:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewController:finished:"}],"roleHeading":"Instance Method","title":"eyeGazeLivenessViewController(_:finished:)"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:finished:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:finished:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness has finished with result. This callback is called after the component has stopped."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"finished"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult","text":"EyeGazeLivenessResult"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:finished:)"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"kind":"symbol","type":"topic","title":"EyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewController(_:finished:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewController:finished:"}],"title":"eyeGazeLivenessViewController(_:finished:)","abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness has finished with result. This callback is called after the component has stopped."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:finished:)","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:finished:)","required":true},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","url":"\/documentation\/dotfacecore\/eyegazelivenessresult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessResult"}],"role":"symbol","abstract":[{"type":"text","text":"The final result of the eye gaze liveness process."}],"title":"EyeGazeLivenessResult"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","title":"EyeGazeLivenessViewControllerDelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"eyeGazeLivenessViewController:finished:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewController:finished:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"eyeGazeLivenessViewController:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"finished:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFEyeGazeLivenessResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:finished:)\/title","value":"eyeGazeLivenessViewController:finished:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewController:finished:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:finished:)\/fragments"},{"value":"DOTFEyeGazeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments","value":[{"text":"DOTFEyeGazeLivenessResult","kind":"identifier"}]},{"value":"DOTFEyeGazeLivenessViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}]}]}]}