{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerfacetrackingfailed(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerfacetrackingfailed(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerFaceTrackingFailed(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that face tracking has failed. This callback is called after the component has stopped."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed:"}],"role":"symbol","title":"eyeGazeLivenessViewControllerFaceTrackingFailed(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewControllerFaceTrackingFailed:","required":true,"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"role":"symbol","title":"EyeGazeLivenessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerFaceTrackingFailed(_:)":{"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed:"}],"role":"symbol","title":"eyeGazeLivenessViewControllerFaceTrackingFailed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that face tracking has failed. This callback is called after the component has stopped."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerFaceTrackingFailed(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerfacetrackingfailed(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"eyeGazeLivenessViewControllerFaceTrackingFailed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title","value":"DOTFEyeGazeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerFaceTrackingFailed(_:)\/title","value":"eyeGazeLivenessViewControllerFaceTrackingFailed:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerFaceTrackingFailed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerFaceTrackingFailed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}