{"metadata":{"title":"eyeGazeLivenessViewControllerViewWillDisappear(_:)","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewControllerViewWillDisappear:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewWillDisappear:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"required":true,"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwilldisappear(_:)"]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillDisappear(_:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewWillDisappear(_:)":{"title":"eyeGazeLivenessViewControllerViewWillDisappear(_:)","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwilldisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillDisappear:"}],"abstract":[],"type":"topic","required":true,"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"title":"EyeGazeLivenessViewControllerDelegate","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","role":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this delegate to handle the eye gaze liveness events.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"type":"topic","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"title":"EyeGazeLivenessViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"eyeGazeLivenessViewControllerViewWillDisappear:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewWillDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier","text":"DOTFEyeGazeLivenessViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillDisappear(_:)\/title","value":"eyeGazeLivenessViewControllerViewWillDisappear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillDisappear:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillDisappear(_:)\/fragments"},{"op":"replace","value":"DOTFEyeGazeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title"},{"value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments"},{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]}]}]}