{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A rectangular region defined relative to the container where the camera image is displayed in the container."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/cameraImage","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(py)cameraImage","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"title":"cameraImage","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"cameraImage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, "},{"type":"codeVoice","code":"RectangleDouble(left=0.0, top=0.25, right=1.0, bottom=0.75)"},{"type":"text","text":" means that the "},{"type":"codeVoice","code":"cameraImage"},{"type":"text","text":" is positioned in the full width of the container,"},{"type":"text","text":" "},{"type":"text","text":"but the height is shorter than the container height. This is typical for scale type "},{"type":"codeVoice","code":"CameraPreviewScaleType.fit"},{"type":"text","text":"."}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/cameraimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/cameraimage"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/cameraImage":{"title":"cameraImage","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/cameraImage","navigatorTitle":[{"text":"cameraImage","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotfacelite\/faceautocapturepreview\/cameraimage","type":"topic","abstract":[{"type":"text","text":"A rectangular region defined relative to the container where the camera image is displayed in the container."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"title":"FaceAutoCapturePreview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","title":"RectangleDouble","url":"\/documentation\/dotfacelite\/rectangledouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cameraImage","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"cameraImage"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cameraImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1cameraImage\/title","op":"replace"},{"value":[{"text":"cameraImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1cameraImage\/fragments","op":"replace"},{"value":"DOTFaceAutoCapturePreview","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","op":"replace"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle","op":"replace"}]}]}