{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A value defined relative to the container shorter side that represents the placeholder diameter."}],"metadata":{"symbolKind":"property","externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(py)placeholderDiameterToShorterSideRatio","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"placeholderDiameterToShorterSideRatio","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/placeholderdiametertoshortersideratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/placeholderdiametertoshortersideratio"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"title":"FaceAutoCapturePreview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/placeholderDiameterToShorterSideRatio":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"}],"title":"placeholderDiameterToShorterSideRatio","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview\/placeholderdiametertoshortersideratio","role":"symbol","abstract":[{"text":"A value defined relative to the container shorter side that represents the placeholder diameter.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"placeholderDiameterToShorterSideRatio","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/title","value":"placeholderDiameterToShorterSideRatio","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/fragments","value":[{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}