{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"]]},"abstract":[{"type":"text","text":"Default threshold value."}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooLargeValidator(cpy)defaultMaxDetectionSizeToImageShorterSideRatioThreshold","modules":[{"name":"DotFaceLite"}],"title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Type Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/defaultMaxDetectionSizeToImageShorterSideRatioThreshold":{"navigatorTitle":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold","type":"topic","abstract":[{"type":"text","text":"Default threshold value."}],"kind":"symbol","title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"role":"symbol","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","url":"\/documentation\/dotfacelite\/sizetoolargevalidator","kind":"symbol","type":"topic","title":"SizeTooLargeValidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/title","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}