{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"title":"DotDocumentModuleId.barcode","externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"role":"symbol","symbolKind":"case"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/barcode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid\/barcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid\/barcode"]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId":{"role":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"title":"DotDocumentModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfacecore\/dotdocumentmoduleid","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/barcode":{"title":"DotDocumentModuleId.barcode","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/barcode","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/barcode","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotDocumentModuleIdBarcode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId~1barcode\/title","value":"DotDocumentModuleIdBarcode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId~1barcode\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}]}]}]}