{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/hashValue"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/hash(into:)"]}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotFaceCore"}],"title":"RawRepresentable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/hashValue":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/hashValue","title":"hashValue","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/hashvalue","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId":{"title":"DotDocumentModuleId","type":"topic","abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfacecore\/dotdocumentmoduleid","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/hash(into:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/hash(into:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"abstract":[],"title":"hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/fragments","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/navigatorTitle","op":"replace"}]}]}