{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTCameraFacing) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/camerafacing"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/back","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/front"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/native"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH","doc:\/\/com.innovatrics.dot.face.lite\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"metadata":{"symbolKind":"enum","role":"symbol","title":"CameraFacing","externalID":"c:@M@DotFaceLite@E@DOTCameraFacing","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerafacing","type":"topic","title":"CameraFacing","kind":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing"},"doc://com.innovatrics.dot.face.lite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/back":{"role":"symbol","abstract":[{"type":"text","text":"Back facing camera."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/back","title":"CameraFacing.back","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerafacing\/back"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/description":{"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/description","title":"description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/dotfacelite\/camerafacing\/description"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/init(rawValue:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacelite\/camerafacing\/init(rawvalue:)"},"doc://com.innovatrics.dot.face.lite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/camerafacing\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/native":{"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/native","title":"native","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","text":"Position","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/camerafacing\/native"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/camerafacing\/equatable-implementations"},"doc://com.innovatrics.dot.face.lite/SY":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing/front":{"role":"symbol","abstract":[{"type":"text","text":"Front facing camera."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/front","title":"CameraFacing.front","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerafacing\/front"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraFacing"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/back","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing\/front"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTCameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing~1back\/title","value":"DOTCameraFacingBack","op":"replace"},{"op":"replace","value":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing~1back\/fragments"},{"value":"DOTCameraFacingFront","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing~1front\/title","op":"replace"},{"value":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing~1front\/fragments"}]}]}