{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"text":", ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"text":", ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)","roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"s:7DotCore0A3SdkC13ConfigurationC12licenseBytes9libraries24transactionCountingTokenAE10Foundation4DataV_AA9LibrariesCSSSgtcfc"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","title":"DotSdk","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Configuration":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration","title":"DotSdk.Configuration","url":"\/documentation\/dotpalmcore\/dotsdk\/configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"url":"\/documentation\/dotpalmcore\/libraries","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"role":"symbol","title":"Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Libraries","kind":"identifier"}],"abstract":[{"text":"Container for library configurations.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","abstract":[{"text":"version: 9.4.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Configuration/init(licenseBytes:libraries:transactionCountingToken:)":{"url":"\/documentation\/dotpalmcore\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)","role":"symbol","title":"init(licenseBytes:libraries:transactionCountingToken:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","text":"Libraries"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}