{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"libraries","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp"},"abstract":[{"type":"text","text":"Libraries configuration."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdk\/configuration\/libraries"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration\/libraries","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Configuration":{"url":"\/documentation\/dotpalmcore\/dotsdk\/configuration","role":"symbol","title":"DotSdk.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","title":"Libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"url":"\/documentation\/dotpalmcore\/libraries"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Configuration/libraries":{"kind":"symbol","abstract":[{"text":"Libraries configuration.","type":"text"}],"title":"libraries","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Configuration\/libraries","url":"\/documentation\/dotpalmcore\/dotsdk\/configuration\/libraries","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"role":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title","op":"replace","value":"Libraries"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle"},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}