{"metadata":{"navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:qualityAttributeThresholds:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration","text":"DOTCommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" *) ","kind":"text"},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"camera:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTCameraConfiguration"},{"text":" *) ","kind":"text"},{"text":"camera","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration","text":"DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"autoCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"abstract":[{"text":"Create the fingers auto capture configuration.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgbasefingersautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/CommonConfiguration":{"url":"\/documentation\/dotfingerscore\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration","title":"CommonConfiguration","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGBaseFingersAutoCaptureConfiguration/initWithCommon:camera:autoCapture:qualityAttributeThresholds:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfgbasefingersautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:","abstract":[{"type":"text","text":"Create the fingers auto capture configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","title":"FingersAutoCaptureQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the fingers auto capture result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGBaseFingersAutoCaptureConfiguration":{"fragments":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfgbasefingersautocaptureconfiguration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration","title":"DOTFGBaseFingersAutoCaptureConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/title","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"}]}]}