{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.backgroundColor, "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" = Defaults.instructionFont, "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionTextColor, "},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionCandidateSelectionTextColor, "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionBackgroundColor, "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionCandidateSelectionBackgroundColor, "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.placeholderColor, "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.placeholderCandidateSelectionColor, "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.detectionLayerColor, "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.overlayColor)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-qhwu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-qhwu"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessStyle(im)initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)":{"role":"symbol","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-qhwu"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.3"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle":{"role":"symbol","title":"MagnifEyeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionFont"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionTextColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"placeholderColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderCandidateSelectionColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detectionLayerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"overlayColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/title","value":"DOTFMagnifEyeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}