{"variants":[{"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/debug"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/debug"]}],"metadata":{"navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"title":"LoggerLogLevel.debug","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelDebug"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel"]]},"abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/debug","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/loggerloglevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","abstract":[{"type":"text","text":"Available log levels."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/debug":{"url":"\/documentation\/dotpalmcore\/loggerloglevel\/debug","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"title":"LoggerLogLevel.debug","kind":"symbol","abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/debug"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTLoggerLogLevelDebug","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments"},{"op":"replace","value":"DOTLoggerLogLevelDebug","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1debug\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1debug\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}