{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hashValue","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DOTLoggerLogLevel","roleHeading":"Instance Property","extendedModule":"Swift","title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"DotPalmCore"}],"symbolKind":"property","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]}},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/RawRepresentable-Implementations":{"url":"\/documentation\/dotpalmcore\/loggerloglevel\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/RawRepresentable-Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"type":"topic","title":"LoggerLogLevel","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"url":"\/documentation\/dotpalmcore\/loggerloglevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/hashValue":{"url":"\/documentation\/dotpalmcore\/loggerloglevel\/hashvalue","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hashValue","kind":"symbol","title":"hashValue","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title"},{"op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}