{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel"]]},"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Case","title":"LoggerLogLevel.info","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/info"},"abstract":[{"text":"Logs informative events.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/info"]},{"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/info"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/info":{"abstract":[{"text":"Logs informative events.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/loggerloglevel\/info","kind":"symbol","title":"LoggerLogLevel.info","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/info"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/loggerloglevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","abstract":[{"type":"text","text":"Available log levels."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTLoggerLogLevelInfo","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1info\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}]},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}