{"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hashValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hash(into:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel"]]},"metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"DotPalmCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/RawRepresentable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/rawrepresentable-implementations"]}],"kind":"article","references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/hashValue":{"title":"hashValue","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hashValue","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/dotpalmcore\/loggerloglevel\/hashvalue","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","title":"LoggerLogLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotpalmcore\/loggerloglevel","role":"symbol","abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/hash(into:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel\/hash(into:)","kind":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hash(into:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}