{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/randomsegmentsgenerator\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFRandomSegmentsGenerator(im)init","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RandomSegmentsGenerator/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacecore\/randomsegmentsgenerator\/init"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RandomSegmentsGenerator":{"role":"symbol","title":"RandomSegmentsGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RandomSegmentsGenerator"}],"abstract":[{"type":"text","text":"Generates random segments for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RandomSegmentsGenerator"}],"url":"\/documentation\/dotfacecore\/randomsegmentsgenerator"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator\/title","value":"DOTFRandomSegmentsGenerator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator\/fragments","value":[{"kind":"identifier","text":"DOTFRandomSegmentsGenerator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}