{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPQualityAttributeThresholds","text":"DOTPQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"text":" ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"placeholderType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTPPlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"},{"text":") ","kind":"text"},{"text":"placeholderType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvi-64v7t"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotpalmcore\/camerafacing","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","title":"CameraFacing"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholds":{"fragments":[{"kind":"identifier","text":"DOTPQualityAttributeThresholds"}],"url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholds","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"}],"kind":"symbol","title":"DOTPQualityAttributeThresholds","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"kind":"symbol","title":"DOTPPalmAutoCaptureConfiguration","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"title":"PlaceholderType","role":"symbol","url":"\/documentation\/dotpalmcore\/placeholdertype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","kind":"symbol","abstract":[{"type":"text","text":"Represents the type of placeholder used in palm auto-capture UI."}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"title":"CameraPreviewScaleType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:":{"kind":"symbol","abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvi-64v7t","title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:error:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments"},{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}]}]}