{"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","externalID":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC7isEqualySbypSgF","modules":[{"name":"DotFaceLite"}],"title":"isEqual(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped\/isEqual(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped\/isequal(_:)"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped":{"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"title":"MultiRangeLivenessChallengeItem.Wrapped","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"text":".","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped/isEqual(_:)":{"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped\/isequal(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped\/isEqual(_:)","kind":"symbol","title":"isEqual(_:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}