{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/pointint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/pointint"]}],"metadata":{"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"title":"PointInt","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointInt","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"roleHeading":"Class"},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/init(x:y:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/cgPoint","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/x","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/y"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/isEqual(_:)"]},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/from(cgPoint:)"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPointInt) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/PointInt/y":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"y","url":"\/documentation\/dotfacecore\/pointint\/y","role":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"y","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/y"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/hash":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/hash","url":"\/documentation\/dotfacecore\/pointint\/hash","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/from(cgPoint:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/from(cgPoint:)","url":"\/documentation\/dotfacecore\/pointint\/from(cgpoint:)","title":"from(cgPoint:)","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/cgPoint":{"url":"\/documentation\/dotfacecore\/pointint\/cgpoint","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/cgPoint","title":"cgPoint","role":"symbol","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/PointInt":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/pointint","title":"PointInt","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/isEqual(_:)":{"role":"symbol","type":"topic","title":"isEqual(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotfacecore\/pointint\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/init(x:y:)":{"title":"init(x:y:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/pointint\/init(x:y:)","role":"symbol","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/init(x:y:)","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/x":{"abstract":[{"type":"text","text":"X coordinate."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/x","url":"\/documentation\/dotfacecore\/pointint\/x","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"x"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"x","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/description":{"url":"\/documentation\/dotfacecore\/pointint\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","type":"topic","kind":"symbol","title":"description"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTPointInt"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/cgPoint","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/x","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/y"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/init(x:y:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/isEqual(_:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/from(cgPoint:)"],"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPointInt","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1y\/title","op":"replace","value":"y"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1y\/fragments","op":"replace","value":[{"kind":"identifier","text":"y"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1from(cgPoint:)\/title","op":"replace","value":"fromCgPoint:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1from(cgPoint:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1cgPoint\/title","op":"replace","value":"cgPoint"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1cgPoint\/fragments","op":"replace","value":[{"kind":"identifier","text":"cgPoint"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/title","op":"replace","value":"DOTPointInt"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/fragments","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1init(x:y:)\/title","op":"replace","value":"initWithX:y:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1init(x:y:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1x\/title","op":"replace","value":"x"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1x\/fragments","op":"replace","value":[{"kind":"identifier","text":"x"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}