{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/autoCapture","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is:"}],"type":"paragraph"},{"code":[".init(","    minValidSamplesInRowToStartCandidateSelection: 2,","    candidateSelectionDurationMillis: 2000",")"],"syntax":null,"type":"codeListing"}],"kind":"content"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","title":"autoCapture","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"}],"externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC04autoE00aE00deH0Cvp","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}]},"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/autocapture"]}],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/autoCapture":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/autocapture","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/autoCapture","kind":"symbol","title":"autoCapture","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration"}],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"url":"\/documentation\/dotdocument\/autocaptureconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"type":"topic","title":"AutoCaptureConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}]},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","role":"symbol","abstract":[{"text":"UI component for capturing document images with customizable UI.","type":"text"}],"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}