{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"symbolKind":"property","role":"symbol","externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC6common0A4Core06CommonH0Cvp","title":"common"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/common"]}],"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/common"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"type":"topic","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"BaseDocumentAutoCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/common":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"code":".init()","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/common","title":"common","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/common"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"type":"topic","role":"symbol","kind":"symbol","title":"BaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","title":"CommonConfiguration","url":"\/documentation\/dotdocument\/commonconfiguration"}},"variantOverrides":[{"patch":[{"value":"DOTDBaseDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}