{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"]]},"metadata":{"title":"init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","text":"DocumentAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","text":"MrzValidation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"BarcodeValidation"},{"kind":"text","text":")"}],"symbolKind":"init","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC6common6camera04autoE026qualityAttributeThresholds14validationMode13mrzValidation07barcodeR0AE0A4Core06CommonH0C_0aE006CameraH0CAP0deH0CAA0bde7QualitymN0CAA0rP0OAA03MrzR0OAA07BarcodeR0Otcfc","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":" = .init(facing: .back), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"text":" = .Presets.standard.build(), ","kind":"text"},{"text":"validationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ValidationMode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"text":" = Defaults.validationMode, ","kind":"text"},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":" = Defaults.mrzValidation, ","kind":"text"},{"text":"barcodeValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BarcodeValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"},{"text":" = Defaults.barcodeValidation)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:barcodevalidation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)"},"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)":{"kind":"symbol","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":", ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"text":", ","kind":"text"},{"text":"validationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"text":", ","kind":"text"},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"text":"barcodeValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BarcodeValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)","title":"init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:barcodevalidation:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"title":"BaseDocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol","title":"DocumentAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"kind":"symbol","abstract":[],"title":"ValidationMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"type":"topic","url":"\/documentation\/dotdocument\/validationmode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}]},"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"role":"symbol","title":"CameraConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","type":"topic","url":"\/documentation\/dotdocument\/cameraconfiguration"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"title":"CommonConfiguration","url":"\/documentation\/dotdocument\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Common configuration for all components."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","type":"topic","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration","url":"\/documentation\/dotdocument\/autocaptureconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"kind":"symbol","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"role":"symbol","type":"topic","title":"MrzValidation","url":"\/documentation\/dotdocument\/mrzvalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"type":"topic","url":"\/documentation\/dotdocument\/barcodevalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","abstract":[{"type":"text","text":"Mode of barcode validation."}],"role":"symbol","title":"BarcodeValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","op":"replace","value":"DOTDValidationMode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle","op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","op":"replace","value":"DOTDMrzValidation"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","op":"replace","value":"DOTDBarcodeValidation"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}