{"metadata":{"title":"mrzValidation","externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC13mrzValidationAA03MrzJ0Ovp","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","kind":"typeIdentifier","text":"MrzValidation"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/mrzValidation"},"abstract":[{"text":"Specify MRZ validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/mrzvalidation"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/mrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/mrzValidation","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/mrzvalidation","type":"topic","abstract":[{"text":"Specify MRZ validation. Default is ","type":"text"},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","kind":"typeIdentifier"}],"kind":"symbol","title":"mrzValidation"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"kind":"symbol","role":"symbol","title":"MrzValidation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzvalidation"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"BaseDocumentAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}