{"variants":[{"paths":["\/documentation\/dotnfc\/dotnfclibrary\/deinitialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/deinitialize()"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","title":"deinitialize()","externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary(im)deinitializeAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0"}],"roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Throws an error if the "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library fails to deinitialize."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Throws"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/deinitialize()"},"abstract":[{"type":"text","text":"Deinitialize library."}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library initialization."}],"title":"DotNfcLibrary","role":"symbol","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/dotnfclibrary","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/deinitialize()":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/deinitialize()","title":"deinitialize()","url":"\/documentation\/dotnfc\/dotnfclibrary\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize library."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotNfcLibrary","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","value":[{"kind":"identifier","text":"DotNfcLibrary"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1deinitialize()\/fragments"}]}]}