{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary(im)initializeWithLicense:error:","modules":[{"name":"DotNfc"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"13.0","name":"iOS","deprecated":false}],"roleHeading":"Instance Method","title":"initialize(license:)"},"abstract":[{"type":"text","text":"Initialize library with license."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" license."}],"type":"paragraph"}],"name":"license"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"style":"note","content":[{"inlineContent":[{"text":"Throws an error if the ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library is not enabled in the license."}],"type":"paragraph"}],"name":"Throws","type":"aside"}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/initialize(license:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/initialize(license:)"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/initialize(license:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/initialize(license:)":{"abstract":[{"text":"Initialize library with license.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/initialize(license:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotnfclibrary\/initialize(license:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"title":"initialize(license:)"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"kind":"symbol","title":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library initialization."}],"title":"DotNfcLibrary","role":"symbol","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/dotnfclibrary","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initializeWithLicense:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"id<DotSdkLicenseProxyProtocol>"},{"kind":"text","text":" *) "},{"text":"license","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1initialize(license:)\/title","op":"replace","value":"initializeWithLicense:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1initialize(license:)\/fragments","op":"replace"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotNfcLibrary"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments"}]}]}