{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/anymultirangelivenesscontroller\/imagesize"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"s:14DotFaceCommons31AnyMultiRangeLivenessControllerC9imageSize0A4Core05ImageJ0CSgvp","symbolKind":"property","title":"imageSize","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyMultiRangeLivenessController\/imageSize","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyMultiRangeLivenessController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/AnyMultiRangeLivenessController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyMultiRangeLivenessController","url":"\/documentation\/dotfacecore\/anymultirangelivenesscontroller","abstract":[],"title":"AnyMultiRangeLivenessController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyMultiRangeLivenessController"}],"navigatorTitle":[{"kind":"identifier","text":"AnyMultiRangeLivenessController"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/AnyMultiRangeLivenessController/imageSize":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyMultiRangeLivenessController\/imageSize","title":"imageSize","kind":"symbol","url":"\/documentation\/dotfacecore\/anymultirangelivenesscontroller\/imagesize","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"url":"\/documentation\/dotfacecore\/imagesize","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"type":"topic","title":"ImageSize","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"text":"Image size in pixels.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}]}]}]}