{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithLicenseBytes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"licenseBytes"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","text":"Libraries"},{"kind":"text","text":" *) "},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transactionCountingToken:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"]}],"metadata":{"title":"initWithLicenseBytes:libraries:transactionCountingToken:","roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/Libraries":{"url":"\/documentation\/dotdocument\/libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}]},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"url":"\/documentation\/dotdocument\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}]},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"url":"\/documentation\/dotdocument\/dotsdkconfiguration","abstract":[{"type":"text","text":"The "},{"type":"text","text":"DotSdk"},{"type":"text","text":" configuration."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","title":"DotSdkConfiguration","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]}]}]}