{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/devicetiltangles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/devicetiltangles"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"]]},"sections":[],"kind":"symbol","metadata":{"title":"deviceTiltAngles","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deviceTiltAngles"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection(py)deviceTiltAngles"},"abstract":[{"type":"text","text":"Tilt angles of the device."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/deviceTiltAngles"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/deviceTiltAngles":{"abstract":[{"type":"text","text":"Tilt angles of the device."}],"navigatorTitle":[{"text":"deviceTiltAngles","kind":"identifier"}],"title":"deviceTiltAngles","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/deviceTiltAngles","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/devicetiltangles","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles":{"title":"TiltAngles","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TiltAngles"}],"abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","kind":"symbol","url":"\/documentation\/dotfacecore\/tiltangles","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"role":"symbol","kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"deviceTiltAngles","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"deviceTiltAngles","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"DOTTiltAngles"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deviceTiltAngles"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"deviceTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1deviceTiltAngles\/title"},{"value":[{"text":"deviceTiltAngles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1deviceTiltAngles\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}]}]}]}