{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/image","interfaceLanguage":"swift"},"abstract":[{"text":"Detection image.","type":"text"}],"kind":"symbol","metadata":{"title":"image","role":"symbol","navigatorTitle":[{"text":"image","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection(py)image","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/image"]},{"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image":{"url":"\/documentation\/dotfacecore\/image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","title":"Image","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/image":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection\/image","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"kind":"symbol","type":"topic","abstract":[{"text":"Detection image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/image","title":"image","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"image","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier","text":"DOTImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage","op":"replace"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"image","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1image\/title"},{"op":"replace","value":[{"text":"image","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1image\/fragments"}]}]}