{"metadata":{"role":"symbol","title":"widthToHeightRatio","symbolKind":"property","externalID":"s:11DotDocument0B8DetectorC0B0C18widthToHeightRatioSdvp","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/widthToHeightRatio","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/document\/widthtoheightratio"]}],"abstract":[{"type":"text","text":"Detected width to height ratio of the document."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"abstract":[{"text":"Result of the document detection process.","type":"text"}],"url":"\/documentation\/dotdocument\/documentdetector\/document","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"title":"DocumentDetector.Document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","type":"topic","role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/widthToHeightRatio":{"type":"topic","abstract":[{"type":"text","text":"Detected width to height ratio of the document."}],"title":"widthToHeightRatio","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotdocument\/documentdetector\/document\/widthtoheightratio","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/widthToHeightRatio","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]}]}]}