{"abstract":[{"type":"text","text":"Create palm auto capture controller configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"validators","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","kind":"typeIdentifier","text":"PalmAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = Defaults.minValidFramesInRowToStartCandidateSelection, ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.candidateSelectionDurationMillis, "},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"? = nil) "},{"text":"throws","kind":"keyword"}]}]},{"kind":"parameters","parameters":[{"name":"sessionToken","content":[{"inlineContent":[{"type":"text","text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Array of validators which will be used to validate input image.","type":"text"}],"type":"paragraph"}],"name":"validators"},{"name":"minValidFramesInRowToStartCandidateSelection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Duration of candidate selection phase.","type":"text"}]}],"name":"candidateSelectionDurationMillis"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Normalized detection rectangle in an image.","type":"text"}]}],"name":"detectionNormalizedRectangle"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"style":"note","name":"Throws","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Throws an error when validator dependencies are missing."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/init(sessiontoken:validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC12sessionToken10validators44minValidFramesInRowToStartCandidateSelection09candidateS14DurationMillis28detectionNormalizedRectangleAESSSg_SayAA0bdE18DetectionValidator_pGS2i0aC00Y6DoubleCSgtKcfc","title":"init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validators","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureDetectionValidator","kind":"typeIdentifier","text":"PalmAutoCaptureDetectionValidator"},{"text":"], ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/init(sessiontoken:validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:)","abstract":[{"text":"Create palm auto capture controller configuration.","type":"text"}],"title":"init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureDetectionValidator","text":"PalmAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.7.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"title":"PalmAutoCaptureDetectionValidator","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","title":"PalmAutoCaptureController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"title":"RectangleDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","type":"topic","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"role":"symbol","kind":"symbol","title":"PalmAutoCaptureController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","op":"replace","value":"DOTPPalmAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments","value":[{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}