{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/failureReason","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/helpAnchor","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/recoverySuggestion"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/error\/localizederror-implementations"]}],"sections":[],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"DotDocument"}],"title":"LocalizedError Implementations"},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error","title":"AutoCaptureConfiguration.Error","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/helpAnchor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/helpAnchor","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/helpanchor","type":"topic","kind":"symbol","abstract":[],"title":"helpAnchor","role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/recoverySuggestion":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/recoverySuggestion","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/recoverysuggestion","type":"topic","kind":"symbol","abstract":[],"title":"recoverySuggestion","role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","role":"symbol","title":"AutoCaptureConfiguration","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","url":"\/documentation\/dotdocument\/autocaptureconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/failureReason":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/failureReason","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/failurereason","title":"failureReason","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}