{"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"common","fragments":[{"kind":"identifier","text":"common"}],"navigatorTitle":[{"kind":"identifier","text":"common"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(py)common","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/common","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/common"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"fragments":[{"text":"DOTFEyeGazeLivenessConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","title":"DOTFEyeGazeLivenessConfiguration","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","abstract":[{"type":"text","text":"Configuration options for the UI Eye Gaze Liveness component."}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/common":{"fragments":[{"kind":"identifier","text":"common"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/common","title":"common","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/common"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"kind":"symbol","role":"symbol","abstract":[{"text":"Common configuration for all components.","type":"text"}],"url":"\/documentation\/dotfacecore\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle"}]}]}