{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory"]]},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgrRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" object."}]}]}]},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(bgrrawimage:)"]}],"metadata":{"title":"create(bgrRawImage:)","externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgrRawImage:","modules":[{"name":"DotNfc"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"symbolKind":"method","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"role":"symbol"},"sections":[],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/CGImageFactory/create(bgrRawImage:)":{"url":"\/documentation\/dotnfc\/cgimagefactory\/create(bgrrawimage:)","role":"symbol","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(bgrRawImage:)","title":"create(bgrRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}]},"doc://DotNfc/documentation/DotNfc/BgrRawImage":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrrawimage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}]},"doc://DotNfc/documentation/DotNfc/CGImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory","title":"CGImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/cgimagefactory"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createWithBgrRawImage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"text":"createWithBgrRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgrRawImage"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createWithBgrRawImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(bgrRawImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgrRawImage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/title","op":"replace","value":"DOTCGImageFactory"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}