{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/template\/version-swift.class\/minor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"minor","externalID":"s:11DotFaceCore8TemplateC7VersionC5minorSivp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/minor","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/minor":{"url":"\/documentation\/dotfacecore\/template\/version-swift.class\/minor","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/minor","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","abstract":[],"title":"minor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"abstract":[{"type":"text","text":"Stateless class which can match templates."}],"kind":"symbol","title":"TemplateMatcher","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"url":"\/documentation\/dotfacecore\/templatematcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TemplateMatcher","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/template","navigatorTitle":[{"text":"Template","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","abstract":[{"type":"text","text":"Face template."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"title":"Template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"title":"Template.Version","navigatorTitle":[{"text":"Version","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","type":"topic","url":"\/documentation\/dotfacecore\/template\/version-swift.class","abstract":[{"type":"text","text":"Template compatibility version."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Version","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFTemplateMatcher","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title","op":"replace"},{"value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}]}]}]}