{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}],"type":"paragraph"}],"metadata":{"externalID":"s:6DotNfc0B3KeyC5ErrorO18invalidDateOfBirthyA2EmF","symbolKind":"case","title":"NfcKey.Error.invalidDateOfBirth","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateOfBirth"}],"modules":[{"name":"DotNfc"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/error\/invaliddateofbirth"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateOfBirth"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/invalidDateOfBirth","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","title":"NfcKey.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfckey\/error","kind":"symbol","deprecated":true,"type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/NfcKey":{"title":"NfcKey","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfckey","role":"symbol","type":"topic","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","deprecated":true},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/invalidDateOfBirth":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/invalidDateOfBirth","title":"NfcKey.Error.invalidDateOfBirth","url":"\/documentation\/dotnfc\/nfckey\/error\/invaliddateofbirth","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDateOfBirth","kind":"identifier"}],"deprecated":true,"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","title":"NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","op":"replace","value":"DOTNNfcKey"},{"value":[{"text":"DOTNNfcKey","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","op":"replace"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}