{"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facematcher\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/DotSdkError-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.composeWithInternalError()","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:11DotFaceCore0B7MatcherC5ErrorO","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"composeWithInternalError()","extendedModule":"DotCore"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/DotSdkError-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/facematcher\/error\/dotsdkerror-implementations","title":"DotSdkError Implementations","role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/DotSdkError-Implementations","kind":"article"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error","role":"symbol","abstract":[{"type":"text","text":"Matching errors."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"FaceMatcher.Error"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","kind":"symbol","url":"\/documentation\/dotfacecore\/facematcher","title":"FaceMatcher","role":"symbol","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/composeWithInternalError()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/composeWithInternalError()","role":"symbol","abstract":[],"title":"composeWithInternalError()","url":"\/documentation\/dotfacecore\/facematcher\/error\/composewithinternalerror()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"}]}]}