{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/description"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facematcher\/error\/customstringconvertible-implementations"]}],"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"DotFaceCore"}],"title":"CustomStringConvertible Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/CustomStringConvertible-Implementations"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/description":{"title":"description","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/description","url":"\/documentation\/dotfacecore\/facematcher\/error\/description"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error":{"kind":"symbol","title":"FaceMatcher.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[{"type":"text","text":"Matching errors."}],"type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"title":"FaceMatcher","url":"\/documentation\/dotfacecore\/facematcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"navigatorTitle":[{"text":"FaceMatcher","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}