{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"]]},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/errorDescription"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/composeWithInternalError()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facematcher\/error\/dotsdkerror-implementations"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"DotSdkError Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error":{"abstract":[{"text":"Matching errors.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/facematcher\/error","title":"FaceMatcher.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"type":"topic","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"title":"FaceMatcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceMatcher"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facematcher"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/composeWithInternalError()":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotfacecore\/facematcher\/error\/composewithinternalerror()","title":"composeWithInternalError()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/composeWithInternalError()","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/errorDescription":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/errorDescription","title":"errorDescription","url":"\/documentation\/dotfacecore\/facematcher\/error\/errordescription","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/description","title":"description","url":"\/documentation\/dotfacecore\/facematcher\/error\/description","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}