{"variants":[{"paths":["\/documentation\/dotfacecore\/facematcher\/error\/referencefacenotdetected(internalerror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"]]},"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceFaceNotDetected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"roleHeading":"Case","title":"FaceMatcher.Error.referenceFaceNotDetected(internalError:)","externalID":"s:11DotFaceCore0B7MatcherC5ErrorO09referenceB11NotDetectedyAEsAD_pSg_tcAEmF","modules":[{"name":"DotFaceCore"}]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/referenceFaceNotDetected(internalError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face not detected in reference image."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceFaceNotDetected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/facematcher\/error","title":"FaceMatcher.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error","abstract":[{"text":"Matching errors.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"url":"\/documentation\/dotfacecore\/facematcher","title":"FaceMatcher","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error/referenceFaceNotDetected(internalError:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceFaceNotDetected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facematcher\/error\/referencefacenotdetected(internalerror:)","title":"FaceMatcher.Error.referenceFaceNotDetected(internalError:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error\/referenceFaceNotDetected(internalError:)","abstract":[{"type":"text","text":"Face not detected in reference image."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","op":"replace","value":"DOTFFaceMatcher"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}