{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init()"},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"init","title":"init()","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery(im)init","roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/headposequery\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/headposequery\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"kind":"symbol","type":"topic","title":"HeadPoseQuery"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/init()":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init()","url":"\/documentation\/dotfacecore\/headposequery\/init()","abstract":[],"kind":"symbol","type":"topic","title":"init()"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}