{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/travelDocumentType","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult(py)travelDocumentType","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?"}],"title":"travelDocumentType","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/traveldocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/traveldocumenttype"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Resolved travel document type.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/travelDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"abstract":[{"type":"text","text":"Resolved travel document type."}],"type":"topic","kind":"symbol","title":"travelDocumentType","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/travelDocumentType","url":"\/documentation\/dotdocument\/documentautocaptureresult\/traveldocumenttype"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"type":"topic","kind":"symbol","title":"DocumentAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","url":"\/documentation\/dotdocument\/documentautocaptureresult"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","type":"topic","title":"TravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"travelDocumentType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"travelDocumentType","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":" * "},{"text":"travelDocumentType","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"travelDocumentType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1travelDocumentType\/title"},{"value":[{"text":"travelDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1travelDocumentType\/fragments"},{"value":"DOTDDocumentAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}]},{"value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}