{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","text":"DotFaceModule"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/init(license:modules:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/init(license:modules:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithLicense:modules:"}],"role":"symbol","title":"init(license:modules:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"])"}],"symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration(im)initWithLicense:modules:","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryConfiguration instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/init(license:modules:)":{"deprecated":true,"role":"symbol","title":"init(license:modules:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLicense:modules:"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/init(license:modules:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","title":"DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModule"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}],"url":"\/documentation\/dotfacecore\/dotfacemodule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLicense:modules:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicense:modules:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLicense:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"license"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<DotFaceModule>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"modules"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:)\/title","value":"initWithLicense:modules:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicense:modules:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}