{"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg1","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg1"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}],"symbolKind":"case","title":"Lds1ElementaryFileId.dg1","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg1"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg1"},"abstract":[{"type":"text","text":"File identifier for data group 1. Data group 1 contains the MRZ."}],"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg1"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg1":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg1"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg1","abstract":[{"type":"text","text":"File identifier for data group 1. Data group 1 contains the MRZ."}],"title":"Lds1ElementaryFileId.dg1","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg1"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"title":"Lds1ElementaryFileId","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg1"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg1\/title","value":"DOTNLds1ElementaryFileIdDg1"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg1\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}