{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/common"},"metadata":{"title":"common","fragments":[{"kind":"identifier","text":"common"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration(py)common","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"common"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/common"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration"]]},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration/common":{"title":"common","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/common","role":"symbol","abstract":[{"text":"Common configuration for all UI components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"fragments":[{"text":"common","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/common"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","role":"symbol","title":"DOTFMultiRangeLivenessConfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"text":"DOTFMultiRangeLivenessConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"title":"CommonConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle"}]}]}