{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculatePixelCount"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/calculatePixelCount()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"variants":[{"paths":["\/documentation\/dotnfc\/imagesize\/calculatepixelcount()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagesize\/calculatepixelcount()"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculatePixelCount"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"calculatePixelCount","kind":"identifier"}],"role":"symbol","title":"calculatePixelCount()","modules":[{"name":"DotNfc"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculatePixelCount"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/ImageSize/calculatePixelCount()":{"type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/imagesize\/calculatepixelcount()","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/calculatePixelCount()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"calculatePixelCount","kind":"identifier"}],"kind":"symbol","title":"calculatePixelCount()","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagesize","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","type":"topic","role":"symbol","kind":"symbol","title":"ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"calculatePixelCount","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"calculatePixelCount","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1calculatePixelCount()\/fragments","value":[{"kind":"text","text":"- "},{"text":"calculatePixelCount","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"}]}]}