{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"variants":[{"paths":["\/documentation\/dotnfc\/imagesize\/calculatewidthtoheightratio()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagesize\/calculatewidthtoheightratio()"]}],"metadata":{"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTImageSize(im)calculateWidthToHeightRatio","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"calculateWidthToHeightRatio()","symbolKind":"method","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":"() -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculateWidthToHeightRatio()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"url":"\/documentation\/dotnfc\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/calculateWidthToHeightRatio()":{"url":"\/documentation\/dotnfc\/imagesize\/calculatewidthtoheightratio()","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","role":"symbol","title":"calculateWidthToHeightRatio()","abstract":[{"text":"Calculate width to height ratio.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculateWidthToHeightRatio()","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"calculateWidthToHeightRatio"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculateWidthToHeightRatio()\/title","value":"calculateWidthToHeightRatio"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculateWidthToHeightRatio()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"calculateWidthToHeightRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}