{"sections":[],"abstract":[{"text":"Image height in pixels.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/height","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"height","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)height","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagesize\/height"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagesize\/height"]}],"references":{"doc://DotNfc/documentation/DotNfc/ImageSize":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagesize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","title":"ImageSize","role":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}]},"doc://DotNfc/documentation/DotNfc/ImageSize/height":{"navigatorTitle":[{"text":"height","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/height","type":"topic","url":"\/documentation\/dotnfc\/imagesize\/height","title":"height","role":"symbol","abstract":[{"text":"Image height in pixels.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"height","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"height","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1height\/title","op":"replace","value":"height"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1height\/fragments","op":"replace","value":[{"text":"height","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}