{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","title":"shorterSide","role":"symbol","externalID":"c:@CM@DotNfc@objc(cs)DOTImageSize(py)shorterSide"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagesize\/shorterside"]},{"paths":["\/documentation\/dotnfc\/imagesize\/shorterside"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/shorterSide","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.2.0","type":"text"}],"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/shorterSide":{"title":"shorterSide","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shorterSide","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"role":"symbol","url":"\/documentation\/dotnfc\/imagesize\/shorterside","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/shorterSide","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"abstract":[{"text":"Image size in pixels.","type":"text"}],"title":"ImageSize","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shorterSide"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shorterSide"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shorterSide"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"shorterSide","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1shorterSide\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1shorterSide\/fragments","value":[{"text":"shorterSide","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]}]}]}