{"variants":[{"paths":["\/documentation\/dotnfc\/dotlibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotlibrary"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"roleHeading":"Protocol","externalID":"c:@M@DotNfc@objc(pl)DotLibrary","modules":[{"name":"DotNfc"}],"role":"symbol","title":"DotLibrary"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary"],"type":"conformingTypes"}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/initialize(license:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/verifyIsActive()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/deinitialize()":{"required":true,"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotlibrary\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"deinitialize()","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.2.1"}],"role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/initialize(license:)":{"title":"initialize(license:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/initialize(license:)","abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/dotlibrary\/initialize(license:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"type":"topic","title":"DotLibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/dotlibrary","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/id":{"url":"\/documentation\/dotnfc\/dotlibrary\/id","abstract":[],"title":"id","required":true,"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotNfcLibrary":{"type":"topic","title":"DotNfcLibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary","kind":"symbol","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotNfc"},{"text":" library initialization.","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotNfcLibrary"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/verifyIsActive()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"verifyIsActive()","url":"\/documentation\/dotnfc\/dotlibrary\/verifyisactive()","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/verifyIsActive()","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DotLibrary"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotLibrary","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/initialize(license:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/verifyIsActive()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"deinitializeAndReturnError:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1deinitialize()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1deinitialize()\/fragments","op":"replace"},{"value":"initializeWithLicense:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1initialize(license:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title","value":"DotLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1id\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1id\/fragments","value":[{"kind":"identifier","text":"id"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary"},{"op":"replace","value":[{"text":"DotNfcLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments"},{"value":"verifyIsActiveAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1verifyIsActive()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1verifyIsActive()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]}]}]}