{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"MrzDateElementWithCheckDigit","roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"sections":[],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/date","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/hash"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/isEqual(_:)"],"title":"Instance Methods"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzDateElementWithCheckDigit) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit/hash":{"title":"hash","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/hash"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit/isEqual(_:)":{"title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/isEqual(_:)"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"title":"MrzDateElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit/description":{"title":"description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/description"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit/date":{"title":"date","abstract":[{"type":"text","text":"Parsed date."}],"navigatorTitle":[{"kind":"identifier","text":"date"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/date","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"text":": ","kind":"text"},{"text":"MrzDate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDate"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/date"},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit/init(value:positions:checkDigit:date:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)","kind":"symbol","navigatorTitle":[{"text":"initWithValue:positions:checkDigit:date:","kind":"identifier"}],"title":"init(value:positions:checkDigit:date:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"positions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MrzStringPosition","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"checkDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDate","text":"MrzDate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElementWithCheckDigit":{"kind":"symbol","title":"MrzElementWithCheckDigit","role":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"type":"topic","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}]},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.2.1"}],"role":"collection"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTMrzDateElementWithCheckDigit","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/date","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/isEqual(_:)"]}]},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1hash\/title","value":"hash","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1isEqual(_:)\/fragments"},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1date\/title","value":"date","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1date\/fragments","op":"replace","value":[{"text":"date","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/title","value":"initWithValue:positions:checkDigit:date:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithValue:positions:checkDigit:date:","kind":"identifier"}]},{"op":"replace","value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}