{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"DOTAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"autoCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionArea"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DOTFLFaceAutoCaptureFrameParametersValidator>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validators"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration\/initwithcommon:autocapture:detectionarea:validators:error:"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:detectionArea:validators:error:"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCommon:autoCapture:detectionArea:validators:error:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:autoCapture:detectionArea:validators:error:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration(im)initWithCommon:autoCapture:detectionArea:validators:error:","role":"symbol","title":"initWithCommon:autoCapture:detectionArea:validators:error:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","title":"RectangleDouble","url":"\/documentation\/dotfacelite\/rectangledouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration":{"title":"DOTFLFaceAutoCaptureControllerConfiguration","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration","type":"topic","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"title":"CommonConfiguration","abstract":[{"type":"text","text":"Common configuration for all components."}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","kind":"symbol","url":"\/documentation\/dotfacelite\/commonconfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration/initWithCommon:autoCapture:detectionArea:validators:error:":{"kind":"symbol","abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:detectionArea:validators:error:","title":"initWithCommon:autoCapture:detectionArea:validators:error:","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:autoCapture:detectionArea:validators:error:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:autoCapture:detectionArea:validators:error:"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration\/initwithcommon:autocapture:detectionarea:validators:error:","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}