{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","text":"DocumentAutoCapturePhase"},{"kind":"text","text":")"}]}]}],"metadata":{"roleHeading":"Initializer","role":"symbol","title":"init(detection:result:phase:)","externalID":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC9detection6result5phaseAeA0bcD9DetectionC_AA0bcdG0CSgAA0bcD5PhaseOtcfc","modules":[{"name":"DotDocument"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","text":"DocumentAutoCapturePhase","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult\/init(detection:result:phase:)"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","title":"DocumentAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult/init(detection:result:phase:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","text":"DocumentAutoCapturePhase"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","role":"symbol","type":"topic","title":"init(detection:result:phase:)","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult\/init(detection:result:phase:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"title":"DocumentAutoCaptureController.ProcessingResult","type":"topic","abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"title":"DocumentAutoCapturePhase","type":"topic","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturephase","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"title":"DocumentAutoCaptureResult","type":"topic","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","url":"\/documentation\/dotdocument\/documentautocaptureresult","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","op":"replace","value":"DOTDDocumentAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","op":"replace","value":"DOTDDocumentAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace","value":"DOTDDocumentAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}]}]}]}