{"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"result","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC6resultAA0bcdG0CSgvp","title":"result","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult\/result","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult\/result"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult","title":"DocumentAutoCaptureController.ProcessingResult","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingResult"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult/result":{"type":"topic","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"title":"result","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult\/result","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureResult":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"type":"topic","title":"DocumentAutoCaptureResult","navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureresult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}]}]}