{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Calculate width to height ratio.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculateWidthToHeightRatio()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/imagesize\/calculatewidthtoheightratio()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize\/calculatewidthtoheightratio()"]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculateWidthToHeightRatio","role":"symbol","symbolKind":"method","title":"calculateWidthToHeightRatio()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"]]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/ImageSize/calculateWidthToHeightRatio()":{"title":"calculateWidthToHeightRatio()","role":"symbol","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"abstract":[{"text":"Calculate width to height ratio.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":"() -> ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculateWidthToHeightRatio()","url":"\/documentation\/dotdocument\/imagesize\/calculatewidthtoheightratio()","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"url":"\/documentation\/dotdocument\/imagesize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"calculateWidthToHeightRatio","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"calculateWidthToHeightRatio","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculateWidthToHeightRatio()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculateWidthToHeightRatio()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}