{"abstract":[{"type":"text","text":"Resolved travel document type."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result\/travelDocumentType","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/result\/traveldocumenttype"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:11DotDocument9MrzReaderC6ResultC06travelB4TypeAA06TravelbG7WrapperCSgvp","title":"travelDocumentType","symbolKind":"property","modules":[{"name":"DotDocument"}]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/Result/travelDocumentType":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Resolved travel document type."}],"type":"topic","role":"symbol","kind":"symbol","title":"travelDocumentType","url":"\/documentation\/dotdocument\/mrzreader\/result\/traveldocumenttype","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result\/travelDocumentType"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}],"title":"TravelDocumentTypeWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"type":"topic","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","kind":"symbol","title":"MrzReader","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/Result":{"url":"\/documentation\/dotdocument\/mrzreader\/result","abstract":[{"text":"MRZ reading result.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Result"}],"type":"topic","title":"MrzReader.Result","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTTravelDocumentTypeWrapper","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title"},{"op":"replace","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"}]}]}