{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules\/barcode"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules"]]},"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"barcode","kind":"identifier"}],"title":"barcode","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode","fragments":[{"text":"barcode","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules\/barcode"},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfigurationModules":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules","title":"DotDocumentLibraryConfigurationModules","type":"topic","role":"symbol","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"abstract":[{"text":"Document library module configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"title":"DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfigurationModules/barcode":{"type":"topic","title":"barcode","fragments":[{"text":"barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules\/barcode","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules\/barcode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace","value":"DotDocumentBarcodeModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}]}]}