{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/error\/dotsdkerror-implementations"]}],"metadata":{"role":"collectionGroup","title":"DotSdkError Implementations","roleHeading":"API Collection","modules":[{"name":"DotDocument"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/composeWithInternalError()"],"generated":true,"anchor":"Instance-Methods"}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/DotSdkError-Implementations"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error","title":"DocumentAutoCaptureController.Error","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"title":"DocumentAutoCaptureController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/composeWithInternalError()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/composeWithInternalError()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/composewithinternalerror()","kind":"symbol","type":"topic","abstract":[],"title":"composeWithInternalError()"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}