{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/errorDescription","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/error\/errordescription"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.errorDescription","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"metadata":{"modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","extendedModule":"DotCore","title":"errorDescription","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:11DotDocument22ImagePerspectiveWarperC5ErrorO","role":"symbol","symbolKind":"property"},"references":{"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"ImagePerspectiveWarper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"ImagePerspectiveWarper.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/error"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error/errorDescription":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/imageperspectivewarper\/error\/errordescription","title":"errorDescription","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDImagePerspectiveWarper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace"},{"value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace"},{"value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","op":"replace"}]}]}