{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/configuration-swift.property","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureController(py)configuration","role":"symbol","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"title":"configuration","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC"}]},"abstract":[{"text":"Current configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.property"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/configuration-swift.property":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/configuration-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC"}],"abstract":[{"type":"text","text":"Current configuration."}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.property","kind":"symbol","title":"configuration"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.16.0"}],"type":"topic","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"abstract":[{"text":"Configuration of the document auto capture non-UI component.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"DocumentAutoCaptureController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration":{"abstract":[{"text":"Configuration of the document auto capture non-UI component.","type":"text"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","fragments":[{"text":"DOTDDocumentAutoCaptureControllerConfiguration","kind":"identifier"}],"role":"symbol","title":"DOTDDocumentAutoCaptureControllerConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"configuration","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","text":"DOTDDocumentAutoCaptureControllerConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"configuration"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"op":"replace","value":"configuration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1configuration-swift.property\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"}]}]}