{"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"roleHeading":"Type Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:cornerRadius:","symbolKind":"method","title":"createDetectionPath(corners:cornerRadius:)","navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Corners","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory"]]},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","type":"topic","abstract":[],"title":"createDetectionPath(corners:cornerRadius:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","text":"Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory":{"url":"\/documentation\/dotfacelite\/bezierpathfactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory","title":"BezierPathFactory","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners":{"title":"Corners","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/corners","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"createDetectionPathWithCorners:cornerRadius:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createDetectionPathWithCorners:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","text":"DOTCorners"},{"text":" *) ","kind":"text"},{"text":"corners","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cornerRadius"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/title","value":"DOTBezierPathFactory","op":"replace"},{"value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/title","value":"DOTCorners"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}