{"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotDocument"}],"title":"facing","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"facing"},{"kind":"text","text":": "},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"facing","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)facing"},"abstract":[{"type":"text","text":"Front or back camera facing."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/facing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/facing"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/facing"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"url":"\/documentation\/dotdocument\/cameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"type":"topic","role":"symbol","title":"CameraConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration/facing":{"abstract":[{"text":"Front or back camera facing.","type":"text"}],"navigatorTitle":[{"text":"facing","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/cameraconfiguration\/facing","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/facing","title":"facing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotdocument\/camerafacing","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","role":"symbol","kind":"symbol","title":"CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"facing"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"facing","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"facing"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1facing\/title","value":"facing"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1facing\/fragments","value":[{"text":"facing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}