{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"An index of the last character in the MRZ line.","type":"text"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","title":"endIndex","role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(py)endIndex","navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/endIndex"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzstringposition\/endindex"]},{"paths":["\/documentation\/dotnfc\/mrzstringposition\/endindex"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.10.0"}]},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"kind":"symbol","type":"topic","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"title":"MrzStringPosition","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","url":"\/documentation\/dotnfc\/mrzstringposition","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}]},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/endIndex":{"kind":"symbol","type":"topic","abstract":[{"text":"An index of the last character in the MRZ line.","type":"text"}],"title":"endIndex","role":"symbol","url":"\/documentation\/dotnfc\/mrzstringposition\/endindex","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/endIndex","navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"endIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"endIndex","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"endIndex"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"endIndex","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1endIndex\/title","value":"endIndex"},{"value":[{"text":"endIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1endIndex\/fragments"}]}]}