{"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(py)detection","role":"symbol","title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}],"fragments":[{"text":"detection","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules/detection":{"type":"topic","kind":"symbol","title":"detection","url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules\/detection","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules\/detection"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules":{"title":"DotPalmLibraryConfigurationModules","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmDetectionModuleConfiguration":{"role":"symbol","title":"DotPalmDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"abstract":[{"type":"text","text":"Palm detection module configuration."}],"url":"\/documentation\/dotfingerscore\/dotpalmdetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}