{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"isLibraryActive(libraryId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotSdk(im)isLibraryActiveWithLibraryId:"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isLibraryActive(libraryId:)","interfaceLanguage":"swift"},"abstract":[{"text":"Check whether ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library is active.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotSdk":{"type":"topic","title":"DotSdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","kind":"symbol","url":"\/documentation\/dotdocument\/dotsdk","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/isLibraryActive(libraryId:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLibraryActive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"role":"symbol","title":"isLibraryActive(libraryId:)","url":"\/documentation\/dotdocument\/dotsdk\/islibraryactive(libraryid:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isLibraryActive(libraryId:)","navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","type":"topic","title":"DotLibraryId","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isLibraryActiveWithLibraryId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"kind":"text","text":") "},{"kind":"internalParam","text":"libraryId"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isLibraryActive(libraryId:)\/title","value":"isLibraryActiveWithLibraryId:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isLibraryActive(libraryId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}