{"kind":"article","sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/localizedDescription"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/Error-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/intervaldouble\/error\/error-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"Error Implementations","modules":[{"name":"DotPalmCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"title":"IntervalDouble","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotpalmcore\/intervaldouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/localizedDescription":{"title":"localizedDescription","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/localizedDescription","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/localizeddescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/intervaldouble\/error","kind":"symbol","title":"IntervalDouble.Error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}