{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/expressionNeutral"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/expressionneutral"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/expressionneutral"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdExpressionNeutral","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"title":"DotFaceModuleId.expressionNeutral"},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","url":"\/documentation\/dotnfc\/dotfacemoduleid","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/expressionNeutral":{"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotfacemoduleid\/expressionneutral","kind":"symbol","role":"symbol","title":"DotFaceModuleId.expressionNeutral","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/expressionNeutral"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceModuleIdExpressionNeutral","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceModuleId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1expressionNeutral\/title","op":"replace","value":"DotFaceModuleIdExpressionNeutral"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1expressionNeutral\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}]}]}]}