{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"externalID":"s:7DotCore0A12FaceModuleIdO8rawValueACSgSi_tcfc","symbolKind":"init","modules":[{"name":"DotNfc"}],"role":"symbol","title":"init(rawValue:)","roleHeading":"Initializer"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/init(rawValue:)":{"kind":"symbol","abstract":[],"role":"symbol","title":"init(rawValue:)","type":"topic","url":"\/documentation\/dotnfc\/dotfacemoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","url":"\/documentation\/dotnfc\/dotfacemoduleid","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle"}]}]}