{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"aspects","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","text":"FaceAspects","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keypoints","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"title":"init(confidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:)","symbolKind":"init","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"aspects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","text":"FaceAspects","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keypoints","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"s:11DotFaceCore0B8DetectorC0B0C10confidence8position7aspects7quality9keypoints15passiveLiveness16fullFrontalImage8templateAESd_0aB7Commons17DetectionPositionCAA0B7AspectsCAA0B7QualityCAA0B9KeypointsCAA0B9AttributeCSg0aC00N0CSgAA8TemplateCSgtcfc","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:aspects:quality:keypoints:passiveliveness:fullfrontalimage:template:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"title":"Image","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/image"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"kind":"symbol","title":"FaceKeypoints","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","type":"topic","abstract":[{"type":"text","text":"The position of the detected face in the image."}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","url":"\/documentation\/dotfacecore\/detectionposition","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"url":"\/documentation\/dotfacecore\/template","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}],"abstract":[{"type":"text","text":"Face template."}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","role":"symbol","title":"Template","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequality","title":"FaceQuality","type":"topic","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"navigatorTitle":[{"kind":"identifier","text":"Face"}],"abstract":[{"text":"Detected face in the image.","type":"text"}],"title":"FaceDetector.Face","url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","title":"FaceAspects","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/faceaspects","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"kind":"symbol","title":"FaceAttribute"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","type":"topic","title":"FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/init(confidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition"},{"text":", ","kind":"text"},{"text":"aspects","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keypoints","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(confidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:)","type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:aspects:quality:keypoints:passiveliveness:fullfrontalimage:template:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","value":"DOTFFaceKeypoints"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle","value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}