{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keypoints","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints","kind":"typeIdentifier"}],"externalID":"s:11DotFaceCore0B8DetectorC0B0C9keypointsAA0B9KeypointsCvp","title":"keypoints"},"kind":"symbol","abstract":[{"type":"text","text":"Face keypoints."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/keypoints"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keypoints","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","text":"FaceKeypoints","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/keypoints","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"navigatorTitle":[{"kind":"identifier","text":"Face"}],"abstract":[{"text":"Detected face in the image.","type":"text"}],"title":"FaceDetector.Face","url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/keypoints":{"url":"\/documentation\/dotfacecore\/facedetector\/face\/keypoints","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/keypoints","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keypoints","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoints","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints"}],"role":"symbol","abstract":[{"text":"Face keypoints.","type":"text"}],"title":"keypoints","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","type":"topic","title":"FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"kind":"symbol","title":"FaceKeypoints","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace","value":"DOTFFaceDetector"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","op":"replace","value":"DOTFFaceKeypoints"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}]}]}]}