{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/threshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/threshold"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/threshold"},"kind":"symbol","metadata":{"title":"threshold","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBrightnessTooHighValidator(py)threshold","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Current maximal accepted brightness."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected palm."}],"url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","kind":"symbol","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","title":"PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/threshold":{"title":"threshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/threshold","abstract":[{"type":"text","text":"Current maximal accepted brightness."}],"url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/threshold","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"threshold"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"threshold","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"threshold"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","value":"DOTPBrightnessTooHighValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1threshold\/title","value":"threshold"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}