{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Face passive liveness module.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","role":"symbol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"roleHeading":"Class","title":"DotFacePassiveLivenessModuleConfiguration"},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"title":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","type":"topic","abstract":[{"type":"text","text":"Face passive liveness module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"role":"symbol"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 9.1.1","type":"text"}],"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration/init":{"title":"init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration\/init","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration\/init"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DotFacePassiveLivenessModuleConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration\/init"],"title":"Instance Methods"}],"op":"add"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}