{"metadata":{"modules":[{"name":"DotNfc"}],"role":"collectionGroup","title":"LocalizedError Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"]]},"kind":"article","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/localizederror-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/failureReason","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/helpAnchor","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/recoverySuggestion"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/LocalizedError-Implementations"},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error/failureReason":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"failureReason","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/failurereason","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/failureReason"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error/recoverySuggestion":{"title":"recoverySuggestion","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/recoverySuggestion","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","title":"NfcTravelDocumentReader.Error","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error/helpAnchor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"helpAnchor","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/helpanchor","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/helpAnchor"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"}]}]}