{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isEvaluation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol(py)isEvaluation","required":true,"title":"isEvaluation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isevaluation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isevaluation"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isEvaluation":{"required":true,"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isEvaluation","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isevaluation","title":"isEvaluation","navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"role":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DotSdkLicenseProxyProtocol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"isEvaluation","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"isEvaluation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"}]}]}},{"value":"isEvaluation","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments","value":[{"text":"isEvaluation","kind":"identifier"}]},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}