{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/mineyesstatusscore"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Minimal valid eyes status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"title":"minEyesStatusScore","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC18minEyesStatusScoreAA13WrappedDoubleCSgvp","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minEyesStatusScore":{"role":"symbol","title":"minEyesStatusScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid eyes status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/mineyesstatusscore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedDouble":{"role":"symbol","title":"WrappedDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotfacecore\/wrappeddouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/title","value":"DOTFFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}