{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage","role":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"symbolKind":"class","title":"BgrRawImage","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimage"]},{"paths":["\/documentation\/dotpalmcore\/bgrrawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBgrRawImage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/init(bytesPointer:size:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytesPointer","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/size"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/init(bytesPointer:size:)":{"navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"abstract":[{"text":"Do not use this, use ","type":"text"},{"code":"BgrRawImageFactory","type":"codeVoice"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrrawimage\/init(bytespointer:size:)","title":"init(bytesPointer:size:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/init(bytesPointer:size:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"text":")","kind":"text"}],"role":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/bytesPointer":{"navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/bgrrawimage\/bytespointer","title":"bytesPointer","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytesPointer","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"role":"symbol"},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotpalmcore\/bgrrawimage","title":"BgrRawImage","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"type":"topic"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/size":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/size","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}],"title":"size","type":"topic","url":"\/documentation\/dotpalmcore\/bgrrawimage\/size","role":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}]},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/bytes":{"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/bgrrawimage\/bytes","title":"bytes","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytes","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotPalmCore/@M@DotCore@objc(pl)_RawImage":{"identifier":"doc:\/\/DotPalmCore\/@M@DotCore@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTBgrRawImage","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/bytesPointer","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/size"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/init(bytesPointer:size:)"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotPalmCore\/@M@DotCore@objc(pl)_RawImage"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTBgrRawImage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"initWithBytesPointer:size:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1init(bytesPointer:size:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBytesPointer:size:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1init(bytesPointer:size:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1bytesPointer\/title","value":"bytesPointer"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1bytesPointer\/fragments","value":[{"kind":"identifier","text":"bytesPointer"}]},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title"},{"op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1size\/title","value":"size","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1size\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1bytes\/title","value":"bytes"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}