{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"major","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/init(major:minor:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore8TemplateC7VersionC5major5minorAESi_Sitcfc","role":"symbol","title":"init(major:minor:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"major","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minor"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/template\/version-swift.class\/init(major:minor:)"]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/template","navigatorTitle":[{"kind":"identifier","text":"Template"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","abstract":[{"type":"text","text":"Face template."}],"type":"topic","title":"Template","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Version"}],"kind":"symbol","title":"Template.Version","type":"topic","role":"symbol","abstract":[{"text":"Template compatibility version.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Version"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","url":"\/documentation\/dotfacecore\/template\/version-swift.class"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","title":"TemplateMatcher","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/templatematcher","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/init(major:minor:)":{"url":"\/documentation\/dotfacecore\/template\/version-swift.class\/init(major:minor:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/init(major:minor:)","role":"symbol","title":"init(major:minor:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"major","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"minor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","op":"replace","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]}]}]}