{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"cgImage"}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"New "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"create(cgImage:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"modules":[{"name":"DotNfc"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory(cm)createWithCgImage:","role":"symbol"},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"object."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory"]]},"variants":[{"paths":["\/documentation\/dotnfc\/bgrrawimagefactory\/create(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrrawimagefactory\/create(cgimage:)"]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(cgImage:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/BgrRawImage":{"role":"symbol","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrrawimage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory/create(cgImage:)":{"url":"\/documentation\/dotnfc\/bgrrawimagefactory\/create(cgimage:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"title":"create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(cgImage:)"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImageFactory"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"url":"\/documentation\/dotnfc\/bgrrawimagefactory","title":"BgrRawImageFactory","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"createWithCgImage:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGImage","text":"CGImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(cgImage:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"}]},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/title"},{"value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/fragments"}]}]}