{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory\/create(cgImage:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage","text":"BgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"cgImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Type Method","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImageFactory(cm)createWithCgImage:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}],"title":"create(cgImage:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrrawimagefactory\/create(cgimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrrawimagefactory\/create(cgimage:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImageFactory":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory","title":"BgrRawImageFactory","url":"\/documentation\/dotfacelite\/bgrrawimagefactory","type":"topic","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImageFactory/create(cgImage:)":{"title":"create(cgImage:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory\/create(cgImage:)","url":"\/documentation\/dotfacelite\/bgrrawimagefactory\/create(cgimage:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":"object.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage":{"title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrrawimage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createWithCgImage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier","text":"CGImage"},{"text":" *) ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory\/title"},{"op":"replace","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory\/fragments"},{"value":"createWithCgImage:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory~1create(cgImage:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory~1create(cgImage:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]}]}]}