{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrrawimagefactory\/create(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrrawimagefactory\/create(ciimage:cicontext:)"]}],"metadata":{"role":"symbol","title":"create(ciImage:ciContext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImageFactory(cm)createWithCiImage:ciContext:","symbolKind":"method","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"object."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"ciImage"},{"content":[{"inlineContent":[{"text":"CIContext.","type":"text"}],"type":"paragraph"}],"name":"ciContext"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}]}]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImageFactory":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory","title":"BgrRawImageFactory","url":"\/documentation\/dotfacelite\/bgrrawimagefactory","type":"topic","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage":{"title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrrawimage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImageFactory/create(ciImage:ciContext:)":{"title":"create(ciImage:ciContext:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/bgrrawimagefactory\/create(ciimage:cicontext:)","type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createWithCiImage:ciContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","kind":"typeIdentifier","text":"DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"text":"createWithCiImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory\/title"},{"value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments"}]}]}