{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentmoduleid\/init(rawvalue:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId"]]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"externalID":"s:7DotCore0A16DocumentModuleIdO8rawValueACSgSi_tcfc","modules":[{"name":"DotFingersCore"}],"title":"init(rawValue:)","symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId":{"type":"topic","title":"DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid","abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/init(rawvalue:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/fragments","op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace"}]}]}