{"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glasses","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"Glasses","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearables(py)glasses","roleHeading":"Instance Property","title":"glasses","navigatorTitle":[{"text":"glasses","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/glasses","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glasses","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","text":"Glasses","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wearables\/glasses"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wearables\/glasses"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Glasses evaluation result."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"url":"\/documentation\/dotfacecore\/glasses","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"title":"Glasses","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/glasses":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"glasses","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"Glasses","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Glasses evaluation result.","type":"text"}],"title":"glasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/glasses","role":"symbol","navigatorTitle":[{"text":"glasses","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wearables\/glasses"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"type":"topic","title":"Wearables","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"url":"\/documentation\/dotfacecore\/wearables","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"glasses","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"glasses","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"DOTFGlasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"},{"kind":"text","text":" * "},{"kind":"identifier","text":"glasses"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/navigatorTitle","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1glasses\/title","value":"glasses","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1glasses\/fragments","value":[{"text":"glasses","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace"}]}]}