{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wearables\/mask"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wearables\/mask"]}],"abstract":[{"text":"Face mask evaluation result.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/mask"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"]]},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"mask","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearables(py)mask","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"mask","kind":"identifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Wearables/mask":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/dotfacecore\/wearables\/mask","abstract":[{"text":"Face mask evaluation result.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mask"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/mask","title":"mask"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"title":"FaceAttribute","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"kind":"symbol","url":"\/documentation\/dotfacecore\/wearables","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"type":"topic","title":"Wearables","role":"symbol","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mask","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"mask","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFFaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mask"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mask","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1mask\/title","op":"replace"},{"value":[{"text":"mask","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1mask\/fragments","op":"replace"},{"value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","op":"replace"},{"value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}