{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.class\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-16pbs"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class"]]},"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC15backgroundColor15instructionFont0k4TextJ00k18CandidateSelectionmJ00k10BackgroundJ00knopJ0011placeholderJ00qnoJ0014detectionLayerJ0AESo7UIColorC_So6UIFontCA7Ptcfc","role":"symbol","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":", ","kind":"text"},{"text":"instructionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionCandidateSelectionBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"placeholderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"placeholderCandidateSelectionColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"detectionLayerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = PreviewViewStyle.Defaults.backgroundColor, ","kind":"text"},{"text":"instructionFont","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":" = InstructionCandidateSelectionStyle.Defaults.font, ","kind":"text"},{"text":"instructionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = InstructionCandidateSelectionStyle.Defaults.textColor, ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = InstructionCandidateSelectionStyle.Defaults.candidateSelectionTextColor, ","kind":"text"},{"text":"instructionBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" = InstructionCandidateSelectionStyle.Defaults.backgroundColor, "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" = InstructionCandidateSelectionStyle.Defaults.candidateSelectionBackgroundColor, "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" = PlaceholderCandidateSelectionStyle.Defaults.color, "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" = PlaceholderCandidateSelectionStyle.Defaults.candidateSelectionColor, "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" = PreviewViewStyle.Defaults.detectionLayerColor)"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Style-swift.class/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)":{"kind":"symbol","type":"topic","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.class\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-16pbs","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Style-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Style","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the fingers auto capture user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","type":"topic","title":"FingersAutoCaptureViewController","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewController"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle"}]}]}