{"sections":[],"abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/document"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"roleHeading":"Case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","title":"DotLibraryId.document","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdDocument"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/document"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/document"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/document":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/document","url":"\/documentation\/dotfacecore\/dotlibraryid\/document","type":"topic","title":"DotLibraryId.document","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId","title":"DotLibraryId","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdDocument"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1document\/title","value":"DotLibraryIdDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1document\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}