{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration(im)init","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentBarcodeModuleConfiguration":{"role":"symbol","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"kind":"symbol","title":"DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentBarcodeModuleConfiguration/init":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration\/init","kind":"symbol","title":"init","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration\/init","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}