{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:7DotCore0A15FingersModuleIdO8rawValueACSgSi_tcfc","symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotDocument"}],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfingersmoduleid\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/init(rawValue:)":{"type":"topic","role":"symbol","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/init(rawValue:)","url":"\/documentation\/dotdocument\/dotfingersmoduleid\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId":{"url":"\/documentation\/dotdocument\/dotfingersmoduleid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/title"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}