{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdTransformation","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"DotFingersModuleId.transformation","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/transformation"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfingersmoduleid\/transformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfingersmoduleid\/transformation"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DotFingersModuleId":{"url":"\/documentation\/dotdocument\/dotfingersmoduleid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/transformation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/transformation","role":"symbol","url":"\/documentation\/dotdocument\/dotfingersmoduleid\/transformation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DotFingersModuleId.transformation","abstract":[],"navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFingersModuleIdTransformation","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/navigatorTitle"},{"op":"replace","value":"DotFingersModuleIdTransformation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1transformation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1transformation\/fragments"}]}]}