{"kind":"symbol","metadata":{"externalID":"c:@M@DotDocument@E@DOTDValidationMode@DOTDValidationModeStrict","title":"ValidationMode.strict","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"strict"}],"modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStrict"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"strict"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/strict"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"]]},"abstract":[{"text":"Document must be clearly visible, sharp enough and well aligned with the placeholder.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/validationmode\/strict"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/validationmode\/strict"]}],"references":{"doc://DotDocument/documentation/DotDocument/ValidationMode":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","kind":"symbol","title":"ValidationMode","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ValidationMode","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}],"url":"\/documentation\/dotdocument\/validationmode"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode/strict":{"title":"ValidationMode.strict","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"strict","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/strict","abstract":[{"type":"text","text":"Document must be clearly visible, sharp enough and well aligned with the placeholder."}],"role":"symbol","url":"\/documentation\/dotdocument\/validationmode\/strict","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStrict"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDValidationModeStrict","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDValidationModeStrict"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTDValidationModeStrict","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDValidationMode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode~1strict\/title","value":"DOTDValidationModeStrict","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode~1strict\/fragments","value":[{"text":"DOTDValidationModeStrict","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}