{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/left"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/left"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/left","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Left edge."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"left","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTRectangleDouble(py)left","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"left"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotdocument\/rectangledouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/left":{"role":"symbol","title":"left","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Left edge."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"left"}],"url":"\/documentation\/dotdocument\/rectangledouble\/left"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"left"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"left"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1left\/title","value":"left"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1left\/fragments","value":[{"kind":"identifier","text":"left"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}