{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/bottom","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Bottom edge.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/rectangleint\/bottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/rectangleint\/bottom"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(py)bottom","title":"bottom","modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"bottom"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt":{"title":"RectangleInt","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotfacelite\/rectangleint","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/bottom":{"title":"bottom","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"abstract":[{"type":"text","text":"Bottom edge."}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/bottom","url":"\/documentation\/dotfacelite\/rectangleint\/bottom"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bottom"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"bottom","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1bottom\/title","value":"bottom"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1bottom\/fragments","value":[{"kind":"identifier","text":"bottom"}]}]}]}