{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Top edge.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(py)top","title":"top","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"top"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/top","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacelite\/rectangleint\/top"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/rectangleint\/top"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt":{"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/rectangleint","title":"RectangleInt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/top":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/top","type":"topic","title":"top","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Top edge."}],"url":"\/documentation\/dotfacelite\/rectangleint\/top","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"top"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"top","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"top"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/title"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/navigatorTitle"},{"op":"replace","value":"top","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1top\/title"},{"op":"replace","value":[{"kind":"identifier","text":"top"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1top\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}