{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotlibraryid\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibraryid\/face"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"]]},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"}],"title":"DotLibraryId.face","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFace"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/face"},"references":{"doc://DotDocument/documentation/DotDocument/DotLibraryId/face":{"role":"symbol","kind":"symbol","title":"DotLibraryId.face","navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/face","url":"\/documentation\/dotdocument\/dotlibraryid\/face","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"}]},"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotlibraryid","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DotLibraryIdFace","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFace"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotLibraryIdFace"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1face\/title","value":"DotLibraryIdFace","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1face\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments"}]}]}