{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"eyeGazeLiveness","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLiveness"}],"title":"eyeGazeLiveness","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)eyeGazeLiveness","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/eyegazeliveness"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"abstract":[{"text":"Face library module configuration.","type":"text"}],"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"title":"DotFaceLibraryConfigurationModules","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/eyeGazeLiveness":{"abstract":[],"fragments":[{"text":"eyeGazeLiveness","kind":"identifier"}],"title":"eyeGazeLiveness","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/eyegazeliveness","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness"},"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"title":"DotFaceEyeGazeLivenessModuleConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}