{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoint\/score"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/score","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optional keypoint detection score."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"metadata":{"title":"score","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"s:11DotFaceCore0B8KeypointC5scoreSdSgvp","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/score":{"kind":"symbol","title":"score","abstract":[{"type":"text","text":"Optional keypoint detection score."}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/score","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoint\/score","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"title":"FaceKeypoint","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoint"}],"abstract":[{"text":"Face Keypoint","type":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoint","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","value":"DOTFFaceKeypoint","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}