{"sections":[],"metadata":{"navigatorTitle":[{"text":"detectWithFaceImage:query:limit:error:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"method","title":"detect(faceImage:query:limit:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"faceImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"text":", ","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector(im)detectWithFaceImage:query:limit:error:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/detect(faceimage:query:limit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facedetector\/detect(faceimage:query:limit:)"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/detect(faceImage:query:limit:)","interfaceLanguage":"swift"},"abstract":[{"text":"Detect faces in an image.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","text":"FaceImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery"},{"text":" = .init(), ","kind":"text"},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"kind":"text","text":"]"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Face image."}],"type":"paragraph"}],"name":"faceImage"},{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Query for additional evaluation of each detected face."}]}]},{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limit the number of faces to detect."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Array of detected faces.","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method requires "},{"code":"DotFaceDetection*","type":"codeVoice"},{"text":" module to be active. This method should be called on the background thread.","type":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/detect(faceImage:query:limit:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/detect(faceImage:query:limit:)","role":"symbol","title":"detect(faceImage:query:limit:)","url":"\/documentation\/dotfacecore\/facedetector\/detect(faceimage:query:limit:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"faceImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","kind":"typeIdentifier","text":"FaceImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"text":"]","kind":"text"}],"abstract":[{"text":"Detect faces in an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectWithFaceImage:query:limit:error:"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"role":"symbol","title":"FaceDetector","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImage","kind":"identifier"}],"kind":"symbol","title":"FaceImage","type":"topic","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"url":"\/documentation\/dotfacecore\/faceimage","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery","kind":"symbol","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","title":"FaceDetectionQuery","role":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","abstract":[{"type":"text","text":"Detected face in the image."}],"role":"symbol","title":"FaceDetector.Face","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"detectWithFaceImage:query:limit:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"detectWithFaceImage:query:limit:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<Face *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectWithFaceImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":" *) "},{"text":"faceImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"query:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":" *) "},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"limit:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"limit","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1detect(faceImage:query:limit:)\/title","op":"replace","value":"detectWithFaceImage:query:limit:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithFaceImage:query:limit:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1detect(faceImage:query:limit:)\/fragments"},{"value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title","op":"replace","value":"DOTFFaceImage"},{"value":[{"text":"DOTFFaceImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","op":"replace"},{"value":"FaceDetectionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}