{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration"]]},"abstract":[{"text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to ","type":"text"},{"code":"0","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/candidateselectiondurationmillis"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/candidateselectiondurationmillis"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)candidateSelectionDurationMillis","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"candidateSelectionDurationMillis","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"url":"\/documentation\/dotdocument\/autocaptureconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","title":"AutoCaptureConfiguration","type":"topic"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/candidateSelectionDurationMillis":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"candidateSelectionDurationMillis","type":"topic","abstract":[{"text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to ","type":"text"},{"type":"codeVoice","code":"0"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/candidateselectiondurationmillis","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"candidateSelectionDurationMillis"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/title","op":"replace","value":"candidateSelectionDurationMillis"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/fragments","op":"replace","value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}]}]}]}