{"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}],"title":"qualityAttributeThresholds","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC26qualityAttributeThresholdsAA0bef7QualitykL0Cvp","modules":[{"name":"DotPalmCore"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"]]},"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" preset."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/qualityattributethresholds"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","title":"BasePalmAutoCaptureViewController.Configuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","text":"PalmAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/qualityattributethresholds","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Customize thresholds for the quality attributes of the capture result. Default is ","type":"text"},{"type":"codeVoice","code":".standard"},{"text":" preset.","type":"text"}],"title":"qualityAttributeThresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/qualityAttributeThresholds"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"kind":"symbol","type":"topic","title":"BasePalmAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","title":"PalmAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","type":"topic","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","value":"DOTPBasePalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}]}]}]}