{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Type Property","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC8DefaultsV22cameraPreviewScaleType0A6Camera0olmN0OvpZ","modules":[{"name":"DotFaceLite"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/Defaults/cameraPreviewScaleType":{"role":"symbol","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","kind":"symbol","abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"kind":"symbol","type":"topic","title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","type":"topic","title":"MagnifEyeLivenessViewController","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/Defaults":{"role":"symbol","title":"MagnifEyeLivenessViewController.Configuration.Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Defaults"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","type":"topic","title":"MagnifEyeLivenessViewController.Configuration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}