{"variants":[{"paths":["\/documentation\/dotdocument\/documentimagequality\/hotspotsscore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentimagequality\/hotspotsscore"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hotspotsScore"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality(py)hotspotsScore","roleHeading":"Instance Property","role":"symbol","title":"hotspotsScore","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"]]},"abstract":[{"type":"text","text":"Hotspots score value in range [0, 1.0]."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hotspotsScore","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/hotspotsScore":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hotspotsScore","kind":"identifier"}],"abstract":[{"text":"Hotspots score value in range [0, 1.0].","type":"text"}],"title":"hotspotsScore","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/hotspotsScore","kind":"symbol","url":"\/documentation\/dotdocument\/documentimagequality\/hotspotsscore","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"title":"DocumentImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentImageQuality","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentimagequality","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","abstract":[{"type":"text","text":"Document image quality."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DocumentImageQuality","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hotspotsScore"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"hotspotsScore","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hotspotsScore\/title","op":"replace","value":"hotspotsScore"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1hotspotsScore\/fragments","op":"replace","value":[{"text":"hotspotsScore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title","op":"replace","value":"DOTDDocumentImageQuality"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments","op":"replace","value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}