{"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper(im)init","role":"symbol","symbolKind":"init","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/init()"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper"]]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/init()","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/init()":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/init()","abstract":[],"title":"init()","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"title":"ImagePerspectiveWarper","url":"\/documentation\/dotdocument\/imageperspectivewarper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]}]}]}