{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Input image.","type":"text"}]}]},{"name":"detectionPosition","content":[{"type":"paragraph","inlineContent":[{"text":"Detected document corners.","type":"text"}]}]},{"name":"targetImageSize","content":[{"type":"paragraph","inlineContent":[{"text":"Size of the resulting image.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"New warped image.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"aside","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error if ","type":"text"},{"code":"ImagePerspectiveWarper","type":"codeVoice"},{"text":" fails to warp the image.","type":"text"}]}],"style":"note"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(image:detectionPosition:targetImageSize:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"title":"warp(image:detectionPosition:targetImageSize:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"warpWithImage:detectionPosition:targetImageSize:error:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper(im)warpWithImage:detectionPosition:targetImageSize:error:","symbolKind":"method"},"abstract":[{"text":"Warp the image perspective using the document detection result.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(image:detectionposition:targetimagesize:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(image:detectionposition:targetimagesize:)"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/warp(image:detectionPosition:targetImageSize:)":{"url":"\/documentation\/dotdocument\/imageperspectivewarper\/warp(image:detectionposition:targetimagesize:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(image:detectionPosition:targetImageSize:)","kind":"symbol","role":"symbol","title":"warp(image:detectionPosition:targetImageSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"abstract":[{"text":"Warp the image perspective using the document detection result.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"warpWithImage:detectionPosition:targetImageSize:error:"}]},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"title":"ImagePerspectiveWarper","url":"\/documentation\/dotdocument\/imageperspectivewarper"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"type":"text","text":"Position of the document card in the image."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","url":"\/documentation\/dotdocument\/detectionposition"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"title":"ImageSize","url":"\/documentation\/dotdocument\/imagesize"},"doc://DotDocument/documentation/DotDocument/Image":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"title":"Image","url":"\/documentation\/dotdocument\/image"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"warpWithImage:detectionPosition:targetImageSize:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"warpWithImage:detectionPosition:targetImageSize:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"},{"text":" *) ","kind":"text"},{"text":"warpWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectionPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTDDetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},{"text":" *) ","kind":"text"},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"targetImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"targetImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Input image.","type":"text"}]}]},{"name":"detectionPosition","content":[{"type":"paragraph","inlineContent":[{"text":"Detected document corners.","type":"text"}]}]},{"name":"targetImageSize","content":[{"type":"paragraph","inlineContent":[{"text":"Size of the resulting image.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"New warped image.","type":"text"},{"text":" On failure, this method returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"warpWithImage:detectionPosition:targetImageSize:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(image:detectionPosition:targetImageSize:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"warpWithImage:detectionPosition:targetImageSize:error:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(image:detectionPosition:targetImageSize:)\/fragments"},{"value":"DOTDImagePerspectiveWarper","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title"},{"value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments"},{"value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle"},{"value":"DOTDDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}