{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"warp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"targetImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"role":"symbol","navigatorTitle":[{"text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper(im)warpWithBgraRawImage:detectionPosition:targetImageSize:error:","modules":[{"name":"DotDocument"}],"title":"warp(bgraRawImage:detectionPosition:targetImageSize:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:detectionPosition:targetImageSize:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectionPosition"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"targetImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image.","type":"text"}]}],"name":"bgraRawImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detected document corners."}]}],"name":"detectionPosition"},{"name":"targetImageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Size of the resulting image."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New warped image.","type":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:detectionposition:targetimagesize:)"]},{"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:detectionposition:targetimagesize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Warp the image perspective using the document detection result."}],"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/warp(bgraRawImage:detectionPosition:targetImageSize:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"warp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectionPosition"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:detectionposition:targetimagesize:)","abstract":[{"text":"Warp the image perspective using the document detection result.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:detectionPosition:targetImageSize:)","kind":"symbol","title":"warp(bgraRawImage:detectionPosition:targetImageSize:)"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper","kind":"symbol","title":"ImagePerspectiveWarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"type":"topic","navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","type":"topic","abstract":[{"text":"Position of the document card in the image.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","title":"DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotDocument/documentation/DotDocument/ImageSize":{"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","url":"\/documentation\/dotdocument\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","type":"topic","kind":"symbol","title":"ImageSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"warpWithBgraRawImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionPosition:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTDDetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},{"kind":"text","text":" *) "},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"targetImageSize:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"targetImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:detectionPosition:targetImageSize:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:detectionPosition:targetImageSize:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:"}]},{"op":"replace","value":"DOTDImagePerspectiveWarper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title"},{"value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"}]}]}