{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New warped image."}]}]},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image."}]}]},{"name":"corners","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detected document corners."}]}]},{"name":"targetImageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Size of the resulting image."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:corners:targetimagesize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:corners:targetimagesize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:corners:targetImageSize:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Warp the image perspective using the document detection result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"title":"warp(bgraRawImage:corners:targetImageSize:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper(im)warpWithBgraRawImage:corners:targetImageSize:error:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"warpWithBgraRawImage:corners:targetImageSize:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper/warp(bgraRawImage:corners:targetImageSize:)":{"role":"symbol","title":"warp(bgraRawImage:corners:targetImageSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"abstract":[{"type":"text","text":"Warp the image perspective using the document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:corners:targetImageSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"warpWithBgraRawImage:corners:targetImageSize:error:"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:corners:targetimagesize:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper":{"role":"symbol","title":"ImagePerspectiveWarper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"warpWithBgraRawImage:corners:targetImageSize:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"warpWithBgraRawImage:corners:targetImageSize:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"warpWithBgraRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"corners:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTCorners","preciseIdentifier":"c:objc(cs)DOTCorners"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"corners"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetImageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTImageSize","preciseIdentifier":"c:objc(cs)DOTImageSize"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"targetImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:corners:targetImageSize:)\/title","value":"warpWithBgraRawImage:corners:targetImageSize:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:corners:targetImageSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"warpWithBgraRawImage:corners:targetImageSize:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}