{"sections":[],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery(py)evaluateMask","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"evaluateMask"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateMask","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceCore"}],"title":"evaluateMask"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery\/evaluateMask","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateMask","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wearablesquery\/evaluatemask"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wearablesquery\/evaluatemask"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Face mask evaluation flag.","type":"text"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}],"url":"\/documentation\/dotfacecore\/wearablesquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"type":"topic","abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","kind":"symbol","title":"WearablesQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery/evaluateMask":{"url":"\/documentation\/dotfacecore\/wearablesquery\/evaluatemask","kind":"symbol","type":"topic","abstract":[{"text":"Face mask evaluation flag.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"evaluateMask","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery\/evaluateMask","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateMask"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"evaluateMask"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.1.0","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"evaluateMask"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"evaluateMask"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"evaluateMask","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery~1evaluateMask\/title","value":"evaluateMask","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery~1evaluateMask\/fragments","value":[{"text":"evaluateMask","kind":"identifier"}]}]}]}