{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/optionaldetails\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/optionaldetails\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"metadata":{"title":"isEqual(_:)","externalID":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails(im)isEqual:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/isEqual(_:)"},"references":{"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"title":"OptionalDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OptionalDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","url":"\/documentation\/dotnfc\/optionaldetails","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/isEqual(_:)":{"title":"isEqual(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotnfc\/optionaldetails\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"isEqual:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1isEqual(_:)\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}