{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/name","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)name","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"name"}],"modules":[{"name":"DotDocument"}],"title":"name"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/name"]}],"references":{"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"kind":"symbol","type":"topic","title":"Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","title":"MrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone/name":{"url":"\/documentation\/dotdocument\/td2machinereadablezone\/name","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"abstract":[],"title":"name","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/name","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","type":"topic","role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","kind":"typeIdentifier","text":"DOTMrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"name"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/navigatorTitle","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}