{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","symbolKind":"property","roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator(cpy)defaultMinEdgeLengthToImageShorterSideRatioThreshold"},"variants":[{"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Default threshold.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/defaultMinEdgeLengthToImageShorterSideRatioThreshold":{"title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold","abstract":[{"text":"Default threshold.","type":"text"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","title":"PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"title":"SizeTooSmallValidator","abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"languages":["occ"]}]}},{"value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}],"op":"replace"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}]}]}]}