{"abstract":[{"text":"Application Bundle ID.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundleId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"bundleId","navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotSdk(py)bundleId","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/bundleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/bundleid"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/bundleId","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/bundleId":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacelite\/dotsdk\/bundleid","title":"bundleId","navigatorTitle":[{"text":"bundleId","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/bundleId","abstract":[{"type":"text","text":"Application Bundle ID."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"type":"text","text":"version: 8.15.2"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bundleId"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"bundleId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bundleId"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","op":"replace","value":"DotSdk"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","op":"replace"},{"value":"bundleId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1bundleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bundleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1bundleId\/fragments"}]}]}