{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/warning"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel"]]},"variants":[{"paths":["\/documentation\/dotdocument\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]}]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"roleHeading":"Case","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelWarning","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"case","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"title":"LoggerLogLevel.warning"},"abstract":[{"text":"Logs unexpected events which indicate malfunction.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel":{"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/loggerloglevel","title":"LoggerLogLevel"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel/warning":{"abstract":[{"text":"Logs unexpected events which indicate malfunction.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/warning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/loggerloglevel\/warning","title":"LoggerLogLevel.warning"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTLoggerLogLevelWarning","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/navigatorTitle","op":"replace"},{"value":"DOTLoggerLogLevelWarning","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1warning\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1warning\/fragments","op":"replace"}]}]}