{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdk"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/getlibrary(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibraryId","preciseIdentifier":"c:@M@DotPalmCore@E@DotLibraryId"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"title":"getLibrary(libraryId:)","externalID":"s:11DotPalmCore0A3SdkC10getLibrary9libraryIdAA0aF0_pSgAA0afH0O_tF","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"kind":"text","text":") -> "},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdk\/getLibrary(libraryId:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary":{"title":"DotLibrary","role":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdk":{"type":"topic","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdk","title":"DotSdk","url":"\/documentation\/dotpalmcore\/dotsdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdk/getLibrary(libraryId:)":{"title":"getLibrary(libraryId:)","role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/getlibrary(libraryid:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdk\/getLibrary(libraryId:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"kind":"text","text":") -> "},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibraryId":{"abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"DotLibraryId","url":"\/documentation\/dotpalmcore\/dotlibraryid"}},"variantOverrides":[{"patch":[{"value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibraryId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}