{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init(preview:phase:detection:result:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","text":"DocumentAutoCapturePhase","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC7preview5phase9detection6resultAeA0bcD7PreviewC_AA0bcD5PhaseO7WrappedCSgAA0bcD9DetectionCSgAA0bcD6ResultCSgtcfc"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running\/init(preview:phase:detection:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"title":"DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"title":"DocumentAutoCaptureDetection","url":"\/documentation\/dotdocument\/documentautocapturedetection","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/init(preview:phase:detection:result:)":{"type":"topic","title":"init(preview:phase:detection:result:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCapturePreview","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"},{"kind":"text","text":", "},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/init(preview:phase:detection:result:)","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"title":"DocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureResult"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Running state."}],"title":"DocumentAutoCaptureUiState.Running"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/Wrapped":{"url":"\/documentation\/dotdocument\/documentautocapturephase\/wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped","role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"DocumentAutoCapturePhase.Wrapped"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate","type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"title":"DocumentAutoCaptureUiState","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"identifier"}],"title":"DocumentAutoCapturePhase","url":"\/documentation\/dotdocument\/documentautocapturephase","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"navigatorTitle":[{"text":"DocumentAutoCapturePhase","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","value":"DOTDDocumentAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","value":"DOTDDocumentAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","value":"DOTDDocumentAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","value":"DOTDDocumentAutoCapturePhase","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"op":"replace"}]}]}