{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/bytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/bytes"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage\/bytes","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"_RawImage.bytes"},{"type":"text","text":"."}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"title":"bytes","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.1"}],"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","title":"BgraRawImage","role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage/bytes":{"navigatorTitle":[{"text":"bytes","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/bgrarawimage\/bytes","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage\/bytes","title":"bytes","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"type":"topic","role":"symbol","title":"FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bytes","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"bytes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" * ","kind":"text"},{"text":"bytes","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage~1bytes\/title","value":"bytes"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"},{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace"}]}]}