{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/TransitionType-swift.enum","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO","text":"TransitionType"},{"kind":"text","text":" = Defaults.transitionType, "},{"kind":"externalParam","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment","text":"Segment"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"minValidSegmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.minValidSegmentCount, "},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = Defaults.minFaceSizeRatio, "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = Defaults.maxFaceSizeRatio, "},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"objectImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" = Defaults.objectImageSize, "},{"kind":"externalParam","text":"proximityTolerance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = Defaults.proximityTolerance) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/init(transitiontype:segments:minvalidsegmentcount:minfacesizeratio:maxfacesizeratio:objectimage:objectimagesize:proximitytolerance:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/init(transitiontype:segments:minvalidsegmentcount:minfacesizeratio:maxfacesizeratio:objectimage:objectimagesize:proximitytolerance:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransitionType","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidSegmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"objectImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proximityTolerance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(im)initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"role":"symbol","title":"DOTFEyeGazeLivenessTransitionType","fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessTransitionType"}],"abstract":[{"type":"text","text":"Eye gaze liveness available transition types."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment":{"role":"symbol","title":"Segment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Segment"}],"abstract":[{"type":"text","text":"Eye gaze liveness segment representing the position on the screen which should be watched by the user for the specified duration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Segment"}],"url":"\/documentation\/dotfacecore\/segment"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration/init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)":{"role":"symbol","title":"init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransitionType","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidSegmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"objectImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proximityTolerance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/init(transitiontype:segments:minvalidsegmentcount:minfacesizeratio:maxfacesizeratio:objectimage:objectimagesize:proximitytolerance:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration":{"role":"symbol","title":"EyeGazeLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration/TransitionType-swift.enum":{"role":"symbol","title":"EyeGazeLivenessConfiguration.TransitionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionType"}],"abstract":[{"type":"text","text":"Eye gaze liveness available transition types."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/TransitionType-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionType"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/transitiontype-swift.enum"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTransitionType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType","text":"DOTFEyeGazeLivenessTransitionType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"transitionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"segments:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DOTFSegment *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"segments"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSegmentCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minValidSegmentCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minFaceSizeRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFaceSizeRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"objectImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectImageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"objectImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"proximityTolerance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"proximityTolerance"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/title","value":"DOTFSegment"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/fragments","value":[{"kind":"identifier","text":"DOTFSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration~1init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)\/title","value":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration~1init(transitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTransitionType:segments:minValidSegmentCount:minFaceSizeRatio:maxFaceSizeRatio:objectImage:objectImageSize:proximityTolerance:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/title","value":"DOTFEyeGazeLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}