{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","text":"EncodedIdentificationFeaturesFace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/encodedidentificationfeaturesface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocument\/encodedidentificationfeaturesface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/encodedIdentificationFeaturesFace","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}],"role":"symbol","title":"encodedIdentificationFeaturesFace","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)encodedIdentificationFeaturesFace","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/encodedIdentificationFeaturesFace":{"role":"symbol","title":"encodedIdentificationFeaturesFace","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"}],"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/encodedIdentificationFeaturesFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}],"url":"\/documentation\/dotnfc\/traveldocument\/encodedidentificationfeaturesface"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"role":"symbol","title":"EncodedIdentificationFeaturesFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encodedIdentificationFeaturesFace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","text":"DOTNEncodedIdentificationFeaturesFace"},{"kind":"text","text":" * "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1encodedIdentificationFeaturesFace\/title","value":"encodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1encodedIdentificationFeaturesFace\/fragments","value":[{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}