{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":" ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewController:processed:","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","role":"symbol","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","kind":"typeIdentifier","text":"FaceAutoCaptureDetection"},{"kind":"text","text":")"}],"title":"faceAutoCaptureViewController(_:processed:)","navigatorTitle":[{"text":"faceAutoCaptureViewController:processed:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:processed:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:processed:)":{"navigatorTitle":[{"text":"faceAutoCaptureViewController:processed:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:processed:)","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:processed:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","kind":"typeIdentifier","text":"FaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"title":"faceAutoCaptureViewController(_:processed:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"kind":"symbol","title":"FaceAutoCaptureViewController","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureDetection":{"kind":"symbol","title":"FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"kind":"symbol","title":"FaceAutoCaptureViewControllerDelegate","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"faceAutoCaptureViewController:processed:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewController:processed:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"faceAutoCaptureViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":" ","kind":"text"},{"text":"processed:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","text":"DOTFFaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"faceAutoCaptureViewController:processed:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:processed:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewController:processed:"}],"op":"replace"},{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments"}]}]}