{"abstract":[{"text":"Create new ","type":"text"},{"code":"BaseFaceAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":" = .init()) -> "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController"}]}],"kind":"declarations"},{"parameters":[{"name":"baseConfiguration","content":[{"inlineContent":[{"type":"text","text":"Configure the capture process."}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController","kind":"typeIdentifier"}],"title":"create(baseConfiguration:)","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController(cm)createWithBaseConfiguration:","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"createWithBaseConfiguration:","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/create(baseConfiguration:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","title":"DOTFBaseFaceAutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","role":"symbol","kind":"symbol","fragments":[{"text":"DOTFBaseFaceAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","title":"BaseFaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","title":"BaseFaceAutoCaptureViewController"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/create(baseConfiguration:)":{"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)","title":"create(baseConfiguration:)","navigatorTitle":[{"kind":"identifier","text":"createWithBaseConfiguration:"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"BaseFaceAutoCaptureViewController"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/create(baseConfiguration:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWithBaseConfiguration:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTFBaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"createWithBaseConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"baseConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Configure the capture process.","type":"text"}]}],"name":"baseConfiguration"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFBaseFaceAutoCaptureViewController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"createWithBaseConfiguration:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1create(baseConfiguration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1create(baseConfiguration:)\/fragments"}]}]}