{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate\/noface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate\/noface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/noFace","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFace"}],"title":"EyeGazeLivenessState.noFace","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState@DOTFEyeGazeLivenessStateNoFace","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState":{"role":"symbol","title":"EyeGazeLivenessState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessState"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/noFace":{"role":"symbol","title":"EyeGazeLivenessState.noFace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFace"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/noFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/noface"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTFEyeGazeLivenessStateNoFace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/title","value":"DOTFEyeGazeLivenessState"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1noFace\/title","value":"DOTFEyeGazeLivenessStateNoFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1noFace\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}