{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose"]]},"abstract":[{"type":"text","text":"Head pose pitch."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headpose\/pitch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headpose\/pitch"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"pitch"}],"title":"pitch","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose(py)pitch","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/pitch"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/pitch":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/pitch","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"pitch","kind":"symbol","navigatorTitle":[{"text":"pitch","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Head pose pitch."}],"url":"\/documentation\/dotfacecore\/headpose\/pitch","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"type":"topic","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"title":"HeadPoseAttribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose":{"url":"\/documentation\/dotfacecore\/headpose","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","title":"HeadPose","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pitch","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"pitch","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"DOTFHeadPoseAttribute","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pitch"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1pitch\/title","value":"pitch","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1pitch\/fragments","value":[{"kind":"identifier","text":"pitch"}]},{"value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"value":"DOTFHeadPose","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}