{"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/documentNumber","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcKey(py)documentNumber","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"title":"documentNumber","role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/documentnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfckey\/documentnumber"]}],"abstract":[{"text":"Document number in MRZ format.","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/NfcKey":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","kind":"symbol","abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"role":"symbol","deprecated":true,"navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey"},"doc://DotNfc/documentation/DotNfc/NfcKey/documentNumber":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"Document number in MRZ format.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/documentNumber","title":"documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/dotnfc\/nfckey\/documentnumber"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"type":"topic","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentNumber","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"documentNumber","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTNNfcKey","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title"},{"value":[{"text":"DOTNNfcKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"value":"documentNumber","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1documentNumber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1documentNumber\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}