{"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytes","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTBgrRawImage(py)bytes","title":"bytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"bytes","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage"]]},"abstract":[{"type":"text","text":"Raw image data."}],"variants":[{"paths":["\/documentation\/dotnfc\/bgrrawimage\/bytes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrrawimage\/bytes"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage/bytes":{"kind":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage\/bytes","title":"bytes","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"navigatorTitle":[{"text":"bytes","kind":"identifier"}],"abstract":[{"text":"Raw image data.","type":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage":{"type":"topic","title":"BgrRawImage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"url":"\/documentation\/dotnfc\/bgrrawimage","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bytes"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" * ","kind":"text"},{"text":"bytes","kind":"identifier"}]}]}},{"value":"bytes","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytes\/title","op":"replace"},{"value":[{"text":"bytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytes\/fragments"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}