{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage\/init(bytesPointer:size:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage"]]},"variants":[{"paths":["\/documentation\/dotnfc\/bgrrawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/bgrrawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","title":"init(bytesPointer:size:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(im)initWithBytesPointer:size:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgrRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/BgrRawImage/init(bytesPointer:size:)":{"role":"symbol","type":"topic","title":"init(bytesPointer:size:)","url":"\/documentation\/dotnfc\/bgrrawimage\/init(bytespointer:size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgrRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage\/init(bytesPointer:size:)"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"type":"topic","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"title":"ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/BgrRawImage":{"kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"title":"BgrRawImage","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","url":"\/documentation\/dotnfc\/bgrrawimage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithBytesPointer:size:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:"},{"kind":"text","text":"("},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"text":"size:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage~1init(bytesPointer:size:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/fragments"}]}]}