{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalPersonalDetails"},"abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalPersonalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"additionalPersonalDetails"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)additionalPersonalDetails","symbolKind":"property","title":"additionalPersonalDetails"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/additionalpersonaldetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/additionalpersonaldetails"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","text":"AdditionalPersonalDetails"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"title":"AdditionalPersonalDetails","navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/additionalPersonalDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalPersonalDetails","navigatorTitle":[{"text":"additionalPersonalDetails","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"title":"additionalPersonalDetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalPersonalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","text":"AdditionalPersonalDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/traveldocument\/additionalpersonaldetails"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"additionalPersonalDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionalPersonalDetails"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","text":"DOTNAdditionalPersonalDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionalPersonalDetails"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle","op":"replace"},{"value":"additionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalPersonalDetails\/title"},{"value":[{"text":"additionalPersonalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalPersonalDetails\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}