{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ldsMasterFile","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ldsMasterFile"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"LdsMasterFile"}],"title":"ldsMasterFile","navigatorTitle":[{"kind":"identifier","text":"ldsMasterFile"}],"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)ldsMasterFile"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsMasterFile"},"abstract":[{"type":"text","text":"Logical data structure master file. Contains raw data read from the document."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/ldsmasterfile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocument\/ldsmasterfile"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/TravelDocument/ldsMasterFile":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ldsMasterFile","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"LdsMasterFile","kind":"typeIdentifier"}],"title":"ldsMasterFile","navigatorTitle":[{"text":"ldsMasterFile","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsMasterFile","type":"topic","url":"\/documentation\/dotnfc\/traveldocument\/ldsmasterfile","abstract":[{"text":"Logical data structure master file. Contains raw data read from the document.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LdsMasterFile","kind":"identifier"}],"navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}],"title":"LdsMasterFile","url":"\/documentation\/dotnfc\/ldsmasterfile","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ldsMasterFile","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ldsMasterFile"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","text":"DOTNLdsMasterFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ldsMasterFile"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsMasterFile\/title","value":"ldsMasterFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsMasterFile\/fragments","value":[{"text":"ldsMasterFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/navigatorTitle","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}