{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodenotpresentvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/barcodenotpresentvalidator"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDBarcodeNotPresentValidator) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator"},"metadata":{"title":"BarcodeNotPresentValidator","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeNotPresentValidator","navigatorTitle":[{"text":"BarcodeNotPresentValidator","kind":"identifier"}],"role":"symbol"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/identifier"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"Validate if barcode is present."}],"references":{"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator/validate(documentAutoCaptureFrameParameters:)":{"title":"validate(documentAutoCaptureFrameParameters:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotdocument\/barcodenotpresentvalidator\/validate(documentautocaptureframeparameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"abstract":[{"type":"text","text":"Validate presence of barcode on the detected document."}]},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator/identifier":{"title":"identifier","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotdocument\/barcodenotpresentvalidator\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator/dependencyIdentifiers":{"role":"symbol","url":"\/documentation\/dotdocument\/barcodenotpresentvalidator\/dependencyidentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/dependencyIdentifiers","kind":"symbol","type":"topic"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator":{"type":"topic","title":"BarcodeNotPresentValidator","kind":"symbol","url":"\/documentation\/dotdocument\/barcodenotpresentvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeNotPresentValidator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"BarcodeNotPresentValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate if barcode is present."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator":{"title":"DocumentAutoCaptureFrameParametersValidator","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}],"abstract":[{"text":"Use this protocol to create document validators.","type":"text"}]},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeNotPresentValidator/init":{"title":"init","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeNotPresentValidator\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotdocument\/dotdbarcodenotpresentvalidator\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDBarcodeNotPresentValidator","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/identifier"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeNotPresentValidator\/init"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1identifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1identifier\/fragments"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1dependencyIdentifiers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1dependencyIdentifiers\/fragments"},{"op":"replace","value":"DOTDBarcodeNotPresentValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/navigatorTitle"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/navigatorTitle"}]}]}