{"sections":[],"metadata":{"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"roleHeading":"Class","title":"Barcode","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcode","modules":[{"name":"DotDocument"}],"role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"],"title":"Classes","generated":true,"anchor":"Classes"},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/init(bytes:detectionPosition:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/bytes","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/position"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"abstract":[{"text":"Result of barcode detection process.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/barcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDBarcode) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/Barcode/isEqual(_:)":{"type":"topic","url":"\/documentation\/dotdocument\/barcode\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/isEqual(_:)"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Barcode/hash":{"url":"\/documentation\/dotdocument\/barcode\/hash","type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/hash"},"doc://DotDocument/documentation/DotDocument/Barcode/position":{"url":"\/documentation\/dotdocument\/barcode\/position","type":"topic","navigatorTitle":[{"text":"position","kind":"identifier"}],"abstract":[{"text":"Position of the barcode in image.","type":"text"}],"title":"position","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"Barcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/position"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Barcode/description":{"type":"topic","url":"\/documentation\/dotdocument\/barcode\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/description"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Barcode/bytes":{"url":"\/documentation\/dotdocument\/barcode\/bytes","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/bytes","navigatorTitle":[{"kind":"identifier","text":"bytes"}],"abstract":[{"type":"text","text":"Barcode bytes."}],"title":"bytes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","title":"Barcode.DetectionPosition","url":"\/documentation\/dotdocument\/barcode\/detectionposition"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/Barcode/init(bytes:detectionPosition:)":{"url":"\/documentation\/dotdocument\/barcode\/init(bytes:detectionposition:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/init(bytes:detectionPosition:)","navigatorTitle":[{"text":"initWithBytes:detectionPosition:","kind":"identifier"}],"abstract":[],"title":"init(bytes:detectionPosition:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode"},{"kind":"text","text":"."},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/Barcode":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Result of barcode detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","title":"Barcode","url":"\/documentation\/dotdocument\/barcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDBarcode","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTDBarcode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTDBarcode"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/bytes","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/position"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/init(bytes:detectionPosition:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDBarcode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1isEqual(_:)\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1hash\/fragments"},{"value":"position","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1position\/title"},{"value":[{"text":"position","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1position\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1description\/fragments"},{"value":"bytes","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1bytes\/title"},{"value":[{"text":"bytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1bytes\/fragments"},{"value":"initWithBytes:detectionPosition:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1init(bytes:detectionPosition:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:detectionPosition:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1init(bytes:detectionPosition:)\/fragments"},{"value":"DOTDBarcode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title"},{"value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments"},{"value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}