{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"roleHeading":"Class","title":"BaseDocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","modules":[{"name":"DotDocument"}],"role":"symbol"},"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/baseConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/delegate"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/requestCapture()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/start()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/stop()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillTransition(to:with:)"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/create(baseConfiguration:)"],"generated":true}],"abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDBaseDocumentAutoCaptureViewController) ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"If you want to use "},{"type":"codeVoice","code":"BarcodeValidation.requirePresenceAndValidity"},{"type":"text","text":", you will need the "},{"type":"codeVoice","code":"DotDocumentBarcode"},{"type":"text","text":" module to be active."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)UIViewController"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSCoding","doc:\/\/DotDocument\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/s8SendableP","doc:\/\/DotDocument\/s16SendableMetatypeP","doc:\/\/DotDocument\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotDocument\/objc(pl)UIAppearanceContainer","doc:\/\/DotDocument\/objc(pl)UIContentContainer","doc:\/\/DotDocument\/objc(pl)UIFocusEnvironment","doc:\/\/DotDocument\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotDocument\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotDocument\/objc(pl)UIStateRestoring","doc:\/\/DotDocument\/5UIKit23UITraitChangeObservableP","doc:\/\/DotDocument\/objc(pl)UITraitEnvironment","doc:\/\/DotDocument\/objc(pl)UIUserActivityRestoring"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"},"references":{"doc://DotDocument/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://DotDocument/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://DotDocument/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidAppear(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidAppear(_:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidappear(_:)","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"abstract":[],"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/start()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/start()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/start()","navigatorTitle":[{"text":"start","kind":"identifier"}],"abstract":[{"type":"text","text":"Start the document auto capture process."}],"title":"start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://DotDocument/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"type":"topic","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"BaseDocumentAutoCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"},"doc://DotDocument/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidDisappear(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidDisappear(_:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdiddisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"abstract":[],"title":"viewDidDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/delegate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/delegate","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Set this delegate to handle the document auto capture events."}],"title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate","text":"DocumentAutoCaptureViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewWillDisappear(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewwilldisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"abstract":[],"title":"viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)UIViewController","title":"UIViewController"},"doc://DotDocument/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"type":"topic","role":"symbol","kind":"symbol","title":"BaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}]},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotDocument/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidLayoutSubviews()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLayoutSubviews()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidlayoutsubviews()","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"abstract":[],"title":"viewDidLayoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s8SendableP","title":"Swift.Sendable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/stop()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/stop()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"abstract":[{"type":"text","text":"Stop the face auto capture process."}],"title":"stop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/requestCapture()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/requestCapture()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/requestcapture()","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}],"abstract":[{"type":"text","text":"Request capture of the next detection."}],"title":"requestCapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewWillTransition(to:with:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillTransition(to:with:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewwilltransition(to:with:)","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"abstract":[],"title":"viewWillTransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI Document Auto Capture component"}],"title":"DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://DotDocument/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewWillAppear(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillAppear(_:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewwillappear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"abstract":[],"title":"viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/create(baseConfiguration:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/create(baseConfiguration:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/create(baseconfiguration:)","navigatorTitle":[{"text":"createWithBaseConfiguration:","kind":"identifier"}],"abstract":[{"type":"text","text":"Create new "},{"code":"BaseDocumentAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"title":"create(baseConfiguration:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidLoad()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLoad()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"abstract":[],"title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/baseConfiguration":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/baseconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/baseConfiguration","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Current configuration."}],"title":"baseConfiguration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDBaseDocumentAutoCaptureViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/baseConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/delegate"],"generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/requestCapture()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/start()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/stop()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/create(baseConfiguration:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"],"title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidAppear(_:)\/fragments"},{"op":"replace","value":"start","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1start()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1start()\/fragments"},{"op":"replace","value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidDisappear(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidDisappear(_:)\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillDisappear(_:)\/fragments"},{"op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"viewDidLayoutSubviews","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLayoutSubviews()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments"},{"op":"replace","value":"stop","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1stop()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1stop()\/fragments"},{"op":"replace","value":"requestCapture","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1requestCapture()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1requestCapture()\/fragments"},{"op":"replace","value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillTransition(to:with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"viewWillAppear:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewWillAppear(_:)\/fragments"},{"op":"replace","value":"createWithBaseConfiguration:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1create(baseConfiguration:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithBaseConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1create(baseConfiguration:)\/fragments"},{"op":"replace","value":"viewDidLoad","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLoad()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLoad()\/fragments"},{"op":"replace","value":"baseConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1baseConfiguration\/title"},{"op":"replace","value":[{"text":"baseConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1baseConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}