{"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTBezierPathFactory","roleHeading":"Class","title":"BezierPathFactory","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTBezierPathFactory) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bezierpathfactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bezierpathfactory"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"],"title":"Type Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory":{"role":"symbol","navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"url":"\/documentation\/dotdocument\/bezierpathfactory","type":"topic","title":"BezierPathFactory","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"title":"createPlaceholderPath(rect:cornerRadius:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"url":"\/documentation\/dotdocument\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","kind":"symbol","title":"createDetectionPath(corners:cornerRadius:)","url":"\/documentation\/dotdocument\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTBezierPathFactory","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTBezierPathFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTBezierPathFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTBezierPathFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/fragments","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]},{"value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}