{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"],["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector"],["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/init(bytesPointer:size:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytes","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointerPacked","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/size"],"title":"Instance Properties"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"],"generated":true,"title":"Converting images"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgraRawImage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrarawimage"]},{"paths":["\/documentation\/dotdocument\/bgrarawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimagefactory","role":"symbol","title":"BgraRawImageFactory"},"doc://com.innovatrics.dot.document/@M@DotDocument@objc(pl)_RawImage":{"type":"unresolvable","title":"_RawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/@M@DotDocument@objc(pl)_RawImage"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","url":"\/documentation\/dotdocument\/cgimagefactory","role":"symbol","title":"CGImageFactory"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/bytes":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Raw image data."}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/bgrarawimage\/bytes","title":"bytes","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytes"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/bytesPointer":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytesPointer","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointer","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage\/bytespointer","role":"symbol","title":"bytesPointer"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"url":"\/documentation\/dotdocument\/documentdetector","type":"topic","title":"DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","role":"symbol"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/init(bytesPointer:size:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgraRawImageFactory"},{"text":" to create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/init(bytesPointer:size:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage\/init(bytespointer:size:)","role":"symbol","title":"init(bytesPointer:size:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/size":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/size","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage\/size","role":"symbol","title":"size"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/bytesPointerPacked":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointerPacked"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointerPacked","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytesPointerPacked"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage\/bytespointerpacked","role":"symbol","title":"bytesPointerPacked"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","type":"topic","title":"CIImageFactory","url":"\/documentation\/dotdocument\/ciimagefactory","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgraRawImage"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytes","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/bytesPointerPacked","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/size"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/init(bytesPointer:size:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/@M@DotDocument@objc(pl)_RawImage"],"title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"Converting images","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgraRawImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/fragments"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/title"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}]},{"op":"replace","value":"bytesPointer","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytesPointer\/title"},{"value":[{"text":"bytesPointer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytesPointer\/fragments","op":"replace"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"value":"initWithBytesPointer:size:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1init(bytesPointer:size:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1init(bytesPointer:size:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1size\/title","op":"replace","value":"size"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1size\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytesPointerPacked\/title","value":"bytesPointerPacked"},{"value":[{"text":"bytesPointerPacked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1bytesPointerPacked\/fragments","op":"replace"},{"op":"replace","value":"DOTCIImageFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments","op":"replace"}]}]}