{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"title":"BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTBgraRawImageFactory","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory"},"sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(ciImage:ciContext:)"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"],"title":"Converting images","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBgraRawImageFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrarawimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrarawimagefactory"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"references":{"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","type":"topic","title":"CIImageFactory","url":"\/documentation\/dotdocument\/ciimagefactory","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimagefactory","role":"symbol","title":"BgraRawImageFactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory/create(ciImage:ciContext:)":{"url":"\/documentation\/dotdocument\/bgrarawimagefactory\/create(ciimage:cicontext:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(ciImage:ciContext:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","url":"\/documentation\/dotdocument\/cgimagefactory","role":"symbol","title":"CGImageFactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory/create(cgImage:)":{"type":"topic","title":"create(cgImage:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(cgImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotdocument\/bgrarawimagefactory\/create(cgimage:)","role":"symbol","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}]},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgraRawImageFactory"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]}]},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"],"title":"Converting images","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTBgraRawImageFactory","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments"},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory~1create(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}