{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Validate minimum brightness of the detected document.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"variants":[{"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init(threshold:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/threshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/defaultThreshold"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDBrightnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"To use this validator also following validators must be applied: "},{"type":"codeVoice","code":"DocumentOutOfBoundsValidator"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator"},"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"class"},"references":{"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/identifier":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/identifier","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"identifier","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/dependencyIdentifiers":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/dependencyidentifiers","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/dependencyIdentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"title":"dependencyIdentifiers"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/init()":{"title":"init()","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Initialize with default threshold."}],"kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/threshold":{"abstract":[{"type":"text","text":"Current minimal accepted brightness."}],"role":"symbol","type":"topic","title":"threshold","navigatorTitle":[{"kind":"identifier","text":"threshold"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/threshold","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/threshold"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/init(threshold:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init(threshold:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(threshold:)","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"type":"topic","abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol","title":"DocumentAutoCaptureDetectionValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/defaultThreshold":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/defaultThreshold","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"defaultThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/defaultthreshold","abstract":[{"type":"text","text":"Default threshold is 0.25."}],"type":"topic"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/validate(documentAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"validate(documentAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/validate(documentautocaptureframeparameters:)","abstract":[{"type":"text","text":"Validate brightness of the detected document."}],"type":"topic"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"role":"symbol","title":"BrightnessTooLowValidator","type":"topic","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"DOTDBrightnessTooLowValidator","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}]},{"op":"replace","value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/threshold"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init(threshold:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/defaultThreshold"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1identifier\/title","value":"identifier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init()\/title","op":"replace","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1threshold\/title","op":"replace","value":"threshold"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1threshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"threshold"}]},{"value":"initWithThreshold:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init(threshold:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init(threshold:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","op":"replace","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1defaultThreshold\/title","op":"replace","value":"defaultThreshold"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1defaultThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","op":"replace"},{"value":"DOTDBrightnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments"}]}]}