{"seeAlsoSections":[{"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeSmallValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessHighValidator"}],"title":"BrightnessHighValidator","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTBrightnessHighValidator","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessHighValidator"}]},"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init(threshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/validate(documentAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/defaultThreshold"]}],"variants":[{"paths":["\/documentation\/dotdocument\/brightnesshighvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/brightnesshighvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTBrightnessHighValidator) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessHighValidator"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/defaultThreshold":{"role":"symbol","title":"defaultThreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/defaultThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/defaultthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/SizeSmallValidator":{"role":"symbol","title":"SizeSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeSmallValidator"}],"abstract":[{"type":"text","text":"Validate size of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeSmallValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SizeSmallValidator"}],"url":"\/documentation\/dotdocument\/sizesmallvalidator"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/init(threshold:)":{"role":"symbol","title":"init(threshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init(threshold:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/init(threshold:)"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/init()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/validate(documentAutoCaptureFrameParameters:)":{"role":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate brightness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/validate(documentAutoCaptureFrameParameters:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/validate(documentautocaptureframeparameters:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"role":"symbol","title":"DocumentDoesNotFitPlaceholderValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/threshold":{"role":"symbol","title":"threshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Current maximal accepted brightness."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/threshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threshold"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/threshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"role":"symbol","title":"DocumentAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessLowValidator":{"role":"symbol","title":"BrightnessLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessLowValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessLowValidator"}],"url":"\/documentation\/dotdocument\/brightnesslowvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator":{"role":"symbol","title":"BrightnessHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessHighValidator"}],"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessHighValidator"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotValidValidator":{"role":"symbol","title":"MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotValidValidator"}],"abstract":[{"type":"text","text":"Validate detected Machine Readable Zone."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreHighValidator":{"role":"symbol","title":"HotspotsScoreHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HotspotsScoreHighValidator"}],"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreHighValidator"}],"url":"\/documentation\/dotdocument\/hotspotsscorehighvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessHighValidator/identifier":{"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/identifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesshighvalidator\/identifier"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator":{"role":"symbol","title":"DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/SharpnessLowValidator":{"role":"symbol","title":"SharpnessLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessLowValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharpnessLowValidator"}],"url":"\/documentation\/dotdocument\/sharpnesslowvalidator"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentOutOfBoundsValidator":{"role":"symbol","title":"DocumentOutOfBoundsValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTBrightnessHighValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBrightnessHighValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTBrightnessHighValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/init(threshold:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/validate(documentAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessHighValidator\/defaultThreshold"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeSmallValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBrightnessHighValidator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1defaultThreshold\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeSmallValidator\/title","value":"DOTSizeSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTSizeSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1init(threshold:)\/title","value":"initWithThreshold:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1init(threshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDocumentDoesNotFitPlaceholderValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentDoesNotFitPlaceholderValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1threshold\/title","value":"threshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDocumentAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureDetectionValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessLowValidator\/title","value":"DOTBrightnessLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTBrightnessLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator\/title","value":"DOTBrightnessHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTBrightnessHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTMrzNotValidValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","value":[{"kind":"identifier","text":"DOTMrzNotValidValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator\/title","value":"DOTHotspotsScoreHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTHotspotsScoreHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessHighValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDocumentNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentNotDetectedValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessLowValidator\/title","value":"DOTSharpnessLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTSharpnessLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","value":"DOTDocumentOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentOutOfBoundsValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}