{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDCameraPreset) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"title":"CameraPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotDocument@E@DOTDCameraPreset","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/fullHD","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/hd","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/high","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/photo"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/camerapreset\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/camerapreset\/description"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/camerapreset\/init(rawvalue:)"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.document\/SY"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/high":{"role":"symbol","title":"CameraPreset.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"Outputs Full HD (1920x1080) video frames on high-end devices and HD (1280x720) on low-end devices."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetHigh"}],"url":"\/documentation\/dotdocument\/camerapreset\/high"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/photo":{"role":"symbol","title":"CameraPreset.photo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"abstract":[{"type":"text","text":"Outputs low resolution video frames and enables high resolution photo capture. Exact resolution differs between devices."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/photo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}],"url":"\/documentation\/dotdocument\/camerapreset\/photo"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/fullHD":{"role":"symbol","title":"CameraPreset.fullHD","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHD"}],"abstract":[{"type":"text","text":"Outputs Full HD (1920x1080) video frames and enables Full HD (1920x1080) photo capture."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/fullHD","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}],"url":"\/documentation\/dotdocument\/camerapreset\/fullhd"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/hd":{"role":"symbol","title":"CameraPreset.hd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hd"}],"abstract":[{"type":"text","text":"Outputs HD (1280x720) video frames and enables HD (1280x720) photo capture."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/hd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetHd"}],"url":"\/documentation\/dotdocument\/camerapreset\/hd"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset":{"role":"symbol","title":"CameraPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}],"url":"\/documentation\/dotdocument\/camerapreset"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/camerapreset\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/fullHD","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/hd","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/high","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/photo"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDCameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1high\/title","value":"DOTDCameraPresetHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1high\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1photo\/title","value":"DOTDCameraPresetPhoto"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1photo\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetPhoto"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1fullHD\/title","value":"DOTDCameraPresetFullHD"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1fullHD\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1hd\/title","value":"DOTDCameraPresetHd"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1hd\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetHd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}