{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fill","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fit"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/native"]},{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType"},"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"title":"CameraPreviewScaleType","externalID":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCameraPreviewScaleType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/camerapreviewscaletype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/camerapreviewscaletype"]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"type":"conformsTo"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/fill":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/fill","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"type":"text","text":" "},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fill","title":"CameraPreviewScaleType.fill","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/init(rawValue:)":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/init(rawValue:)","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/fit":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/fit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"type":"text","text":" "},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fit","title":"CameraPreviewScaleType.fit","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/RawRepresentable-Implementations":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/RawRepresentable-Implementations","kind":"article"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.document\/SY","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","type":"topic","url":"\/documentation\/dotdocument\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/native":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"native"},{"text":": ","kind":"text"},{"text":"AVLayerVideoGravity","preciseIdentifier":"c:@T@AVLayerVideoGravity","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/native","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/native","title":"native","kind":"symbol","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/description":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/description","title":"description","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/description","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/equatable-implementations","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraPreviewScaleType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fill","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fit"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fill\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fill\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"op":"replace"},{"value":"DOTCameraPreviewScaleTypeFit","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fit\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fit\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"}]}]}