{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCameraFacing) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/camerafacing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/camerafacing"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/back","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/front"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/init(rawValue:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/native"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"enum","title":"CameraFacing","modules":[{"name":"DotDocument"}],"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing"},"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"references":{"doc://DotDocument/documentation/DotDocument/CameraFacing/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/camerafacing\/description","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/description","abstract":[],"title":"description"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SY"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"url":"\/documentation\/dotdocument\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","title":"CameraFacing"},"doc://DotDocument/documentation/DotDocument/CameraFacing/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/dotdocument\/camerafacing\/equatable-implementations","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations"},"doc://DotDocument/documentation/DotDocument/CameraFacing/back":{"abstract":[{"type":"text","text":"Back facing camera."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/back","title":"CameraFacing.back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerafacing\/back","navigatorTitle":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraFacing/native":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","text":"Position","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/camerafacing\/native","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/native","abstract":[],"title":"native"},"doc://DotDocument/documentation/DotDocument/CameraFacing/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/camerafacing\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/init(rawValue:)","kind":"symbol"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/CameraFacing/front":{"title":"CameraFacing.front","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/front","navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"abstract":[{"text":"Front facing camera.","type":"text"}],"url":"\/documentation\/dotdocument\/camerafacing\/front","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"front","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/CameraFacing/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/dotdocument\/camerafacing\/rawrepresentable-implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/RawRepresentable-Implementations","kind":"article"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/back","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/front"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/navigatorTitle","op":"replace"},{"value":"DOTCameraFacingBack","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1back\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1back\/fragments","op":"replace"},{"value":"DOTCameraFacingFront","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1front\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1front\/fragments","op":"replace"}]}]}