{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreviewview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreviewview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSCoding","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/objc(pl)CALayerDelegate","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/s8SendableP","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAppearance","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAppearanceContainer","doc:\/\/com.innovatrics.dot.document\/objc(pl)UICoordinateSpace","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIDynamicItem","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusEnvironment","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusItem","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusItemContainer","doc:\/\/com.innovatrics.dot.document\/objc(pl)UILargeContentViewerItem","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.innovatrics.dot.document\/objc(pl)UITraitEnvironment","doc:\/\/com.innovatrics.dot.document\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/videoPreviewLayer"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/layerClass"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewView"}],"title":"CameraPreviewView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)CameraPreviewView","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewView"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"references":{"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusItemContainer"},"doc://com.innovatrics.dot.document/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UILargeContentViewerItem"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/dotdocument\/camerapreviewview\/initwithframe:"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewView/videoPreviewLayer":{"role":"symbol","title":"videoPreviewLayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPreviewLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"}],"abstract":[{"type":"text","text":"Convenience wrapper to get layer as its statically known type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/videoPreviewLayer","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/camerapreviewview\/videopreviewlayer"},"doc://com.innovatrics.dot.document/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSCoding"},"doc://com.innovatrics.dot.document/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIResponderStandardEditActions"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/dotdocument\/camerapreviewview\/initwithcoder:"},"doc://com.innovatrics.dot.document/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.innovatrics.dot.document/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.innovatrics.dot.document/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAccessibilityIdentification"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.innovatrics.dot.document\/s8SendableP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewView":{"role":"symbol","title":"CameraPreviewView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewView"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewView"}],"url":"\/documentation\/dotdocument\/camerapreviewview"},"doc://com.innovatrics.dot.document/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIDynamicItem"},"doc://com.innovatrics.dot.document/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusItem"},"doc://com.innovatrics.dot.document/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UICoordinateSpace"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewView/layerClass":{"role":"symbol","title":"layerClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/layerClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerClass"}],"url":"\/documentation\/dotdocument\/camerapreviewview\/layerclass"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAppearanceContainer"},"doc://com.innovatrics.dot.document/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIFocusEnvironment"},"doc://com.innovatrics.dot.document/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)CALayerDelegate"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)UIView"},"doc://com.innovatrics.dot.document/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UITraitEnvironment"},"doc://com.innovatrics.dot.document/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIAppearance"},"doc://com.innovatrics.dot.document/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraPreviewView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraPreviewView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraPreviewView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/initWithCoder:","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/initWithFrame:"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewView\/layerClass"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewView\/title","value":"CameraPreviewView"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewView\/fragments","value":[{"kind":"identifier","text":"CameraPreviewView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewView~1layerClass\/title","value":"layerClass"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewView~1layerClass\/fragments","value":[{"kind":"identifier","text":"layerClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}