{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCIImageFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Converting images","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory"],"generated":true}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgrRawImage:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:ciContext:)"],"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotdocument\/ciimagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/ciimagefactory"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CIImageFactory","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DOTCIImageFactory","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"title":"CIImageFactory"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory":{"type":"topic","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"CGImageFactory","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","url":"\/documentation\/dotdocument\/cgimagefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}]},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory":{"type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"kind":"symbol","title":"BgraRawImageFactory","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","url":"\/documentation\/dotdocument\/bgrarawimagefactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","type":"topic","kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"title":"BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory/create(bgrRawImage:)":{"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotdocument\/ciimagefactory\/create(bgrrawimage:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgrRawImage:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"title":"create(bgrRawImage:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"type":"topic","abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"kind":"symbol","title":"CIImageFactory","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","url":"\/documentation\/dotdocument\/ciimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory/create(bgraRawImage:ciContext:)":{"url":"\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:cicontext:)","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"title":"create(bgraRawImage:ciContext:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:ciContext:)","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}]},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCIImageFactory"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgrRawImage:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:ciContext:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory"],"title":"Converting images","generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTCIImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/fragments","op":"replace","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}]},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"value":"createWithBgraRawImage:ciContext:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:ciContext:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}]}]}]}