{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","roleHeading":"Class","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","symbolKind":"class"},"abstract":[{"text":"Common configuration for all components.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"},"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/init(sessionToken:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/sessionToken"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/isEqual(_:)"],"title":"Instance Methods","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCommonConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/commonconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/commonconfiguration"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/sessionToken":{"type":"topic","title":"sessionToken","abstract":[{"text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotdocument\/commonconfiguration\/sessiontoken","navigatorTitle":[{"kind":"identifier","text":"sessionToken"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/sessionToken","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"url":"\/documentation\/dotdocument\/commonconfiguration","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","kind":"symbol","role":"symbol","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"text":"Common configuration for all components.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}]},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/description":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/description","url":"\/documentation\/dotdocument\/commonconfiguration\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/hash":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/hash","url":"\/documentation\/dotdocument\/commonconfiguration\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","kind":"symbol","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/isEqual(_:)":{"type":"topic","title":"isEqual(_:)","abstract":[],"url":"\/documentation\/dotdocument\/commonconfiguration\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/isEqual(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/init(sessionToken:)":{"type":"topic","title":"init(sessionToken:)","abstract":[],"url":"\/documentation\/dotdocument\/commonconfiguration\/init(sessiontoken:)","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/init(sessionToken:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTCommonConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/sessionToken"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/init(sessionToken:)","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCommonConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"value":"sessionToken","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1sessionToken\/title"},{"value":[{"kind":"identifier","text":"sessionToken"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1sessionToken\/fragments"},{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1description\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1hash\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1isEqual(_:)\/fragments"},{"value":"initWithSessionToken:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1init(sessionToken:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1init(sessionToken:)\/fragments"}]}]}