{"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomRight","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/points","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topRight"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/isEqual(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/mirrored()","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/from(rectangle:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"title":"Corners","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTCorners","modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCorners) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"variants":[{"paths":["\/documentation\/dotdocument\/corners"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/corners"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"sections":[],"references":{"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Corners/bottomRight":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/corners\/bottomright","abstract":[{"type":"text","text":"Bottom right corner point."}],"title":"bottomRight","navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomRight","type":"topic"},"doc://DotDocument/documentation/DotDocument/Corners/points":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"points"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/points","url":"\/documentation\/dotdocument\/corners\/points","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","title":"points","abstract":[]},"doc://DotDocument/documentation/DotDocument/Corners/rebased(parentRectangle:)":{"role":"symbol","title":"rebased(parentRectangle:)","url":"\/documentation\/dotdocument\/corners\/rebased(parentrectangle:)","type":"topic","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/rebased(parentRectangle:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/Corners/isEqual(_:)":{"title":"isEqual(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/corners\/isequal(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/isEqual(_:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Corners/topRight":{"type":"topic","navigatorTitle":[{"text":"topRight","kind":"identifier"}],"abstract":[{"type":"text","text":"Top right corner point."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topRight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"url":"\/documentation\/dotdocument\/corners\/topright","title":"topRight","role":"symbol","kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/Corners/description":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/description","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotdocument\/corners\/description","kind":"symbol","title":"description","type":"topic"},"doc://DotDocument/documentation/DotDocument/Corners/from(rectangle:)":{"abstract":[],"url":"\/documentation\/dotdocument\/corners\/from(rectangle:)","title":"from(rectangle:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/from(rectangle:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","type":"topic","url":"\/documentation\/dotdocument\/corners\/init(topleft:topright:bottomright:bottomleft:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Corners/topLeft":{"type":"topic","title":"topLeft","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"topLeft"}],"url":"\/documentation\/dotdocument\/corners\/topleft","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topLeft","abstract":[{"type":"text","text":"Top left corner point."}],"role":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/Corners/mirrored()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/mirrored()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/corners\/mirrored()","type":"topic","title":"mirrored()","kind":"symbol","role":"symbol"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Corners/hash":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"hash","type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/corners\/hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/hash"},"doc://DotDocument/documentation/DotDocument/Corners/bottomLeft":{"url":"\/documentation\/dotdocument\/corners\/bottomleft","kind":"symbol","type":"topic","abstract":[{"text":"Bottom left corner point.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomLeft","title":"bottomLeft","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}]},"doc://DotDocument/documentation/DotDocument/Corners":{"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"title":"Corners","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"kind":"symbol","url":"\/documentation\/dotdocument\/corners","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTCorners"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomRight","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/points","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topRight"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/isEqual(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/mirrored()","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/from(rectangle:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCorners"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomRight\/title","value":"bottomRight"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomRight\/fragments","value":[{"kind":"identifier","text":"bottomRight"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1points\/title","value":"points"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1points\/fragments","value":[{"text":"points","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1rebased(parentRectangle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topRight\/title","value":"topRight"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topRight\/fragments","value":[{"text":"topRight","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1from(rectangle:)\/title","value":"fromRectangle:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1from(rectangle:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromRectangle:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topLeft\/title","value":"topLeft"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topLeft\/fragments","value":[{"text":"topLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1mirrored()\/title","value":"mirrored"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomLeft\/title","value":"bottomLeft"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomLeft\/fragments","value":[{"text":"bottomLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}