{"seeAlsoSections":[{"generated":true,"title":"Non-UI components","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentDetector) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Document detection input","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"]},{"title":"Document detection output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:limit:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error"]}],"metadata":{"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","roleHeading":"Class","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"title":"DocumentDetector"},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentdetector"]}],"references":{"doc://DotDocument/documentation/DotDocument/ImageParametersAnalyzer":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParametersAnalyzer"}],"navigatorTitle":[{"text":"ImageParametersAnalyzer","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can analyze image parameters."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","kind":"symbol","type":"topic","title":"ImageParametersAnalyzer","url":"\/documentation\/dotdocument\/imageparametersanalyzer"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetector/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetector\/init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/dotdocument\/dotddocumentdetector\/init","type":"topic","kind":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.15.1","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"kind":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/documentdetector\/document","title":"DocumentDetector.Document","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Document"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/detect(bgraRawImage:limit:)":{"title":"detect(bgraRawImage:limit:)","url":"\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:limit:)","type":"topic","abstract":[{"type":"text","text":"Detect documents in an image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:limit:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limit"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"title":"BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error":{"role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error","title":"DocumentDetector.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector\/error"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","url":"\/documentation\/dotdocument\/detectionposition","title":"DetectionPosition","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Position of the document card in the image."}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"role":"symbol","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","title":"DocumentDetector","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","type":"topic","title":"ImagePerspectiveWarper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"],"title":"Document detection input"},{"title":"Document detection output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetector\/init","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:limit:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Non-UI components","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentDetector","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","value":"DOTDImageParametersAnalyzer"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","value":[{"text":"DOTDImageParametersAnalyzer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:limit:)\/title","op":"replace","value":"detectWithBgraRawImage:limit:error:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:limit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","op":"replace","value":"DOTDDetectionPosition"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace","value":"DOTDImagePerspectiveWarper"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]}]}]}