{"seeAlsoSections":[{"title":"Document auto capture process","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDDocumentAutoCaptureDetection) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetection"]}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/bgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/document","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/machineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/travelDocumentType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/validatorIdentifiers"],"title":"Instance Properties"}],"metadata":{"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"DotDocument"}],"title":"DocumentAutoCaptureDetection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","role":"symbol","title":"DocumentAutoCaptureFrameParameters","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","title":"DocumentAutoCaptureController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/travelDocumentType":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/traveldocumenttype","abstract":[{"type":"text","text":"Resolved travel document type."}],"navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"type":"topic","kind":"symbol","title":"travelDocumentType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/travelDocumentType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/machineReadableZone":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/machinereadablezone","abstract":[{"text":"Result of MRZ reading.","type":"text"}],"navigatorTitle":[{"text":"machineReadableZone","kind":"identifier"}],"type":"topic","kind":"symbol","title":"machineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/machineReadableZone","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/description":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","kind":"symbol","title":"description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"kind":"symbol","title":"DocumentAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","url":"\/documentation\/dotdocument\/documentautocapturedetection","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/bgraRawImage":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/bgrarawimage","abstract":[{"type":"text","text":"Detection image."}],"navigatorTitle":[{"text":"bgraRawImage","kind":"identifier"}],"type":"topic","kind":"symbol","title":"bgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/bgraRawImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgraRawImage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}],"role":"symbol"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/validatorIdentifiers":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/validatoridentifiers","abstract":[{"type":"text","text":"Validator identifiers for which the validation has failed."}],"navigatorTitle":[{"text":"validatorIdentifiers","kind":"identifier"}],"type":"topic","kind":"symbol","title":"validatorIdentifiers","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/validatorIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"validatorIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/document":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/document","abstract":[{"type":"text","text":"Detected document, or "},{"type":"codeVoice","code":"nil"},{"text":" if the document was not detected in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"document"}],"type":"topic","kind":"symbol","title":"document","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/document","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/init(bgrarawimage:document:traveldocumenttype:machinereadablezone:validatoridentifiers:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"}],"type":"topic","kind":"symbol","title":"init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"role":"symbol"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureResult":{"abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureresult","title":"DocumentAutoCaptureResult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureResult"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTDDocumentAutoCaptureDetection"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/bgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/document","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/machineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/travelDocumentType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/validatorIdentifiers"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]}]},{"op":"replace","value":[{"title":"Document auto capture process","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"value":"travelDocumentType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1travelDocumentType\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1travelDocumentType\/fragments","value":[{"kind":"identifier","text":"travelDocumentType"}],"op":"replace"},{"op":"replace","value":"machineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1machineReadableZone\/title"},{"value":[{"text":"machineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1machineReadableZone\/fragments","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","op":"replace"},{"value":"bgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1bgraRawImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1bgraRawImage\/fragments","value":[{"text":"bgraRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1validatorIdentifiers\/title","value":"validatorIdentifiers","op":"replace"},{"value":[{"kind":"identifier","text":"validatorIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1validatorIdentifiers\/fragments"},{"op":"replace","value":"document","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1document\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1document\/fragments","value":[{"text":"document","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)\/title","op":"replace","value":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace","value":"DOTDDocumentAutoCaptureResult"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","op":"replace"}]}]}