{"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureFrameParametersValidator","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}],"role":"symbol","title":"DocumentAutoCaptureFrameParametersValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"symbolKind":"protocol"},"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"title":"Validators","generated":true,"anchor":"Validators"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentAutoCaptureFrameParametersValidator) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/identifier"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"references":{"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"title":"SharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"title":"HotspotsScoreTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/mrznotvalidvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"title":"MrzNotValidValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotValidValidator"}]},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","navigatorTitle":[{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}],"abstract":[{"type":"text","text":"Validate if barcode is inside detected document bounds."}],"title":"BarcodeOutsideOfDocumentValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"title":"DocumentOutOfBoundsValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator/validate(documentAutoCaptureFrameParameters:)":{"title":"validate(documentAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate current frame parameters."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/validate(documentAutoCaptureFrameParameters:)","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/validate(documentautocaptureframeparameters:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"type":"topic","required":true},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/dependencyIdentifiers","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/dependencyidentifiers","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"type":"topic","required":true},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"title":"DocumentAutoCaptureFrameParametersValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"title":"BrightnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotPresentValidator"}],"abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","title":"MrzNotPresentValidator","role":"symbol","url":"\/documentation\/dotdocument\/mrznotpresentvalidator","navigatorTitle":[{"kind":"identifier","text":"MrzNotPresentValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"title":"DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"title":"DocumentDoesNotFitPlaceholderValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator/identifier":{"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/identifier","required":true,"role":"symbol","type":"topic","title":"identifier","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/identifier"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"type":"text","text":"Validate size of the detected document."}],"title":"SizeTooSmallValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"title":"BrightnessTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"abstract":[{"type":"text","text":"Validate if barcode is present."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","title":"BarcodeNotPresentValidator","role":"symbol","url":"\/documentation\/dotdocument\/barcodenotpresentvalidator","navigatorTitle":[{"text":"BarcodeNotPresentValidator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParametersValidator","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/identifier"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/validate(documentAutoCaptureFrameParameters:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Conforming Types","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"],"type":"conformingTypes","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Validators","title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator","op":"replace"},{"op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments"},{"op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/navigatorTitle"},{"op":"replace","value":"DOTDHotspotsScoreTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title"},{"op":"replace","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments"},{"op":"replace","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/navigatorTitle"},{"op":"replace","value":"DOTDMrzNotValidValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/title","value":"DOTDBarcodeOutsideOfDocumentValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/navigatorTitle","value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","value":"DOTDDocumentOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/title","value":"DOTDDocumentAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/fragments","value":[{"text":"DOTDDocumentAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}]},{"op":"replace","value":"DOTDBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/title","value":"DOTDMrzNotPresentValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotPresentValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/navigatorTitle","value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/navigatorTitle","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/title","value":"DOTDBarcodeNotPresentValidator"},{"value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}