{"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentAutoCaptureUiState) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureUiState"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Initializing","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"],"title":"Classes"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Initializing","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"],"title":"Inherited By"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureuistate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureuistate"]}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState","title":"DocumentAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"roleHeading":"Class","modules":[{"name":"DotDocument"}],"symbolKind":"class","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning":{"abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning","title":"DOTDDocumentAutoCaptureUiStateRunning","fragments":[{"text":"DOTDDocumentAutoCaptureUiStateRunning","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"title":"DocumentAutoCaptureUiState","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle":{"title":"DOTDDocumentAutoCaptureUiStateIdle","role":"symbol","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle","fragments":[{"text":"DOTDDocumentAutoCaptureUiStateIdle","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Idle":{"title":"DocumentAutoCaptureUiState.Idle","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle","abstract":[{"type":"text","text":"Idle state."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"navigatorTitle":[{"text":"Idle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/idle"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateInitializing":{"abstract":[{"text":"Initializing state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active right after the component is created for a short period of time.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateInitializing","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateinitializing","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateInitializing"}],"title":"DOTDDocumentAutoCaptureUiStateInitializing"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Initializing":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Initializing","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/initializing","abstract":[{"text":"Initializing state.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"title":"DocumentAutoCaptureUiState.Initializing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Initializing","kind":"identifier"}]},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","title":"DocumentAutoCaptureUiState.Running","navigatorTitle":[{"text":"Running","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"abstract":[{"text":"Running state.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiState/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiState\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistate\/init","abstract":[],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDDocumentAutoCaptureUiState","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiState\/init"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateInitializing","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle"}]}]}