{"sections":[],"topicSections":[{"title":"Style and configuration","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]},{"title":"Delegate","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/init(configuration:style:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/delegate","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/style-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/requestCapture()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/start()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillTransition(to:with:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentAutoCaptureViewController) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSCoding","doc:\/\/DotDocument\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/s8SendableP","doc:\/\/DotDocument\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotDocument\/objc(pl)UIAppearanceContainer","doc:\/\/DotDocument\/objc(pl)UIContentContainer","doc:\/\/DotDocument\/objc(pl)UIFocusEnvironment","doc:\/\/DotDocument\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotDocument\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotDocument\/objc(pl)UIStateRestoring","doc:\/\/DotDocument\/5UIKit23UITraitChangeObservableP","doc:\/\/DotDocument\/objc(pl)UITraitEnvironment","doc:\/\/DotDocument\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"symbolKind":"class","title":"DocumentAutoCaptureViewController","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewDidDisappear(_:)":{"abstract":[],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdiddisappear(_:)","title":"viewDidDisappear(_:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidDisappear(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/init(configuration:style:)":{"type":"topic","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"title":"init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"DocumentAutoCaptureViewController"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/init(configuration:style:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/init(configuration:style:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/stopAsync(onStopped:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/stopAsync(onStopped:)","title":"stopAsync(onStopped:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onStopped","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Stop the document auto capture process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"type":"text","text":" callback is called after the process has stopped."}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/stopasync(onstopped:)","type":"topic","navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/configuration-swift.property":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.property","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"title":"configuration","abstract":[{"type":"text","text":"Current configuration."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/configuration-swift.property"},"doc://DotDocument/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewWillDisappear(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewwilldisappear(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"abstract":[],"title":"viewWillDisappear(_:)","kind":"symbol"},"doc://DotDocument/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"role":"symbol","title":"DocumentAutoCaptureViewControllerDelegate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic"},"doc://DotDocument/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://DotDocument/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://DotDocument/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://DotDocument/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"DocumentAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)UIViewController","title":"UIViewController"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewDidAppear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdidappear(_:)","title":"viewDidAppear(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewWillTransition(to:with:)":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewwilltransition(to:with:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"abstract":[],"type":"topic","title":"viewWillTransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillTransition(to:with:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/style-swift.property":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.property","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC"}],"title":"style","abstract":[{"text":"Current style.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"style"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/style-swift.property"},"doc://DotDocument/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewWillAppear(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","abstract":[]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/delegate":{"role":"symbol","kind":"symbol","type":"topic","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[{"text":"Set this delegate to handle the document auto capture events.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/delegate"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewDidLayoutSubviews()":{"title":"viewDidLayoutSubviews()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdidlayoutsubviews()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLayoutSubviews()","type":"topic","abstract":[],"navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/requestCapture()":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/requestcapture()","role":"symbol","type":"topic","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"text":"()","kind":"text"}],"title":"requestCapture()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/requestCapture()","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}]},"doc://DotDocument/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://DotDocument/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"DocumentAutoCaptureViewController.Style","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/start()":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/start()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/start()","type":"topic","navigatorTitle":[{"text":"start","kind":"identifier"}],"title":"start()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"text":"Start the document auto capture process.","type":"text"}]},"doc://DotDocument/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://DotDocument/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s8SendableP","title":"Swift.Sendable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewDidLoad()":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdidload()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLoad()"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Delegate","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/delegate","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/init(configuration:style:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/requestCapture()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/start()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewWillTransition(to:with:)"]}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"},{"text":" : ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidDisappear(_:)\/title","op":"replace","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}]},{"value":"DOTDDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1init(configuration:style:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1stopAsync(onStopped:)\/title","op":"replace","value":"stopAsyncOnStopped:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1stopAsync(onStopped:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAsyncOnStopped:"}],"op":"replace"},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1configuration-swift.property\/title"},{"value":[{"kind":"identifier","text":"configuration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1configuration-swift.property\/fragments","op":"replace"},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureViewControllerDelegate","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillTransition(to:with:)\/title","op":"replace","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1style-swift.property\/title","value":"style"},{"op":"replace","value":[{"kind":"identifier","text":"style"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1style-swift.property\/fragments"},{"value":"viewWillAppear:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillAppear(_:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewWillAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1delegate\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidLayoutSubviews()\/title","op":"replace","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"value":"requestCapture","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1requestCapture()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"requestCapture","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1requestCapture()\/fragments"},{"value":"start","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1start()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidLoad()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidLoad()\/fragments"}]}]}