{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentAutoCaptureFrameParameters) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters"]}],"metadata":{"title":"DocumentAutoCaptureFrameParameters","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"symbolKind":"class"},"seeAlsoSections":[{"generated":true,"title":"Document auto capture process","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"],"anchor":"Document-auto-capture-process"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/mrzRecognitionResult","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/travelDocumentType"],"generated":true,"title":"Instance Properties"}],"references":{"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/document":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/document","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/document","title":"document","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","abstract":[{"text":"Detected document, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the document was not detected in the image."}],"navigatorTitle":[{"kind":"identifier","text":"document"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/travelDocumentType":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Resolved travel document type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/traveldocumenttype","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/travelDocumentType","title":"travelDocumentType"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"type":"topic","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","title":"DocumentAutoCaptureDetection","url":"\/documentation\/dotdocument\/documentautocapturedetection","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","type":"topic","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"title":"DocumentAutoCaptureFrameParameters"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/description","title":"description","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureresult","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","title":"DocumentAutoCaptureResult"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/detectionAreaImageSize":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectionAreaImageSize"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/detectionareaimagesize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/detectionAreaImageSize","abstract":[{"type":"text","text":"Image size of the detection area."}],"title":"detectionAreaImageSize"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","title":"init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mrzRecognitionResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","kind":"typeIdentifier","text":"MrzRecognitionResult"},{"kind":"text","text":"?)"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/mrzRecognitionResult":{"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/mrzrecognitionresult","abstract":[{"type":"text","text":"Result of MRZ recognition."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/mrzRecognitionResult","title":"mrzRecognitionResult","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"mrzRecognitionResult","kind":"identifier"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/mrzRecognitionResult","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/travelDocumentType"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"anchor":"Document-auto-capture-process","title":"Document auto capture process","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1document\/title","value":"document","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1document\/fragments","value":[{"text":"document","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1travelDocumentType\/title","value":"travelDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1travelDocumentType\/fragments","value":[{"text":"travelDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","value":"DOTDDocumentAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1detectionAreaImageSize\/title","value":"detectionAreaImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1detectionAreaImageSize\/fragments","value":[{"text":"detectionAreaImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)\/title","value":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1mrzRecognitionResult\/title","value":"mrzRecognitionResult","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1mrzRecognitionResult\/fragments","value":[{"text":"mrzRecognitionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}