{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDocumentAutoCaptureControllerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"title":"DocumentAutoCaptureControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@DotDocument@objc(pl)DOTDocumentAutoCaptureControllerDelegate","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:captured:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:detected:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureControllerCandidateSelectionStarted(_:)"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate/documentAutoCaptureController(_:detected:)":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureController:detected:"}],"role":"symbol","title":"documentAutoCaptureController(_:detected:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureDetection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:detected:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontroller(_:detected:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate/documentAutoCaptureControllerCandidateSelectionStarted(_:)":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}],"role":"symbol","title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontrollercandidateselectionstarted(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate/documentAutoCaptureController(_:captured:)":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureController:captured:"}],"role":"symbol","title":"documentAutoCaptureController(_:captured:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureResult"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the document was captured."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:captured:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontroller(_:captured:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate":{"role":"symbol","title":"DocumentAutoCaptureControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTDocumentAutoCaptureControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:captured:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureController(_:detected:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureControllerCandidateSelectionStarted(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureController(_:detected:)\/title","value":"documentAutoCaptureController:detected:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureController(_:detected:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureController:detected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureController(_:captured:)\/title","value":"documentAutoCaptureController:captured:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureController(_:captured:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureController:captured:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate\/title","value":"DOTDocumentAutoCaptureControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}