{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/init(imageQuality:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/imageQuality"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/isEqual(_:)"],"generated":true}],"abstract":[{"text":"Document quality.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentQuality) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentQuality"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentQuality"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality","title":"DocumentQuality","modules":[{"name":"DotDocument"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotdocument\/documentquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentquality"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentQuality/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/isEqual(_:)","abstract":[],"title":"isEqual(_:)","role":"symbol","url":"\/documentation\/dotdocument\/documentquality\/isequal(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentQuality/imageQuality":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality","kind":"typeIdentifier","text":"DocumentImageQuality"}],"abstract":[{"text":"Image quality.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageQuality"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/imageQuality","url":"\/documentation\/dotdocument\/documentquality\/imagequality","kind":"symbol","type":"topic","title":"imageQuality","role":"symbol"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentquality","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}],"title":"DocumentQuality","abstract":[{"type":"text","text":"Document quality."}]},"doc://DotDocument/documentation/DotDocument/DocumentQuality/description":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/description","url":"\/documentation\/dotdocument\/documentquality\/description","title":"description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/DocumentQuality/init(imageQuality:)":{"navigatorTitle":[{"text":"initWithImageQuality:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/init(imageQuality:)","title":"init(imageQuality:)","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentquality\/init(imagequality:)"},"doc://DotDocument/documentation/DotDocument/DocumentQuality/hash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/hash","url":"\/documentation\/dotdocument\/documentquality\/hash","kind":"symbol","type":"topic","title":"hash","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTDDocumentQuality","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/imageQuality"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/init(imageQuality:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/isEqual(_:)"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentQuality","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1imageQuality\/title","value":"imageQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1imageQuality\/fragments","value":[{"kind":"identifier","text":"imageQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title","value":"DOTDDocumentQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1init(imageQuality:)\/title","value":"initWithImageQuality:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1init(imageQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"}]}]}