{"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true,"title":"Validators"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator"]}],"metadata":{"modules":[{"name":"DotDocument"}],"title":"DocumentOutOfBoundsValidator","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentOutOfBoundsValidator","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDDocumentOutOfBoundsValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"title":"DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"kind":"symbol","title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","navigatorTitle":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold","abstract":[{"text":"Default threshold is 0.03.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","title":"HotspotsScoreTooHighValidator","abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/init()":{"kind":"symbol","title":"init()","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init()","abstract":[{"text":"Initialize with default threshold.","type":"text"}]},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","role":"symbol","abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"title":"DocumentNotDetectedValidator"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","type":"topic","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","title":"DocumentOutOfBoundsValidator"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"type":"topic","title":"MrzNotValidValidator","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzNotValidValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/dependencyIdentifiers":{"kind":"symbol","title":"dependencyIdentifiers","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/dependencyidentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":">"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","title":"DocumentAutoCaptureDetectionValidator","kind":"symbol"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"title":"DocumentDoesNotFitPlaceholderValidator","type":"topic","kind":"symbol","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","url":"\/documentation\/dotdocument\/sizetoosmallvalidator","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotDocument/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"title":"BrightnessTooLowValidator","type":"topic","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","role":"symbol","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/identifier":{"kind":"symbol","title":"identifier","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/identifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","title":"SharpnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/minCornerDistanceToImageShorterSideRatioThreshold":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold","kind":"symbol","abstract":[{"text":"Current minimal distance between detected document corner and image edge to image shorter side ratio threshold.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold","title":"minCornerDistanceToImageShorterSideRatioThreshold","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:)":{"role":"symbol","navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/validate(documentAutoCaptureFrameParameters:)":{"kind":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/validate(documentautocaptureframeparameters:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/validate(documentAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTDDocumentOutOfBoundsValidator","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"kind":"relationships"}]},{"value":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init()\/title","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","op":"replace","value":"DOTDDocumentOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}]},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1dependencyIdentifiers\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","value":"DOTDDocumentAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator","op":"replace"},{"value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":"DOTDBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1identifier\/title","value":"identifier","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1identifier\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/title","op":"replace","value":"minCornerDistanceToImageShorterSideRatioThreshold"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/title","op":"replace","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}]},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}