{"relationshipsSections":[{"type":"conformingTypes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"],"title":"Conforming Types","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"roleHeading":"Protocol","modules":[{"name":"DotDocument"}],"symbolKind":"protocol","title":"DocumentAutoCaptureDetectionValidator"},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/identifier"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true,"title":"Validators"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDDocumentAutoCaptureDetectionValidator) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetectionvalidator"]},{"paths":["\/documentation\/dotdocument\/documentautocapturedetectionvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"type":"topic","title":"DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create document validators."}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","role":"symbol","navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","title":"DocumentOutOfBoundsValidator"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","title":"DocumentNotDetectedValidator","abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentNotDetectedValidator"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/sizetoosmallvalidator","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator/dependencyIdentifiers":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/dependencyIdentifiers","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator\/dependencyidentifiers","type":"topic","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"title":"dependencyIdentifiers"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","title":"HotspotsScoreTooHighValidator","abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator/identifier":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator\/identifier","role":"symbol","title":"identifier","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/identifier","type":"topic","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"required":true},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator/validate(documentAutoCaptureFrameParameters:)":{"type":"topic","abstract":[{"type":"text","text":"Validate current frame parameters."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/validate(documentAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"role":"symbol","title":"validate(documentAutoCaptureFrameParameters:)"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrznotvalidvalidator","title":"MrzNotValidValidator","abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"navigatorTitle":[{"kind":"identifier","text":"MrzNotValidValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzNotValidValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator","abstract":[{"text":"Validate maximum brightness of the detected document.","type":"text"}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator":{"url":"\/documentation\/dotdocument\/mrznotpresentvalidator","abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"title":"MrzNotPresentValidator","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNotPresentValidator"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzNotPresentValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","title":"DocumentDoesNotFitPlaceholderValidator","abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}]},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/identifier"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator\/validate(documentAutoCaptureFrameParameters:)"]}],"op":"replace"},{"op":"replace","value":[{"type":"conformingTypes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"],"title":"Conforming Types","kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"title":"Validators"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments"},{"value":"DOTDDocumentOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title"},{"value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","op":"replace","value":"DOTDDocumentNotDetectedValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","op":"replace","value":"DOTDSizeTooSmallValidator"},{"value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1dependencyIdentifiers\/title","op":"replace"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTDSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments"},{"value":"DOTDHotspotsScoreTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1identifier\/title","op":"replace","value":"identifier"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1identifier\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":"DOTDMrzNotValidValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","op":"replace","value":"DOTDBrightnessTooHighValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","op":"replace","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/title","value":"DOTDMrzNotPresentValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}