{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateIdle","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateIdle"}],"roleHeading":"Class","symbolKind":"class","title":"DOTDDocumentAutoCaptureUiStateIdle","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateIdle"}]},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/preview"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/initWithPreview:","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/isEqual:"]}],"abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateIdle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureUiState","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","interfaceLanguage":"occ"},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/description":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/description","role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/description","fragments":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol","title":"description","abstract":[]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/preview":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/preview","type":"topic","abstract":[{"type":"text","text":"Preview information."}],"title":"preview","fragments":[{"text":"preview","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/preview"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","url":"\/documentation\/dotdocument\/documentautocaptureuistate","navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"DocumentAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/isEqual:":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/isEqual:","title":"isEqual:","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/isequal:"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/initWithPreview:":{"type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/initwithpreview:","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:"}],"abstract":[],"title":"initWithPreview:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/initWithPreview:"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/hash":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/hash","title":"hash","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/hash"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"fragments":[{"text":"DOTDDocumentAutoCaptureUiStateIdle","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","title":"DOTDDocumentAutoCaptureUiStateIdle","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDDocumentAutoCaptureUiState","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}