{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden","interfaceLanguage":"occ"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/hash"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/init","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/isEqual:"],"generated":true,"anchor":"Instance-Methods"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Hidden placeholder."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDPlaceholderHidden","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DOTDPlaceholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDPlaceholder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"class","title":"DOTDPlaceholderHidden","roleHeading":"Class","modules":[{"name":"DotDocument"}],"fragments":[{"text":"DOTDPlaceholderHidden","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDPlaceholderHidden","navigatorTitle":[{"kind":"identifier","text":"DOTDPlaceholderHidden"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdplaceholderhidden"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/Placeholder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","url":"\/documentation\/dotdocument\/placeholder","kind":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"role":"symbol","abstract":[{"type":"text","text":"Placeholder."}]},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden/init":{"url":"\/documentation\/dotdocument\/dotdplaceholderhidden\/init","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/init","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden/description":{"role":"symbol","url":"\/documentation\/dotdocument\/dotdplaceholderhidden\/description","title":"description","fragments":[{"text":"description","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/description","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden/isEqual:":{"role":"symbol","url":"\/documentation\/dotdocument\/dotdplaceholderhidden\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/isEqual:","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden":{"role":"symbol","url":"\/documentation\/dotdocument\/dotdplaceholderhidden","title":"DOTDPlaceholderHidden","fragments":[{"text":"DOTDPlaceholderHidden","kind":"identifier"}],"abstract":[{"text":"Hidden placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden/hash":{"title":"hash","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden\/hash","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdplaceholderhidden\/hash","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDPlaceholder","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}