{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/init()"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/initialize(license:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/verifyIsActive()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/Error"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentLibrary"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"title":"Global components","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization"]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary"]}],"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotDocumentLibrary","kind":"identifier"}],"role":"symbol","title":"DotDocumentLibrary","roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"modules":[{"name":"DotDocument"}]},"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotDocument"},{"text":" library initialization.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"title":"Logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotdocument\/logger"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","title":"DotLibrary","url":"\/documentation\/dotdocument\/dotlibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/Error":{"title":"DotDocumentLibrary.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/deinitialize()":{"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"abstract":[{"type":"text","text":"Deinitialize library."}],"title":"deinitialize()","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/deinitialize()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/deinitialize()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentLibrary","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" library initialization."}],"title":"DotDocumentLibrary","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Localization":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"url":"\/documentation\/dotdocument\/localization","title":"Localization","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}]},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/id":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId"}],"role":"symbol","abstract":[{"text":"The library identifier.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/id","title":"id","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/id"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/initialize(license:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary\/initialize(license:)","abstract":[{"text":"Initialize library with license.","type":"text"}],"title":"initialize(license:)","role":"symbol","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/initialize(license:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/verifyIsActive()":{"url":"\/documentation\/dotdocument\/dotdocumentlibrary\/verifyisactive()","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/verifyIsActive()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol","title":"verifyIsActive()","navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Verify that library is initialized.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/init()":{"title":"init()","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/init()","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DotDocumentLibrary","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibrary"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibrary"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/id"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/initialize(license:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/verifyIsActive()"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization"],"generated":true}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DotDocumentLibrary","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/title","value":"DOTDLogger","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDLogger"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/fragments"},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]},{"value":"deinitializeAndReturnError:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1deinitialize()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1deinitialize()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/title","op":"replace","value":"DOTDLocalization"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDLocalization"}]},{"value":"id","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1id\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1id\/fragments","op":"replace","value":[{"kind":"identifier","text":"id"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}]},{"value":"verifyIsActiveAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1verifyIsActive()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1verifyIsActive()\/fragments","value":[{"kind":"text","text":"- "},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1init()\/title","value":"init","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1init()\/fragments"}]}]}