{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule\/moduleId"],"title":"Instance Properties","anchor":"Instance-Properties"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModule"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModule"}],"title":"DotDocumentModule","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModule"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(pl)DotDocumentModule","symbolKind":"protocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentmodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentmodule"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentModule/moduleId":{"url":"\/documentation\/dotdocument\/dotdocumentmodule\/moduleid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule\/moduleId","title":"moduleId","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotDocumentModuleId","kind":"typeIdentifier","text":"DotDocumentModuleId"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentModule":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModule"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule","url":"\/documentation\/dotdocument\/dotdocumentmodule","title":"DotDocumentModule","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModule"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentModule","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotDocumentModule"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModule"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule\/moduleId"],"generated":true,"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModule"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"moduleId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule~1moduleId\/title"},{"value":[{"kind":"identifier","text":"moduleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule~1moduleId\/fragments"},{"value":"DotDocumentModule","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModule"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModule"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}