{"variants":[{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfigurationbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"],"kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced\/init"],"generated":true,"anchor":"Instance-Methods"}],"metadata":{"navigatorTitle":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationBalanced","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Class","title":"DotFaceDetectionModuleConfigurationBalanced"},"abstract":[{"text":"Face detection balanced module.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfigurationBalanced":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"title":"DotFaceDetectionModuleConfigurationBalanced","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfigurationbalanced","abstract":[{"type":"text","text":"Face detection balanced module."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"abstract":[{"type":"text","text":"Face detection module configuration."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","type":"topic","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfigurationBalanced/init":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfigurationBalanced\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfigurationbalanced\/init","title":"init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}]}]}