{"kind":"symbol","metadata":{"title":"DotFaceModuleId","externalID":"c:@M@DotCore@E@DotFaceModuleId","modules":[{"name":"DotDocument"}],"symbolKind":"enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"roleHeading":"Enumeration"},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"]}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionFast","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/verification"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/RawRepresentable-Implementations"]}],"references":{"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/expressionNeutral":{"url":"\/documentation\/dotdocument\/dotfacemoduleid\/expressionneutral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}],"title":"DotFaceModuleId.expressionNeutral","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/expressionNeutral","type":"topic","abstract":[],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/passiveLiveness":{"title":"DotFaceModuleId.passiveLiveness","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/passiveliveness","type":"topic","navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/passiveLiveness"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/detectionBalanced":{"title":"DotFaceModuleId.detectionBalanced","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/detectionbalanced","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionBalanced","navigatorTitle":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionBalanced","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SY":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SY","title":"Swift.RawRepresentable"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/init(rawvalue:)","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/backgroundUniformity":{"title":"DotFaceModuleId.backgroundUniformity","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/backgrounduniformity","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/backgroundUniformity","navigatorTitle":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/eyeGazeLiveness":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/eyeGazeLiveness","navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/eyegazeliveness","title":"DotFaceModuleId.eyeGazeLiveness","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/dotdocument\/dotfacemoduleid\/rawrepresentable-implementations"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotdocument\/dotfacemoduleid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","kind":"symbol","type":"topic","title":"DotFaceModuleId","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/verification":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/verification","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/verification","title":"DotFaceModuleId.verification","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/Equatable-Implementations","abstract":[],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/equatable-implementations","title":"Equatable Implementations","kind":"article","role":"collectionGroup"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/description":{"abstract":[],"title":"description","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/detectionFast":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionFast","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/detectionfast","title":"DotFaceModuleId.detectionFast","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionFast","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/verification"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1expressionNeutral\/title","op":"replace","value":"DotFaceModuleIdExpressionNeutral"},{"value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1expressionNeutral\/fragments"},{"value":"DotFaceModuleIdPassiveLiveness","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1passiveLiveness\/title"},{"value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1passiveLiveness\/fragments"},{"value":"DotFaceModuleIdDetectionBalanced","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionBalanced\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionBalanced\/fragments"},{"value":"DotFaceModuleIdBackgroundUniformity","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1backgroundUniformity\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1backgroundUniformity\/fragments"},{"value":"DotFaceModuleIdEyeGazeLiveness","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1eyeGazeLiveness\/title"},{"value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1eyeGazeLiveness\/fragments"},{"value":"DotFaceModuleId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle"},{"value":"DotFaceModuleIdVerification","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1verification\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1verification\/fragments"},{"value":"DotFaceModuleIdDetectionFast","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionFast\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionFast\/fragments"}]}]}