{"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/id"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/deinitialize()","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/initialize(license:)"],"title":"Instance Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotlibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotlibrary"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"modules":[{"name":"DotDocument"}],"title":"DotLibrary","role":"symbol","externalID":"c:@M@DotCore@objc(pl)DotLibrary"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DotLibrary/initialize(license:)":{"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"required":true,"title":"initialize(license:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotlibrary\/initialize(license:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/initialize(license:)"},"doc://DotDocument/documentation/DotDocument/DotLibrary":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","title":"DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary","abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","title":"DotDocumentLibrary","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibrary"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentLibrary"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotLibrary/deinitialize()":{"required":true,"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary\/deinitialize()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/deinitialize()","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"abstract":[],"title":"deinitialize()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]},"doc://DotDocument/documentation/DotDocument/DotLibrary/id":{"required":true,"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary\/id","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/id","navigatorTitle":[{"kind":"identifier","text":"id"}],"abstract":[],"title":"id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DotLibrary"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}]},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/id"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/deinitialize()","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/initialize(license:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initializeWithLicense:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1initialize(license:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments","op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1deinitialize()\/title","op":"replace","value":"deinitializeAndReturnError:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1id\/title"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1id\/fragments","op":"replace"}]}]}