{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotnfclibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotnfclibraryconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},"abstract":[{"type":"text","text":"NFC library configuration."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://DotDocument/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable"},"doc://DotDocument/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotNfcLibraryConfiguration":{"url":"\/documentation\/dotdocument\/dotnfclibraryconfiguration","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","kind":"symbol","role":"symbol","title":"DotNfcLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"abstract":[{"text":"NFC library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotNfcLibraryConfiguration/init":{"url":"\/documentation\/dotdocument\/dotnfclibraryconfiguration\/init","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration\/init","kind":"symbol","role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]}]}]}