{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"metadata":{"title":"DotPalmModuleId","roleHeading":"Enumeration","externalID":"c:@M@DotCore@E@DotPalmModuleId","symbolKind":"enum","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/detection"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"references":{"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/Equatable-Implementations":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/equatable-implementations","kind":"article","type":"topic","title":"Equatable Implementations","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/rawrepresentable-implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotDocument\/SY"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","title":"DotPalmModuleId","url":"\/documentation\/dotdocument\/dotpalmmoduleid"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/description":{"type":"topic","title":"description","kind":"symbol","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/description","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/description"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/init(rawValue:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/init(rawvalue:)"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/detection":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/detection","role":"symbol","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/detection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"kind":"symbol","type":"topic","title":"DotPalmModuleId.detection","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/detection"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId~1detection\/title","value":"DotPalmModuleIdDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId~1detection\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}