{"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdk"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/bundleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isInitialized","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/versionName"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/deinitialize()","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/initialize(configuration:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/shared"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"],"title":"Enumerations"}],"metadata":{"role":"symbol","title":"DotSdk","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"url":"\/documentation\/dotdocument\/dotsdk\/error","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","kind":"symbol","title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","url":"\/documentation\/dotdocument\/dotsdk","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/initialize(configuration:)":{"navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"title":"initialize(configuration:)","url":"\/documentation\/dotdocument\/dotsdk\/initialize(configuration:)","abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" with configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/initialize(configuration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.15.1","type":"text"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotSdk/isInitialized":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isInitialized","type":"topic","title":"isInitialized","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isInitialized"}],"url":"\/documentation\/dotdocument\/dotsdk\/isinitialized","abstract":[{"text":"Flag to determine if ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" is initialized."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/deinitialize()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"title":"deinitialize()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/deinitialize()","url":"\/documentation\/dotdocument\/dotsdk\/deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Deinitialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/versionName":{"navigatorTitle":[{"kind":"identifier","text":"versionName"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"code":"DotSdk","type":"codeVoice"},{"text":" version.","type":"text"}],"url":"\/documentation\/dotdocument\/dotsdk\/versionname","type":"topic","title":"versionName","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/versionName"},"doc://DotDocument/documentation/DotDocument/DotSdk/shared":{"role":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/shared","type":"topic","abstract":[{"text":"Shared singleton instance.","type":"text"}],"kind":"symbol","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/shared","navigatorTitle":[{"kind":"identifier","text":"shared"}]},"doc://DotDocument/documentation/DotDocument/DotSdk/isLibraryActive(libraryId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isLibraryActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/islibraryactive(libraryid:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isLibraryActive(libraryId:)","title":"isLibraryActive(libraryId:)","role":"symbol","abstract":[{"type":"text","text":"Check whether "},{"code":"DotSdk","type":"codeVoice"},{"text":" library is active.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}]},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/DotSdk/bundleId":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[{"type":"text","text":"Application Bundle ID."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/bundleId","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/bundleid","navigatorTitle":[{"text":"bundleId","kind":"identifier"}],"title":"bundleId"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DotSdk","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/bundleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isInitialized","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/versionName"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/deinitialize()","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/initialize(configuration:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/isLibraryActive(libraryId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/shared"]}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","op":"replace","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1initialize(configuration:)\/title","value":"initializeWithConfiguration:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1initialize(configuration:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isInitialized\/title","op":"replace","value":"isInitialized"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isInitialized\/fragments","op":"replace","value":[{"kind":"identifier","text":"isInitialized"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1versionName\/title","value":"versionName"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1versionName\/fragments","op":"replace","value":[{"kind":"identifier","text":"versionName"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isLibraryActive(libraryId:)\/title","value":"isLibraryActiveWithLibraryId:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1isLibraryActive(libraryId:)\/fragments"},{"op":"replace","value":"bundleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1bundleId\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1bundleId\/fragments","value":[{"kind":"identifier","text":"bundleId"}]}]}]}