{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol"]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isFaceEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceliteenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isFaceLiteEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isFaceEyeGazeLivenessScoreEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isRealTimeTransactionReportingEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isEvaluation":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isevaluation","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"kind":"symbol","role":"symbol","required":true,"title":"isEvaluation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isEvaluation"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"abstract":[],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isdocumentenabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","role":"symbol","title":"isDocumentEnabled","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/licenseBytes":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/licensebytes","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"kind":"symbol","role":"symbol","required":true,"title":"licenseBytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/licenseBytes"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"abstract":[],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","kind":"symbol","type":"topic","title":"DotSdkLicenseProxyProtocol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isPalmEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/ispalmenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isPalmEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPalmEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isPalmEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isRealTimeAnalyticsReportingEnabled":{"abstract":[],"navigatorTitle":[{"text":"isRealTimeAnalyticsReportingEnabled","kind":"identifier"}],"required":true,"role":"symbol","kind":"symbol","title":"isRealTimeAnalyticsReportingEnabled","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isrealtimeanalyticsreportingenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeAnalyticsReportingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isNfcEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isnfcenabled","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"kind":"symbol","role":"symbol","required":true,"title":"isNfcEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isNfcEnabled"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"title":"isFacePassiveLivenessEnabled","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","required":true,"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfacematchingenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"role":"symbol","title":"isFaceMatchingEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/licenseBytes"]}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title","value":"isFaceEnabled","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments","op":"replace","value":[{"text":"isFaceEnabled","kind":"identifier"}]},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isEvaluation\/title","value":"isEvaluation","op":"replace"},{"op":"replace","value":[{"text":"isEvaluation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title","value":"isDocumentEnabled"},{"op":"replace","value":[{"text":"isDocumentEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments"},{"value":"licenseBytes","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1licenseBytes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"value":"isPalmEnabled","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isPalmEnabled"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isRealTimeAnalyticsReportingEnabled\/title","value":"isRealTimeAnalyticsReportingEnabled","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isRealTimeAnalyticsReportingEnabled"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isRealTimeAnalyticsReportingEnabled\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","value":"isNfcEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title","value":"isFacePassiveLivenessEnabled","op":"replace"},{"value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","value":"isFaceMatchingEnabled","op":"replace"},{"op":"replace","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"}]}]}