{"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"title":"HotspotsScoreTooHighValidator","externalID":"c:@M@DotDocument@objc(cs)DOTDHotspotsScoreTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"role":"symbol","symbolKind":"class","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init(threshold:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/threshold"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/defaultThreshold"],"title":"Type Properties"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDHotspotsScoreTooHighValidator) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"text":"To use this validator also following validators must be applied: ","type":"text"},{"type":"codeVoice","code":"DocumentOutOfBoundsValidator"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"title":"DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"abstract":[{"text":"Use this protocol to create document validators.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"title":"validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/validate(documentautocaptureframeparameters:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/validate(documentAutoCaptureFrameParameters:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","type":"topic","title":"HotspotsScoreTooHighValidator","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/dependencyIdentifiers":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/dependencyidentifiers","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"type":"topic","title":"dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/defaultThreshold":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/defaultThreshold","abstract":[{"type":"text","text":"Default threshold is 0.008."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"defaultThreshold","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"role":"symbol","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/defaultthreshold","kind":"symbol"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/init(threshold:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init(threshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(threshold:)","type":"topic","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init(threshold:)","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/identifier":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/identifier","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"identifier"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/threshold":{"title":"threshold","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/threshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/threshold","role":"symbol","abstract":[{"type":"text","text":"Current maximal accepted hotspots score."}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init()","title":"init()","type":"topic","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/identifier","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init(threshold:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/validate(documentAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/defaultThreshold"]}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"title":"Conforms To"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDDocumentAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}],"op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace"},{"value":"defaultThreshold","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1defaultThreshold\/title","op":"replace"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1defaultThreshold\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init(threshold:)\/title","op":"replace","value":"initWithThreshold:error:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init(threshold:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1identifier\/title","op":"replace","value":"identifier"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1identifier\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1threshold\/title","value":"threshold","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init()\/title","op":"replace","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init()\/fragments","op":"replace"}]}]}