{"variants":[{"paths":["\/documentation\/dotdocument\/imageparametersanalyzer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparametersanalyzer"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer"},"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Non-UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDImageParametersAnalyzer) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParametersAnalyzer","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","title":"ImageParametersAnalyzer","modules":[{"name":"DotDocument"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageParametersAnalyzer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ImageParametersAnalyzer","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImageParametersAnalyzer"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"abstract":[{"type":"text","text":"Stateless class which can analyze image parameters."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer\/analyze(bgraRawImage:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer\/Error"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParametersAnalyzer":{"role":"symbol","kind":"symbol","title":"ImageParametersAnalyzer","abstract":[{"type":"text","text":"Stateless class which can analyze image parameters."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageParametersAnalyzer","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","url":"\/documentation\/dotdocument\/imageparametersanalyzer","navigatorTitle":[{"text":"ImageParametersAnalyzer","kind":"identifier"}]},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDImageParametersAnalyzer/init":{"title":"init","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDImageParametersAnalyzer\/init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotdocument\/dotdimageparametersanalyzer\/init"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParametersAnalyzer/Error":{"role":"symbol","kind":"symbol","title":"ImageParametersAnalyzer.Error","abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer\/Error","url":"\/documentation\/dotdocument\/imageparametersanalyzer\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","title":"DocumentAutoCaptureController"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper":{"title":"ImagePerspectiveWarper","type":"topic","url":"\/documentation\/dotdocument\/imageperspectivewarper","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}]},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParametersAnalyzer/analyze(bgraRawImage:)":{"title":"analyze(bgraRawImage:)","abstract":[{"type":"text","text":"Analyze an image and return "},{"code":"ImageParameters","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer\/analyze(bgraRawImage:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"analyze","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}],"kind":"symbol","navigatorTitle":[{"text":"analyzeWithBgraRawImage:error:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageparametersanalyzer\/analyze(bgrarawimage:)"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTDImageParametersAnalyzer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDImageParametersAnalyzer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDImageParametersAnalyzer\/init","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer\/analyze(bgraRawImage:)"],"title":"Instance Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"],"generated":true,"title":"Non-UI components"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTDImageParametersAnalyzer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","op":"replace","value":"DOTDImageParametersAnalyzer"},{"op":"replace","value":[{"text":"DOTDImageParametersAnalyzer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","value":"DOTDImagePerspectiveWarper","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace","value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace"},{"op":"replace","value":"analyzeWithBgraRawImage:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer~1analyze(bgraRawImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer~1analyze(bgraRawImage:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"analyzeWithBgraRawImage:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}