{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagefactory"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"anchor":"Type-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"title":"Type Methods","generated":true}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"sections":[],"seeAlsoSections":[{"anchor":"Converting-images","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Image","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory"],"title":"Converting images","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"ImageFactory","symbolKind":"class","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory"},"abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"kind":"symbol","title":"createBgraRawImage(ciImage:ciContext:)","navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}]},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgraRawImage(cgImage:)":{"navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"title":"createBgraRawImage(cgImage:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"type":"topic","kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(cgimage:)"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFactory":{"url":"\/documentation\/dotdocument\/imagefactory","kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" from iOS native image types.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"title":"ImageFactory","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgraRawImage(bgrRawImage:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(bgrRawImage:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(bgrrawimage:)","title":"createBgraRawImage(bgrRawImage:)","role":"symbol","navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"title":"createBgrRawImage(ciImage:ciContext:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"type":"topic","kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/imagefactory\/createbgrrawimage(ciimage:cicontext:)"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/CGImageFactory":{"type":"topic","url":"\/documentation\/dotdocument\/cgimagefactory","title":"CGImageFactory","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgrRawImage(cgImage:)":{"url":"\/documentation\/dotdocument\/imagefactory\/createbgrrawimage(cgimage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(cgImage:)","type":"topic","kind":"symbol","title":"createBgrRawImage(cgImage:)","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotdocument\/image","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"type":"topic","role":"symbol","title":"Image"},"doc://DotDocument/documentation/DotDocument/CIImageFactory":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory","url":"\/documentation\/dotdocument\/ciimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"title":"CIImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFactory"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Converting images","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Image","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory"],"anchor":"Converting-images","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","op":"replace","value":"createBgraRawImageWithCiImage:ciContext:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(cgImage:)\/title","value":"createBgraRawImageWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title","value":"createBgrRawImageWithCiImage:ciContext:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/navigatorTitle","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/navigatorTitle","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace"}]}]}