{"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg2000","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgr","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgra"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/init(rawValue:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/description"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/RawRepresentable-Implementations"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFormat) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"},"abstract":[{"type":"text","text":"Supported image formats."}],"variants":[{"paths":["\/documentation\/dotdocument\/imageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"modules":[{"name":"DotDocument"}],"symbolKind":"enum","externalID":"c:@M@DotCore@E@DOTImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","roleHeading":"Enumeration","role":"symbol"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/ImageFormat/rawBgra":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgra","role":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"title":"ImageFormat.rawBgra","url":"\/documentation\/dotdocument\/imageformat\/rawbgra"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFormat/jpeg":{"url":"\/documentation\/dotdocument\/imageformat\/jpeg","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"JPEG compressed image format","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg","title":"ImageFormat.jpeg"},"doc://DotDocument/documentation/DotDocument/ImageFormat/jpeg2000":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/imageformat\/jpeg2000","role":"symbol","abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg2000","title":"ImageFormat.jpeg2000"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFormat/rawBgr":{"url":"\/documentation\/dotdocument\/imageformat\/rawbgr","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgr","kind":"symbol","role":"symbol","title":"ImageFormat.rawBgr","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"abstract":[{"text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes.","type":"text"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImageFormat/description":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/imageformat\/description","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/description","title":"description"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImageFormat/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/Equatable-Implementations","abstract":[],"url":"\/documentation\/dotdocument\/imageformat\/equatable-implementations","type":"topic","kind":"article","title":"Equatable Implementations"},"doc://DotDocument/SY":{"identifier":"doc:\/\/DotDocument\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/ImageFormat/init(rawValue:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/init(rawValue:)","url":"\/documentation\/dotdocument\/imageformat\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/ImageFormat/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/dotdocument\/imageformat\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations"},"doc://DotDocument/documentation/DotDocument/ImageFormat":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","abstract":[{"text":"Supported image formats.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","url":"\/documentation\/dotdocument\/imageformat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg2000","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgr","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgra"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageFormat","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormatRawBgra","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgra\/title"},{"value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgra\/fragments"},{"value":"DOTImageFormatJpeg","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg\/title","op":"replace"},{"value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg\/fragments","op":"replace"},{"value":"DOTImageFormatJpeg2000","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg2000\/title","op":"replace"},{"value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg2000\/fragments","op":"replace"},{"value":"DOTImageFormatRawBgr","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgr\/title","op":"replace"},{"value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgr\/fragments","op":"replace"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","op":"replace"}]}]}