{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageSize) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/init(width:height:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/cgSize","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/height","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/longerSide","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/shorterSide","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/width"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculatePixelCount()","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/isEqual(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/from(cgSize:)"],"anchor":"Type-Methods"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"kind":"symbol","metadata":{"title":"ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize","role":"symbol","roleHeading":"Class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize"]}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"references":{"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","url":"\/documentation\/dotdocument\/imagesize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"title":"ImageSize","type":"topic"},"doc://DotDocument/documentation/DotDocument/ImageSize/shorterSide":{"kind":"symbol","type":"topic","title":"shorterSide","url":"\/documentation\/dotdocument\/imagesize\/shorterside","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/shorterSide","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"shorterSide"}]},"doc://DotDocument/documentation/DotDocument/ImageSize/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","url":"\/documentation\/dotdocument\/imagesize\/hash","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/hash","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageSize/longerSide":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"longerSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"longerSide","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/longerSide","title":"longerSide","type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/imagesize\/longerside","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageSize/calculateWidthToHeightRatio()":{"type":"topic","role":"symbol","title":"calculateWidthToHeightRatio()","abstract":[{"type":"text","text":"Calculate width to height ratio."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculateWidthToHeightRatio()","navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"kind":"symbol","url":"\/documentation\/dotdocument\/imagesize\/calculatewidthtoheightratio()"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/ImageSize/from(cgSize:)":{"role":"symbol","title":"from(cgSize:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/from(cgSize:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"url":"\/documentation\/dotdocument\/imagesize\/from(cgsize:)","navigatorTitle":[{"text":"fromCgSize:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImageSize/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/imagesize\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/isEqual(_:)"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/ImageSize/calculatePixelCount()":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculatePixelCount"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotdocument\/imagesize\/calculatepixelcount()","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculatePixelCount()","navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"title":"calculatePixelCount()","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageSize/height":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/height","abstract":[{"type":"text","text":"Image height in pixels."}],"title":"height","type":"topic","url":"\/documentation\/dotdocument\/imagesize\/height","kind":"symbol","role":"symbol"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/ImageSize/cgSize":{"url":"\/documentation\/dotdocument\/imagesize\/cgsize","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cgSize","kind":"identifier"}],"title":"cgSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/cgSize","type":"topic","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageSize/description":{"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/description","url":"\/documentation\/dotdocument\/imagesize\/description","kind":"symbol","abstract":[]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageSize/width":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/width","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/dotdocument\/imagesize\/width","abstract":[{"text":"Image width in pixels.","type":"text"}],"title":"width","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/ImageSize/init(width:height:)":{"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/imagesize\/init(width:height:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:"}],"title":"init(width:height:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/init(width:height:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTImageSize","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/cgSize","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/height","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/longerSide","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/shorterSide","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/width"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculatePixelCount()","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/init(width:height:)","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/from(cgSize:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageSize","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1shorterSide\/title","value":"shorterSide","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1shorterSide\/fragments","value":[{"text":"shorterSide","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1longerSide\/title","value":"longerSide","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1longerSide\/fragments","value":[{"text":"longerSide","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculateWidthToHeightRatio()\/title","value":"calculateWidthToHeightRatio","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculateWidthToHeightRatio()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1from(cgSize:)\/title","value":"fromCgSize:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1from(cgSize:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgSize:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculatePixelCount()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculatePixelCount"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1height\/title","value":"height","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1height\/fragments","value":[{"kind":"identifier","text":"height"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1cgSize\/title","value":"cgSize","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1cgSize\/fragments","value":[{"kind":"identifier","text":"cgSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1width\/title","value":"width","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1width\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1init(width:height:)\/title","value":"initWithWidth:height:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1init(width:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:"}],"op":"replace"}]}]}