{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/init(min:max:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/max","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/min"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble"]},{"paths":["\/documentation\/dotdocument\/intervaldouble"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTIntervalDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","symbolKind":"class"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/hash","type":"topic","title":"hash"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/max":{"title":"max","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Maximal interval value."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/max","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"max"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/max","navigatorTitle":[{"kind":"identifier","text":"max"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/isEqual(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/isEqual(_:)","abstract":[],"type":"topic","title":"isEqual(_:)","url":"\/documentation\/dotdocument\/intervaldouble\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/init(min:max:)":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/init(min:max:)","type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/init(min:max:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"min","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(min:max:)","navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/min":{"abstract":[{"type":"text","text":"Minimal interval value."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/min","type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/min","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"min","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"min","navigatorTitle":[{"text":"min","kind":"identifier"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/description":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/description","type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/description","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","abstract":[],"url":"\/documentation\/dotdocument\/intervaldouble\/error","title":"IntervalDouble.Error","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTIntervalDouble","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/max","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/min"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/init(min:max:)","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/isEqual(_:)"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTIntervalDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1hash\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1max\/title","value":"max"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1max\/fragments","value":[{"text":"max","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1init(min:max:)\/title","value":"initWithMin:max:error:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1init(min:max:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1min\/title","op":"replace","value":"min"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1min\/fragments","value":[{"kind":"identifier","text":"min"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1description\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}