{"seeAlsoSections":[{"title":"Global components","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDLocalization) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/localization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/localization"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"},"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDLocalization","modules":[{"name":"DotDocument"}],"roleHeading":"Class","title":"Localization","role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/bundle","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/localizationDictionary","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/useLocalizationDictionary"],"title":"Type Properties"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"references":{"doc://DotDocument/documentation/DotDocument/Localization/localizationDictionary":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/localizationDictionary","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizationDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"url":"\/documentation\/dotdocument\/localization\/localizationdictionary","title":"localizationDictionary","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","title":"DotDocumentLibrary","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibrary"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentLibrary"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Localization":{"title":"Localization","url":"\/documentation\/dotdocument\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization","kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Logger":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"title":"Logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger","kind":"symbol","url":"\/documentation\/dotdocument\/logger","navigatorTitle":[{"kind":"identifier","text":"Logger"}]},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/DOTDLocalization/init":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDLocalization\/init","title":"init","url":"\/documentation\/dotdocument\/dotdlocalization\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[]},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/Localization/useLocalizationDictionary":{"title":"useLocalizationDictionary","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"If you set this to "},{"code":"true","type":"codeVoice"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"type":"text","text":" will be used to localize strings. Default value is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotdocument\/localization\/uselocalizationdictionary","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/useLocalizationDictionary","role":"symbol","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://DotDocument/documentation/DotDocument/Localization/bundle":{"title":"bundle","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"type":"codeVoice","code":"Bundle.main"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/bundle","url":"\/documentation\/dotdocument\/localization\/bundle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bundle"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTDLocalization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDLocalization"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDLocalization"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDLocalization\/init"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/bundle","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/localizationDictionary","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/useLocalizationDictionary"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger"],"title":"Global components","generated":true}]},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTDLocalization","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"localizationDictionary","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1localizationDictionary\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1localizationDictionary\/fragments","value":[{"text":"localizationDictionary","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DotDocumentLibrary","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"text":"DotDocumentLibrary","kind":"identifier"}]},{"op":"replace","value":"DOTDLocalization","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/title"},{"op":"replace","value":[{"text":"DOTDLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger\/title","value":"DOTDLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTDLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1useLocalizationDictionary\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}]},{"value":"bundle","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1bundle\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1bundle\/fragments","value":[{"text":"bundle","kind":"identifier"}],"op":"replace"}]}]}