{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDLogger) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/logger"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/logger"]}],"seeAlsoSections":[{"title":"Global components","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/logLevel"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/debug(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/error(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/info(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/warning(_:file:function:)"]}],"metadata":{"symbolKind":"class","role":"symbol","title":"Logger","externalID":"c:@M@DotDocument@objc(cs)DOTDLogger","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"modules":[{"name":"DotDocument"}]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Logger/debug(_:file:function:)":{"abstract":[],"title":"debug(_:file:function:)","type":"topic","url":"\/documentation\/dotdocument\/logger\/debug(_:file:function:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"debug:file:function:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/debug(_:file:function:)"},"doc://DotDocument/documentation/DotDocument/Logger/logLevel":{"abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"title":"logLevel","type":"topic","url":"\/documentation\/dotdocument\/logger\/loglevel","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LoggerLogLevel","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/logLevel"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Localization":{"abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"title":"Localization","type":"topic","url":"\/documentation\/dotdocument\/localization","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"},"doc://DotDocument/documentation/DotDocument/Logger":{"abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"title":"Logger","type":"topic","url":"\/documentation\/dotdocument\/logger","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/Logger/info(_:file:function:)":{"abstract":[],"title":"info(_:file:function:)","type":"topic","url":"\/documentation\/dotdocument\/logger\/info(_:file:function:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"info:file:function:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/info(_:file:function:)"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"role":"symbol","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentLibrary"}],"title":"DotDocumentLibrary","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","url":"\/documentation\/dotdocument\/dotdocumentlibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Logger/error(_:file:function:)":{"title":"error(_:file:function:)","abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/logger\/error(_:file:function:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"function","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"error:file:function:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/error(_:file:function:)"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/Logger/warning(_:file:function:)":{"title":"warning(_:file:function:)","abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/logger\/warning(_:file:function:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warning"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"warning:file:function:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/warning(_:file:function:)"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DOTDLogger","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTDLogger","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDLogger","kind":"identifier"}]},{"op":"replace","value":[{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/logLevel"]},{"title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/debug(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/error(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/info(_:file:function:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Logger\/warning(_:file:function:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Global components","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDLogger"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"debug:file:function:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1debug(_:file:function:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1debug(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"debug:file:function:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1logLevel\/title","value":"logLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1logLevel\/fragments","value":[{"text":"logLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/title","op":"replace","value":"DOTDLocalization"},{"value":[{"text":"DOTDLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger\/title","value":"DOTDLogger","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger\/fragments","op":"replace","value":[{"text":"DOTDLogger","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1info(_:file:function:)\/title","value":"info:file:function:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1info(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"info:file:function:"}]},{"op":"replace","value":"DotDocumentLibrary","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title"},{"value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments"},{"value":"error:file:function:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1error(_:file:function:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1error(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:file:function:"}]},{"value":"warning:file:function:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1warning(_:file:function:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"warning:file:function:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Logger~1warning(_:file:function:)\/fragments"}]}]}