{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzCheckDigit) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"title":"MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/init(value:isValid:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isValid","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/value"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzcheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzcheckdigit"]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/value":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A string value of the check digit belonging to a particular MRZ element."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/value","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/description":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/description","kind":"symbol","type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/hash":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/hash","kind":"symbol","type":"topic"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/isValid":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/isvalid","navigatorTitle":[{"text":"isValid","kind":"identifier"}],"title":"isValid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Denotes whether a checksum of a particular MRZ element is valid."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isValid","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/init(value:isValid:)":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/init(value:isvalid:)","navigatorTitle":[{"text":"initWithValue:isValid:","kind":"identifier"}],"title":"init(value:isValid:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/init(value:isValid:)","kind":"symbol","type":"topic"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"type":"topic","title":"MrzCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/isEqual(_:)":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isEqual(_:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isValid","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/value"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/init(value:isValid:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isEqual(_:)"],"title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTMrzCheckDigit","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"value":"isValid","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isValid\/title"},{"value":[{"text":"isValid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isValid\/fragments"},{"value":"initWithValue:isValid:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1init(value:isValid:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:isValid:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1init(value:isValid:)\/fragments"},{"value":"DOTMrzCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}