{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzDateElementWithCheckDigit) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]}]}],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","title":"MrzDateElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"roleHeading":"Class","symbolKind":"class"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/date","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/hash"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/isEqual(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","interfaceLanguage":"swift"},"abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"seeAlsoSections":[{"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"references":{"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}],"title":"MrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"title":"MrzReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"title":"MrzNameElement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","url":"\/documentation\/dotdocument\/mrznameelement","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}]},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"role":"symbol","title":"MachineReadableZone","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"title":"MrzStringPosition","url":"\/documentation\/dotdocument\/mrzstringposition","type":"topic","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}]},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/init(value:positions:checkDigit:date:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"positions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"checkDigit"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"date"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","title":"init(value:positions:checkDigit:date:)","role":"symbol","kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/date":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"date"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","text":"MrzDate"}],"navigatorTitle":[{"text":"date","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/date","abstract":[{"text":"Parsed date.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/date","kind":"symbol","role":"symbol","title":"date"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzDate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"title":"MrzDate","type":"topic","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"title":"Td1MachineReadableZone","url":"\/documentation\/dotdocument\/td1machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","type":"topic","kind":"symbol","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"title":"MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/description","type":"topic","kind":"symbol","title":"description","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"title":"Td3MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","url":"\/documentation\/dotdocument\/td3machinereadablezone","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/isEqual(_:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/isequal(_:)","role":"symbol","title":"isEqual(_:)"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/hash","kind":"symbol","abstract":[],"role":"symbol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","title":"Td2MachineReadableZone","url":"\/documentation\/dotdocument\/td2machinereadablezone","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzelement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","type":"topic","title":"MrzElement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/date","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/hash"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/isEqual(_:)"],"title":"Instance Methods"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit"}]}]}},{"value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"op":"replace","value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"op":"replace","value":"initWithValue:positions:checkDigit:date:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/fragments"},{"value":"date","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1date\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1date\/fragments","op":"replace","value":[{"text":"date","kind":"identifier"}]},{"value":"DOTMrzDate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments"},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1description\/fragments"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1hash\/title","op":"replace","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1hash\/fragments"},{"value":"DOTTd2MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]}]}]}