{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdate"]},{"paths":["\/documentation\/dotdocument\/mrzdate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotDocument"}],"title":"MrzDate","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/init(year:month:day:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/day","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/month","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/year"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/isEqual(_:)"],"title":"Instance Methods"}],"abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"seeAlsoSections":[{"title":"MRZ reading output","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTMrzDate) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"url":"\/documentation\/dotdocument\/td2machinereadablezone","kind":"symbol","title":"Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/MrzDate/description":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/description","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"title":"description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotdocument\/mrzdate\/description"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"url":"\/documentation\/dotdocument\/mrzdate","kind":"symbol","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"title":"MrzDate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzDate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDate"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"title":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzDate/day":{"abstract":[],"url":"\/documentation\/dotdocument\/mrzdate\/day","navigatorTitle":[{"kind":"identifier","text":"day"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/day","title":"day"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","url":"\/documentation\/dotdocument\/machinereadablezone","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"role":"symbol","title":"MachineReadableZone","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzDate/month":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/month","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"month","kind":"identifier"}],"abstract":[],"title":"month","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"month","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/mrzdate\/month"},"doc://DotDocument/documentation/DotDocument/MrzDate/year":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/year","title":"year","navigatorTitle":[{"kind":"identifier","text":"year"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"year"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/mrzdate\/year","kind":"symbol","role":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"type":"topic","title":"Td1MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDate/init(year:month:day:)":{"url":"\/documentation\/dotdocument\/mrzdate\/init(year:month:day:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"year","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"month","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"day","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithYear:month:day:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/init(year:month:day:)","title":"init(year:month:day:)"},"doc://DotDocument/documentation/DotDocument/MrzDate/isEqual(_:)":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/isEqual(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"isEqual(_:)","role":"symbol","url":"\/documentation\/dotdocument\/mrzdate\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzStringPosition","kind":"identifier"}],"abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","title":"MrzStringPosition","role":"symbol","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzstringposition"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"url":"\/documentation\/dotdocument\/mrznameelement","kind":"symbol","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","title":"MrzNameElement","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"url":"\/documentation\/dotdocument\/mrzelement","kind":"symbol","title":"MrzElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDate/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/hash","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotdocument\/mrzdate\/hash"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTMrzDate","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTMrzDate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/day","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/month","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/year"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/init(year:month:day:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTMrzDate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1description\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"value":"DOTMrzDate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace","value":[{"text":"DOTMrzDate","kind":"identifier"}]},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":"day","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1day\/title"},{"op":"replace","value":[{"kind":"identifier","text":"day"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1day\/fragments"},{"value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1month\/title","value":"month"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1month\/fragments","value":[{"kind":"identifier","text":"month"}],"op":"replace"},{"value":"year","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1year\/title","op":"replace"},{"value":[{"text":"year","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1year\/fragments"},{"value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1init(year:month:day:)\/title","op":"replace","value":"initWithYear:month:day:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1init(year:month:day:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithYear:month:day:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1isEqual(_:)\/fragments"},{"op":"replace","value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace","value":"DOTMrzElement"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}],"op":"replace"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1hash\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments"}]}]}