{"seeAlsoSections":[{"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit"]},{"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTMrzElementWithCheckDigit) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"role":"symbol","title":"MrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/checkDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/hash"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/isEqual(_:)"]}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"]},{"title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","kind":"symbol","title":"Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"type":"topic","title":"MrzElementWithCheckDigit","role":"symbol","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/hash":{"role":"symbol","title":"hash","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/hash","type":"topic"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"kind":"symbol","title":"MrzElement","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelement"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","kind":"symbol","title":"MrzDateElementWithCheckDigit","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/description":{"role":"symbol","title":"description","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/description","type":"topic"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdate","kind":"symbol","title":"MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}]},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"title":"MrzNameElement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/isEqual(_:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/isequal(_:)","title":"isEqual(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzstringposition","kind":"symbol","title":"MrzStringPosition","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"url":"\/documentation\/dotdocument\/machinereadablezone","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"title":"MachineReadableZone","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/init(value:positions:checkDigit:)":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)","title":"init(value:positions:checkDigit:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"positions"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},{"kind":"text","text":"], "},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/checkDigit":{"type":"topic","abstract":[{"text":"An object with check digit value and checksum validity flag.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"checkDigit"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/checkdigit","title":"checkDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/checkDigit","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"kind":"symbol","title":"Td1MachineReadableZone","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"type":"topic","title":"Td2MachineReadableZone","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td2MachineReadableZone","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"DOTMrzElementWithCheckDigit","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/checkDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"],"kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"],"kind":"relationships","title":"Inherited By"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1description\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","value":"DOTMrzDate"},{"value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"op":"replace"},{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"value":"initWithValue:positions:checkDigit:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}]},{"value":"checkDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1checkDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"checkDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1checkDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}