{"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/init()"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/identifier"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"metadata":{"title":"MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotValidValidator","navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDMrzNotValidValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNotValidValidator"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"abstract":[{"text":"Validate size of the detected document.","type":"text"}],"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"type":"topic","title":"SizeTooSmallValidator","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","url":"\/documentation\/dotdocument\/sizetoosmallvalidator"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/init()":{"title":"init()","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/init()","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/init()","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"type":"topic","title":"BrightnessTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"title":"DocumentOutOfBoundsValidator","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","kind":"symbol","role":"symbol","type":"topic","title":"MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/dependencyidentifiers","kind":"symbol","role":"symbol","type":"topic","title":"dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/dependencyIdentifiers"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"type":"topic","title":"BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/identifier":{"title":"identifier","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/identifier","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/validate(documentAutoCaptureFrameParameters:)":{"title":"validate(documentAutoCaptureFrameParameters:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/validate(documentautocaptureframeparameters:)","abstract":[{"text":"Validate MRZ on the detected document.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"title":"DocumentDoesNotFitPlaceholderValidator","abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"type":"topic","title":"DocumentNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"type":"topic","title":"DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"type":"topic","title":"HotspotsScoreTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTDMrzNotValidValidator","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/validate(documentAutoCaptureFrameParameters:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}]},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDMrzNotValidValidator","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDSizeTooSmallValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"value":"DOTDBrightnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":"DOTDDocumentOutOfBoundsValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments"},{"value":"DOTDMrzNotValidValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1dependencyIdentifiers\/fragments","op":"replace"},{"value":"DOTDBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1identifier\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1identifier\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]},{"value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}],"op":"replace"},{"value":"DOTDDocumentNotDetectedValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator","op":"replace"},{"value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments"}]}]}