{"metadata":{"role":"symbol","title":"MrzNotPresentValidator","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNotPresentValidator"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotPresentValidator","symbolKind":"class","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNotPresentValidator"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"abstract":[{"text":"Validate if Machine Readable Zone is present.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator"]},{"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/init()"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/identifier"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDMrzNotPresentValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNotPresentValidator"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator/identifier":{"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/identifier","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","role":"symbol","title":"identifier"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator/init()":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/init()","abstract":[],"kind":"symbol","title":"init()","url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"kind":"symbol","title":"MrzNotPresentValidator","url":"\/documentation\/dotdocument\/mrznotpresentvalidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNotPresentValidator","kind":"identifier"}],"navigatorTitle":[{"text":"MrzNotPresentValidator","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","title":"DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator/dependencyIdentifiers":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/dependencyIdentifiers","kind":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":">","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"title":"dependencyIdentifiers","url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/dependencyidentifiers"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator/validate(documentAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol","abstract":[{"text":"Validate presence of MRZ on the detected document.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"title":"validate(documentAutoCaptureFrameParameters:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDMrzNotPresentValidator","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotPresentValidator"}]},{"value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/identifier"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDMrzNotPresentValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1identifier\/title","value":"identifier","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1identifier\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/title","value":"DOTDMrzNotPresentValidator","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzNotPresentValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}]},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1dependencyIdentifiers\/title"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1dependencyIdentifiers\/fragments"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}]}]}]}