{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDMrzRecognitionResult) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzRecognitionResult"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrzrecognitionresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzrecognitionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzRecognitionResult"}],"roleHeading":"Class","symbolKind":"class","title":"MrzRecognitionResult","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"MrzRecognitionResult","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/init(rawLines:machineReadableZone:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/machineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/rawLines"]}],"references":{"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/init(rawLines:machineReadableZone:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/init(rawLines:machineReadableZone:)","role":"symbol","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/init(rawlines:machinereadablezone:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawLines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","title":"init(rawLines:machineReadableZone:)","abstract":[],"navigatorTitle":[{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"type":"topic","kind":"symbol","title":"MrzRecognitionResult","url":"\/documentation\/dotdocument\/mrzrecognitionresult","navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"role":"symbol","abstract":[{"text":"The result of using OCR on the MRZ text.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzRecognitionResult"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/rawLines":{"type":"topic","kind":"symbol","title":"rawLines","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/rawlines","navigatorTitle":[{"kind":"identifier","text":"rawLines"}],"role":"symbol","abstract":[{"text":"Lines of text recognized by OCR of the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/rawLines"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/description":{"type":"topic","kind":"symbol","title":"description","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/description"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/machineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/machineReadableZone","role":"symbol","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/machinereadablezone","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"machineReadableZone","abstract":[{"text":"Parsed MRZ.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTDMrzRecognitionResult","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/machineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/rawLines"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/init(rawLines:machineReadableZone:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDMrzRecognitionResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithRawLines:machineReadableZone:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1init(rawLines:machineReadableZone:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1init(rawLines:machineReadableZone:)\/fragments","op":"replace"},{"value":"DOTDMrzRecognitionResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title","op":"replace"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments","op":"replace"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/navigatorTitle","op":"replace"},{"value":"rawLines","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1rawLines\/title","op":"replace"},{"value":[{"text":"rawLines","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1rawLines\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1description\/fragments","op":"replace"},{"value":"machineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1machineReadableZone\/title","op":"replace"},{"value":[{"text":"machineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1machineReadableZone\/fragments","op":"replace"}]}]}