{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDMrzValidation) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzvalidation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzvalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships"}],"metadata":{"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"title":"MrzValidation","roleHeading":"Enumeration","externalID":"c:@M@DotDocument@E@DOTDMrzValidation","modules":[{"name":"DotDocument"}],"symbolKind":"enum","role":"symbol"},"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/none","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requirePresenceAndValidity","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requireValidityIfPresent"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/RawRepresentable-Implementations"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/MrzValidation/requirePresenceAndValidity":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationRequirePresenceAndValidity"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requirePresenceAndValidity"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requirePresenceAndValidity","title":"MrzValidation.requirePresenceAndValidity","kind":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation\/requirepresenceandvalidity","abstract":[{"text":"An MRZ must be present and valid.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/RawRepresentable-Implementations","url":"\/documentation\/dotdocument\/mrzvalidation\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://DotDocument/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotDocument\/SY","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzValidation/requireValidityIfPresent":{"url":"\/documentation\/dotdocument\/mrzvalidation\/requirevalidityifpresent","navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationRequireValidityIfPresent"}],"abstract":[{"type":"text","text":"If an MRZ is present, it must be valid."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireValidityIfPresent"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requireValidityIfPresent","type":"topic","title":"MrzValidation.requireValidityIfPresent","kind":"symbol","role":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzValidation/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"title":"description","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/description","url":"\/documentation\/dotdocument\/mrzvalidation\/description","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"kind":"symbol","abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","title":"MrzValidation","type":"topic","url":"\/documentation\/dotdocument\/mrzvalidation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/dotdocument\/mrzvalidation\/equatable-implementations","kind":"article"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzValidation/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation\/init(rawvalue:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/init(rawValue:)"},"doc://DotDocument/documentation/DotDocument/MrzValidation/none":{"type":"topic","title":"MrzValidation.none","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationNone"}],"url":"\/documentation\/dotdocument\/mrzvalidation\/none","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/none","role":"symbol","abstract":[{"type":"text","text":"The presence of an MRZ is not required."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DOTDMrzValidation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/none","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requirePresenceAndValidity","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requireValidityIfPresent"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDMrzValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requirePresenceAndValidity\/title","value":"DOTDMrzValidationRequirePresenceAndValidity","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requirePresenceAndValidity\/fragments","value":[{"text":"DOTDMrzValidationRequirePresenceAndValidity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requireValidityIfPresent\/title","value":"DOTDMrzValidationRequireValidityIfPresent","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requireValidityIfPresent\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidationRequireValidityIfPresent"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1none\/title","value":"DOTDMrzValidationNone","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1none\/fragments","value":[{"text":"DOTDMrzValidationNone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}