{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType"},"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"title":"PlaceholderType","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"externalID":"c:@M@DotDocument@E@DOTDPlaceholderType"},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersAndMrzFillers","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersOnly"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/description"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDPlaceholderType) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/placeholdertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/placeholdertype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/cornersAndMrzFillers":{"kind":"symbol","url":"\/documentation\/dotdocument\/placeholdertype\/cornersandmrzfillers","navigatorTitle":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersAndMrzFillers"}],"title":"PlaceholderType.cornersAndMrzFillers","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cornersAndMrzFillers","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersAndMrzFillers","abstract":[{"text":"Placeholder with corners and MRZ (Machine Readable Zone) filler characters.","type":"text"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/cornersOnly":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersOnly","kind":"symbol","abstract":[{"text":"Placeholder with corners only.","type":"text"}],"title":"PlaceholderType.cornersOnly","url":"\/documentation\/dotdocument\/placeholdertype\/cornersonly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornersOnly"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersOnly"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/placeholdertype","kind":"symbol","abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","role":"symbol","title":"PlaceholderType"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/placeholdertype\/rawrepresentable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/init(rawValue:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/dotdocument\/placeholdertype\/init(rawvalue:)"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/Equatable-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/placeholdertype\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/Equatable-Implementations","abstract":[]},"doc://DotDocument/SY":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SY","title":"Swift.RawRepresentable"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/description":{"url":"\/documentation\/dotdocument\/placeholdertype\/description","kind":"symbol","role":"symbol","title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"DOTDPlaceholderType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}]},{"value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersAndMrzFillers","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersOnly"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTDPlaceholderType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTDPlaceholderTypeCornersAndMrzFillers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersAndMrzFillers\/title"},{"value":[{"text":"DOTDPlaceholderTypeCornersAndMrzFillers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersAndMrzFillers\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersOnly\/title","op":"replace","value":"DOTDPlaceholderTypeCornersOnly"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersOnly\/fragments","value":[{"text":"DOTDPlaceholderTypeCornersOnly","kind":"identifier"}],"op":"replace"},{"value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","op":"replace"},{"value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}