{"metadata":{"roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DOTDPlaceholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"symbolKind":"class","title":"Placeholder","modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Placeholder."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDPlaceholder) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"],"title":"Classes","generated":true,"anchor":"Classes"}],"variants":[{"paths":["\/documentation\/dotdocument\/placeholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/placeholder"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderVisible":{"fragments":[{"text":"DOTDPlaceholderVisible","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"DOTDPlaceholderVisible","url":"\/documentation\/dotdocument\/dotdplaceholdervisible","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible","abstract":[{"text":"Visible placeholder.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible":{"title":"Placeholder.Visible","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Visible placeholder."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible","url":"\/documentation\/dotdocument\/placeholder\/visible","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderHidden":{"url":"\/documentation\/dotdocument\/dotdplaceholderhidden","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden","kind":"symbol","title":"DOTDPlaceholderHidden","fragments":[{"text":"DOTDPlaceholderHidden","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Hidden placeholder.","type":"text"}]},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/Placeholder":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholder","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"role":"symbol","title":"Placeholder","abstract":[{"text":"Placeholder.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Placeholder/Hidden":{"kind":"symbol","title":"Placeholder.Hidden","role":"symbol","type":"topic","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholder\/hidden","abstract":[{"type":"text","text":"Hidden placeholder."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholder/init":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholder\/init","abstract":[],"title":"init","kind":"symbol","url":"\/documentation\/dotdocument\/dotdplaceholder\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDPlaceholder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDPlaceholder"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholder\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderHidden","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible"],"title":"Inherited By","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDPlaceholder","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title","value":"DOTDPlaceholder"},{"value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}