{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/pointint"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPointInt) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}]}]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/init(x:y:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/cgPoint","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/x","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/y"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/isEqual(_:)"]},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/from(cgPoint:)"]}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointInt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","title":"PointInt"},"references":{"doc://DotDocument/documentation/DotDocument/PointInt/x":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/x","url":"\/documentation\/dotdocument\/pointint\/x","type":"topic","kind":"symbol","title":"x","role":"symbol","abstract":[{"type":"text","text":"X coordinate."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"x"}]},"doc://DotDocument/documentation/DotDocument/PointInt/from(cgPoint:)":{"type":"topic","url":"\/documentation\/dotdocument\/pointint\/from(cgpoint:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/from(cgPoint:)","abstract":[],"role":"symbol","title":"from(cgPoint:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/PointInt/cgPoint":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}],"navigatorTitle":[{"kind":"identifier","text":"cgPoint"}],"role":"symbol","url":"\/documentation\/dotdocument\/pointint\/cgpoint","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/cgPoint","title":"cgPoint"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/PointInt/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[],"role":"symbol","title":"description","type":"topic","url":"\/documentation\/dotdocument\/pointint\/description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/description"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/PointInt/init(x:y:)":{"title":"init(x:y:)","url":"\/documentation\/dotdocument\/pointint\/init(x:y:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/init(x:y:)","type":"topic","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/PointInt/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/hash","url":"\/documentation\/dotdocument\/pointint\/hash","type":"topic","kind":"symbol","title":"hash","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotDocument/documentation/DotDocument/PointInt/y":{"title":"y","url":"\/documentation\/dotdocument\/pointint\/y","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Y coordinate."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/y","type":"topic","navigatorTitle":[{"text":"y","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/PointInt/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/dotdocument\/pointint\/isequal(_:)","title":"isEqual(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/isEqual(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/PointInt":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"url":"\/documentation\/dotdocument\/pointint","title":"PointInt","role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"type":"topic"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTPointInt","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/cgPoint","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/x","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/y"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/init(x:y:)","doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/PointInt\/from(cgPoint:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPointInt"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"x","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1x\/title"},{"op":"replace","value":[{"text":"x","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1x\/fragments"},{"op":"replace","value":"fromCgPoint:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1from(cgPoint:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1from(cgPoint:)\/fragments"},{"op":"replace","value":"cgPoint","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1cgPoint\/title"},{"op":"replace","value":[{"text":"cgPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1cgPoint\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1description\/fragments"},{"op":"replace","value":"initWithX:y:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1init(x:y:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1init(x:y:)\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1hash\/fragments"},{"op":"replace","value":"y","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1y\/title"},{"op":"replace","value":[{"text":"y","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1y\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/title","value":"DOTPointInt"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/fragments","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointInt"}]}]}]}