{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"role":"symbol","roleHeading":"Class","title":"RectangleInt","symbolKind":"class","modules":[{"name":"DotDocument"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTRectangleInt) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/init(left:top:right:bottom:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/bottom","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/cgRect","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/height","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/left","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/origin","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/right","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/top","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/width","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/widthToHeightRatio"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/from(cgRect:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/rectangleint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/rectangleint"]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/RectangleInt/from(cgRect:)":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/from(cgRect:)","role":"symbol","type":"topic","title":"from(cgRect:)","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/from(cgrect:)"},"doc://DotDocument/documentation/DotDocument/RectangleInt/hash":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/hash","title":"hash","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/width":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"width","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/width","role":"symbol","title":"width","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/width"},"doc://DotDocument/documentation/DotDocument/RectangleInt/left":{"abstract":[{"type":"text","text":"Left edge."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"left"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/left","role":"symbol","type":"topic","title":"left","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/left"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/RectangleInt/cgRect":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/cgRect","title":"cgRect","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/cgrect","navigatorTitle":[{"text":"cgRect","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/bottom":{"title":"bottom","abstract":[{"type":"text","text":"Bottom edge."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/bottom","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/bottom","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"bottom","kind":"identifier"}],"type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/RectangleInt/init(left:top:right:bottom:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/init(left:top:right:bottom:)","title":"init(left:top:right:bottom:)","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/init(left:top:right:bottom:)","navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/widthToHeightRatio":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/widthToHeightRatio","title":"widthToHeightRatio","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/widthtoheightratio","navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/right":{"abstract":[{"type":"text","text":"Right edge."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"right"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/right","role":"symbol","title":"right","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/right"},"doc://DotDocument/documentation/DotDocument/RectangleInt/top":{"abstract":[{"text":"Top edge.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"top","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/top","role":"symbol","type":"topic","title":"top","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/top"},"doc://DotDocument/documentation/DotDocument/RectangleInt/isEqual(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/isEqual(_:)","role":"symbol","type":"topic","title":"isEqual(_:)","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/isequal(_:)"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/RectangleInt/height":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/height","role":"symbol","type":"topic","title":"height","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/height"},"doc://DotDocument/documentation/DotDocument/RectangleInt":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","title":"RectangleInt","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/description":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/description","title":"description","role":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/description","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleInt/origin":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier","text":"PointInt"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/origin","role":"symbol","type":"topic","title":"origin","kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/origin"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTRectangleInt"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/bottom","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/cgRect","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/height","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/left","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/origin","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/right","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/top","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/width","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/widthToHeightRatio"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/from(cgRect:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTRectangleInt","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","value":"fromCgRect:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1from(cgRect:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1from(cgRect:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgRect:"}]},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1hash\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1width\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1width\/fragments","op":"replace","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","value":"left","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1left\/title"},{"op":"replace","value":[{"text":"left","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1left\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1cgRect\/title","op":"replace","value":"cgRect"},{"op":"replace","value":[{"kind":"identifier","text":"cgRect"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1cgRect\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1bottom\/title","op":"replace","value":"bottom"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1bottom\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottom"}]},{"op":"replace","value":"initWithLeft:top:right:bottom:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1init(left:top:right:bottom:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1init(left:top:right:bottom:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1widthToHeightRatio\/title","op":"replace","value":"widthToHeightRatio"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1widthToHeightRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"widthToHeightRatio"}]},{"op":"replace","value":"right","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1right\/title"},{"op":"replace","value":[{"text":"right","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1right\/fragments"},{"op":"replace","value":"top","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1top\/title"},{"op":"replace","value":[{"kind":"identifier","text":"top"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1top\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1isEqual(_:)\/fragments"},{"op":"replace","value":"height","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1height\/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1height\/fragments"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1description\/fragments"},{"op":"replace","value":"origin","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1origin\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1origin\/fragments","op":"replace","value":[{"kind":"identifier","text":"origin"}]}]}]}