{"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator","title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"abstract":[{"text":"Validate size of the detected document.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"title":"Validators","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDSizeTooSmallValidator) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator"]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"kind":"symbol","title":"DocumentDoesNotFitPlaceholderValidator","type":"topic","abstract":[{"type":"text","text":"Validates position of the detected document relative to the placeholder."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/validate(documentAutoCaptureFrameParameters:)":{"title":"validate(documentAutoCaptureFrameParameters:)","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/validate(documentautocaptureframeparameters:)","abstract":[{"text":"Validate size of the detected document.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/validate(documentAutoCaptureFrameParameters:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/defaultMinEdgeLengthToImageShorterSideRatioThreshold":{"title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold","abstract":[{"type":"text","text":"Default threshold is 0.43."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","type":"topic","title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"title":"DocumentNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"kind":"symbol","abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"type":"topic","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","title":"DocumentOutOfBoundsValidator"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/init()":{"title":"init()","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/init()","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/minEdgeLengthToImageShorterSideRatioThreshold":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold","abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"title":"minEdgeLengthToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/init(minEdgeLengthToImageShorterSideRatioThreshold:)":{"title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/dependencyidentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/dependencyIdentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/identifier":{"title":"identifier","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/identifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"title":"MrzNotValidValidator","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrznotvalidvalidator","abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotValidValidator"}],"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"type":"topic","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","title":"HotspotsScoreTooHighValidator"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","kind":"symbol","role":"symbol"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"title":"DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDSizeTooSmallValidator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"]}],"op":"replace"},{"value":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDSizeTooSmallValidator","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","op":"replace"},{"op":"replace","value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}]},{"value":"DOTDSizeTooSmallValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","op":"replace"},{"value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","op":"replace","value":"DOTDDocumentOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/title","value":"minEdgeLengthToImageShorterSideRatioThreshold","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/title","value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1identifier\/title","op":"replace","value":"identifier"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1identifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":"DOTDBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"op":"replace","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments"},{"value":"DOTDHotspotsScoreTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","op":"replace","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}],"op":"replace"}]}]}