{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTTd2MachineReadableZone) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/td2machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentNumber","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hasAllChecksumsValid","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/optionalData","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/sex"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/isEqual(_:)"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone","title":"Td2MachineReadableZone","role":"symbol"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"title":"Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/documentNumber":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit"}],"navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentNumber","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone\/documentnumber","title":"documentNumber","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/dateOfBirth":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfBirth","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"}],"abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/dateofbirth","title":"dateOfBirth","role":"symbol"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/hasAllChecksumsValid":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hasAllChecksumsValid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAllChecksumsValid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"title":"hasAllChecksumsValid","type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/hasallchecksumsvalid","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/issuingStateOrOrganization":{"role":"symbol","title":"issuingStateOrOrganization","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/issuingStateOrOrganization","url":"\/documentation\/dotdocument\/td2machinereadablezone\/issuingstateororganization","type":"topic","navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/compositeCheckDigit":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/compositeCheckDigit","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"}],"abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/compositecheckdigit","title":"compositeCheckDigit","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","url":"\/documentation\/dotdocument\/mrzelement","kind":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/nationality":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/nationality","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}],"abstract":[],"title":"nationality","type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/nationality","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/hash":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hash","url":"\/documentation\/dotdocument\/td2machinereadablezone\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","title":"hash"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/description":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/description","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/description","title":"description","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/td1machinereadablezone","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"title":"Td1MachineReadableZone","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"optionalData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":"?, ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"abstract":[],"title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)","role":"symbol"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","url":"\/documentation\/dotdocument\/td2machinereadablezone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Td2MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","type":"topic","url":"\/documentation\/dotdocument\/mrzreader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/optionalData":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/optionalData","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"optionalData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/optionaldata","title":"optionalData","role":"symbol"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDate":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzdate","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"title":"MrzDate","navigatorTitle":[{"text":"MrzDate","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/dateOfExpiry":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfExpiry","url":"\/documentation\/dotdocument\/td2machinereadablezone\/dateofexpiry","abstract":[],"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"type":"topic","kind":"symbol","title":"dateOfExpiry","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/isEqual(_:)","url":"\/documentation\/dotdocument\/td2machinereadablezone\/isequal(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement","title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"url":"\/documentation\/dotdocument\/machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/sex":{"url":"\/documentation\/dotdocument\/td2machinereadablezone\/sex","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/sex","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sex"}],"title":"sex"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/documentCode":{"type":"topic","navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"title":"documentCode","url":"\/documentation\/dotdocument\/td2machinereadablezone\/documentcode","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentCode","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/name":{"url":"\/documentation\/dotdocument\/td2machinereadablezone\/name","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"title":"name"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzStringPosition":{"navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition","role":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"kind":"symbol","title":"MrzStringPosition"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTTd2MachineReadableZone","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/documentNumber","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/optionalData","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/sex"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":[{"title":"MRZ reading output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTTd2MachineReadableZone","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace","value":"DOTTd3MachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1documentNumber\/title","value":"documentNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1documentNumber\/fragments","value":[{"text":"documentNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfBirth\/title","value":"dateOfBirth","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfBirth\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}],"op":"replace"},{"value":"issuingStateOrOrganization","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1issuingStateOrOrganization\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1issuingStateOrOrganization\/fragments","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1compositeCheckDigit\/title","value":"compositeCheckDigit","op":"replace"},{"value":[{"kind":"identifier","text":"compositeCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1compositeCheckDigit\/fragments"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments"},{"value":"nationality","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1nationality\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1nationality\/fragments","value":[{"kind":"identifier","text":"nationality"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1hash\/title","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1description\/title","value":"description"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1description\/fragments"},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"value":"optionalData","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1optionalData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1optionalData\/fragments","value":[{"kind":"identifier","text":"optionalData"}]},{"value":"DOTMrzDate","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/fragments"},{"value":"dateOfExpiry","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfExpiry\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfExpiry\/fragments","value":[{"kind":"identifier","text":"dateOfExpiry"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1sex\/title","value":"sex","op":"replace"},{"value":[{"text":"sex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1sex\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1documentCode\/title","value":"documentCode"},{"op":"replace","value":[{"kind":"identifier","text":"documentCode"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1documentCode\/fragments"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1name\/title"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1name\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/fragments"}]}]}