{"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"Td3MachineReadableZone","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone","symbolKind":"class","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Class"},"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/compositeCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfBirth","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfExpiry","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/documentCode","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/name","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/nationality","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/passportNumber","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/sex"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/isEqual(_:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTTd3MachineReadableZone) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/compositeCheckDigit":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/compositecheckdigit","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/compositeCheckDigit","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"abstract":[],"title":"compositeCheckDigit"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/passportNumber":{"title":"passportNumber","url":"\/documentation\/dotdocument\/td3machinereadablezone\/passportnumber","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passportNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/passportNumber","navigatorTitle":[{"text":"passportNumber","kind":"identifier"}],"abstract":[]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","kind":"typeIdentifier","text":"MrzNameElement"},{"text":", ","kind":"text"},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","abstract":[],"navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"title":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelement","kind":"symbol","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/isEqual(_:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/isEqual(_:)","url":"\/documentation\/dotdocument\/td3machinereadablezone\/isequal(_:)","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"title":"MrzDateElementWithCheckDigit","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/dateOfExpiry":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone\/dateofexpiry","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfExpiry","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"abstract":[],"title":"dateOfExpiry"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/documentCode":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/documentcode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"}],"title":"documentCode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/documentCode","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/sex":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/sex","url":"\/documentation\/dotdocument\/td3machinereadablezone\/sex","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"sex"}],"title":"sex"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"title":"Td1MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","type":"topic","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"title":"MrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNameElement"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/name":{"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/td3machinereadablezone\/name","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/name","role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/personalNumberOrOtherOptionalData":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/personalnumberorotheroptionaldata","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"personalNumberOrOtherOptionalData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"title":"personalNumberOrOtherOptionalData","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","abstract":[],"navigatorTitle":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzdate","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"title":"MrzDate","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"title":"MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","role":"symbol","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"url":"\/documentation\/dotdocument\/machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"title":"MrzStringPosition","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/nationality":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/nationality","abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone\/nationality","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"}],"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"title":"nationality"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/description":{"type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone\/description","abstract":[],"title":"description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/description","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/issuingStateOrOrganization":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/issuingstateororganization","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"title":"issuingStateOrOrganization","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/issuingStateOrOrganization","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/dateOfBirth":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone\/dateofbirth","title":"dateOfBirth","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfBirth"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/hash":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/hash","abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTTd3MachineReadableZone","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"op":"replace"},{"op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/compositeCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfBirth","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfExpiry","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/documentCode","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/name","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/nationality","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/passportNumber","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/sex"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTTd3MachineReadableZone","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1compositeCheckDigit\/title","op":"replace","value":"compositeCheckDigit"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1compositeCheckDigit\/fragments"},{"value":"passportNumber","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1passportNumber\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1passportNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"passportNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments"},{"op":"replace","value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"value":"dateOfExpiry","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfExpiry\/title"},{"value":[{"text":"dateOfExpiry","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfExpiry\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1documentCode\/title","op":"replace","value":"documentCode"},{"value":[{"kind":"identifier","text":"documentCode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1documentCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1sex\/title","value":"sex","op":"replace"},{"value":[{"text":"sex","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1sex\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1name\/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit","op":"replace"},{"op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments"},{"value":"personalNumberOrOtherOptionalData","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/fragments","op":"replace","value":[{"kind":"identifier","text":"personalNumberOrOtherOptionalData"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"value":[{"text":"DOTMrzDate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"nationality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1nationality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1nationality\/fragments","value":[{"text":"nationality","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1description\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"replace","value":"issuingStateOrOrganization","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1issuingStateOrOrganization\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1issuingStateOrOrganization\/fragments","op":"replace","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfBirth\/title","value":"dateOfBirth","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"dateOfBirth"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfBirth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]}]}]}