{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTTiltAngles) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/init(pitch:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/pitch"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/tiltangles"]},{"paths":["\/documentation\/dotdocument\/tiltangles"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"metadata":{"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"title":"TiltAngles","externalID":"c:@M@DotDocument@objc(cs)DOTTiltAngles","roleHeading":"Class","role":"symbol","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles"},"sections":[],"references":{"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles":{"kind":"symbol","title":"TiltAngles","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles","url":"\/documentation\/dotdocument\/tiltangles","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true,"type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles/init(pitch:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/init(pitch:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPitch:"}],"type":"topic","abstract":[],"title":"init(pitch:)","kind":"symbol","url":"\/documentation\/dotdocument\/tiltangles\/init(pitch:)","role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles/pitch":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}],"url":"\/documentation\/dotdocument\/tiltangles\/pitch","title":"pitch","type":"topic","navigatorTitle":[{"text":"pitch","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/pitch"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles/description":{"kind":"symbol","title":"description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/description","url":"\/documentation\/dotdocument\/tiltangles\/description","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTTiltAngles"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/pitch"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/init(pitch:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTTiltAngles","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"value":"initWithPitch:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1init(pitch:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1init(pitch:)\/fragments"},{"op":"replace","value":"pitch","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1pitch\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1pitch\/fragments","value":[{"text":"pitch","kind":"identifier"}]},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1description\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}