{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"MRZ reading input","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTTravelDocumentType) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td1","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td2","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td3"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/lineLength","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/numberOfLines","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/scale","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/widthToHeightRatio"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/s12CaseIterableP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@DotDocument@E@DOTTravelDocumentType","modules":[{"name":"DotDocument"}],"title":"TravelDocumentType","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/td1":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype\/td1","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td1","title":"TravelDocumentType.td1","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"td1","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/lineLength":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/linelength","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/lineLength","title":"lineLength","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lineLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","type":"topic","url":"\/documentation\/dotdocument\/mrzreader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"role":"symbol"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/init(rawValue:)":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage"},"doc://com.innovatrics.dot.document/SY":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/scale":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/scale","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/scale","title":"scale","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/td2":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td2","type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype\/td2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"}],"title":"TravelDocumentType.td2","navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd2"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType":{"abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType","url":"\/documentation\/dotdocument\/traveldocumenttype","title":"TravelDocumentType"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/widthToHeightRatio":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/widthtoheightratio","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/widthToHeightRatio","title":"widthToHeightRatio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"widthToHeightRatio"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/description":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/description","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/s12CaseIterableP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/dotdocument\/traveldocumenttype\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/td3":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DOTTravelDocumentTypeTd3","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype\/td3","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td3","title":"TravelDocumentType.td3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td3"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/numberOfLines":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype\/numberoflines","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/numberOfLines","title":"numberOfLines","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"numberOfLines","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/dotdocument\/traveldocumenttype\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTTravelDocumentType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td1","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td2","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td3"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"MRZ reading input","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"],"generated":true}]},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTTravelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td1\/title","value":"DOTTravelDocumentTypeTd1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td1\/fragments","value":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}]},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td2\/title","value":"DOTTravelDocumentTypeTd2","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td2\/fragments","value":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}]},{"op":"replace","value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/title"},{"op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td3\/title","op":"replace","value":"DOTTravelDocumentTypeTd3"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td3\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}