{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTValidationFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ValidationFloat","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTValidationFloat","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationFloat"}],"navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"title":"ValidationFloat","role":"symbol","symbolKind":"class","roleHeading":"Class"},"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat\/validate(value:interval:)"],"title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/validationfloat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/validationfloat"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationFloat/validate(value:interval:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat\/validate(value:interval:)","kind":"symbol","title":"validate(value:interval:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","text":"IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"url":"\/documentation\/dotdocument\/validationfloat\/validate(value:interval:)","type":"topic","abstract":[],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationFloat":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat","kind":"symbol","title":"ValidationFloat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationFloat","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"url":"\/documentation\/dotdocument\/validationfloat","type":"topic","abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTValidationFloat","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DOTValidationFloat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTValidationFloat","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat\/validate(value:interval:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTValidationFloat","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat~1validate(value:interval:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"validateWithValue:interval:error:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/title","value":"DOTValidationFloat","op":"replace"},{"value":[{"kind":"identifier","text":"DOTValidationFloat"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/fragments"}]}]}