{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/RawRepresentable-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholdertype\/hash(into:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/hash(into:)"},"metadata":{"modules":[{"name":"DotDocument","relatedModules":["Swift"]}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"hash(into:)","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotDocument@E@DOTDPlaceholderType","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Swift"},"references":{"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"role":"symbol","title":"PlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","abstract":[{"text":"Type of placeholder.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholdertype","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/hash(into:)":{"kind":"symbol","role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)","abstract":[],"url":"\/documentation\/dotdocument\/placeholdertype\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/hash(into:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/RawRepresentable-Implementations":{"type":"topic","kind":"article","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/dotdocument\/placeholdertype\/rawrepresentable-implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/RawRepresentable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","op":"replace","value":"DOTDPlaceholderType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","op":"replace","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle","op":"replace","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}]}]}]}