{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholdertype\/init(rawvalue:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType"]]},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"init","externalID":"s:11DotDocument15PlaceholderTypeO8rawValueACSgSi_tcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","title":"init(rawValue:)"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/init(rawValue:)","abstract":[],"url":"\/documentation\/dotdocument\/placeholdertype\/init(rawvalue:)","role":"symbol"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"text":"Type of placeholder.","type":"text"}],"url":"\/documentation\/dotdocument\/placeholdertype","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}