{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/failureReason","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"relatedModules":["Foundation"],"name":"DotNfc"}],"extendedModule":"Foundation","roleHeading":"Instance Property","title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":[{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"10.10","unavailable":false,"name":"macOS","beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS","beta":false}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:6DotNfc0B3KeyC5ErrorO","symbolKind":"property"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/error\/failurereason"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/LocalizedError-Implementations"]]},"references":{"doc://DotNfc/documentation/DotNfc/NfcKey":{"role":"symbol","title":"NfcKey","type":"topic","url":"\/documentation\/dotnfc\/nfckey","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"kind":"symbol","deprecated":true},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/failureReason":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"failureReason","url":"\/documentation\/dotnfc\/nfckey\/error\/failurereason","abstract":[],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","title":"NfcKey.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/nfckey\/error"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/LocalizedError-Implementations":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/LocalizedError-Implementations","role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/localizederror-implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"}]}]}