{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/Error-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/localizedDescription"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"extendedModule":"Swift","modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"roleHeading":"Instance Property","title":"localizedDescription","role":"symbol","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:6DotNfc0B3KeyC5ErrorO","platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.10","unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"9.0","unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","title":"NfcKey.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/nfckey\/error"},"doc://DotNfc/documentation/DotNfc/NfcKey":{"role":"symbol","title":"NfcKey","type":"topic","url":"\/documentation\/dotnfc\/nfckey","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"kind":"symbol","deprecated":true},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/Error-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/error-implementations","title":"Error Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/Error-Implementations","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/localizedDescription":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/localizedDescription","title":"localizedDescription","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/localizeddescription"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"},{"value":"DOTNNfcKey","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","op":"replace"},{"value":[{"text":"DOTNNfcKey","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcKey"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/navigatorTitle","op":"replace"}]}]}