{"abstract":[{"text":"Index finger detection result, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the finger was not detected in the image.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector","kind":"typeIdentifier","text":"FingerDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C","kind":"typeIdentifier","text":"Finger"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"index"}],"title":"index","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingers(py)index","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector","text":"FingerDetector"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C","text":"Finger"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingers\/index"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingers\/index"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/index","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/index":{"url":"\/documentation\/dotfingerscore\/fingers\/index","abstract":[{"text":"Index finger detection result, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the finger was not detected in the image.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector","text":"FingerDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C","text":"Finger","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"index","kind":"identifier"}],"title":"index","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/index"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger","type":"topic","fragments":[{"text":"DOTFGFingerDetectorFinger","kind":"identifier"}],"title":"DOTFGFingerDetectorFinger","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger","kind":"symbol","abstract":[{"type":"text","text":"Result of the finger detection process."}]},"doc://DotFingersCore/documentation/DotFingersCore/Fingers":{"url":"\/documentation\/dotfingerscore\/fingers","abstract":[{"type":"text","text":"Detected fingers."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"navigatorTitle":[{"text":"Fingers","kind":"identifier"}],"title":"Fingers","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"index","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"index"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTFGFingerDetectorFinger","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetectorFinger","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger"},{"text":" * ","kind":"text"},{"text":"index","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1index\/title","value":"index"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1index\/fragments","value":[{"kind":"identifier","text":"index"}]},{"op":"replace","value":"DOTFGFingers","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/fragments","value":[{"text":"DOTFGFingers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingers"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","op":"replace","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]}]}]}