{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","text":"FingerDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","text":"Finger","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Middle finger detection result, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingers\/middle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingers\/middle"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"middle","symbolKind":"property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingers(py)middle","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"text":".","kind":"text"},{"text":"Finger","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"middle","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/middle","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/Fingers/middle":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/middle","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"text":".","kind":"text"},{"text":"Finger","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"text":"?","kind":"text"}],"title":"middle","navigatorTitle":[{"text":"middle","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingers\/middle","kind":"symbol","abstract":[{"text":"Middle finger detection result, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the finger was not detected in the image.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/Fingers":{"url":"\/documentation\/dotfingerscore\/fingers","abstract":[{"type":"text","text":"Detected fingers."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"navigatorTitle":[{"text":"Fingers","kind":"identifier"}],"title":"Fingers","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger","type":"topic","fragments":[{"text":"DOTFGFingerDetectorFinger","kind":"identifier"}],"title":"DOTFGFingerDetectorFinger","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger","kind":"symbol","abstract":[{"type":"text","text":"Result of the finger detection process."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"middle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"middle","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTFGFingerDetectorFinger","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetectorFinger","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger"},{"text":" * ","kind":"text"},{"text":"middle","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"middle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1middle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"middle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1middle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/title","op":"replace","value":"DOTFGFingers"},{"value":[{"kind":"identifier","text":"DOTFGFingers"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingers"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector"},{"value":[{"kind":"identifier","text":"DOTFGFingerDetector"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","op":"replace"}]}]}