{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLFaceAutoCaptureUiStateInitializing) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"text":"This state is active right after the component is created for a short period of time.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"FaceAutoCaptureUiState.Initializing","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC12InitializingC","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Initializing state."}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/hash"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/isEqual(_:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"references":{"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"kind":"symbol","title":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate","type":"topic","role":"symbol"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing/hash":{"title":"hash","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/hash","abstract":[]},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/isEqual(_:)","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing\/isequal(_:)","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing/description":{"title":"description","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/description","abstract":[]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing":{"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"navigatorTitle":[{"kind":"identifier","text":"Initializing"}],"kind":"symbol","title":"FaceAutoCaptureUiState.Initializing","type":"topic","abstract":[{"type":"text","text":"Initializing state."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing","role":"symbol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","op":"replace","value":"DOTFLFaceAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]}]}]}