{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"optionalDetails"}],"title":"optionalDetails","symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)optionalDetails","role":"symbol","roleHeading":"Instance Property","platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"optionalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","text":"OptionalDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/optionaldetails"]},{"paths":["\/documentation\/dotnfc\/traveldocument\/optionaldetails"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/optionalDetails","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"role":"symbol","type":"topic","title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"text":"version: 8.4.1","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","type":"topic","title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails":{"abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"type":"topic","navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/optionaldetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"title":"OptionalDetails","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/optionalDetails":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/optionalDetails","navigatorTitle":[{"kind":"identifier","text":"optionalDetails"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocument\/optionaldetails","kind":"symbol","role":"symbol","title":"optionalDetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionalDetails"},{"text":": ","kind":"text"},{"text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"optionalDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"optionalDetails","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","text":"DOTNOptionalDetails"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"optionalDetails"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}]},{"value":"optionalDetails","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1optionalDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1optionalDetails\/fragments","value":[{"kind":"identifier","text":"optionalDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}