{"variants":[{"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(cgImage:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"cgImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory"]]},"metadata":{"navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgrRawImageWithCgImage:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","title":"createBgrRawImage(cgImage:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgrRawImage(cgImage:)":{"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"type":"topic","title":"createBgrRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"url":"\/documentation\/dotnfc\/imagefactory\/createbgrrawimage(cgimage:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(cgImage:)"},"doc://DotNfc/documentation/DotNfc/Image":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","title":"Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/ImageFactory":{"title":"ImageFactory","type":"topic","url":"\/documentation\/dotnfc\/imagefactory","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createBgrRawImageWithCgImage:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"cgImage"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"createBgrRawImageWithCgImage:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(cgImage:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle"},{"op":"replace","value":"DOTImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/fragments"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}