{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/date"},"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzDate","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDate"}],"externalID":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit(py)date","title":"date","navigatorTitle":[{"text":"date","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/date"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/date"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Parsed date."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"date","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDate","text":"MrzDate","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithCheckDigit":{"abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","title":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithCheckDigit/date":{"abstract":[{"type":"text","text":"Parsed date."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDate","text":"MrzDate"}],"navigatorTitle":[{"text":"date","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/date","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/date","kind":"symbol","title":"date","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDate":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"url":"\/documentation\/dotdocument\/mrzdate","kind":"symbol","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"role":"symbol","title":"MrzDate","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"date"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"date","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDate","text":"DOTMrzDate","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"date"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]},{"value":"date","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1date\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1date\/fragments","value":[{"kind":"identifier","text":"date"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace"}]}]}