{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/description"},"metadata":{"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(py)description","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","symbolKind":"property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","abstract":[],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/description"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.7.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","title":"MrzDateElementWithCheckDigit"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}