{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/hash"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(py)hash","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"modules":[{"name":"DotDocument"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/hash"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"]]},"references":{"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","kind":"symbol","title":"MrzDateElementWithCheckDigit","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/hash","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/hash","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1hash\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1hash\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}