{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"verifyIsModuleActiveFailed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"moduleId"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","text":"DotPalmModuleId"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/error\/verifyismoduleactivefailed(moduleid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/Error"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/Error\/verifyIsModuleActiveFailed(moduleId:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DotPalmCore0aB7LibraryC5ErrorO26verifyIsModuleActiveFailedyAeA0abH2IdO_tcAEmF","roleHeading":"Case","role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"DotPalmLibrary.Error.verifyIsModuleActiveFailed(moduleId:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"verifyIsModuleActiveFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"moduleId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","text":"DotPalmModuleId","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"case"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/Error":{"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/error","role":"symbol","title":"DotPalmLibrary.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/Error/verifyIsModuleActiveFailed(moduleId:)":{"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/error\/verifyismoduleactivefailed(moduleid:)","role":"symbol","title":"DotPalmLibrary.Error.verifyIsModuleActiveFailed(moduleId:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyIsModuleActiveFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"moduleId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","text":"DotPalmModuleId"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/Error\/verifyIsModuleActiveFailed(moduleId:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"title":"DotPalmModuleId","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotPalmModuleId","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"title":"DotPalmLibrary","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibrary"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmModuleId","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","value":"DotPalmLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","op":"replace","value":[{"text":"DotPalmLibrary","kind":"identifier"}]}]}]}