{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/dotsdkerror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"collectionGroup","title":"DotSdkError Implementations","roleHeading":"API Collection"},"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/errorDescription"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/composeWithInternalError()"],"anchor":"Instance-Methods"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/errorDescription":{"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/errordescription","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/errorDescription","title":"errorDescription","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error":{"type":"topic","title":"AutoCaptureConfiguration.Error","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/description":{"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/description","title":"description","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/composeWithInternalError()":{"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/composewithinternalerror()","title":"composeWithInternalError()","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/composeWithInternalError()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]}]}]}