{"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/Equatable-Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/!=(_:_:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/equatable-implementations"]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"title":"AutoCaptureConfiguration","url":"\/documentation\/dotfacelite\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/!=(_:_:)":{"title":"!=(_:_:)","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/!=(_:_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error":{"title":"AutoCaptureConfiguration.Error","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"}]}]}