{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.errorMessage"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/errormessage"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO12errorMessageSSvp","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"errorMessage"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/errorMessage","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error","role":"symbol","title":"AutoCaptureConfiguration.Error","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/errorMessage":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/errormessage","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/errorMessage","title":"errorMessage"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","title":"AutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle"}]}]}