{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"]]},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/authenticationProtocol-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol used for that purpose."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","text":"AuthenticationProtocol","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"authenticationProtocol"}],"title":"authenticationProtocol","externalID":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus(py)authenticationProtocol","roleHeading":"Instance Property","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"authenticationProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AuthenticationProtocol","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"}],"modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusProtocol":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","title":"DOTNDataAuthenticationStatusProtocol","abstract":[{"type":"text","text":"Protocol for authentication of the data."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"DOTNDataAuthenticationStatusProtocol"}],"type":"topic","url":"\/documentation\/dotnfc\/dotndataauthenticationstatusprotocol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.6.1"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/authenticationProtocol-swift.property":{"title":"authenticationProtocol","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.property","navigatorTitle":[{"text":"authenticationProtocol","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationProtocol","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationProtocol","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/authenticationProtocol-swift.property","abstract":[{"text":"Protocol used for that purpose.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","title":"DataAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"type":"topic","url":"\/documentation\/dotnfc\/dataauthenticationstatus","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"abstract":[{"type":"text","text":"Protocol for authentication of the data."}],"kind":"symbol","role":"symbol","title":"DataAuthenticationStatus.AuthenticationProtocol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"authenticationProtocol","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"authenticationProtocol","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","text":"DOTNDataAuthenticationStatusProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNDataAuthenticationStatusProtocol"},{"kind":"text","text":" "},{"text":"authenticationProtocol","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1authenticationProtocol-swift.property\/title","value":"authenticationProtocol","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1authenticationProtocol-swift.property\/fragments","value":[{"text":"authenticationProtocol","kind":"identifier"}],"op":"replace"},{"value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}