{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"typeIdentifier","text":"MrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement"},{"kind":"text","text":", "},{"text":"optionalData","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","text":"MrzElement"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Initializer","title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)"]},{"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"title":"MrzElement","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","type":"topic","url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)":{"title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithCheckDigit":{"title":"MrzElementWithCheckDigit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithCheckDigit"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"title":"Td1MachineReadableZone","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"title":"MrzDateElementWithCheckDigit","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrznameelement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"title":"MrzNameElement","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit":{"title":"MrzCheckDigit","url":"\/documentation\/dotdocument\/mrzcheckdigit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithDocumentCode:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"documentCode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":" "},{"text":"documentNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":" *) "},{"text":"documentNumber","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dateOfBirth:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"text":"dateOfBirth","kind":"internalParam"},{"kind":"text","text":" "},{"text":"sex:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"sex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dateOfExpiry:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"text":"dateOfExpiry","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nationality:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement"},{"text":" *) ","kind":"text"},{"text":"nationality","kind":"internalParam"},{"kind":"text","text":" "},{"text":"name:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","kind":"typeIdentifier","text":"DOTMrzNameElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"text":"optionalData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<DOTMrzElement *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"optionalData"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositeCheckDigit:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"DOTMrzCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"compositeCheckDigit","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","op":"replace"},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace"},{"value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]}]}]}