{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/description","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/rectangledouble\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangledouble\/description"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","role":"symbol","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)description"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","url":"\/documentation\/dotpalmcore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"kind":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"title":"PalmDetector","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/description","url":"\/documentation\/dotpalmcore\/rectangledouble\/description"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace","value":"DOTPPalmDetector"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1description\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]}]}]}