{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"]]},"abstract":[{"text":"Detected palm, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the palm was not detected in the image.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"text":"Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/palm"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/palm"]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters(py)palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"palm"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected palm.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","title":"PalmAutoCaptureFrameParameters"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"role":"symbol","title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of the palm detection process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","role":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmDetectorPalm"}],"abstract":[{"type":"text","text":"Result of the palm detection process."}],"type":"topic","title":"DOTPPalmDetectorPalm","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/palm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/palm","abstract":[{"type":"text","text":"Detected palm, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the palm was not detected in the image."}],"kind":"symbol","navigatorTitle":[{"text":"palm","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"type":"topic","title":"palm","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"palm"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"palm"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPPalmDetectorPalm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm"},{"text":" * ","kind":"text"},{"text":"palm","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","value":"DOTPPalmAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1palm\/title","value":"palm"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1palm\/fragments","value":[{"kind":"identifier","text":"palm"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}