{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidload(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLoad(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"kind":"text","text":")"}],"externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate(im)palmAutoCaptureViewControllerViewDidLoad:","title":"palmAutoCaptureViewControllerViewDidLoad(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"title":"BasePalmAutoCaptureViewController","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidLoad(_:)":{"title":"palmAutoCaptureViewControllerViewDidLoad(_:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidload(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}],"required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLoad(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad:"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","title":"PalmAutoCaptureViewController","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","title":"PalmAutoCaptureViewControllerDelegate","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"role":"symbol","abstract":[{"text":"Implement this delegate to handle the palm auto capture events.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"palmAutoCaptureViewControllerViewDidLoad:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewDidLoad:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","value":"DOTPBasePalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLoad(_:)\/title","value":"palmAutoCaptureViewControllerViewDidLoad:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"}]}]}