{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotPalmCore"}],"required":true,"title":"palmAutoCaptureViewControllerViewWillDisappear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate(im)palmAutoCaptureViewControllerViewWillDisappear:","symbolKind":"method","navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilldisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilldisappear(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillDisappear(_:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"title":"BasePalmAutoCaptureViewController","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","title":"PalmAutoCaptureViewController","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewWillDisappear(_:)":{"title":"palmAutoCaptureViewControllerViewWillDisappear(_:)","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilldisappear(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear:"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillDisappear(_:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","title":"PalmAutoCaptureViewControllerDelegate","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"role":"symbol","abstract":[{"text":"Implement this delegate to handle the palm auto capture events.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"palmAutoCaptureViewControllerViewWillDisappear:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"DOTPBasePalmAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPBasePalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillDisappear(_:)\/title","value":"palmAutoCaptureViewControllerViewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}