{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdiddisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdiddisappear(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","text":"PalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidDisappear(_:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate(im)palmAutoCaptureViewControllerViewDidDisappear:","symbolKind":"method","navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController"},{"kind":"text","text":")"}],"required":true,"title":"palmAutoCaptureViewControllerViewDidDisappear(_:)","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Method","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidDisappear(_:)":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdiddisappear(_:)","kind":"symbol","navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController","text":"PalmAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","title":"palmAutoCaptureViewControllerViewDidDisappear(_:)","required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidDisappear(_:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"title":"PalmAutoCaptureViewControllerDelegate","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the palm auto capture events."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"palmAutoCaptureViewControllerViewDidDisappear:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","text":"DOTPPalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidDisappear(_:)\/title","value":"palmAutoCaptureViewControllerViewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear:"}],"op":"replace"},{"value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"}]}]}