{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"ciImage"},{"content":[{"type":"paragraph","inlineContent":[{"text":"CIContext.","type":"text"}]}],"name":"ciContext"}]},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"New "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(ciImage:ciContext:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory"]]},"metadata":{"roleHeading":"Type Method","modules":[{"name":"DotPalmCore"}],"title":"create(ciImage:ciContext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCiImage:ciContext:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(ciimage:cicontext:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.12.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","role":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","kind":"symbol","title":"BgraRawImageFactory","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory/create(ciImage:ciContext:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(ciImage:ciContext:)","url":"\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(ciimage:cicontext:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithCiImage:ciContext:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCiImage:ciContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"text":"createWithCiImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"text":"ciImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ciContext:"},{"text":"(","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"value":"DOTBgraRawImageFactory","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]}]}]}