{"sections":[],"metadata":{"roleHeading":"Operator","title":"!=(_:_:)","role":"symbol","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotFaceLite"}],"symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/Equatable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/intervaldouble\/error\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/!=(_:_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/Error/Equatable-Implementations":{"url":"\/documentation\/dotfacelite\/intervaldouble\/error\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/Equatable-Implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/Error/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacelite\/intervaldouble\/error\/!=(_:_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error\/!=(_:_:)","type":"topic","role":"symbol","abstract":[],"title":"!=(_:_:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/Error":{"kind":"symbol","title":"IntervalDouble.Error","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/Error","type":"topic","url":"\/documentation\/dotfacelite\/intervaldouble\/error","abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/fragments","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}