{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator"]]},"metadata":{"navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"title":"defaultMinConfidenceThreshold","modules":[{"name":"DotPalmCore"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmNotDetectedValidator(cpy)defaultMinConfidenceThreshold"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/defaultminconfidencethreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/defaultminconfidencethreshold"]}],"abstract":[{"text":"Default threshold.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/defaultMinConfidenceThreshold"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","title":"PalmNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"PalmNotDetectedValidator"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","role":"symbol","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/defaultMinConfidenceThreshold":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/defaultminconfidencethreshold","kind":"symbol","role":"symbol","title":"defaultMinConfidenceThreshold","type":"topic","navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"abstract":[{"type":"text","text":"Default threshold."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/defaultMinConfidenceThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMinConfidenceThreshold"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","value":"DOTPPalmNotDetectedValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"op":"replace","value":"defaultMinConfidenceThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1defaultMinConfidenceThreshold\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments","value":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"op":"replace"}]}]}