{"kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/dependencyIdentifiers"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmNotDetectedValidator(py)dependencyIdentifiers","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"title":"dependencyIdentifiers","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"roleHeading":"Instance Property"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/dependencyIdentifiers":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/dependencyidentifiers","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/dependencyIdentifiers","type":"topic","title":"dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","kind":"symbol","title":"PalmNotDetectedValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","value":"DOTPPalmNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}]}]}]}