{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/accessControlProtocolUsed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Access Control protocol used to read the document."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accessControlProtocolUsed","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"accessControlProtocolUsed"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","title":"accessControlProtocolUsed","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)accessControlProtocolUsed","platforms":[{"unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iOS"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accessControlProtocolUsed","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/accesscontrolprotocolused"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/accesscontrolprotocolused"]}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument/accessControlProtocolUsed":{"url":"\/documentation\/dotnfc\/traveldocument\/accesscontrolprotocolused","abstract":[{"type":"text","text":"Access Control protocol used to read the document."}],"role":"symbol","kind":"symbol","type":"topic","title":"accessControlProtocolUsed","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/accessControlProtocolUsed","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessControlProtocolUsed"},{"text":": ","kind":"text"},{"text":"AccessControlProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"accessControlProtocolUsed"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"title":"AccessControlProtocol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","role":"symbol","abstract":[{"text":"Access Control protocol.","type":"text"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"accessControlProtocolUsed","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"accessControlProtocolUsed"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTNAccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"accessControlProtocolUsed","kind":"identifier"}]}]},"op":"replace"},{"value":"accessControlProtocolUsed","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1accessControlProtocolUsed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1accessControlProtocolUsed\/fragments","value":[{"text":"accessControlProtocolUsed","kind":"identifier"}]},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTNAccessControlProtocol"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}