{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalDocumentDetails","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/additionaldocumentdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/additionaldocumentdetails"]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalDocumentDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"additionalDocumentDetails"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)additionalDocumentDetails","symbolKind":"property","title":"additionalDocumentDetails"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"type":"topic","url":"\/documentation\/dotnfc\/additionaldocumentdetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","role":"symbol","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"title":"AdditionalDocumentDetails"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument/additionalDocumentDetails":{"title":"additionalDocumentDetails","url":"\/documentation\/dotnfc\/traveldocument\/additionaldocumentdetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalDocumentDetails","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalDocumentDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"additionalDocumentDetails","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"role":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"additionalDocumentDetails","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"additionalDocumentDetails","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNAdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"additionalDocumentDetails","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalDocumentDetails\/title","value":"additionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"additionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}]}]}