{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"authenticationStatus"}],"roleHeading":"Instance Property","platforms":[{"name":"iOS","introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)authenticationStatus","title":"authenticationStatus","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"AuthenticationStatus"}],"modules":[{"name":"DotNfc"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/authenticationStatus"},"sections":[],"abstract":[{"type":"text","text":"Authentication status of data and chip."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/authenticationstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/authenticationstatus"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"authenticationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"AuthenticationStatus","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"url":"\/documentation\/dotnfc\/authenticationstatus","kind":"symbol","title":"AuthenticationStatus","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","role":"symbol","navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument/authenticationStatus":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/authenticationStatus","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/traveldocument\/authenticationstatus","title":"authenticationStatus","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationStatus"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol","role":"symbol","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","url":"\/documentation\/dotnfc\/traveldocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"authenticationStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"authenticationStatus"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"DOTNAuthenticationStatus","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"},{"kind":"text","text":" * "},{"text":"authenticationStatus","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title","op":"replace","value":"DOTNAuthenticationStatus"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","op":"replace","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1authenticationStatus\/title","value":"authenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1authenticationStatus\/fragments","value":[{"text":"authenticationStatus","kind":"identifier"}]},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}