{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/debuginfo"]},{"paths":["\/documentation\/dotnfc\/traveldocument\/debuginfo"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"debugInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DebugInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo"}],"navigatorTitle":[{"text":"debugInfo","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)debugInfo","role":"symbol","symbolKind":"property","title":"debugInfo"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DebugInfo","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/debugInfo"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument/debugInfo":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/debugInfo","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugInfo"},{"text":": ","kind":"text"},{"text":"DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"debugInfo"}],"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/debuginfo","role":"symbol","abstract":[],"title":"debugInfo"},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"title":"DebugInfo","navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DebugInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic","title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"debugInfo","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"debugInfo","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTNDebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"debugInfo"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1debugInfo\/title","value":"debugInfo"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1debugInfo\/fragments","value":[{"text":"debugInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","op":"replace","value":"DOTNDebugInfo"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","op":"replace","value":[{"text":"DOTNDebugInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"}]}]}