{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/displayedsignatureorusualmark"]},{"paths":["\/documentation\/dotnfc\/traveldocument\/displayedsignatureorusualmark"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/displayedSignatureOrUsualMark","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"displayedSignatureOrUsualMark","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark"},{"kind":"text","text":"?"}]}]}],"metadata":{"title":"displayedSignatureOrUsualMark","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)displayedSignatureOrUsualMark","navigatorTitle":[{"text":"displayedSignatureOrUsualMark","kind":"identifier"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"kind":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"title":"DisplayedSignatureOrUsualMark","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/displayedSignatureOrUsualMark":{"title":"displayedSignatureOrUsualMark","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/displayedSignatureOrUsualMark","navigatorTitle":[{"kind":"identifier","text":"displayedSignatureOrUsualMark"}],"url":"\/documentation\/dotnfc\/traveldocument\/displayedsignatureorusualmark"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"displayedSignatureOrUsualMark","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"displayedSignatureOrUsualMark"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":" * "},{"text":"displayedSignatureOrUsualMark","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}]},{"op":"replace","value":"displayedSignatureOrUsualMark","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1displayedSignatureOrUsualMark\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1displayedSignatureOrUsualMark\/fragments","op":"replace","value":[{"text":"displayedSignatureOrUsualMark","kind":"identifier"}]}]}]}