{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","title":"hash","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)hash","modules":[{"name":"DotNfc"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/hash"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/hash","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument/hash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/traveldocument\/hash","title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"role":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1hash\/fragments"},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}