{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTAccessControlProtocol","text":"AccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus","text":"PassiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus","text":"ActiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"LdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZoneInformation","text":"MachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTEncodedIdentificationFeaturesFace","text":"EncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTDisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalPersonalDetails","text":"AdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalDocumentDetails","text":"AdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTOptionalDetails","text":"OptionalDetails"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:passiveauthenticationstatus:activeauthenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:addition-189oo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:passiveauthenticationstatus:activeauthenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:addition-189oo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}],"role":"symbol","title":"init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTAccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTEncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTOptionalDetails"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTTravelDocument(im)initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"role":"symbol","title":"MachineReadableZoneInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus":{"role":"symbol","title":"PassiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO)."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"role":"symbol","title":"EncodedIdentificationFeaturesFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"role":"symbol","title":"DisplayedSignatureOrUsualMark","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails":{"role":"symbol","title":"OptionalDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"url":"\/documentation\/dotnfc\/optionaldetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile":{"role":"symbol","title":"LdsMasterFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LdsMasterFile"}],"abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}],"url":"\/documentation\/dotnfc\/ldsmasterfile"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails":{"role":"symbol","title":"AdditionalPersonalDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","title":"AccessControlProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalDocumentDetails":{"role":"symbol","title":"AdditionalDocumentDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus":{"role":"symbol","title":"ActiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)":{"role":"symbol","title":"init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTAccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTEncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTOptionalDetails"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}],"url":"\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:passiveauthenticationstatus:activeauthenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:addition-189oo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLdsVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ldsVersion"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocolUsed:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTAccessControlProtocol","text":"DOTAccessControlProtocol"},{"kind":"text","text":")"},{"kind":"internalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveAuthenticationStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus","text":"DOTPassiveAuthenticationStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"passiveAuthenticationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus","text":"DOTActiveAuthenticationStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"activeAuthenticationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"ldsMasterFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"DOTNLdsMasterFile"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ldsMasterFile"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZoneInformation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZoneInformation","text":"DOTMachineReadableZoneInformation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTEncodedIdentificationFeaturesFace","text":"DOTEncodedIdentificationFeaturesFace"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTDisplayedSignatureOrUsualMark","text":"DOTDisplayedSignatureOrUsualMark"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalPersonalDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalPersonalDetails","text":"DOTAdditionalPersonalDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"additionalPersonalDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocumentDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTAdditionalDocumentDetails","text":"DOTAdditionalDocumentDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"additionalDocumentDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTOptionalDetails","text":"DOTOptionalDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"optionalDetails"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/title","value":"DOTPassiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTEncodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"kind":"identifier","text":"DOTEncodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTDisplayedSignatureOrUsualMark"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"kind":"identifier","text":"DOTDisplayedSignatureOrUsualMark"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTOptionalDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"kind":"identifier","text":"DOTOptionalDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTAdditionalPersonalDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTAdditionalPersonalDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"kind":"identifier","text":"DOTAccessControlProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"DOTAdditionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/title","value":"DOTActiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)\/title","value":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:passiveAuthenticationStatus:activeAuthenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}