{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"AuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"LdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"MachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","text":"EncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","text":"AdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","text":"AdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","text":"OptionalDetails"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-8ej29"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-8ej29"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}],"role":"symbol","title":"init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(im)initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"role":"symbol","title":"MachineReadableZoneInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalDocumentDetails":{"role":"symbol","title":"AdditionalDocumentDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"role":"symbol","title":"EncodedIdentificationFeaturesFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AuthenticationStatus":{"role":"symbol","title":"AuthenticationStatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of data and chip."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationStatus"}],"url":"\/documentation\/dotnfc\/authenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile":{"role":"symbol","title":"LdsMasterFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LdsMasterFile"}],"abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}],"url":"\/documentation\/dotnfc\/ldsmasterfile"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"role":"symbol","title":"DisplayedSignatureOrUsualMark","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","title":"AccessControlProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails":{"role":"symbol","title":"OptionalDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"url":"\/documentation\/dotnfc\/optionaldetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)":{"role":"symbol","title":"init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ldsVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ldsMasterFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"additionalDocumentDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"optionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}],"url":"\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-8ej29"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails":{"role":"symbol","title":"AdditionalPersonalDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLdsVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ldsVersion"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocolUsed:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"DOTNAccessControlProtocol"},{"kind":"text","text":")"},{"kind":"internalParam","text":"accessControlProtocolUsed"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"DOTNAuthenticationStatus"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticationStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"ldsMasterFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","text":"DOTNLdsMasterFile"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ldsMasterFile"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZoneInformation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"DOTNMachineReadableZoneInformation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"machineReadableZoneInformation"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedIdentificationFeaturesFace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","text":"DOTNEncodedIdentificationFeaturesFace"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"displayedSignatureOrUsualMark"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalPersonalDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","text":"DOTNAdditionalPersonalDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"additionalPersonalDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocumentDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","text":"DOTNAdditionalDocumentDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"additionalDocumentDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","text":"DOTNOptionalDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"optionalDetails"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AuthenticationStatus\/title","value":"DOTNAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTNAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)\/title","value":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}