{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ldsVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"ldsVersion","navigatorTitle":[{"kind":"identifier","text":"ldsVersion"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)ldsVersion","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ldsVersion","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"abstract":[{"type":"text","text":"Logical data structure version."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/ldsversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocument\/ldsversion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsVersion","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/TravelDocument/ldsVersion":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsVersion","title":"ldsVersion","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ldsVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/traveldocument\/ldsversion","abstract":[{"text":"Logical data structure version.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ldsVersion","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","title":"TravelDocument","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ldsVersion","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ldsVersion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"ldsVersion","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ldsVersion","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsVersion\/title"},{"value":[{"text":"ldsVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsVersion\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle"}]}]}