{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZoneInformation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"MachineReadableZoneInformation","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","platforms":[{"introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument(py)machineReadableZoneInformation","navigatorTitle":[{"text":"machineReadableZoneInformation","kind":"identifier"}],"title":"machineReadableZoneInformation","modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/machineReadableZoneInformation","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZoneInformation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"MachineReadableZoneInformation","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocument\/machinereadablezoneinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocument\/machinereadablezoneinformation"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"text":"Result of NFC reading.","type":"text"}],"type":"topic","kind":"symbol","title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"type":"topic","title":"MachineReadableZoneInformation","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"kind":"symbol","abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument/machineReadableZoneInformation":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","kind":"typeIdentifier","text":"MachineReadableZoneInformation"}],"title":"machineReadableZoneInformation","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/machinereadablezoneinformation","navigatorTitle":[{"text":"machineReadableZoneInformation","kind":"identifier"}],"abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument\/machineReadableZoneInformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.2.0","type":"text"}],"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"machineReadableZoneInformation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"machineReadableZoneInformation"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"DOTNMachineReadableZoneInformation","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","op":"replace","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1machineReadableZoneInformation\/title","op":"replace","value":"machineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument~1machineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"machineReadableZoneInformation"}]}]}]}