{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/facefeature\/mouthloweredge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthloweredge"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLowerEdge","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureMouthLowerEdge","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLowerEdge","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"FaceFeature.mouthLowerEdge","symbolKind":"case","roleHeading":"Case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mouthLowerEdge","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthLowerEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/mouthloweredge","kind":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthLowerEdge","kind":"identifier"}],"role":"symbol","title":"FaceFeature.mouthLowerEdge","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLowerEdge","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"kind":"symbol","url":"\/documentation\/dotfacecore\/facefeature","type":"topic","abstract":[{"text":"Available face features.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceFeature"}],"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","title":"FaceFeature","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFFaceFeatureMouthLowerEdge","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLowerEdge\/title","value":"DOTFFaceFeatureMouthLowerEdge"},{"value":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLowerEdge\/fragments"},{"op":"replace","value":"DOTFFaceFeature","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}]}]}