{"abstract":[{"type":"text","text":"X coordinate."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/x"},"kind":"symbol","metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)x","role":"symbol","title":"x","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"x","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/x"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble\/x"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"references":{"doc://DotNfc/documentation/DotNfc/PointDouble":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","type":"topic","title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotnfc\/pointdouble","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/PointDouble/x":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/x","url":"\/documentation\/dotnfc\/pointdouble\/x","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"x"}],"kind":"symbol","title":"x","abstract":[{"text":"X coordinate.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"x","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"x","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPointDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/navigatorTitle","op":"replace"},{"value":"x","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1x\/title","op":"replace"},{"value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1x\/fragments","op":"replace"}]}]}