{"abstract":[{"text":"Face detection fast module.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Fast\/init()"]}],"metadata":{"role":"symbol","symbolKind":"class","externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC4FastC","navigatorTitle":[{"text":"Fast","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Fast","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"title":"DotFaceDetectionModuleConfiguration.Fast","roleHeading":"Class"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/fast"]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Fast","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFaceDetectionModuleConfigurationFast) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Fast","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"]]},"references":{"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration/Fast/init()":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/fast\/init()","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Fast\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration/Fast":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"navigatorTitle":[{"kind":"identifier","text":"Fast"}],"abstract":[{"text":"Face detection fast module.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/fast","title":"DotFaceDetectionModuleConfiguration.Fast","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Fast","role":"symbol","kind":"symbol"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}