{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/validationdouble\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/validationdouble\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble\/validate(value:interval:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble","text":"IntervalDouble"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"metadata":{"title":"validate(value:interval:)","externalID":"c:@M@DotNfc@objc(cs)DOTValidationDouble(cm)validateWithValue:interval:error:","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationDouble/validate(value:interval:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"validate(value:interval:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble\/validate(value:interval:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/validationdouble\/validate(value:interval:)","navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"abstract":[],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationDouble","kind":"identifier"}],"title":"ValidationDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/validationdouble","navigatorTitle":[{"kind":"identifier","text":"ValidationDouble"}],"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble":{"title":"IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotnfc\/intervaldouble"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.3.2"}],"url":"\/documentation\/dotnfc","title":"DotNfc"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"validateWithValue:interval:error:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"validateWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"text":"interval:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" *) "},{"text":"interval","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble~1validate(value:interval:)\/title","op":"replace","value":"validateWithValue:interval:error:"},{"value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble~1validate(value:interval:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble\/title","value":"DOTValidationDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTValidationDouble"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}