{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/localizedDescription","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Error.localizedDescription","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/Error-Implementations"]]},"metadata":{"title":"localizedDescription","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","introducedAt":"10.10","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","introducedAt":"9.0","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false}],"symbolKind":"property","extendedModule":"Swift","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"DotPalmCore","relatedModules":["Swift"]}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:11DotPalmCore0B8DetectorC5ErrorO"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error","url":"\/documentation\/dotpalmcore\/palmdetector\/error","title":"PalmDetector.Error","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error/Error-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/Error-Implementations","abstract":[],"title":"Error Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/error\/error-implementations"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error/localizedDescription":{"url":"\/documentation\/dotpalmcore\/palmdetector\/error\/localizeddescription","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/localizedDescription","title":"localizedDescription"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"}]}]}