{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Default threshold value.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/defaultThreshold","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceLite"}],"title":"defaultThreshold","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator(cpy)defaultThreshold","roleHeading":"Type Property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","role":"symbol","abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"kind":"symbol","title":"BrightnessTooLowValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/defaultThreshold":{"title":"defaultThreshold","type":"topic","abstract":[{"text":"Default threshold value.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/defaultthreshold","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/defaultThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"defaultThreshold"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1defaultThreshold\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}]}]}]}