{"abstract":[{"text":"Current minimal accepted brightness.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/threshold"]},{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/threshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/threshold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"]]},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator(py)threshold","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"title":"threshold","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator/threshold":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/threshold","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"threshold","kind":"symbol","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"abstract":[{"type":"text","text":"Current minimal accepted brightness."}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/threshold"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"role":"symbol","type":"topic","title":"BrightnessTooLowValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"threshold"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"threshold","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"}]}],"kind":"declarations"}},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1threshold\/title","value":"threshold","op":"replace"},{"op":"replace","value":[{"text":"threshold","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1threshold\/fragments"},{"value":"DOTFLBrightnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title"},{"value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments"}]}]}