{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotSdkConfiguration","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}]}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/initialize(configuration:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdkConfiguration","text":"DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"initialize(configuration:)","role":"symbol","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DotSdk(im)initializeWithConfiguration:error:","modules":[{"name":"DotNfc"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/initialize(configuration:)"]},{"paths":["\/documentation\/dotnfc\/dotsdk\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk"]]},"abstract":[{"text":"Initialize ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" with configuration."}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotnfc\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/initialize(configuration:)":{"navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotsdk\/initialize(configuration:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdkConfiguration","text":"DotSdkConfiguration"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/initialize(configuration:)","title":"initialize(configuration:)","role":"symbol","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"text":" with configuration.","type":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"}],"navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"title":"DotSdkConfiguration","url":"\/documentation\/dotnfc\/dotsdkconfiguration"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initializeWithConfiguration:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdkConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DotSdk","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","value":"initializeWithConfiguration:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1initialize(configuration:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1initialize(configuration:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}