{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"versionName","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotSdk(py)versionName","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" version."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/versionName","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/versionname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdk\/versionname"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.15.0"}],"url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotSdk/versionName":{"abstract":[{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" version."}],"role":"symbol","title":"versionName","url":"\/documentation\/dotnfc\/dotsdk\/versionname","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/versionName","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"versionName","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdk":{"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotnfc\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"DotSdk","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"versionName","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"versionName","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"versionName"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"versionName","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1versionName\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1versionName\/fragments","value":[{"text":"versionName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}