{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyeoutercorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyeoutercorner"]}],"metadata":{"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeOuterCorner","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"FaceFeature.leftEyeOuterCorner","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureLeftEyeOuterCorner","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeOuterCorner","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyeOuterCorner":{"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeOuterCorner","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"leftEyeOuterCorner","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeOuterCorner","title":"FaceFeature.leftEyeOuterCorner","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/lefteyeoutercorner"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"type":"topic","role":"symbol","abstract":[{"text":"Available face features.","type":"text"}],"title":"FaceFeature","navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"url":"\/documentation\/dotfacecore\/facefeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceFeature"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeatureLeftEyeOuterCorner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DOTFFaceFeatureLeftEyeOuterCorner","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureLeftEyeOuterCorner","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFFaceFeatureLeftEyeOuterCorner","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeOuterCorner\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeOuterCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeOuterCorner"}]},{"value":"DOTFFaceFeature","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}