{"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator"},"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Class","title":"BarcodeOutsideOfDocumentValidator","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeOutsideOfDocumentValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}]},"abstract":[{"type":"text","text":"Validate if barcode is inside detected document bounds."}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/identifier"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/validate(documentAutoCaptureFrameParameters:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDBarcodeOutsideOfDocumentValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator/dependencyIdentifiers":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"type":"topic","role":"symbol","title":"dependencyIdentifiers","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/dependencyidentifiers"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator/validate(documentAutoCaptureFrameParameters:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/validate(documentautocaptureframeparameters:)","title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","kind":"symbol","title":"DocumentAutoCaptureFrameParametersValidator","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}]},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"navigatorTitle":[{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"type":"topic","role":"symbol","title":"BarcodeOutsideOfDocumentValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator/identifier":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/identifier","url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"identifier"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeOutsideOfDocumentValidator/init":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeOutsideOfDocumentValidator\/init","url":"\/documentation\/dotdocument\/dotdbarcodeoutsideofdocumentvalidator\/init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","role":"symbol","title":"init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTDBarcodeOutsideOfDocumentValidator","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/identifier"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/validate(documentAutoCaptureFrameParameters:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeOutsideOfDocumentValidator\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1dependencyIdentifiers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1dependencyIdentifiers\/fragments"},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/navigatorTitle"},{"op":"replace","value":"DOTDBarcodeOutsideOfDocumentValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/navigatorTitle"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1identifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1identifier\/fragments"}]}]}