{"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPBrightnessTooLowValidator(im)initWithThreshold:error:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(threshold:)"},"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"threshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init(threshold:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/init(threshold:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum brightness of the detected palm."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","type":"topic","title":"BrightnessTooLowValidator","kind":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/init(threshold:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init(threshold:)","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"title":"init(threshold:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithThreshold:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"threshold","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"value":"initWithThreshold:error:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init(threshold:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init(threshold:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}]}]}]}