{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"case","title":"BarcodeValidation.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"text":"DOTDBarcodeValidationNone","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@DotDocument@E@DOTDBarcodeValidation@DOTDBarcodeValidationNone"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/none","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/barcodevalidation\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcodevalidation\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Barcode presence is not required."}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/none":{"url":"\/documentation\/dotdocument\/barcodevalidation\/none","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/none","title":"BarcodeValidation.none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"abstract":[{"type":"text","text":"Barcode presence is not required."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DOTDBarcodeValidationNone","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeValidation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"BarcodeValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodevalidation","title":"BarcodeValidation","abstract":[{"text":"Mode of barcode validation.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTDBarcodeValidationNone","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTDBarcodeValidationNone","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"DOTDBarcodeValidationNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTDBarcodeValidationNone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1none\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidationNone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1none\/fragments","op":"replace"},{"value":"DOTDBarcodeValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}