{"kind":"symbol","abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"type":"text","text":" case) during an auto capture process."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fill","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType"]]},"variants":[{"paths":["\/documentation\/dotdocument\/camerapreviewscaletype\/fill"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreviewscaletype\/fill"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"title":"CameraPreviewScaleType.fill","navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"role":"symbol","externalID":"c:@M@DotDocument@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFill","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType/fill":{"navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"role":"symbol","abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This configuration may produce images with lower resolution (compared to "},{"code":"fit","type":"codeVoice"},{"type":"text","text":" case) during an auto capture process."}],"type":"topic","title":"CameraPreviewScaleType.fill","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType\/fill","url":"\/documentation\/dotdocument\/camerapreviewscaletype\/fill","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/camerapreviewscaletype","role":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"title":"CameraPreviewScaleType","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DOTCameraPreviewScaleTypeFill","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fill\/title","value":"DOTCameraPreviewScaleTypeFill"},{"value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType~1fill\/fragments"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}]}]}