{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/tiltangles\/pitch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/tiltangles\/pitch"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}],"metadata":{"title":"pitch","navigatorTitle":[{"kind":"identifier","text":"pitch"}],"symbolKind":"property","externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(py)pitch","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles\/pitch","interfaceLanguage":"swift"},"kind":"symbol","references":{"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFingersCore/documentation/DotFingersCore/TiltAngles/pitch":{"title":"pitch","kind":"symbol","url":"\/documentation\/dotfingerscore\/tiltangles\/pitch","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pitch"}],"type":"topic","abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles\/pitch"},"doc://DotFingersCore/documentation/DotFingersCore/TiltAngles":{"title":"TiltAngles","kind":"symbol","url":"\/documentation\/dotfingerscore\/tiltangles","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"pitch","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"pitch"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"pitch","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles~1pitch\/title"},{"value":[{"kind":"identifier","text":"pitch"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles~1pitch\/fragments"},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/title"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/fragments"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/navigatorTitle"}]}]}