{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzNameElement","text":"MrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElementWithChecksum","text":"MrzElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum","text":"MrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum","text":"MrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:hasvalidchecksum:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:hasvalidchecksum:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDTd2MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum":{"role":"symbol","title":"MrzElementWithChecksum","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithChecksum"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with checksum validity flag."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithChecksum"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithChecksum":{"role":"symbol","title":"MrzDateElementWithChecksum","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithChecksum"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithChecksum"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithChecksum"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithchecksum"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"role":"symbol","title":"MrzElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)":{"role":"symbol","title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:hasvalidchecksum:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"role":"symbol","title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element with primary and secondary elements."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"url":"\/documentation\/dotdocument\/mrznameelement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"role":"symbol","title":"Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzNameElement","text":"DOTDMrzNameElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElementWithChecksum","text":"DOTDMrzElementWithChecksum"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentNumber"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nationality"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum","text":"DOTDMrzDateElementWithChecksum"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dateOfBirth"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sex"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzDateElementWithChecksum","text":"DOTDMrzDateElementWithChecksum"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dateOfExpiry"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"optionalData"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasValidChecksum:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hasValidChecksum"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/title","value":"DOTDMrzElementWithChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElementWithChecksum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithChecksum\/title","value":"DOTDMrzDateElementWithChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithChecksum\/fragments","value":[{"kind":"identifier","text":"DOTDMrzDateElementWithChecksum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTDMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:hasValidChecksum:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTDMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNameElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTDTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDTd2MachineReadableZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}