{"sections":[],"metadata":{"title":"barcode","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"property","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"title":"barcode","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration","kind":"symbol","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"title":"DotDocumentBarcodeModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document barcode detection module configuration."}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"abstract":[{"type":"text","text":"Document library configuration."}],"title":"DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Document library module configuration."}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class","kind":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}