{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/description","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:7DotCore11ImageFormatO11descriptionSSvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","role":"symbol"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/imageformat\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"url":"\/documentation\/dotpalmcore\/imageformat","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","abstract":[{"type":"text","text":"Supported image formats."}],"type":"topic","kind":"symbol","title":"ImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/description","url":"\/documentation\/dotpalmcore\/imageformat\/description","kind":"symbol","title":"description","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]}]}]}