{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/defaultThreshold","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Default threshold.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator(cpy)defaultThreshold","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"defaultThreshold","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol","role":"symbol","title":"SharpnessTooLowValidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/defaultThreshold":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/defaultthreshold","abstract":[{"type":"text","text":"Default threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/defaultThreshold","title":"defaultThreshold","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFGSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle"},{"value":"defaultThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1defaultThreshold\/title","op":"replace"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1defaultThreshold\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}