{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"x"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(im)initWithX:y:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"init(x:y:)"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble\/init(x:y:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/pointdouble\/init(x:y:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/pointdouble\/init(x:y:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotfacecore\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","kind":"symbol","type":"topic","title":"PointDouble"},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble/init(x:y:)":{"type":"topic","url":"\/documentation\/dotfacecore\/pointdouble\/init(x:y:)","navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"title":"init(x:y:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble\/init(x:y:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"y"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.14.1"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithX:y:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithX:y:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithX:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"x"},{"kind":"text","text":" "},{"text":"y:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"y","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments","op":"replace"},{"value":"initWithX:y:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble~1init(x:y:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble~1init(x:y:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithX:y:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}