{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"kind":"text","text":" "},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","text":"DOTFQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttributeThresholds","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":" *) "},{"text":"query","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cameraFacing","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"kind":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"type":"topic","kind":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFQualityAttributeThresholds":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfqualityattributethresholds","type":"topic","abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"kind":"identifier","text":"DOTFQualityAttributeThresholds"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","title":"DOTFQualityAttributeThresholds","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","type":"topic","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"IntervalDouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"kind":"symbol","fragments":[{"text":"DOTFFaceAutoCaptureConfiguration","kind":"identifier"}],"type":"topic","title":"DOTFFaceAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}