{"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"mouthLeftCorner","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthLeftCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mouthLeftCorner"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)mouthLeftCorner","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthLeftCorner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"text":"Left corner of the mouth.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLeftCorner","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthleftcorner"]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthleftcorner"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthLeftCorner":{"url":"\/documentation\/dotfacecore\/facekeypoints\/mouthleftcorner","abstract":[{"type":"text","text":"Left corner of the mouth."}],"title":"mouthLeftCorner","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthLeftCorner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLeftCorner","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mouthLeftCorner"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoint"}],"abstract":[{"type":"text","text":"Face Keypoint"}],"url":"\/documentation\/dotfacecore\/facekeypoint","title":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"url":"\/documentation\/dotfacecore\/facekeypoints","title":"FaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mouthLeftCorner","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"mouthLeftCorner"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mouthLeftCorner"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"mouthLeftCorner","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLeftCorner\/title"},{"value":[{"kind":"identifier","text":"mouthLeftCorner"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLeftCorner\/fragments"},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}