{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV11captureMode0aF00fL0OvpZ","role":"symbol","symbolKind":"property","roleHeading":"Type Property","title":"captureMode","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"modules":[{"name":"DotFaceLite"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"type":"topic","abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","title":"BaseFaceAutoCaptureViewController"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","url":"\/documentation\/dotfacelite\/capturemode","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"abstract":[],"title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults/captureMode":{"type":"topic","kind":"symbol","role":"symbol","title":"captureMode","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"CaptureMode"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"title":"BaseFaceAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","value":"DOTFLBaseFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCaptureMode"}]}]}]}