{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrrawimage(cgimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrrawimage(cgimage:)"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(cgImage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"cgImage"}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgrRawImageWithCgImage:","navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"title":"createBgrRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"title":"ImageFactory","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/imagefactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgrRawImage(cgImage:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(cgImage:)","url":"\/documentation\/dotfacecore\/imagefactory\/createbgrrawimage(cgimage:)","navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"type":"topic","title":"createBgrRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgrRawImageWithCgImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"},{"text":"(","kind":"text"},{"text":"CGImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/title"},{"value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/fragments"},{"value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}]}]}]}