{"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:query:facesizeratiointerval:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"},{"kind":"text","text":", "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(sessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds5query21faceSizeRatioInterval23isDetectionLayerVisible0S12TorchEnabled12cameraFacing0Y16PreviewScaleTypeAESSSg_AE07QualitylM0CAA0bT5QueryCAA0R6DoubleCS2bAA06CameraZ0OAA22CameraPreviewScaleTypeOtcfc","roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":" = QualityAttributeThresholdPresets.standard.build(), ","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"text":"IntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" = Defaults.faceSizeRatioInterval, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","text":"CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":" = Defaults.cameraPreviewScaleType)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","title":"init(sessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":", ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:query:facesizeratiointerval:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","type":"topic","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic","title":"FaceAutoCaptureViewController.Configuration","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.1.0","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","title":"FaceDetectionQuery","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","title":"CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"}]}]}