{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistate\/init"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiState(im)init","symbolKind":"method","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiState\/init","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"kind":"symbol","title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiState/init":{"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistate\/init","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiState\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureUiState","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle"}]}]}