{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/expressionneutral"]}],"metadata":{"title":"expressionNeutral","role":"symbol","fragments":[{"kind":"identifier","text":"expressionNeutral"}],"navigatorTitle":[{"text":"expressionNeutral","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)expressionNeutral","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/expressionNeutral","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceExpressionNeutralModuleConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}],"title":"DotFaceExpressionNeutralModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules":{"title":"DotFaceLibraryConfigurationModules","type":"topic","abstract":[{"text":"Face library module configuration.","type":"text"}],"role":"symbol","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules/expressionNeutral":{"title":"expressionNeutral","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"expressionNeutral","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/expressionNeutral","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/expressionneutral"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}