{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/eyegazeliveness"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","interfaceLanguage":"occ"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)eyeGazeLiveness","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLiveness"}],"title":"eyeGazeLiveness","roleHeading":"Instance Property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules/eyeGazeLiveness":{"url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/eyegazeliveness","abstract":[],"fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","role":"symbol","type":"topic","title":"eyeGazeLiveness"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules":{"role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","abstract":[{"text":"Face library module configuration.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration","type":"topic","kind":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace"}]}]}