{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/verification","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"verification"},{"kind":"text","text":";"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"verification","role":"symbol","navigatorTitle":[{"text":"verification","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"verification","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)verification"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/verification"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules","abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration","title":"DotFaceVerificationModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration","abstract":[{"type":"text","text":"Face verification module."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules/verification":{"url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/verification","fragments":[{"text":"verification","kind":"identifier"}],"kind":"symbol","title":"verification","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/verification","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}