{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"passiveLiveness","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15passiveLivenessAA0ac7Passiveh6ModuleE0CSgvp","role":"symbol","modules":[{"name":"DotFaceLite"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class","type":"topic","role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"abstract":[{"text":"Face library module configuration.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face passive liveness module."}],"title":"DotFacePassiveLivenessModuleConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class/passiveLiveness":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"title":"passiveLiveness"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","type":"topic","abstract":[{"type":"text","text":"Face library configuration."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFacePassiveLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title"},{"value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle"}]}]}