{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Default is:","type":"text"}],"type":"paragraph"},{"syntax":null,"code":[".init(cameraFacing: .front)"],"type":"codeListing"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/camera"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC6camera0A7Capture06CameraI0Cvp","title":"camera","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"url":"\/documentation\/dotfacelite\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/camera":{"type":"topic","title":"camera","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/camera","role":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"title":"MultiRangeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"MultiRangeLivenessViewController.Configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTFLMultiRangeLivenessViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace"}]}]}