{"sections":[],"abstract":[{"text":"List of Multi-Range challenge items. This list represents a liveness challenge and should be obtained from the DIS (Digital Identity Service). The minimum number of items is 4.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC17challengeSequenceSay0aB7Commons0deF13ChallengeItemO7WrappedCGvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeSequence","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","title":"challengeSequence","modules":[{"name":"DotFaceLite"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeSequence","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/challengesequence"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/challengeSequence"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/challengeSequence":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"List of Multi-Range challenge items. This list represents a liveness challenge and should be obtained from the DIS (Digital Identity Service). The minimum number of items is 4."}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/challengesequence","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeSequence","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/challengeSequence","title":"challengeSequence","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"type":"topic","abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}],"kind":"symbol","title":"MultiRangeLivenessChallengeItem","role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"type":"topic","role":"symbol","title":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","kind":"symbol","abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","title":"MultiRangeLivenessViewController.Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.Wrapped","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItem"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/navigatorTitle","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]}]}]}