{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(sessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)"},"metadata":{"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC12sessionToken17challengeSequence23isDetectionLayerVisible0N12TorchEnabled0n12VideoCaptureS012cameraFacing0V16PreviewScaleType0n6CameraxQ0AESSSg_Say0aB7Commons0deF13ChallengeItemO7WrappedCGS3b0A6Camera06CameraW0OAU06CameraxyZ0OSbtKcfc","role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"challengeSequence"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MultiRangeLivenessChallengeItem","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotFaceLite"}],"title":"init(sessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"sections":[],"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:challengesequence:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"challengeSequence"},{"kind":"text","text":": ["},{"text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isVideoCaptureEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = Defaults.isCameraPreviewVisible) ","kind":"text"},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for Multi-Range Liveness evaluation.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"title":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/init(sessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(sessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","title":"init(sessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"challengeSequence"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC"},{"kind":"text","text":"], "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:challengesequence:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)","abstract":[{"text":"Create the Multi-Range Liveness configuration.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the Multi-Range Liveness process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","type":"topic","title":"MultiRangeLivenessViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","type":"topic","title":"CameraFacing","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacelite\/camerafacing"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped":{"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Wrapped","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.Wrapped","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"kind":"symbol","type":"topic","title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItem"},{"value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"}]}]}