{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden\/hash","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/placeholder\/hidden\/hash"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:14DotFingersCore11PlaceholderC6HiddenC4hashSivp","title":"hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Hidden":{"url":"\/documentation\/dotfingerscore\/placeholder\/hidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Hidden"}],"title":"Placeholder.Hidden","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Hidden/hash":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden\/hash","title":"hash","url":"\/documentation\/dotfingerscore\/placeholder\/hidden\/hash","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"abstract":[{"type":"text","text":"Placeholder."}],"url":"\/documentation\/dotfingerscore\/placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFGPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title"},{"value":[{"text":"DOTFGPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments"},{"value":[{"text":"DOTFGPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}