{"variants":[{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"minValidSamplesInRowToStartCandidateSelection","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)minValidSamplesInRowToStartCandidateSelection"},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/minValidSamplesInRowToStartCandidateSelection":{"title":"minValidSamplesInRowToStartCandidateSelection","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection","abstract":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minValidSamplesInRowToStartCandidateSelection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/title","value":"minValidSamplesInRowToStartCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/fragments","value":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}