{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.failureReason","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"platforms":[{"introducedAt":"8.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"8.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"10.10","name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"2.0","name":"watchOS","unavailable":false,"deprecated":false,"beta":false}],"title":"failureReason","extendedModule":"Foundation","roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:6DotNfc22FlatTagStructureParserC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/failureReason","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/error\/failurereason"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"type":"topic","abstract":[{"text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse ","type":"text"},{"type":"codeVoice","code":"OptionalDetails.content"},{"text":" of some documents.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","role":"symbol","navigatorTitle":[{"text":"FlatTagStructureParser","kind":"identifier"}],"title":"FlatTagStructureParser","url":"\/documentation\/dotnfc\/flattagstructureparser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FlatTagStructureParser","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/failureReason":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/failureReason","abstract":[],"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/failurereason","title":"failureReason"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","url":"\/documentation\/dotnfc\/flattagstructureparser\/error","type":"topic","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","title":"FlatTagStructureParser.Error","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTNFlatTagStructureParser","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title"},{"op":"replace","value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments"},{"op":"replace","value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle"}]}]}