{"variants":[{"paths":["\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"palm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:fingers:","title":"init(document:face:faceLite:nfc:palm:fingers:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Libraries":{"url":"\/documentation\/dotdocument\/libraries","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}],"title":"Libraries"},"doc://DotDocument/documentation/DotDocument/Libraries/init(document:face:faceLite:nfc:palm:fingers:)":{"url":"\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:fingers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fingers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:fingers:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)","role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"init(document:face:faceLite:nfc:palm:fingers:)"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"type":"topic","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLibraryConfiguration"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLiteLibraryConfiguration":{"abstract":[{"text":"Face Lite library configuration.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/dotfacelitelibraryconfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DotNfcLibraryConfiguration":{"url":"\/documentation\/dotdocument\/dotnfclibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"NFC library configuration."}],"title":"DotNfcLibraryConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:fingers:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLite"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fingers"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:fingers:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/fragments"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceLiteLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}