{"abstract":[{"text":"Detect faces in an image.","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"detectWithImage:limit:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"]","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector(im)detectWithImage:limit:error:","symbolKind":"method","role":"symbol","title":"detect(image:limit:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Image used for the face detection. Terminates if "},{"type":"codeVoice","code":"image"},{"type":"text","text":" is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"paragraph"}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"Limit the number of faces to detect."}],"type":"paragraph"}],"name":"limit"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Array of detected faces.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"FaceDetector"},{"type":"text","text":" fails to execute face detection."}],"type":"paragraph"}],"name":"Throws","style":"note","type":"aside"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/detect(image:limit:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/detect(image:limit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facedetector\/detect(image:limit:)"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","title":"FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","title":"Image","url":"\/documentation\/dotfacelite\/image","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"navigatorTitle":[{"kind":"identifier","text":"Face"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","title":"FaceDetector.Face","url":"\/documentation\/dotfacelite\/facedetector\/face","abstract":[{"text":"Detected face.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/detect(image:limit:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotfacelite\/facedetector\/detect(image:limit:)","kind":"symbol","role":"symbol","title":"detect(image:limit:)","abstract":[{"text":"Detect faces in an image.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/detect(image:limit:)","navigatorTitle":[{"kind":"identifier","text":"detectWithImage:limit:error:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"detectWithImage:limit:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<DOTFLFaceDetectorFace *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"detectWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"limit"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image used for the face detection. Terminates if "},{"type":"codeVoice","code":"image"},{"type":"text","text":" is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}]}]},{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limit the number of faces to detect."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"Array of detected faces."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","op":"replace"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","op":"replace"},{"value":"detectWithImage:limit:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector~1detect(image:limit:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector~1detect(image:limit:)\/fragments","op":"replace"}]}]}