{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"abstract":[{"text":"Top left corner point.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/topleft"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":";","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/topLeft","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"role":"symbol","title":"topLeft","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(py)topLeft","roleHeading":"Instance Property","fragments":[{"text":"topLeft","kind":"identifier"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/topLeft":{"abstract":[{"text":"Top left corner point.","type":"text"}],"kind":"symbol","role":"symbol","title":"topLeft","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/topLeft","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/topleft","fragments":[{"kind":"identifier","text":"topLeft"}]},"doc://DotDocument/documentation/DotDocument/PointDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotdocument\/pointdouble"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTDBarcodeDetectionPosition"}],"type":"topic","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","title":"DOTDBarcodeDetectionPosition","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}