{"metadata":{"role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"detection"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)detection","title":"detection","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/detection"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules","type":"topic","title":"DotFingersLibraryConfigurationModules","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","title":"DotFingersDetectionModuleConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules/detection":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/detection","abstract":[],"title":"detection","url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/detection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}