{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transformation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transformation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:","roleHeading":"Instance Method","title":"initWithDetection:transformation:","symbolKind":"method","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","title":"initWithDetection:transformation:","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules","type":"topic","title":"DotFingersLibraryConfigurationModules","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersTransformationModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerstransformationmoduleconfiguration","type":"topic","title":"DotFingersTransformationModuleConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","title":"DotFingersDetectionModuleConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/navigatorTitle"},{"value":"DotFingersDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}]}]}