{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/transformation"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/transformation"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"transformation"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)transformation","modules":[{"name":"DotNfc"}],"title":"transformation","fragments":[{"kind":"identifier","text":"transformation"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules/transformation":{"url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules\/transformation","type":"topic","role":"symbol","abstract":[],"title":"transformation","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules\/transformation","kind":"symbol","fragments":[{"kind":"identifier","text":"transformation"}]},"doc://DotNfc/documentation/DotNfc/DotFingersTransformationModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerstransformationmoduleconfiguration","type":"topic","title":"DotFingersTransformationModuleConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules","type":"topic","title":"DotFingersLibraryConfigurationModules","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/title","op":"replace","value":"DotFingersTransformationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}]}]}