{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/faceSizeRatioInterval","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/facesizeratiointerval"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"},{"text":" * ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(py)faceSizeRatioInterval","navigatorTitle":[{"text":"faceSizeRatioInterval","kind":"identifier"}],"roleHeading":"Instance Property","title":"faceSizeRatioInterval","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"faceSizeRatioInterval","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is "},{"type":"text","text":"[0.1, 0.3]"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureConfiguration"}],"role":"symbol","title":"DOTFFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","kind":"symbol","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","title":"IntervalDouble","type":"topic","url":"\/documentation\/dotfacecore\/intervaldouble"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/faceSizeRatioInterval":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/facesizeratiointerval","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/faceSizeRatioInterval","role":"symbol","fragments":[{"text":"faceSizeRatioInterval","kind":"identifier"}],"title":"faceSizeRatioInterval","abstract":[{"text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is ","type":"text"},{"text":"[0.1, 0.3]","type":"text"},{"text":".","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}