{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttributeThresholds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minValidFramesInRowToStartCandidateSelection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"candidateSelectionDurationMillis","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"query:"},{"kind":"text","text":"("},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"query"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"kind":"text","text":"("},{"text":"DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"kind":"text","text":" "},{"text":"captureMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"DOTCaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"kind":"text","text":") "},{"text":"captureMode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isPlaceholderVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isPlaceholderVisible"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"DOTCameraFacing"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraPreviewVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocapture-6o7v8"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"symbol","title":"CameraFacing","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"title":"FaceDetectionQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocapture-6o7v8","title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFQualityAttributeThresholds":{"role":"symbol","kind":"symbol","title":"DOTFQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"type":"text","text":" "},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfqualityattributethresholds","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","fragments":[{"text":"DOTFQualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}],"role":"collection","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalDouble","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/capturemode","type":"topic","title":"CaptureMode"},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol","kind":"symbol","title":"CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration","fragments":[{"text":"DOTFFaceAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTFFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}