{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttributeThresholds","text":"DOTFQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"text":" ","kind":"text"},{"text":"captureMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCaptureMode","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","text":"DOTCaptureMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"captureMode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaceholderVisible:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isPlaceholderVisible"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"text":";","kind":"text"}]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"type":"topic","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"title":"FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"title":"CameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol","title":"IntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFQualityAttributeThresholds":{"abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","role":"symbol","url":"\/documentation\/dotfacecore\/dotfqualityattributethresholds","fragments":[{"text":"DOTFQualityAttributeThresholds","kind":"identifier"}],"title":"DOTFQualityAttributeThresholds","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration","fragments":[{"text":"DOTFFaceAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTFFaceAutoCaptureConfiguration","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.2.0","type":"text"}],"role":"collection","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode":{"abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotfacecore\/capturemode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"kind":"symbol","title":"CaptureMode"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","type":"topic","url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing"}},"variantOverrides":[{"patch":[{"op":"replace","value":"FaceDetectionQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}