{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttributeThresholds","text":"DOTFQualityAttributeThresholds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureMode:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTCaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode"},{"kind":"text","text":") "},{"text":"captureMode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaceholderVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isPlaceholderVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","interfaceLanguage":"occ"},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}]},"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","url":"\/documentation\/dotfacecore\/camerafacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}],"title":"FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facedetectionquery"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","fragments":[{"text":"DOTFFaceAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTFFaceAutoCaptureConfiguration","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"abstract":[{"type":"text","text":"Capture mode."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","url":"\/documentation\/dotfacecore\/capturemode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFQualityAttributeThresholds":{"fragments":[{"text":"DOTFQualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFQualityAttributeThresholds","title":"DOTFQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfqualityattributethresholds"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:":{"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:query:facesizeratiointerval:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:","title":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:query:faceSizeRatioInterval:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"url":"\/documentation\/dotfacecore\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"}},"variantOverrides":[{"patch":[{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}