{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/origin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/origin"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/origin","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)origin","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier","text":"PointInt"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"role":"symbol","title":"origin","extendedModule":"DotCore"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt":{"type":"topic","title":"PointInt","url":"\/documentation\/dotfacecore\/pointint","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt":{"url":"\/documentation\/dotfacecore\/rectangleint","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"type":"topic","title":"RectangleInt"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/origin":{"navigatorTitle":[{"text":"origin","kind":"identifier"}],"title":"origin","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/origin","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/rectangleint\/origin"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"origin","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"origin"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"DOTPointInt","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt"},{"text":" * ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/navigatorTitle"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/navigatorTitle"},{"op":"replace","value":"origin","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1origin\/title"},{"op":"replace","value":[{"kind":"identifier","text":"origin"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1origin\/fragments"}]}]}