{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/bundle","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLocalization(cpy)bundle","title":"bundle","navigatorTitle":[{"text":"bundle","kind":"identifier"}],"roleHeading":"Type Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/localization\/bundle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/localization\/bundle"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Localization/bundle":{"type":"topic","abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"title":"bundle","url":"\/documentation\/dotfingerscore\/localization\/bundle","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/bundle","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"navigatorTitle":[{"text":"bundle","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/Localization":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfingerscore\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","title":"Localization","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","value":"bundle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"bundle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":" * ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1bundle\/title","value":"bundle"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1bundle\/fragments","value":[{"text":"bundle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/title","value":"DOTFGLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/fragments","value":[{"text":"DOTFGLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/navigatorTitle","value":[{"text":"DOTFGLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}