{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/useLocalizationDictionary","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"useLocalizationDictionary","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLocalization(cpy)useLocalizationDictionary","navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"roleHeading":"Type Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"abstract":[{"text":"If you set this to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", ","type":"text"},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/Localization/useLocalizationDictionary":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/localization\/uselocalizationdictionary","abstract":[{"text":"If you set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/useLocalizationDictionary","title":"useLocalizationDictionary","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Localization":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfingerscore\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","title":"Localization","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"useLocalizationDictionary","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"useLocalizationDictionary","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1useLocalizationDictionary\/title"},{"op":"replace","value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1useLocalizationDictionary\/fragments"},{"op":"replace","value":"DOTFGLocalization","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGLocalization"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGLocalization"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}