{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/init(configuration:style:)"},"sections":[],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"FaceAutoCaptureViewController"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/init(configuration:style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/init(configuration:style:)"]}],"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC5StyleC","text":"Style"},{"kind":"text","text":")"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController(im)initWithConfiguration:style:","role":"symbol","title":"init(configuration:style:)","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":" = .init(), "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Style-swift.class","text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC5StyleC"},{"text":" = .init())","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Configure the face auto capture process.","type":"text"}]}],"name":"configuration"},{"name":"style","content":[{"inlineContent":[{"text":"Customize user interface.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New instance of ","type":"text"},{"type":"codeVoice","code":"FaceAutoCaptureViewController"},{"type":"text","text":"."}]}],"kind":"content"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Style-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Style-swift.class","navigatorTitle":[{"kind":"identifier","text":"Style"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the face auto capture user interface.","type":"text"}],"title":"FaceAutoCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"role":"symbol","title":"DOTFLFaceAutoCaptureConfiguration","type":"topic","fragments":[{"text":"DOTFLFaceAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureStyle":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureStyle","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturestyle","abstract":[{"type":"text","text":"Customization options for the face auto capture user interface."}],"kind":"symbol","title":"DOTFLFaceAutoCaptureStyle","fragments":[{"text":"DOTFLFaceAutoCaptureStyle","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.11.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/init(configuration:style:)":{"abstract":[{"text":"Create new ","type":"text"},{"code":"FaceAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(configuration:style:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/init(configuration:style:)","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/init(configuration:style:)","kind":"symbol","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","type":"topic","title":"FaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","type":"topic","title":"FaceAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithConfiguration:style:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureStyle","text":"DOTFLFaceAutoCaptureStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureStyle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":";","kind":"text"}]}]}},{"value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1init(configuration:style:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1init(configuration:style:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]}]}]}