{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles\/init(pitch:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/tiltangles\/init(pitch:)"]},{"paths":["\/documentation\/dotpalmcore\/tiltangles\/init(pitch:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}]}]}],"kind":"symbol","metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(im)initWithPitch:","title":"init(pitch:)","role":"symbol","navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}]},"references":{"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotPalmCore/documentation/DotPalmCore/TiltAngles":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles","kind":"symbol","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}],"url":"\/documentation\/dotpalmcore\/tiltangles","abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"title":"TiltAngles"},"doc://DotPalmCore/documentation/DotPalmCore/TiltAngles/init(pitch:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles\/init(pitch:)","kind":"symbol","navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dotpalmcore\/tiltangles\/init(pitch:)","abstract":[],"title":"init(pitch:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithPitch:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pitch"},{"text":";","kind":"text"}]}]}},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/title"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles~1init(pitch:)\/title","op":"replace","value":"initWithPitch:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles~1init(pitch:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}]}]}]}