{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/fromRectangle:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/fromrectangle:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition","text":"DOTDBarcodeDetectionPosition","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"},{"text":" *) ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":" *) ","kind":"text"},{"text":"rectangle","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"metadata":{"title":"fromRectangle:","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(cm)fromRectangle:","roleHeading":"Type Method","modules":[{"name":"DotDocument"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}],"symbolKind":"method"},"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"url":"\/documentation\/dotdocument\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","title":"RectangleDouble","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/fromRectangle:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/fromRectangle:","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/fromrectangle:","kind":"symbol","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}],"role":"symbol","title":"fromRectangle:","abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","role":"symbol","kind":"symbol","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]}]}]}