{"sections":[],"abstract":[{"type":"text","text":"Image size."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Image"]]},"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"size"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage(py)size","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"roleHeading":"Instance Property","role":"symbol","title":"size","modules":[{"name":"DotDocument"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"ImageSize"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/image\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/image\/size"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/size"},"references":{"doc://DotDocument/documentation/DotDocument/Image/size":{"type":"topic","url":"\/documentation\/dotdocument\/image\/size","abstract":[{"type":"text","text":"Image size."}],"kind":"symbol","title":"size","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/size","navigatorTitle":[{"kind":"identifier","text":"size"}]},"doc://DotDocument/documentation/DotDocument/ImageSize":{"abstract":[{"text":"Image size in pixels.","type":"text"}],"url":"\/documentation\/dotdocument\/imagesize","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"url":"\/documentation\/dotdocument\/image","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"type":"topic","kind":"symbol","title":"Image","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"size"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"DOTImageSize","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"size","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}