{"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"platforms":[],"navigatorTitle":[{"text":"faceSimpleCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"required":true,"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate(im)faceSimpleCaptureViewControllerNoCameraPermission:","title":"faceSimpleCaptureViewControllerNoCameraPermission(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollernocamerapermission(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollernocamerapermission(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerNoCameraPermission(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"kind":"symbol","title":"FaceSimpleCaptureViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"abstract":[{"text":"Implement this delegate to handle the face simple capture events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"deprecated":true,"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.7.1","type":"text"}],"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing face images."}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","title":"FaceSimpleCaptureViewController","kind":"symbol","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerNoCameraPermission(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"faceSimpleCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"required":true,"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceSimpleCaptureViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"title":"faceSimpleCaptureViewControllerNoCameraPermission(_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerNoCameraPermission(_:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollernocamerapermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"faceSimpleCaptureViewControllerNoCameraPermission:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"faceSimpleCaptureViewControllerNoCameraPermission:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title","op":"replace","value":"DOTFFaceSimpleCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerNoCameraPermission(_:)\/title","op":"replace","value":"faceSimpleCaptureViewControllerNoCameraPermission:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerNoCameraPermission(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"faceSimpleCaptureViewControllerNoCameraPermission:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}