{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/isEqual(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(im)isEqual:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat"]]},"variants":[{"paths":["\/documentation\/dotdocument\/intervalfloat\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/intervalfloat\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotdocument\/intervalfloat","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/IntervalFloat/isEqual(_:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","url":"\/documentation\/dotdocument\/intervalfloat\/isequal(_:)","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}