{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/brightnessInterval","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC18brightnessInterval0aC00M6DoubleCSgvp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"brightnessInterval","symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/brightnessinterval"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Valid interval of brightness of the detected face.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents low brightness."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high brightness."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/brightnessInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/brightnessInterval","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Valid interval of brightness of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low brightness."},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents high brightness.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":": "},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/brightnessinterval","role":"symbol","title":"brightnessInterval"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","title":"IntervalDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}]}]}