{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdk\/error\/failedtoloadlibrary(libraryid:)"]}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":")","kind":"text"}],"role":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","externalID":"s:7DotCore0A3SdkC5ErrorO19failedToLoadLibraryyAeA0aH2IdO_tcAEmF","modules":[{"name":"DotPalmCore"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedToLoadLibrary"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error/failedToLoadLibrary(libraryId:)":{"url":"\/documentation\/dotpalmcore\/dotsdk\/error\/failedtoloadlibrary(libraryid:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":")","kind":"text"}],"kind":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"kind":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotsdk","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","title":"DotSdk"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotpalmcore\/dotsdk\/error","title":"DotSdk.Error","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"role":"symbol","title":"DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/navigatorTitle"}]}]}