{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/brightnessinterval(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC18brightnessIntervalyAI0aC00N6DoubleCSgKF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brightnessInterval"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"brightnessInterval(_:)","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"brightnessInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","title":"FaceAutoCaptureViewController.Configuration","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"kind":"symbol","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","title":"FaceAutoCaptureViewController","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds.Builder","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Builder","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Builder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","title":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder/brightnessInterval(_:)":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/brightnessinterval(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)","title":"brightnessInterval(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}