{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionPosition"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","kind":"typeIdentifier","text":"ImageParameters"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","title":"init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)","externalID":"s:11DotDocument0B8DetectorC0B0C17detectionPosition10confidence18widthToHeightRatio15imageParametersAeA09DetectionE0C_S2dAA05ImageL0Ctcfc","roleHeading":"Initializer","modules":[{"name":"DotDocument"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"ImageParameters","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/document\/init(detectionposition:confidence:widthtoheightratio:imageparameters:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","title":"DocumentDetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Document"}],"navigatorTitle":[{"text":"Document","kind":"identifier"}],"role":"symbol","title":"DocumentDetector.Document"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","title":"ImageParameters","url":"\/documentation\/dotdocument\/imageparameters","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)","url":"\/documentation\/dotdocument\/documentdetector\/document\/init(detectionposition:confidence:widthtoheightratio:imageparameters:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"detectionPosition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageParameters"},{"text":": ","kind":"text"},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"},{"kind":"text","text":")"}],"role":"symbol","title":"init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the document card in the image."}],"role":"symbol","url":"\/documentation\/dotdocument\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace"}]}]}