{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Temporary property for liveness evaluation on DIS. It will be replaced by binary content.","type":"text"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileExpressionBgrRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionbgrrawimage"]},{"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionbgrrawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionBgrRawImage","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"smileExpressionBgrRawImage"}],"title":"smileExpressionBgrRawImage","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessResult(py)smileExpressionBgrRawImage","platforms":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileExpressionBgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"abstract":[{"type":"text","text":"Smile expression face image."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.12.1"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/smileExpressionBgrRawImage":{"navigatorTitle":[{"text":"smileExpressionBgrRawImage","kind":"identifier"}],"title":"smileExpressionBgrRawImage","deprecated":true,"url":"\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionbgrrawimage","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionBgrRawImage","abstract":[{"type":"text","text":"Smile expression face image."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileExpressionBgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult":{"navigatorTitle":[{"text":"SmileLivenessResult","kind":"identifier"}],"title":"SmileLivenessResult","url":"\/documentation\/dotfacecore\/smilelivenessresult","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult","abstract":[{"type":"text","text":"The result of smile liveness process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessResult"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","title":"SmileLivenessViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","role":"symbol","url":"\/documentation\/dotfacecore\/bgrrawimage","title":"BgrRawImage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"smileExpressionBgrRawImage","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"smileExpressionBgrRawImage"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"smileExpressionBgrRawImage","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionBgrRawImage\/title","value":"smileExpressionBgrRawImage","op":"replace"},{"value":[{"kind":"identifier","text":"smileExpressionBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionBgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/title","op":"replace","value":"DOTFSmileLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessResult"}]},{"value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}