{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/hashValue"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotpalmmoduleid\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId"]]},"metadata":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","role":"symbol","title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"modules":[{"relatedModules":["Swift"],"name":"DotFingersCore"}],"extendedModule":"Swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId":{"role":"symbol","title":"DotPalmModuleId","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/hashValue":{"role":"symbol","title":"hashValue","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/hashvalue","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/hashValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}]}]}