{"kind":"symbol","metadata":{"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"symbolKind":"method","modules":[{"name":"DotDocument"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:ciContext:","title":"create(bgraRawImage:ciContext:)"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:ciContext:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}]}],"name":"bgraRawImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}],"name":"ciContext"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:cicontext:)"]},{"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","type":"topic","title":"CIImageFactory","url":"\/documentation\/dotdocument\/ciimagefactory","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory/create(bgraRawImage:ciContext:)":{"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:ciContext:)","type":"topic","title":"create(bgraRawImage:ciContext:)","url":"\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:cicontext:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"createWithBgraRawImage:ciContext:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ciContext","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"value":"createWithBgraRawImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:ciContext:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}]},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]}]}]}