{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/sizeinterval(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","title":"sizeInterval(_:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC12sizeIntervalyAE0aC00K6DoubleCSgKF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/intervaldouble","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/sizeInterval(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"title":"sizeInterval(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/sizeinterval(_:)","kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","role":"symbol","title":"PalmAutoCaptureQualityAttributeThresholds"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder":{"title":"PalmAutoCaptureQualityAttributeThresholds.Builder","kind":"symbol","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle"},{"value":"DOTPPalmAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle"}]}]}