{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/init(data:chip:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","text":"DataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"},{"text":", ","kind":"text"},{"text":"chip","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"init(data:chip:)","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus(im)initWithData:chip:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","text":"DataAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"ChipAuthenticationStatus"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithData:chip:","kind":"identifier"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/authenticationstatus\/init(data:chip:)"]},{"paths":["\/documentation\/dotnfc\/authenticationstatus\/init(data:chip:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus","type":"topic","title":"DataAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"title":"ChipAuthenticationStatus","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.4.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationStatus"}],"type":"topic","title":"AuthenticationStatus","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"url":"\/documentation\/dotnfc\/authenticationstatus"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/init(data:chip:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithData:chip:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/init(data:chip:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","text":"DataAuthenticationStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"ChipAuthenticationStatus"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/authenticationstatus\/init(data:chip:)","abstract":[],"title":"init(data:chip:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithData:chip:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:chip:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","text":"DOTNDataAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"chip:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","text":"DOTNChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"chip"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","value":"DOTNDataAuthenticationStatus","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments"},{"value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus","op":"replace"},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle"},{"op":"replace","value":"DOTNAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1init(data:chip:)\/title","value":"initWithData:chip:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1init(data:chip:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:chip:"}],"op":"replace"}]}]}