{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:cornerRadius:","role":"symbol","title":"createDetectionPath(corners:cornerRadius:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Corners":{"title":"Corners","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","abstract":[{"type":"text","text":"Four detected corners in an image."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"type":"topic","url":"\/documentation\/dotfacecore\/corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"url":"\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","role":"symbol","title":"createDetectionPath(corners:cornerRadius:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory":{"abstract":[],"role":"symbol","title":"BezierPathFactory","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory","url":"\/documentation\/dotfacecore\/bezierpathfactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createDetectionPathWithCorners:cornerRadius:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createDetectionPathWithCorners:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"DOTCorners"},{"text":" *) ","kind":"text"},{"text":"corners","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cornerRadius:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cornerRadius"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCorners","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Corners\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace"},{"value":"createDetectionPathWithCorners:cornerRadius:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"op":"replace"},{"value":"DOTBezierPathFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace"}]}]}