{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","text":"Corners"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"title":"createDetectionPath(corners:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Corners":{"role":"symbol","title":"Corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotfacecore\/corners"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory/createDetectionPath(corners:)":{"role":"symbol","title":"createDetectionPath(corners:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:"}],"url":"\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory":{"role":"symbol","title":"BezierPathFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"url":"\/documentation\/dotfacecore\/bezierpathfactory"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createDetectionPathWithCorners:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDetectionPathWithCorners:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createDetectionPathWithCorners:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","text":"DOTCorners"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"corners"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:)\/title","value":"createDetectionPathWithCorners:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDetectionPathWithCorners:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/title","value":"DOTBezierPathFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/fragments","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}