{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/tiltangles\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/tiltangles\/description"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"description","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(py)description","navigatorTitle":[{"text":"description","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","title":"TiltAngles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/tiltangles","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles/description":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/description","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/tiltangles\/description","type":"topic","role":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}