{"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(im)initWithPitch:","navigatorTitle":[{"kind":"identifier","text":"initWithPitch:"}],"role":"symbol","roleHeading":"Initializer","title":"init(pitch:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/init(pitch:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/tiltangles\/init(pitch:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/tiltangles\/init(pitch:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","type":"topic","title":"TiltAngles","url":"\/documentation\/dotfacecore\/tiltangles","role":"symbol","abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}]},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles/init(pitch:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/init(pitch:)","navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/tiltangles\/init(pitch:)","role":"symbol","title":"init(pitch:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithPitch:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPitch:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"pitch"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1init(pitch:)\/title","value":"initWithPitch:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1init(pitch:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}]}]}]}