{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/mrzvalidation\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/none"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/none","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"]]},"metadata":{"title":"MrzValidation.none","symbolKind":"case","navigatorTitle":[{"text":"DOTDMrzValidationNone","kind":"identifier"}],"externalID":"c:@M@DotDocument@E@DOTDMrzValidation@DOTDMrzValidationNone","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","modules":[{"name":"DotDocument"}]},"abstract":[{"type":"text","text":"MRZ is not validated."}],"references":{"doc://DotDocument/documentation/DotDocument/MrzValidation/none":{"type":"topic","kind":"symbol","title":"MrzValidation.none","url":"\/documentation\/dotdocument\/mrzvalidation\/none","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationNone"}],"abstract":[{"type":"text","text":"MRZ is not validated."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"title":"MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzValidation"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzvalidation","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTDMrzValidationNone","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTDMrzValidationNone"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTDMrzValidationNone"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1none\/title","value":"DOTDMrzValidationNone"},{"value":[{"text":"DOTDMrzValidationNone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1none\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","op":"replace","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidation"}]}]}]}