{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerNoCameraPermission(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollernocamerapermission(_:)"]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollernocamerapermission(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate(im)smileLivenessViewControllerNoCameraPermission:","navigatorTitle":[{"text":"smileLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"smileLivenessViewControllerNoCameraPermission(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","kind":"symbol","title":"SmileLivenessViewControllerDelegate","role":"symbol","abstract":[{"text":"Implement this delegate to the handle smile liveness events.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"title":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerNoCameraPermission(_:)":{"navigatorTitle":[{"text":"smileLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerNoCameraPermission(_:)","kind":"symbol","title":"smileLivenessViewControllerNoCameraPermission(_:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"smileLivenessViewControllerNoCameraPermission","kind":"identifier"},{"kind":"text","text":"("},{"text":"SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollernocamerapermission(_:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"text":"version: 8.13.0","type":"text"}],"role":"collection","type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"smileLivenessViewControllerNoCameraPermission:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTFSmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFSmileLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}]},{"value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"smileLivenessViewControllerNoCameraPermission:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerNoCameraPermission(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerNoCameraPermission(_:)\/fragments","op":"replace"}]}]}