{"metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate(im)smileLivenessViewControllerViewWillTransition:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"smileLivenessViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"smileLivenessViewControllerViewWillTransition:","kind":"identifier"}],"title":"smileLivenessViewControllerViewWillTransition(_:)","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerViewWillTransition"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"typeIdentifier","text":"SmileLivenessViewController"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillTransition(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwilltransition(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwilltransition(_:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"navigatorTitle":[{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","abstract":[{"text":"Implement this delegate to the handle smile liveness events.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"type":"topic","title":"SmileLivenessViewControllerDelegate"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"type":"topic","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewWillTransition(_:)":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillTransition(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwilltransition(_:)","title":"smileLivenessViewControllerViewWillTransition(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"smileLivenessViewControllerViewWillTransition:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"smileLivenessViewControllerViewWillTransition:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"smileLivenessViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"smileLivenessViewControllerViewWillTransition:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"typeIdentifier","text":"DOTFSmileLivenessViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFSmileLivenessViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillTransition(_:)\/title","value":"smileLivenessViewControllerViewWillTransition:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"smileLivenessViewControllerViewWillTransition:","kind":"identifier"}]}]}]}