{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)"]}],"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessLiteViewControllerViewDidAppear:","title":"magnifEyeLivenessViewControllerViewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(magnifEyeLivenessLiteViewControllerViewDidAppear:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","type":"topic","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"kind":"symbol","title":"MagnifEyeLivenessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidAppear(_:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)","type":"topic","abstract":[],"kind":"symbol","title":"magnifEyeLivenessViewControllerViewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"magnifEyeLivenessLiteViewControllerViewDidAppear:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFLMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFLMagnifEyeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewDidAppear:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewDidAppear:"}]}]}]}