{"abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNChipAuthenticationStatus) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationStatus","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"],"generated":true,"title":"NFC protocols"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus"]},{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:activeAuthenticationResponse:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/activeAuthenticationResponse","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/authenticationProtocol-swift.property","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/status-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/isEqual(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"platforms":[{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false}],"title":"ChipAuthenticationStatus","symbolKind":"class","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}]},"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus","title":"DataAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/hash":{"kind":"symbol","title":"hash","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/hash","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/isEqual(_:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/isequal(_:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/status-swift.property":{"title":"status","type":"topic","abstract":[{"type":"text","text":"Status of the authentication process."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/status-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.property"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"url":"\/documentation\/dotnfc\/authenticationstatus","title":"AuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","title":"ChipAuthenticationStatus.WrappedProtocol","role":"symbol","type":"topic","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"code":"AuthenticationProtocol","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol","navigatorTitle":[{"text":"WrappedProtocol","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"symbol","title":"ChipAuthenticationStatus","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationStatus","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/description":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/description","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","role":"symbol","kind":"symbol","abstract":[{"text":"Access Control protocol.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","title":"AccessControlProtocol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccessControlProtocol"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","kind":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationProtocol","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"title":"ChipAuthenticationStatus.Status","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","abstract":[{"text":"Authentication status of the chip.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"navigatorTitle":[{"kind":"identifier","text":"Status"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/authenticationProtocol-swift.property":{"kind":"symbol","abstract":[{"type":"text","text":"Protocol used for that purpose."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.property","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/authenticationProtocol-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationProtocol"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","text":"WrappedProtocol","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationProtocol"}],"title":"authenticationProtocol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/activeAuthenticationResponse":{"kind":"symbol","title":"activeAuthenticationResponse","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/activeauthenticationresponse","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/activeAuthenticationResponse","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationResponse"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"activeAuthenticationResponse"}],"abstract":[{"type":"text","text":"The Active Authentication response (signature) is set only if explicit challenge "},{"code":"activeAuthenticationChallenge","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"NfcTravelDocumentReader.read","type":"codeVoice"},{"text":" operation was set by the caller and Active Authentication protocol is supported by the chip. Otherwise ","type":"text"},{"code":"activeAuthenticationResponse","type":"codeVoice"},{"text":" is nil.","type":"text"}]},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/init(status:wrappedProtocol:activeAuthenticationResponse:)":{"kind":"symbol","title":"init(status:wrappedProtocol:activeAuthenticationResponse:)","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:activeauthenticationresponse:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:activeAuthenticationResponse:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","text":"Status","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedProtocol"},{"kind":"text","text":": "},{"text":"WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"activeAuthenticationResponse","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTNChipAuthenticationStatus"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/activeAuthenticationResponse","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/authenticationProtocol-swift.property","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/status-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:activeAuthenticationResponse:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","value":[{"generated":true,"title":"NFC protocols","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"]}],"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTNChipAuthenticationStatus","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","value":"DOTNDataAuthenticationStatus","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1hash\/title","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"op":"replace","value":"status","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1status-swift.property\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1status-swift.property\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title","value":"DOTNAuthenticationStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1description\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace","value":"DOTNAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1authenticationProtocol-swift.property\/title","value":"authenticationProtocol"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1authenticationProtocol-swift.property\/fragments","value":[{"kind":"identifier","text":"authenticationProtocol"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1activeAuthenticationResponse\/title","value":"activeAuthenticationResponse"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1activeAuthenticationResponse\/fragments","value":[{"text":"activeAuthenticationResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:activeAuthenticationResponse:)\/title","value":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:activeAuthenticationResponse:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}