{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/init(displayedSignatureOrUsualMarkImage:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/displayedSignatureOrUsualMarkImage","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/isEqual(_:)"]}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"metadata":{"roleHeading":"Class","title":"DisplayedSignatureOrUsualMark","modules":[{"name":"DotNfc"}],"symbolKind":"class","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"role":"symbol"},"abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"seeAlsoSections":[{"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNDisplayedSignatureOrUsualMark) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark"]}],"sections":[],"references":{"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/isequal(_:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"title":"isEqual(_:)"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","title":"MachineReadableZoneInformation","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/displayedSignatureOrUsualMarkImage":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/displayedsignatureorusualmarkimage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/displayedSignatureOrUsualMarkImage","type":"topic","navigatorTitle":[{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Image of a signature of document holder."}],"role":"symbol","title":"displayedSignatureOrUsualMarkImage","kind":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/hash","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","abstract":[],"title":"hash"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/description":{"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/description","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/description"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/init(displayedSignatureOrUsualMarkImage:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/init(displayedsignatureorusualmarkimage:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"displayedSignatureOrUsualMarkImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"kind":"text","text":"?)"}],"title":"init(displayedSignatureOrUsualMarkImage:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithDisplayedSignatureOrUsualMarkImage:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/init(displayedSignatureOrUsualMarkImage:)"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","title":"DisplayedSignatureOrUsualMark","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","kind":"symbol","navigatorTitle":[{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}]},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"title":"AdditionalDocumentDetails","kind":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OptionalDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","title":"OptionalDetails","url":"\/documentation\/dotnfc\/optionaldetails","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"role":"symbol","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}]},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"title":"EncodedIdentificationFeaturesFace","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"role":"symbol","navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","role":"symbol","navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AdditionalPersonalDetails","url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTNDisplayedSignatureOrUsualMark","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/displayedSignatureOrUsualMarkImage","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/hash"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/init(displayedSignatureOrUsualMarkImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":[{"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1isEqual(_:)\/fragments"},{"value":"DOTNMachineReadableZoneInformation","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1displayedSignatureOrUsualMarkImage\/title","op":"replace","value":"displayedSignatureOrUsualMarkImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1displayedSignatureOrUsualMarkImage\/fragments","value":[{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"}],"op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1description\/title","value":"description"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1description\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1init(displayedSignatureOrUsualMarkImage:)\/title","value":"initWithDisplayedSignatureOrUsualMarkImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1init(displayedSignatureOrUsualMarkImage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDisplayedSignatureOrUsualMarkImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark"},{"value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments"},{"value":"DOTNAdditionalDocumentDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}],"op":"replace"},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","value":"DOTNOptionalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}]},{"value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace"}]}]}