{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullFrontalBgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/fullfrontalbgrrawimage"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"s:11DotFaceCore0B8DetectorC0B0C22fullFrontalBgrRawImage0aC00ghI0CSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullFrontalBgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":"?"}],"title":"fullFrontalBgrRawImage"},"abstract":[{"text":"ICAO full frontal face image. This is evaluated only if it is specified in ","type":"text"},{"code":"FaceDetectionQuery","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/fullFrontalBgrRawImage","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"title":"FaceDetector.Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","url":"\/documentation\/dotfacecore\/facedetector\/face","kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/fullFrontalBgrRawImage":{"url":"\/documentation\/dotfacecore\/facedetector\/face\/fullfrontalbgrrawimage","title":"fullFrontalBgrRawImage","kind":"symbol","abstract":[{"text":"ICAO full frontal face image. This is evaluated only if it is specified in ","type":"text"},{"type":"codeVoice","code":"FaceDetectionQuery"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/fullFrontalBgrRawImage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullFrontalBgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"url":"\/documentation\/dotfacecore\/bgrrawimage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]}]}]}