{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},{"text":" * ","kind":"text"},{"text":"detectionArea","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"property","title":"detectionArea","fragments":[{"text":"detectionArea","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerConfiguration(py)detectionArea","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"detectionArea"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/detectionArea","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/detectionarea"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration"]]},"abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the palm detection.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration/detectionArea":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/detectionArea","title":"detectionArea","abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the palm detection.","type":"text"}],"fragments":[{"kind":"identifier","text":"detectionArea"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/detectionarea","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","type":"topic","fragments":[{"text":"DOTPPalmAutoCaptureControllerConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration","title":"DOTPPalmAutoCaptureControllerConfiguration","abstract":[{"type":"text","text":"Configuration of the palm auto capture non-UI component."}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"patch":[{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}