{"sections":[],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"],"title":"Style and configuration"},{"title":"Delegate","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]},{"title":"MagnifEye liveness result","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/init(configuration:style:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/style-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"}],"seeAlsoSections":[{"generated":true,"title":"UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSCoding","doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/s8SendableP","doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFMagnifEyeLivenessViewController) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"role":"symbol","title":"DetectionPosition","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","title":"FaceAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://DotFaceCore/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIContentContainer"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"role":"symbol","title":"MagnifEyeLivenessViewControllerDelegate","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/style-swift.property":{"type":"topic","title":"style","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/style-swift.property","navigatorTitle":[{"text":"style","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC5StyleC","kind":"typeIdentifier"}],"abstract":[{"text":"Current style.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.property","role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewWillTransition(to:with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"role":"symbol","title":"viewWillTransition(to:with:)","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwilltransition(to:with:)","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)","kind":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/delegate":{"abstract":[{"type":"text","text":"Set this delegate to handle the MagnifEye liveness events."}],"title":"delegate","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate","text":"MagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/delegate"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewDidAppear(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewdidappear(_:)","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/configuration-swift.property":{"abstract":[{"text":"Current configuration.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.property","title":"configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/configuration-swift.property","role":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC","text":"Configuration"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/start()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/start()","title":"start()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Start the MagnifEye liveness process.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/start()","navigatorTitle":[{"text":"start","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","title":"MagnifEyeLivenessViewController","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","title":"SmileLivenessViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"type":"topic","title":"MagnifEyeLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewDidLoad()":{"type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewdidload()","title":"viewDidLoad()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLoad()","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://DotFaceCore/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessResult":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult","type":"topic","title":"MagnifEyeLivenessResult","kind":"symbol","abstract":[{"text":"The final result of the MagnifEye liveness process.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"type":"topic","abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"title":"FaceSimpleCaptureViewController","role":"symbol","kind":"symbol","deprecated":true},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://DotFaceCore/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/init(configuration:style:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/init(configuration:style:)","title":"init(configuration:style:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC5StyleC","kind":"typeIdentifier","text":"Style"},{"text":")","kind":"text"}],"abstract":[{"text":"Create new ","type":"text"},{"code":"MagnifEyeLivenessViewController","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.12.1"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewDidDisappear(_:)":{"title":"viewDidDisappear(_:)","type":"topic","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewdiddisappear(_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","title":"EyeGazeLivenessViewController","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturedetection","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"title":"FaceAutoCaptureDetection","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewDidLayoutSubviews()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewdidlayoutsubviews()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","title":"viewDidLayoutSubviews()"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Style-swift.class":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class","abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class","title":"MagnifEyeLivenessViewController.Style","navigatorTitle":[{"kind":"identifier","text":"Style"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewWillAppear(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","title":"viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwillappear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}]},"doc://DotFaceCore/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)UIViewController"},"doc://DotFaceCore/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer"},"doc://DotFaceCore/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting"},"doc://DotFaceCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s8SendableP"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewWillDisappear(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","title":"viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwilldisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)NSCoding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://DotFaceCore/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://DotFaceCore/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/stopAsync(onStopped:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","title":"stopAsync(onStopped:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onStopped","kind":"externalParam"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Stop the MagnifEye liveness process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/stopasync(onstopped:)","navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFMagnifEyeLivenessViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"],"title":"Delegate"},{"title":"MagnifEye liveness result","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/style-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/init(configuration:style:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)"]}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","op":"replace","value":"DOTDetectionPosition"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"style","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1style-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}]},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillTransition(to:with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillTransition(to:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1delegate\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidAppear(_:)\/title","op":"replace","value":"viewDidAppear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidAppear(_:)\/fragments","op":"replace"},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1configuration-swift.property\/title"},{"value":[{"text":"configuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1configuration-swift.property\/fragments"},{"value":"start","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1start()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1start()\/fragments","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"op":"replace"},{"value":"DOTFMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","op":"replace"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"value":"DOTFMagnifEyeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/title"},{"value":[{"text":"DOTFMagnifEyeLivenessResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/fragments","op":"replace"},{"op":"replace","value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}]},{"value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidDisappear(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidDisappear(_:)\/fragments"},{"value":"DOTFEyeGazeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection"},{"value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":"viewDidLayoutSubviews","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"value":"viewWillAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},{"op":"replace","value":"stopAsyncOnStopped:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1stopAsync(onStopped:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1stopAsync(onStopped:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopAsyncOnStopped:"}]}]}]}