{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg1MachineReadableZoneInformation"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Raw data group DG1."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg1MachineReadableZoneInformation"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg1machinereadablezoneinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg1machinereadablezoneinformation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dg1MachineReadableZoneInformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg1MachineReadableZoneInformation","modules":[{"name":"DotNfc"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dg1MachineReadableZoneInformation"}],"title":"dg1MachineReadableZoneInformation","symbolKind":"property"},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.6.1"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"type":"topic","title":"Lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg1MachineReadableZoneInformation":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg1MachineReadableZoneInformation","type":"topic","title":"dg1MachineReadableZoneInformation","abstract":[{"text":"Raw data group DG1.","type":"text"}],"navigatorTitle":[{"text":"dg1MachineReadableZoneInformation","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg1machinereadablezoneinformation","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dg1MachineReadableZoneInformation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1ElementaryFile"}],"type":"topic","title":"Lds1ElementaryFile","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Result of NFC reading.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dg1MachineReadableZoneInformation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"dg1MachineReadableZoneInformation"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":" * ","kind":"text"},{"text":"dg1MachineReadableZoneInformation","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","op":"replace","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"value":"dg1MachineReadableZoneInformation","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg1MachineReadableZoneInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"dg1MachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}