{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/detection"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/detection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The result of processing image during the palm auto capture process."}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"}],"title":"detection","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC9detectionAA0bdE9DetectionCvp","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureDetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","title":"PalmAutoCaptureController","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"abstract":[{"text":"The result of processing video frame during the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"title":"PalmAutoCaptureDetection","type":"topic","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"type":"topic","kind":"symbol","title":"PalmAutoCaptureController.ProcessingResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/detection":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/detection","title":"detection","kind":"symbol","abstract":[{"text":"The result of processing image during the palm auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection","kind":"typeIdentifier","text":"PalmAutoCaptureDetection"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/detection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","value":"DOTPPalmAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"op":"replace"}]}]}