{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/cgRect"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/cgrect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/cgrect"]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"cgRect","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)cgRect","extendedModule":"DotCore","title":"cgRect"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt":{"url":"\/documentation\/dotfacecore\/rectangleint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","title":"RectangleInt","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/cgRect":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/cgRect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cgRect","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/rectangleint\/cgrect","type":"topic","title":"cgRect","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cgRect"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cgRect"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/title","op":"replace","value":"DOTRectangleInt"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1cgRect\/title","op":"replace","value":"cgRect"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1cgRect\/fragments","op":"replace","value":[{"kind":"identifier","text":"cgRect"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}