{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalNumberOrOtherOptionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/personalnumberorotheroptionaldata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/personalnumberorotheroptionaldata"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"personalNumberOrOtherOptionalData"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"title":"personalNumberOrOtherOptionalData","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)personalNumberOrOtherOptionalData","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"url":"\/documentation\/dotdocument\/td3machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"title":"Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/personalNumberOrOtherOptionalData":{"navigatorTitle":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone\/personalnumberorotheroptionaldata","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","abstract":[],"title":"personalNumberOrOtherOptionalData","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"symbol","title":"MrzElementWithCheckDigit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"personalNumberOrOtherOptionalData","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":" * ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/navigatorTitle"},{"value":"personalNumberOrOtherOptionalData","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/title"},{"value":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/fragments"},{"value":"DOTMrzElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/navigatorTitle"}]}]}