{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/capturemode\/autocapture"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/capturemode\/autocapture"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"metadata":{"title":"CaptureMode.autoCapture","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeAutoCapture","symbolKind":"case","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"autoCapture","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"autoCapture","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once specified count of consecutive valid frames have been acquired,"},{"type":"text","text":" "},{"text":"the candidate selection process is triggered and continues for specified time in milliseconds.","type":"text"},{"text":" ","type":"text"},{"text":"During this period, the system analyzes the pool of valid images to determine the most suitable result image.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/autoCapture"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/autoCapture":{"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"url":"\/documentation\/dotfingerscore\/capturemode\/autocapture","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"}],"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"title":"CaptureMode.autoCapture","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/autoCapture"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode":{"url":"\/documentation\/dotfingerscore\/capturemode","abstract":[{"text":"Capture mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureModeAutoCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCaptureModeAutoCapture","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1autoCapture\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1autoCapture\/fragments","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}