{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.property"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","text":"Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"modules"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration(py)modules","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"title":"modules","symbolKind":"property"},"abstract":[{"type":"text","text":"Module configuration."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/modules-swift.property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/modules-swift.property":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.property","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/modules-swift.property","abstract":[{"type":"text","text":"Module configuration."}],"title":"modules","navigatorTitle":[{"kind":"identifier","text":"modules"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfigurationModules":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"title":"DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Fingers library module configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"modules","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"modules","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules","text":"DotFingersLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"modules","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1modules-swift.property\/title"},{"op":"replace","value":[{"text":"modules","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments"},{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle"}]}]}