{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/init":{"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/init","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","title":"DotDocumentLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}