{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/brightnessInterval(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"}],"externalID":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC18brightnessIntervalyAE0aC00K6DoubleCSgKF","title":"brightnessInterval(_:)","symbolKind":"method"},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/brightnessinterval(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"brightnessInterval"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"title":"PalmAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"title":"IntervalDouble","url":"\/documentation\/dotpalmcore\/intervaldouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/brightnessInterval(_:)":{"role":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/brightnessinterval(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"title":"brightnessInterval(_:)","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/brightnessInterval(_:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","title":"PalmAutoCaptureQualityAttributeThresholds.Builder","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Builder"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}]}]}