{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/helpAnchor"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/helpanchor"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"helpAnchor","extendedModule":"Foundation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:6DotNfc27MachineReadableZonePasswordC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}]},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/helpAnchor":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/helpAnchor","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"helpAnchor","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","type":"topic","title":"MachineReadableZonePassword.Error"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/LocalizedError-Implementations":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizederror-implementations","type":"topic","abstract":[],"title":"LocalizedError Implementations","kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations","role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"kind":"symbol","type":"topic","title":"NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace","value":"DOTNMachineReadableZonePassword"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}