{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble\/validate(value:interval:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTValidationDouble(cm)validateWithValue:interval:error:","title":"validate(value:interval:)","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalDouble"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/validationdouble\/validate(value:interval:)"]},{"paths":["\/documentation\/dotdocument\/validationdouble\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble"]]},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalDouble":{"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationDouble/validate(value:interval:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/validationdouble\/validate(value:interval:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble\/validate(value:interval:)","title":"validate(value:interval:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationDouble":{"navigatorTitle":[{"text":"ValidationDouble","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/validationdouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble","title":"ValidationDouble","abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationDouble"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"validateWithValue:interval:error:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","text":"DOTIntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interval"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalDouble\/fragments","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"value":"validateWithValue:interval:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble~1validate(value:interval:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"validateWithValue:interval:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble~1validate(value:interval:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble\/title","value":"DOTValidationDouble","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble\/fragments","op":"replace","value":[{"text":"DOTValidationDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}