{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFaceDetectionModuleConfigurationBalanced) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"],"generated":true}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"DotDocument"}],"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedC","symbolKind":"class","title":"DotFaceDetectionModuleConfiguration.Balanced"},"abstract":[{"text":"Face detection balanced module.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Balanced/init()":{"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced\/init()","title":"init()","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"abstract":[{"type":"text","text":"Face detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"type":"topic","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Balanced":{"role":"symbol","title":"DotFaceDetectionModuleConfiguration.Balanced","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced","navigatorTitle":[{"kind":"identifier","text":"Balanced"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"abstract":[{"text":"Face detection balanced module.","type":"text"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}