{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFaceDetectionModuleConfigurationFast) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Fast","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast\/init()"],"anchor":"Initializers"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/fast"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Face detection fast module.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC4FastC","navigatorTitle":[{"text":"Fast","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"role":"symbol","title":"DotFaceDetectionModuleConfiguration.Fast","roleHeading":"Class","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Fast/init()":{"title":"init()","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/fast\/init()","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast\/init()"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Face detection module configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","title":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Fast":{"title":"DotFaceDetectionModuleConfiguration.Fast","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/fast","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Fast"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"abstract":[{"text":"Face detection fast module.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Fast"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}