{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(licenseBytes:libraries:transactionCountingToken:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotLibrary","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"], "},{"text":"transactionCountingToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"url":"\/documentation\/dotpalmcore\/dotlibrary","kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}],"title":"DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)","role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","title":"DotSdkConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.1","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLicenseBytes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>"},{"kind":"text","text":" *) "},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transactionCountingToken"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments"},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}]},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/title"},{"value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}