{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/eyegazeliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/eyegazeliveness"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/eyeGazeLiveness"},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryEyeGazeLiveness","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLiveness"}],"title":"DotFaceModuleCategory.eyeGazeLiveness","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryEyeGazeLiveness"}],"symbolKind":"case","roleHeading":"Case"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/eyeGazeLiveness":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"eyeGazeLiveness","kind":"identifier"}],"title":"DotFaceModuleCategory.eyeGazeLiveness","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryEyeGazeLiveness"}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/eyegazeliveness","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/eyeGazeLiveness"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"title":"DotFaceModuleCategory","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","kind":"symbol","navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DotFaceModuleCategoryEyeGazeLiveness","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategoryEyeGazeLiveness"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleCategoryEyeGazeLiveness"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1eyeGazeLiveness\/title","value":"DotFaceModuleCategoryEyeGazeLiveness","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1eyeGazeLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleCategoryEyeGazeLiveness","kind":"identifier"}]},{"op":"replace","value":"DotFaceModuleCategory","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}