{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Default threshold."}],"metadata":{"title":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooSmallValidator(cpy)defaultMinDetectionSizeToImageShorterSideRatioThreshold","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Type Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator/defaultMinDetectionSizeToImageShorterSideRatioThreshold":{"kind":"symbol","title":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"}],"type":"topic","abstract":[{"type":"text","text":"Default threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/title","value":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","value":"DOTFGSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}]}]}]}