{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/identifier"]},{"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"]]},"kind":"symbol","metadata":{"title":"identifier","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooSmallValidator(py)identifier","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/identifier","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator/identifier":{"title":"identifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator\/identifier","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/identifier"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"identifier","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1identifier\/title"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1identifier\/fragments"},{"value":"DOTFGSizeTooSmallValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle"}]}]}