{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Current minimal detection size to image shorter side ratio threshold.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"minDetectionSizeToImageShorterSideRatioThreshold","symbolKind":"property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooSmallValidator(py)minDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator/minDetectionSizeToImageShorterSideRatioThreshold":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold","title":"minDetectionSizeToImageShorterSideRatioThreshold","url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold","abstract":[{"text":"Current minimal detection size to image shorter side ratio threshold.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minDetectionSizeToImageShorterSideRatioThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/title","op":"replace","value":"minDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","value":"DOTFGSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}],"op":"replace"}]}]}