{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","interfaceLanguage":"occ"},"metadata":{"navigatorTitle":[{"text":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","kind":"identifier"}],"role":"symbol","title":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm(im)initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithDetectionPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPDetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"},{"kind":"text","text":" *) "},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageParameters:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","text":"DOTPImageParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageParameters","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palmQuality:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTPPalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palmQuality"},{"text":" ","kind":"text"},{"text":"handPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"DOTPHandPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"handPosition"},{"text":" ","kind":"text"},{"text":"handOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","text":"DOTPHandOrientation","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation"},{"kind":"text","text":") "},{"text":"handOrientation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:imageparameters:palmquality:handposition:handorientation:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 8.14.1"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm/initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","title":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:imageparameters:palmquality:handposition:handorientation:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/imageparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","title":"ImageParameters","role":"symbol","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","abstract":[{"type":"text","text":"Position of the palm in the image."}],"kind":"symbol","title":"DetectionPosition","url":"\/documentation\/dotpalmcore\/detectionposition","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","abstract":[{"type":"text","text":"Result of the palm detection process."}],"role":"symbol","title":"DOTPPalmDetectorPalm","fragments":[{"kind":"identifier","text":"DOTPPalmDetectorPalm"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","url":"\/documentation\/dotpalmcore\/handposition","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HandPosition","kind":"identifier"}],"navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}],"title":"HandPosition"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"navigatorTitle":[{"kind":"identifier","text":"HandOrientation"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","title":"HandOrientation","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandOrientation"}],"abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"url":"\/documentation\/dotpalmcore\/handorientation"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"url":"\/documentation\/dotpalmcore\/palmquality","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"navigatorTitle":[{"text":"PalmQuality","kind":"identifier"}],"title":"PalmQuality","abstract":[{"type":"text","text":"Palm quality."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","value":"DOTPImageParameters"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","op":"replace","value":[{"text":"DOTPImageParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","value":"DOTPHandPosition","op":"replace"},{"value":[{"text":"DOTPHandPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","value":"DOTPHandOrientation","op":"replace"},{"value":[{"text":"DOTPHandOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","value":"DOTPPalmQuality","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]}]}]}