{"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/modules-swift.property"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo"}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Face library module configuration.","type":"text"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/init(modules:)":{"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/init(modules:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"title":"init(modules:)","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:)","abstract":[]},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(modules:faceDetectionConfidenceThreshold:)","navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","abstract":[]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/modules-swift.property":{"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.property","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}],"title":"modules","navigatorTitle":[{"kind":"identifier","text":"modules"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/modules-swift.property","abstract":[{"type":"text","text":"Module configuration."}]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.4.0","type":"text"}]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","abstract":[{"text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval ","type":"text"},{"type":"codeVoice","code":"[0.0, 1.0]"},{"text":". Default value is ","type":"text"},{"type":"codeVoice","code":"0.06"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","title":"faceDetectionConfidenceThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","title":"DotFaceLibraryConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DotFaceLibraryConfiguration","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/modules-swift.property"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:)\/fragments","op":"replace"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments","op":"replace"},{"value":"modules","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1modules-swift.property\/title","op":"replace"},{"value":[{"kind":"identifier","text":"modules"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","op":"replace"},{"value":"faceDetectionConfidenceThreshold","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments","op":"replace"},{"value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace"}]}]}