{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"com"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdCom","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdCom","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"com","kind":"identifier"}],"roleHeading":"Case","platforms":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false}],"title":"Lds1ElementaryFileId.com","symbolKind":"case"},"abstract":[{"type":"text","text":"The data group presence list."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/com","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/com"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/com"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/com":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/com","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdCom"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"com","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/com","kind":"symbol","title":"Lds1ElementaryFileId.com","abstract":[{"text":"The data group presence list.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid","title":"Lds1ElementaryFileId","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.8.0"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdCom"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdCom","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNLds1ElementaryFileIdCom","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1com\/title","op":"replace","value":"DOTNLds1ElementaryFileIdCom"},{"value":[{"text":"DOTNLds1ElementaryFileIdCom","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1com\/fragments","op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFileId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace"}]}]}