{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg11"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg11","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg11"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg11"]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg11","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg11"}],"roleHeading":"Case","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg11","kind":"identifier"}],"title":"Lds1ElementaryFileId.dg11"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"File identifier for data group 11. Data group 11 contains additional personal details.","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"title":"Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg11":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg11","type":"topic","title":"Lds1ElementaryFileId.dg11","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg11","abstract":[{"type":"text","text":"File identifier for data group 11. Data group 11 contains additional personal details."}],"kind":"symbol","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg11","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg11","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg11","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg11"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTNLds1ElementaryFileIdDg11","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNLds1ElementaryFileId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg11","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg11\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg11"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg11\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}