{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg14"},"abstract":[{"text":"File identifier for data group 14. Data group 14 contains security information.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg14"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg14"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg14"]}],"sections":[],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg14"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg14","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg14","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"Lds1ElementaryFileId.dg14","symbolKind":"case"},"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg14":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg14","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg14","type":"topic","kind":"symbol","title":"Lds1ElementaryFileId.dg14","role":"symbol","abstract":[{"text":"File identifier for data group 14. Data group 14 contains security information.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg14","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg14","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","role":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"title":"Lds1ElementaryFileId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTNLds1ElementaryFileIdDg14","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg14"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg14"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNLds1ElementaryFileIdDg14","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg14\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg14"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg14\/fragments"},{"value":"DOTNLds1ElementaryFileId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle"}]}]}