{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg2","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"text":"File identifier for data group 2. Data group 2 contains face image data.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dg2","kind":"identifier"}],"title":"Lds1ElementaryFileId.dg2","roleHeading":"Case","role":"symbol","externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg2","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}],"symbolKind":"case","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg2","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg2"]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg2","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","type":"topic","abstract":[{"text":"version: 8.6.1","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg2":{"abstract":[{"type":"text","text":"File identifier for data group 2. Data group 2 contains face image data."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg2","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFileId.dg2","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg2"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg2","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg2"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"role":"symbol","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"title":"Lds1ElementaryFileId","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfileid","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTNLds1ElementaryFileIdDg2","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg2"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg2","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg2","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg2\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg2\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg2","kind":"identifier"}]},{"value":"DOTNLds1ElementaryFileId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}