{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"abstract":[{"text":"File identifier for data group 4. Data group 4 contains iris data.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg4","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg4"]}],"metadata":{"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg4","symbolKind":"case","role":"symbol","modules":[{"name":"DotNfc"}],"title":"Lds1ElementaryFileId.dg4","roleHeading":"Case","platforms":[{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dg4","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg4","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFileId","navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg4":{"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg4","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg4","abstract":[{"text":"File identifier for data group 4. Data group 4 contains iris data.","type":"text"}],"title":"Lds1ElementaryFileId.dg4","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg4"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg4"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg4"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg4\/title","value":"DOTNLds1ElementaryFileIdDg4","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg4\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}],"op":"replace"}]}]}