{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg5"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg5","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg5","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"kind":"symbol","abstract":[{"text":"File identifier for data group 5. Data group 5 contains displayed portrait.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg5","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg5"}],"role":"symbol","symbolKind":"case","title":"Lds1ElementaryFileId.dg5","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg5"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"kind":"symbol","role":"symbol","title":"Lds1ElementaryFileId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFileId"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg5":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg5","title":"Lds1ElementaryFileId.dg5","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg5","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg5"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg5"}],"type":"topic","abstract":[{"text":"File identifier for data group 5. Data group 5 contains displayed portrait.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg5"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg5"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg5","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg5\/title","value":"DOTNLds1ElementaryFileIdDg5"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg5\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg5","kind":"identifier"}]}]}]}