{"abstract":[{"text":"File identifier for data group 7. Data group 7 contains displayed signature.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dg7","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg7"}],"modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg7","symbolKind":"case","title":"Lds1ElementaryFileId.dg7","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg7"}],"platforms":[{"beta":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"deprecated":false}]},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg7","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg7"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg7"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId":{"type":"topic","title":"Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"kind":"symbol","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId/dg7":{"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg7","abstract":[{"text":"File identifier for data group 7. Data group 7 contains displayed signature.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dg7","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg7"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg7","kind":"symbol","title":"Lds1ElementaryFileId.dg7","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTNLds1ElementaryFileIdDg7","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg7"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg7","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","op":"replace","value":"DOTNLds1ElementaryFileId"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg7\/title","value":"DOTNLds1ElementaryFileIdDg7","op":"replace"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFileIdDg7","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg7\/fragments"}]}]}