{"kind":"article","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotNfc"}]},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/equatable-implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/Equatable-Implementations"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"kind":"symbol","title":"Lds1ElementaryFileId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfileid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/!=(_:_:)":{"title":"!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/!=(_:_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}