{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/init(x:y:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/cgPoint","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/x","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/y"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/rebased(parentRectangle:)"]},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/from(cgPoint:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTPointDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/pointdouble"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/pointdouble"]}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble","symbolKind":"class","title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","role":"symbol"},"kind":"symbol","references":{"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/hash":{"type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/pointdouble\/hash","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/hash"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/rebased(parentRectangle:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/rebased(parentrectangle:)","abstract":[],"title":"rebased(parentRectangle:)","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/rebased(parentRectangle:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/mirrored()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/mirrored()","abstract":[],"title":"mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/mirrored()","type":"topic"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/x":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/x","abstract":[{"type":"text","text":"X coordinate."}],"title":"x","navigatorTitle":[{"text":"x","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/x","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/y":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/y","role":"symbol","title":"y","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/y","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"y"}],"type":"topic","abstract":[{"type":"text","text":"Y coordinate."}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/isEqual(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/isequal(_:)","abstract":[],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/isEqual(_:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/description","abstract":[],"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/description","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotpalmcore\/pointdouble","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","title":"PointDouble"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/from(cgPoint:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/from(cgpoint:)","abstract":[],"title":"from(cgPoint:)","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/from(cgPoint:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/init(x:y:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/init(x:y:)","abstract":[],"title":"init(x:y:)","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/init(x:y:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/cgPoint":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cgPoint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble\/cgpoint","abstract":[],"title":"cgPoint","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/cgPoint","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTPointDouble","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/cgPoint","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/x","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/y"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/init(x:y:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/from(cgPoint:)"],"title":"Type Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPointDouble"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1rebased(parentRectangle:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1rebased(parentRectangle:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1mirrored()\/title","value":"mirrored"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mirrored"}]},{"value":"x","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1x\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1x\/fragments","value":[{"text":"x","kind":"identifier"}],"op":"replace"},{"value":"y","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1y\/title"},{"value":[{"text":"y","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1y\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1description\/fragments"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1from(cgPoint:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1init(x:y:)\/title","value":"initWithX:y:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1init(x:y:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1cgPoint\/title","value":"cgPoint","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1cgPoint\/fragments","value":[{"kind":"identifier","text":"cgPoint"}],"op":"replace"}]}]}