{"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/sizeinterval:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"sizeInterval:error:","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)sizeInterval:error:","fragments":[{"text":"- ","kind":"text"},{"text":"sizeInterval:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"sizeInterval:error:"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"sizeInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"text":"sizeInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","abstract":[],"fragments":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/sizeInterval:error:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeInterval:error:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeInterval:error:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:","abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/sizeinterval:error:","kind":"symbol","role":"symbol","title":"sizeInterval:error:"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfacecore\/intervaldouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","title":"IntervalDouble","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}