{"abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/result"},"metadata":{"title":"result","symbolKind":"property","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC6resultAA0bdeH0CSgvp","role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","text":"PalmAutoCaptureResult"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/result"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"result"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult"]]},"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"abstract":[{"type":"text","text":"The result returned from the processing of one image during the palm auto capture process."}],"kind":"symbol","title":"PalmAutoCaptureController.ProcessingResult","navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/result":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/result","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/result","title":"result","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"kind":"text","text":": "},{"text":"PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"type":"topic","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureresult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureResult","kind":"identifier"}],"title":"PalmAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"}},"variantOverrides":[{"patch":[{"value":"DOTPPalmAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}