{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"kind":"text","text":" = .Visible())"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"kind":"text","text":")"}],"role":"symbol","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC04baseH023isDetectionLayerVisible11placeholderAeA04BasebdefG0CADC_Sb0aB7Commons11PlaceholderCtcfc"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"BaseFaceAutoCaptureViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"url":"\/documentation\/dotfacelite\/placeholder","abstract":[{"type":"text","text":"Placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"kind":"symbol","title":"Placeholder","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/init(baseConfiguration:isDetectionLayerVisible:placeholder:)":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","text":"Placeholder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration options for the UI Face Auto Capture component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","op":"replace","value":"DOTPlaceholder"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}