{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/placeholder"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/placeholder","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC11placeholder0aB7Commons11PlaceholderCvp","title":"placeholder","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","text":"Placeholder"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"codeVoice","code":".Visible"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","abstract":[{"text":"UI Face Auto Capture component.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration","abstract":[{"text":"Configuration options for the UI Face Auto Capture component.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"abstract":[{"type":"text","text":"Placeholder."}],"type":"topic","url":"\/documentation\/dotfacelite\/placeholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","title":"Placeholder","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/placeholder":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/placeholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/placeholder","kind":"symbol","abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"codeVoice","code":".Visible"},{"type":"text","text":"."}],"type":"topic","title":"placeholder","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","text":"Placeholder","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","value":"DOTPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","value":[{"text":"DOTPlaceholder","kind":"identifier"}]}]}]}