{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/configuration\/libraries"]}],"abstract":[{"text":"Libraries configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration"]]},"metadata":{"externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property","title":"libraries","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Libraries","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration\/libraries"},"references":{"doc://DotNfc/documentation/DotNfc/DotSdk/Configuration/libraries":{"url":"\/documentation\/dotnfc\/dotsdk\/configuration\/libraries","abstract":[{"type":"text","text":"Libraries configuration."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration\/libraries","title":"libraries","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/DotSdk":{"kind":"symbol","type":"topic","title":"DotSdk","url":"\/documentation\/dotnfc\/dotsdk","role":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"},"doc://DotNfc/documentation/DotNfc/Libraries":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","role":"symbol","title":"Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"abstract":[{"text":"Container for library configurations.","type":"text"}],"url":"\/documentation\/dotnfc\/libraries","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Libraries"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotSdk/Configuration":{"url":"\/documentation\/dotnfc\/dotsdk\/configuration","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration","role":"symbol","title":"DotSdk.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","value":"Libraries","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}],"op":"replace"}]}]}