{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTDDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectionPosition"},{"text":";","kind":"text"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Detected corners of the document card."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"detectionPosition"}],"title":"detectionPosition","modules":[{"name":"DotDocument"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument(py)detectionPosition","navigatorTitle":[{"kind":"identifier","text":"detectionPosition"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentdetectordocument\/detectionposition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/detectionPosition","interfaceLanguage":"occ"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument/detectionPosition":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument\/detectionposition","type":"topic","title":"detectionPosition","abstract":[{"text":"Detected corners of the document card.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/detectionPosition","role":"symbol","fragments":[{"text":"detectionPosition","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"url":"\/documentation\/dotdocument\/detectionposition","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"type":"text","text":"Position of the document card in the image."}],"title":"DetectionPosition"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","title":"DOTDDocumentDetectorDocument","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"op":"replace"}]}]}