{"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentdetectordocument\/initwithdetectionposition:confidence:widthtoheightratio:quality:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/initWithDetectionPosition:confidence:widthToHeightRatio:quality:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDetectionPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","text":"DOTDDetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"text":" *) ","kind":"text"},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"widthToHeightRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTDDocumentQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"symbolKind":"method","role":"symbol","title":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument(im)initWithDetectionPosition:confidence:widthToHeightRatio:quality:","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"Position of the document card in the image."}],"title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}],"title":"DocumentQuality","url":"\/documentation\/dotdocument\/documentquality","abstract":[{"text":"Document quality.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument/initWithDetectionPosition:confidence:widthToHeightRatio:quality:":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/initWithDetectionPosition:confidence:widthToHeightRatio:quality:","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument\/initwithdetectionposition:confidence:widthtoheightratio:quality:","title":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:","navigatorTitle":[{"text":"initWithDetectionPosition:confidence:widthToHeightRatio:quality:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"role":"symbol","fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","title":"DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDDetectionPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"DOTDDocumentQuality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle"}]}]}