{"abstract":[{"type":"text","text":"File data."}],"metadata":{"title":"bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile(py)bytes","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/bytes"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/bytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/bytes"]}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/bytes":{"abstract":[{"text":"File data.","type":"text"}],"title":"bytes","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/bytes","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile\/bytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytes"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFile","url":"\/documentation\/dotnfc\/lds1elementaryfile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","type":"topic","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"bytes","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1bytes\/title","value":"bytes","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace"}]}]}