{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/description"]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/description","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","platforms":[{"introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"}],"modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile(py)description","title":"description","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol","type":"topic","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","url":"\/documentation\/dotnfc\/lds1elementaryfile","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFile"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/description":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/description","type":"topic","abstract":[],"title":"description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}