{"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile(py)hash","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"iOS"}],"title":"hash"},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile\/hash","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile/hash":{"url":"\/documentation\/dotnfc\/lds1elementaryfile\/hash","type":"topic","title":"hash","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile\/hash"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"url":"\/documentation\/dotnfc\/lds1elementaryfile","type":"topic","title":"Lds1ElementaryFile","role":"symbol","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","title":"TravelDocument","role":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile~1hash\/title","op":"replace","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}