{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFileId","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/id"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile(py)id","role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"id","kind":"identifier"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","text":"Lds1ElementaryFileId","kind":"typeIdentifier"}],"title":"id"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/id"},"abstract":[{"type":"text","text":"File identifier."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","type":"topic","title":"Lds1ElementaryFileId","abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"title":"Lds1ElementaryFile","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}],"abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/id":{"url":"\/documentation\/dotnfc\/lds1elementaryfile\/id","abstract":[{"type":"text","text":"File identifier."}],"type":"topic","title":"id","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/id","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","kind":"typeIdentifier","text":"Lds1ElementaryFileId"}],"navigatorTitle":[{"text":"id","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"url":"\/documentation\/dotnfc\/traveldocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTNLds1ElementaryFileId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","op":"replace","value":"DOTNLds1ElementaryFileId"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"},{"value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","op":"replace"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1id\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"}]}]}