{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","kind":"typeIdentifier","text":"Lds1ElementaryFileId","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/init(id:bytes:)"]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfile\/init(id:bytes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile\/init(id:bytes:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","text":"Lds1ElementaryFileId"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithId:bytes:","kind":"identifier"}],"platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false}],"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","title":"init(id:bytes:)","symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile(im)initWithId:bytes:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile/init(id:bytes:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithId:bytes:"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile\/init(id:bytes:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","kind":"typeIdentifier","text":"Lds1ElementaryFileId"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"init(id:bytes:)","url":"\/documentation\/dotnfc\/lds1elementaryfile\/init(id:bytes:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"symbol","title":"Lds1ElementaryFile","url":"\/documentation\/dotnfc\/lds1elementaryfile","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId":{"title":"Lds1ElementaryFileId","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithId:bytes:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithId:bytes:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithId:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","text":"DOTNLds1ElementaryFileId","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"id","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"bytes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile~1init(id:bytes:)\/title","value":"initWithId:bytes:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithId:bytes:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile~1init(id:bytes:)\/fragments"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}