{"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(ciImage:ciContext:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory\/create(ciimage:cicontext:)"]},{"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImageFactory(cm)createWithCiImage:ciContext:","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Type Method","title":"create(ciImage:ciContext:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}]},"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}],"name":"ciContext"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" instance.","type":"text"}]}]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImageFactory":{"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimagefactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory","type":"topic","abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"title":"BgraRawImageFactory"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImageFactory/create(ciImage:ciContext:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimagefactory\/create(ciimage:cicontext:)","kind":"symbol","title":"create(ciImage:ciContext:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(ciImage:ciContext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"url":"\/documentation\/dotfacelite\/bgrarawimage","title":"BgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithCiImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ciContext:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTBgraRawImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}