{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore","relatedModules":["DotCore"]}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"title":"from(cgPoint:)","externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(cm)fromCgPoint:","symbolKind":"method","extendedModule":"DotCore"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/pointdouble\/from(cgpoint:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/pointdouble\/from(cgpoint:)"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble\/from(cgPoint:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/PointDouble/from(cgPoint:)":{"url":"\/documentation\/dotfingerscore\/pointdouble\/from(cgpoint:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"title":"from(cgPoint:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble\/from(cgPoint:)"},"doc://DotFingersCore/documentation/DotFingersCore/PointDouble":{"type":"topic","title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotfingerscore\/pointdouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fromCgPoint:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromCgPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgPoint"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"fromCgPoint:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble~1from(cgPoint:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble~1from(cgPoint:)\/fragments"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/navigatorTitle"}]}]}