{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble\/mirrored()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/pointdouble\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/pointdouble\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble"]]},"metadata":{"title":"mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(im)mirrored","symbolKind":"method","extendedModule":"DotCore","modules":[{"name":"DotFingersCore","relatedModules":["DotCore"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble","kind":"typeIdentifier","text":"PointDouble"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/PointDouble":{"type":"topic","title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotfingerscore\/pointdouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PointDouble/mirrored()":{"type":"topic","kind":"symbol","title":"mirrored()","url":"\/documentation\/dotfingerscore\/pointdouble\/mirrored()","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble\/mirrored()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"mirrored","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble~1mirrored()\/title","value":"mirrored","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointDouble~1mirrored()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}