{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]},{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"},"kind":"symbol","metadata":{"symbolKind":"init","title":"init(licenseBytes:libraries:transactionCountingToken:)","role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"references":{"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)","abstract":[],"url":"\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"},"doc://DotNfc/documentation/DotNfc/DotLibrary":{"role":"symbol","url":"\/documentation\/dotnfc\/dotlibrary","title":"DotLibrary","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary"},"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"title":"DotSdkConfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotsdkconfiguration"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithLicenseBytes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"licenseBytes"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"libraries"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title","op":"replace","value":"initWithLicenseBytes:libraries:transactionCountingToken:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/title"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/fragments"}]}]}