{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/cameraimagesource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/cameraimagesource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ImageSource","doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/init(configuration:videoQueue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/delegate","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/orientation","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/previewView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/startSession()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/stopSession()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/Error"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"title":"CameraImageSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)CameraImageSource","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"CameraImageSource"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/Error":{"role":"symbol","title":"CameraImageSource.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/cameraimagesource\/error"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource":{"role":"symbol","title":"CameraImageSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraImageSource"}],"url":"\/documentation\/dotfacecore\/cameraimagesource"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/previewView":{"role":"symbol","title":"previewView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/previewView","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/previewview"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/init(configuration:videoQueue:)":{"role":"symbol","title":"init(configuration:videoQueue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraImageSourceConfiguration","preciseIdentifier":"s:11DotFaceCore30CameraImageSourceConfigurationV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/init(configuration:videoQueue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/init(configuration:videoqueue:)"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/stopSession()":{"role":"symbol","title":"stopSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops camera session and stops producing images. This method should be called on the background thread."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/stopSession()","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/stopsession()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ImageSource":{"role":"symbol","title":"ImageSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSource"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"url":"\/documentation\/dotfacecore\/imagesource"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/startSession()":{"role":"symbol","title":"startSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts camera session and starts producing images. This method should be called on the background thread."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/startSession()","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/startsession()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/avcapturevideodataoutputsamplebufferdelegate-implementations"},"doc://com.innovatrics.dot.face.core/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"type":"unresolvable","title":"AVFoundation.AVCaptureVideoDataOutputSampleBufferDelegate","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSourceDelegate","preciseIdentifier":"s:11DotFaceCore19ImageSourceDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/delegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraImageSource/orientation":{"role":"symbol","title":"orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSourceOrientation","preciseIdentifier":"s:11DotFaceCore22ImageSourceOrientationO"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/orientation","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraimagesource\/orientation"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraImageSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraImageSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraImageSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraImageSource\/title","value":"CameraImageSource"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraImageSource\/fragments","value":[{"kind":"identifier","text":"CameraImageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}