{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"modules":[{"name":"DotNfc"}],"title":"initWithDetection:","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules\/initwithdetection:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules\/initWithDetection:"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfigurationModules":{"kind":"symbol","abstract":[{"type":"text","text":"Palm library module configuration."}],"type":"topic","role":"symbol","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules","title":"DotPalmLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules"},"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration":{"title":"DotPalmDetectionModuleConfiguration","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfigurationModules/initWithDetection:":{"url":"\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules\/initwithdetection:","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules\/initWithDetection:","title":"initWithDetection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}