{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController(py)baseConfiguration","title":"baseConfiguration","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"role":"symbol"},"sections":[],"abstract":[{"text":"Current configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/baseConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/baseConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"title":"baseConfiguration","role":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/baseconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/baseConfiguration","type":"topic","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","title":"BaseFaceAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"title":"BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","type":"topic","abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"kind":"symbol","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","role":"symbol","title":"DOTFLBaseFaceAutoCaptureConfiguration","fragments":[{"text":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"baseConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"baseConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration","text":"DOTFLBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"baseConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1baseConfiguration\/title"},{"value":[{"kind":"identifier","text":"baseConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1baseConfiguration\/fragments"},{"value":"DOTFLBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"}]}]}