{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceimagequality\/description"]},{"paths":["\/documentation\/dotfacelite\/faceimagequality\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/description"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","title":"description","role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality(py)description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality":{"url":"\/documentation\/dotfacelite\/faceimagequality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","role":"symbol","abstract":[{"text":"Face image quality.","type":"text"}],"title":"FaceImageQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"description","url":"\/documentation\/dotfacelite\/faceimagequality\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/title","op":"replace","value":"DOTFLFaceImageQuality"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/fragments","op":"replace","value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}