{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"brightness","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality(im)initWithBrightness:sharpness:","role":"symbol","roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","title":"init(brightness:sharpness:)","navigatorTitle":[{"text":"initWithBrightness:sharpness:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceimagequality\/init(brightness:sharpness:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceimagequality\/init(brightness:sharpness:)"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/init(brightness:sharpness:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality/init(brightness:sharpness:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/init(brightness:sharpness:)","navigatorTitle":[{"text":"initWithBrightness:sharpness:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"init(brightness:sharpness:)","url":"\/documentation\/dotfacelite\/faceimagequality\/init(brightness:sharpness:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality":{"url":"\/documentation\/dotfacelite\/faceimagequality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","role":"symbol","abstract":[{"text":"Face image quality.","type":"text"}],"title":"FaceImageQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithBrightness:sharpness:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:sharpness:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1init(brightness:sharpness:)\/title","value":"initWithBrightness:sharpness:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1init(brightness:sharpness:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:sharpness:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/title","value":"DOTFLFaceImageQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/fragments","value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/navigatorTitle","value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"op":"replace"}]}]}