{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration\/init","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration(im)init","symbolKind":"method","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceVerificationModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"url":"\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"title":"DotFaceVerificationModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},"doc://DotNfc/documentation/DotNfc/DotFaceVerificationModuleConfiguration/init":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[],"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration\/init"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}