{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator"]]},"abstract":[{"text":"Default threshold value.","type":"text"}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooSmallValidator(cpy)defaultMinDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","symbolKind":"property"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/defaultMinDetectionSizeToImageShorterSideRatioThreshold":{"title":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[{"text":"Default threshold value.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","abstract":[{"text":"version: 8.3.1","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","title":"SizeTooSmallValidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"type":"text","text":"Validate size of the detected face."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/title","value":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"},{"value":[{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/fragments"},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","value":"DOTFLSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}