{"abstract":[{"type":"text","text":"Current minimal accepted size."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}],"symbolKind":"property","title":"minDetectionSizeToImageShorterSideRatioThreshold","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooSmallValidator(py)minDetectionSizeToImageShorterSideRatioThreshold"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"type":"topic","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"kind":"symbol","title":"SizeTooSmallValidator","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"type":"text","text":"Validate size of the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"text":"version: 8.12.1","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator/minDetectionSizeToImageShorterSideRatioThreshold":{"title":"minDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","kind":"symbol","abstract":[{"text":"Current minimal accepted size.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"minDetectionSizeToImageShorterSideRatioThreshold","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","op":"replace","value":"DOTFLSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"value":"minDetectionSizeToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/title"},{"value":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/fragments"}]}]}