{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/libraries\/document"]},{"paths":["\/documentation\/dotfingerscore\/libraries\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Document library configuration."}],"metadata":{"title":"document","navigatorTitle":[{"text":"document","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)Libraries(py)document","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/document","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries/document":{"title":"document","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"document"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfingerscore\/libraries\/document","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/document"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"document","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"document"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"document"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle"},{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"value":"document","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1document\/title"},{"value":[{"kind":"identifier","text":"document"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1document\/fragments"}]}]}