{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:fingers:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":"?)","kind":"text"}],"title":"init(document:face:faceLite:nfc:palm:fingers:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"symbolKind":"init","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotNfcLibraryConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotnfclibraryconfiguration","kind":"symbol","abstract":[{"type":"text","text":"NFC library configuration."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLiteLibraryConfiguration":{"kind":"symbol","title":"DotFaceLiteLibraryConfiguration","url":"\/documentation\/dotfingerscore\/dotfacelitelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face Lite library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries/init(document:face:faceLite:nfc:palm:fingers:)":{"title":"init(document:face:faceLite:nfc:palm:fingers:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fingers"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration":{"kind":"symbol","title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Fingers library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:fingers:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceLite:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"faceLite","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nfc:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"nfc","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"palm:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"palm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fingers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"fingers","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/title","op":"replace","value":"DotNfcLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/title","op":"replace","value":"DotFaceLiteLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title","op":"replace","value":"Libraries"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/title","op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}]},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/title","op":"replace","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/navigatorTitle"}]}]}