{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/libraries\/palm"]},{"paths":["\/documentation\/dotfingerscore\/libraries\/palm"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"]]},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)Libraries(py)palm","role":"symbol","title":"palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFingersCore"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/palm"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries/palm":{"title":"palm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"palm"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"url":"\/documentation\/dotfingerscore\/libraries\/palm","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries\/palm"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"palm","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"palm"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"palm"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle"},{"value":"palm","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1palm\/title"},{"value":[{"kind":"identifier","text":"palm"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries~1palm\/fragments"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/navigatorTitle"}]}]}