{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDocumentAutoCaptureDetectionValidator","text":"DocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.minValidFramesInRowToStartCandidateSelection, "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.candidateSelectionDurationMillis, "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isMrzReadingEnabled)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/init(validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:imageparametersnormalizedrectangle:ismrzreadingenabled:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/init(validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:imageparametersnormalizedrectangle:ismrzreadingenabled:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureControllerConfiguration(im)initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration":{"role":"symbol","title":"DocumentAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of non-UI component for document auto capture."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration/init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)":{"role":"symbol","title":"init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/init(validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:imageparametersnormalizedrectangle:ismrzreadingenabled:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotdocument\/rectangledouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"role":"symbol","title":"DocumentAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValidators:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<DOTDocumentAutoCaptureDetectionValidator>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"validators"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidFramesInRowToStartCandidateSelection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionNormalizedRectangle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParametersNormalizedRectangle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMrzReadingEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/title","value":"DOTDocumentAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)\/title","value":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1init(validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValidators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:imageParametersNormalizedRectangle:isMrzReadingEnabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDocumentAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureDetectionValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}