{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Validate sharpness of the detected document."}],"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDSharpnessTooLowValidator(im)validateWithDocumentAutoCaptureFrameParameters:","role":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"documentAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" for blurry document."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"DocumentAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/validate(documentAutoCaptureFrameParameters:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/validate(documentautocaptureframeparameters:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","title":"validate(documentAutoCaptureFrameParameters:)","abstract":[{"text":"Validate sharpness of the detected document.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]}]}]}