{"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator(py)dependencyIdentifiers","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator"]]},"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/dependencyidentifiers"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/dependencyIdentifiers"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/dependencyIdentifiers":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.7.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"title":"PalmAutoCaptureController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dependencyIdentifiers","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","value":"DOTPSizeTooSmallValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]}]}]}