{"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","modules":[{"name":"DotNfc"}],"title":"DotLibraryId.document","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/document"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/document"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/document","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","role":"symbol","title":"DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"url":"\/documentation\/dotnfc\/dotlibraryid","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/document":{"url":"\/documentation\/dotnfc\/dotlibraryid\/document","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"title":"DotLibraryId.document","abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/document","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotLibraryIdDocument","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotLibraryId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle","op":"replace"},{"value":"DotLibraryIdDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1document\/title","op":"replace"},{"value":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1document\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}