{"abstract":[{"type":"text","text":"Get face feature description."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeaturewrapper\/description"]},{"paths":["\/documentation\/dotfacecore\/facefeaturewrapper\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeatureWrapper(py)description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeatureWrapper":{"abstract":[{"type":"text","text":"Face feature wrapper."}],"url":"\/documentation\/dotfacecore\/facefeaturewrapper","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceFeatureWrapper"}],"title":"FaceFeatureWrapper","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeatureWrapper"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeatureWrapper/description":{"abstract":[{"type":"text","text":"Get face feature description."}],"url":"\/documentation\/dotfacecore\/facefeaturewrapper\/description","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper\/title","value":"DOTFFaceFeatureWrapper"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}