{"metadata":{"symbolKind":"init","modules":[{"name":"DotFaceCore"}],"title":"init(feature:)","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:"}],"roleHeading":"Initializer","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeatureWrapper(im)initWithFeature:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","text":"FaceFeature","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","text":"FaceFeature"},{"text":")","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper\/init(feature:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeaturewrapper\/init(feature:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeaturewrapper\/init(feature:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeatureWrapper/init(feature:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper\/init(feature:)","title":"init(feature:)","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:"}],"url":"\/documentation\/dotfacecore\/facefeaturewrapper\/init(feature:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","text":"FaceFeature","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeatureWrapper":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeatureWrapper","kind":"symbol","title":"FaceFeatureWrapper","abstract":[{"type":"text","text":"Face feature wrapper."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceFeatureWrapper"}],"url":"\/documentation\/dotfacecore\/facefeaturewrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceFeatureWrapper"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"title":"FaceFeature","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"text":"Available face features.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","url":"\/documentation\/dotfacecore\/facefeature","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithFeature:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFeature:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFeature:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","kind":"typeIdentifier","text":"DOTFFaceFeature","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"feature"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper~1init(feature:)\/title","value":"initWithFeature:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper~1init(feature:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFeature:","kind":"identifier"}]},{"value":"DOTFFaceFeatureWrapper","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeatureWrapper\/fragments","value":[{"text":"DOTFFaceFeatureWrapper","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}