{"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/identifier","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPTemplateExtractionQualityTooLowValidator(py)identifier","title":"identifier","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","abstract":[{"type":"text","text":"Validate minimum template extraction quality of the detected palm."}],"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateExtractionQualityTooLowValidator"}],"kind":"symbol","type":"topic","title":"TemplateExtractionQualityTooLowValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TemplateExtractionQualityTooLowValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator/identifier":{"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/identifier","title":"identifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/identifier","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"identifier","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPTemplateExtractionQualityTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title"},{"value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPTemplateExtractionQualityTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/navigatorTitle"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1identifier\/title"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1identifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}