{"metadata":{"title":"init(rawValue:)","externalID":"s:7DotCore11ImageFormatO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"DotDocument"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/imageformat\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/ImageFormat/init(rawValue:)":{"url":"\/documentation\/dotdocument\/imageformat\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageFormat":{"url":"\/documentation\/dotdocument\/imageformat","title":"ImageFormat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Supported image formats."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}