{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration(im)init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotNfc"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration\/init","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration\/init"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"type":"text","text":"Face background uniformity module."}],"title":"DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration/init":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration\/init","abstract":[],"title":"init","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration\/init"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}