{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdk\/error\/failedtoloadsystemconstants"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"DotSdk.Error.failedToLoadSystemConstants","externalID":"s:7DotCore0A3SdkC5ErrorO27failedToLoadSystemConstantsyA2EmF","symbolKind":"case","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadSystemConstants","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/failedToLoadSystemConstants":{"type":"topic","kind":"symbol","title":"DotSdk.Error.failedToLoadSystemConstants","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/failedtoloadsystemconstants","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadSystemConstants"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/error","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}