{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/common"},"sections":[],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerConfiguration(py)common","navigatorTitle":[{"kind":"identifier","text":"common"}],"symbolKind":"property","roleHeading":"Instance Property","title":"common","fragments":[{"kind":"identifier","text":"common"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/common"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" * ","kind":"text"},{"text":"common","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","url":"\/documentation\/dotpalmcore\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"kind":"symbol","abstract":[{"text":"Common configuration for all components.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration/common":{"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/common","role":"symbol","kind":"symbol","title":"common","fragments":[{"kind":"identifier","text":"common"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/common"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration":{"title":"DOTPPalmAutoCaptureControllerConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerConfiguration"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}