{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:validators:detectionArea:error:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/initwithcommon:autocapture:validators:detectionarea:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerConfiguration(im)initWithCommon:autoCapture:validators:detectionArea:error:","modules":[{"name":"DotPalmCore"}],"title":"initWithCommon:autoCapture:validators:detectionArea:error:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","text":"DOTCommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" *) ","kind":"text"},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"autoCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validators:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<DOTPPalmAutoCaptureFrameParametersValidator>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"validators","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectionArea:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"text":"detectionArea","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"abstract":[{"text":"Create palm auto capture controller configuration.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration/initWithCommon:autoCapture:validators:detectionArea:error:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:autoCapture:validators:detectionArea:error:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:validators:detectionArea:error:","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:autoCapture:validators:detectionArea:error:"}],"title":"initWithCommon:autoCapture:validators:detectionArea:error:","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration\/initwithcommon:autocapture:validators:detectionarea:error:","abstract":[{"text":"Create palm auto capture controller configuration.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","type":"topic","url":"\/documentation\/dotpalmcore\/rectangledouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration":{"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","role":"symbol","kind":"symbol","title":"DOTPPalmAutoCaptureControllerConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}