{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"title":"isFaceEyeGazeLivenessScoreEnabled","role":"symbol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceEyeGazeLivenessScoreEnabled","required":true,"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"]},{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.11.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","kind":"symbol","title":"isFaceEyeGazeLivenessScoreEnabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","kind":"symbol","title":"DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace"},{"value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"}]}]}