{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"("},{"text":"isFacePresenceRequired","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"isFacePresenceRequired","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If true, the result will be captured only if a face is detected with defined quality attributes."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the result will be captured regardless of the face presence. Default is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController(im)requestCaptureWithIsFacePresenceRequired:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isFacePresenceRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","title":"requestCapture(isFacePresenceRequired:)","symbolKind":"method","modules":[{"name":"DotFaceCore"}]},"abstract":[{"type":"text","text":"Request capture of the next detection."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isFacePresenceRequired"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","title":"requestCapture(isFacePresenceRequired:)","abstract":[{"type":"text","text":"Request capture of the next detection."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"requestCaptureWithIsFacePresenceRequired:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isFacePresenceRequired","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","op":"replace","value":"requestCaptureWithIsFacePresenceRequired:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"}]}]}