{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"]]},"metadata":{"navigatorTitle":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator(py)minEdgeLengthToImageShorterSideRatioThreshold","modules":[{"name":"DotDocument"}],"title":"minEdgeLengthToImageShorterSideRatioThreshold","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/minEdgeLengthToImageShorterSideRatioThreshold":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold","abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"title":"minEdgeLengthToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","type":"topic","title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"minEdgeLengthToImageShorterSideRatioThreshold","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/title","value":"minEdgeLengthToImageShorterSideRatioThreshold","op":"replace"},{"op":"replace","value":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}