{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Instance Property","title":"description","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A12FaceModuleIdO11descriptionSSvp","role":"symbol"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/description","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/description"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/description":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/description","title":"description","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/description","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"title":"DotFaceModuleId","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}