{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}],"title":"DotFaceModuleId.detectionFast","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdDetectionFast","modules":[{"name":"DotPalmCore"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionFast","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionfast"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionfast"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","title":"DotFaceModuleId","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/detectionFast":{"abstract":[],"title":"DotFaceModuleId.detectionFast","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionfast","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionFast","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdDetectionFast","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionFast\/title","value":"DotFaceModuleIdDetectionFast","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionFast\/fragments","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"op":"replace"}]}]}