{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdDetectionBalanced","title":"DotFaceModuleId.detectionBalanced"},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionBalanced","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionbalanced"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionbalanced"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/detectionBalanced":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionbalanced","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionBalanced","title":"DotFaceModuleId.detectionBalanced","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"title":"DotFaceModuleId","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionBalanced\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionBalanced\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}