{"abstract":[{"text":"Logs informative events.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","title":"LoggerLogLevel.info","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel"]]},"variants":[{"paths":["\/documentation\/dotdocument\/loggerloglevel\/info"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/loggerloglevel\/info"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/info"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/LoggerLogLevel":{"title":"LoggerLogLevel","kind":"symbol","type":"topic","abstract":[{"text":"Available log levels.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel/info":{"abstract":[{"text":"Logs informative events.","type":"text"}],"url":"\/documentation\/dotdocument\/loggerloglevel\/info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/info","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"title":"LoggerLogLevel.info","kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/navigatorTitle","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1info\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1info\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}