{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCaptureStepId) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureStepId"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/capturestepid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/capturestepid"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/backgroundUniformity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/eyeStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/glassStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/light","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mask","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mouthStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/pitchAngle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/position","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/presence","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/proximity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/yawAngle"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureStepId"}],"title":"CaptureStepId","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotFaceCore@E@DOTCaptureStepId","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureStepId"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/yawAngle":{"role":"symbol","title":"CaptureStepId.yawAngle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"yawAngle"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/yawAngle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdYawAngle"}],"url":"\/documentation\/dotfacecore\/capturestepid\/yawangle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/mask":{"role":"symbol","title":"CaptureStepId.mask","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdMask"}],"url":"\/documentation\/dotfacecore\/capturestepid\/mask"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/proximity":{"role":"symbol","title":"CaptureStepId.proximity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proximity"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/proximity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdProximity"}],"url":"\/documentation\/dotfacecore\/capturestepid\/proximity"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId":{"role":"symbol","title":"CaptureStepId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureStepId"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaptureStepId"}],"url":"\/documentation\/dotfacecore\/capturestepid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/position":{"role":"symbol","title":"CaptureStepId.position","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdPosition"}],"url":"\/documentation\/dotfacecore\/capturestepid\/position"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/light":{"role":"symbol","title":"CaptureStepId.light","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/light","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdLight"}],"url":"\/documentation\/dotfacecore\/capturestepid\/light"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/eyeStatus":{"role":"symbol","title":"CaptureStepId.eyeStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeStatus"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/eyeStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdEyeStatus"}],"url":"\/documentation\/dotfacecore\/capturestepid\/eyestatus"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/capturestepid\/equatable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/pitchAngle":{"role":"symbol","title":"CaptureStepId.pitchAngle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitchAngle"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/pitchAngle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdPitchAngle"}],"url":"\/documentation\/dotfacecore\/capturestepid\/pitchangle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/mouthStatus":{"role":"symbol","title":"CaptureStepId.mouthStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthStatus"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mouthStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdMouthStatus"}],"url":"\/documentation\/dotfacecore\/capturestepid\/mouthstatus"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/presence":{"role":"symbol","title":"CaptureStepId.presence","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presence"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/presence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdPresence"}],"url":"\/documentation\/dotfacecore\/capturestepid\/presence"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/glassStatus":{"role":"symbol","title":"CaptureStepId.glassStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"glassStatus"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/glassStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdGlassStatus"}],"url":"\/documentation\/dotfacecore\/capturestepid\/glassstatus"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/capturestepid\/init(rawvalue:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/capturestepid\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.face.core/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/backgroundUniformity":{"role":"symbol","title":"CaptureStepId.backgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/backgroundUniformity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureStepIdBackgroundUniformity"}],"url":"\/documentation\/dotfacecore\/capturestepid\/backgrounduniformity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureStepId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCaptureStepId"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/backgroundUniformity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/eyeStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/glassStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/light","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mask","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mouthStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/pitchAngle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/position","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/presence","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/proximity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/yawAngle"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCaptureStepId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1yawAngle\/title","value":"DOTCaptureStepIdYawAngle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1yawAngle\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdYawAngle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mask\/title","value":"DOTCaptureStepIdMask"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mask\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdMask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1proximity\/title","value":"DOTCaptureStepIdProximity"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1proximity\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdProximity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId\/title","value":"DOTCaptureStepId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1position\/title","value":"DOTCaptureStepIdPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1position\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1light\/title","value":"DOTCaptureStepIdLight"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1light\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdLight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1eyeStatus\/title","value":"DOTCaptureStepIdEyeStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1eyeStatus\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdEyeStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1pitchAngle\/title","value":"DOTCaptureStepIdPitchAngle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1pitchAngle\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdPitchAngle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mouthStatus\/title","value":"DOTCaptureStepIdMouthStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mouthStatus\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdMouthStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1presence\/title","value":"DOTCaptureStepIdPresence"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1presence\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdPresence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1glassStatus\/title","value":"DOTCaptureStepIdGlassStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1glassStatus\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdGlassStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1backgroundUniformity\/title","value":"DOTCaptureStepIdBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1backgroundUniformity\/fragments","value":[{"kind":"identifier","text":"DOTCaptureStepIdBackgroundUniformity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}