{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"role":"symbol","title":"DotFaceConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration","modules":[{"name":"DotFaceCore"}],"platforms":[]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryConfiguration instead."}]}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:faceDetectionConfidenceThreshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/license","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/modules"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/Error"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/license":{"deprecated":true,"role":"symbol","title":"license","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[{"type":"text","text":"Raw licensing data."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/license","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"license"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/license"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/modules":{"deprecated":true,"role":"symbol","title":"modules","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/modules","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/modules"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/faceDetectionConfidenceThreshold":{"deprecated":true,"role":"symbol","title":"faceDetectionConfidenceThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Face detection confidence threshold, value in range [0.0, 1.0]. Default is 0.06."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/faceDetectionConfidenceThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/facedetectionconfidencethreshold"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/Error":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/error"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/init(license:modules:)":{"deprecated":true,"role":"symbol","title":"init(license:modules:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLicense:modules:"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/init(license:modules:)"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/init(license:modules:faceDetectionConfidenceThreshold:)":{"deprecated":true,"role":"symbol","title":"init(license:modules:faceDetectionConfidenceThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:faceDetectionConfidenceThreshold:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLicense:modules:faceDetectionConfidenceThreshold:error:"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/init(license:modules:facedetectionconfidencethreshold:)"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/license","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/modules"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/init(license:modules:faceDetectionConfidenceThreshold:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1license\/title","value":"license"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1license\/fragments","value":[{"kind":"identifier","text":"license"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1modules\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1faceDetectionConfidenceThreshold\/title","value":"faceDetectionConfidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1faceDetectionConfidenceThreshold\/fragments","value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:)\/title","value":"initWithLicense:modules:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicense:modules:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:faceDetectionConfidenceThreshold:)\/title","value":"initWithLicense:modules:faceDetectionConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1init(license:modules:faceDetectionConfidenceThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicense:modules:faceDetectionConfidenceThreshold:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}