{"seeAlsoSections":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"title":"QualityProvider","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@DotFaceCore@objc(pl)DOTQualityProvider","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}]},"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/findQualityAttributeById(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/getQualityAttributes()"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTQualityProvider) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider":{"role":"symbol","title":"QualityProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}],"url":"\/documentation\/dotfacecore\/qualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IcaoQualityProvider":{"role":"symbol","title":"IcaoQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IcaoQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for ICAO evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IcaoQualityProvider"}],"url":"\/documentation\/dotfacecore\/icaoqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DefaultQualityAttributeRegistry":{"role":"symbol","title":"DefaultQualityAttributeRegistry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"abstract":[{"type":"text","text":"This class contains default "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" for every "},{"type":"codeVoice","code":"QualityAttributeId"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"url":"\/documentation\/dotfacecore\/defaultqualityattributeregistry"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider/getQualityAttributes()":{"navigatorTitle":[{"kind":"identifier","text":"getQualityAttributes"}],"role":"symbol","title":"getQualityAttributes()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getQualityAttributes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/getQualityAttributes()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/qualityprovider\/getqualityattributes()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/PassiveLivenessQualityProvider":{"role":"symbol","title":"PassiveLivenessQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for passive liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"url":"\/documentation\/dotfacecore\/passivelivenessqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider/findQualityAttributeById(_:)":{"navigatorTitle":[{"kind":"identifier","text":"findQualityAttributeById:"}],"role":"symbol","title":"findQualityAttributeById(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findQualityAttributeById"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTQualityAttributeId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/findQualityAttributeById(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/qualityprovider\/findqualityattributebyid(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider":{"role":"symbol","title":"MatchingQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MatchingQualityProvider"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTQualityProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTQualityProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTQualityProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/findQualityAttributeById(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/getQualityAttributes()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTQualityProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/title","value":"DOTQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/title","value":"DOTIcaoQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTIcaoQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/title","value":"DOTDefaultQualityAttributeRegistry"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/fragments","value":[{"kind":"identifier","text":"DOTDefaultQualityAttributeRegistry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1getQualityAttributes()\/title","value":"getQualityAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1getQualityAttributes()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getQualityAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/title","value":"DOTPassiveLivenessQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTPassiveLivenessQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1findQualityAttributeById(_:)\/title","value":"findQualityAttributeById:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1findQualityAttributeById(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findQualityAttributeById:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/title","value":"DOTMatchingQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTMatchingQualityProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}