{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"s:7DotCore14LoggerLogLevelO11descriptionSSvp","role":"symbol","title":"description","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/description","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/loggerloglevel\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/description","kind":"symbol","url":"\/documentation\/dotnfc\/loggerloglevel\/description","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"url":"\/documentation\/dotnfc\/loggerloglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle"}]}]}