{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyFaceAutoCaptureController"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"imageSize","externalID":"s:14DotFaceCommons03AnyB21AutoCaptureControllerC9imageSize0A4Core05ImageI0CSgvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyFaceAutoCaptureController\/imageSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/anyfaceautocapturecontroller\/imagesize"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/AnyFaceAutoCaptureController/imageSize":{"abstract":[],"title":"imageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyFaceAutoCaptureController\/imageSize","type":"topic","url":"\/documentation\/dotfacecore\/anyfaceautocapturecontroller\/imagesize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/AnyFaceAutoCaptureController":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AnyFaceAutoCaptureController"}],"title":"AnyFaceAutoCaptureController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AnyFaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacecore\/anyfaceautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyFaceAutoCaptureController"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"title":"ImageSize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotfacecore\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}