{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Travel document has not passed Passive Authentication."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}],"role":"symbol","title":"PassiveAuthenticationStatus.failed","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus@DOTPassiveAuthenticationStatusFailed","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus":{"role":"symbol","title":"PassiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/failed":{"role":"symbol","title":"PassiveAuthenticationStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Travel document has not passed Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/failed"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO)."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTPassiveAuthenticationStatusFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/title","value":"DOTPassiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1failed\/title","value":"DOTPassiveAuthenticationStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1failed\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}