{"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/activeAuthenticationResponse","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The Active Authentication response (signature) is set only if explicit challenge ","type":"text"},{"type":"codeVoice","code":"activeAuthenticationChallenge"},{"text":" in ","type":"text"},{"type":"codeVoice","code":"NfcTravelDocumentReader.read"},{"text":" operation was set by the caller and Active Authentication protocol is supported by the chip. Otherwise ","type":"text"},{"code":"activeAuthenticationResponse","type":"codeVoice"},{"type":"text","text":" is nil."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activeAuthenticationResponse"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/activeauthenticationresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/activeauthenticationresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"activeAuthenticationResponse","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(py)activeAuthenticationResponse","navigatorTitle":[{"text":"activeAuthenticationResponse","kind":"identifier"}],"title":"activeAuthenticationResponse"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus":{"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus","title":"ChipAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChipAuthenticationStatus","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus/activeAuthenticationResponse":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/activeauthenticationresponse","title":"activeAuthenticationResponse","role":"symbol","abstract":[{"type":"text","text":"The Active Authentication response (signature) is set only if explicit challenge "},{"code":"activeAuthenticationChallenge","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"NfcTravelDocumentReader.read","type":"codeVoice"},{"type":"text","text":" operation was set by the caller and Active Authentication protocol is supported by the chip. Otherwise "},{"type":"codeVoice","code":"activeAuthenticationResponse"},{"type":"text","text":" is nil."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"activeAuthenticationResponse","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/activeAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"activeAuthenticationResponse"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"activeAuthenticationResponse"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"activeAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" * "},{"text":"activeAuthenticationResponse","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","op":"replace","value":"DOTNChipAuthenticationStatus"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","value":"activeAuthenticationResponse","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1activeAuthenticationResponse\/title"},{"value":[{"text":"activeAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1activeAuthenticationResponse\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}