{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"externalID":"s:6DotNfc22FlatTagStructureParserC5ErrorO","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"FlatTagStructureParser.Error","symbolKind":"enum"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError","doc:\/\/DotNfc\/10Foundation14LocalizedErrorP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/s5ErrorP","doc:\/\/DotNfc\/s8SendableP","doc:\/\/DotNfc\/s16SendableMetatypeP"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/error"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/emptyInputData","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/parsing(internalError:)"],"title":"Enumeration Cases","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/errorMessage","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/internalError"],"title":"Instance Properties","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/DotSdkError-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/Error-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"]]},"references":{"doc://DotNfc/s5ErrorP":{"identifier":"doc:\/\/DotNfc\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://DotNfc/s16SendableMetatypeP":{"identifier":"doc:\/\/DotNfc\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/internalError":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"title":"internalError","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/internalError","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/internalerror"},"doc://DotNfc/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/DotNfc\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/parsing(internalError:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"parsing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/parsing(internalerror:)","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/parsing(internalError:)","role":"symbol","title":"FlatTagStructureParser.Error.parsing(internalError:)"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"url":"\/documentation\/dotnfc\/flattagstructureparser","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","kind":"symbol","title":"FlatTagStructureParser","abstract":[{"text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse ","type":"text"},{"code":"OptionalDetails.content","type":"codeVoice"},{"type":"text","text":" of some documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FlatTagStructureParser"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/DotSdkError-Implementations":{"role":"collectionGroup","title":"DotSdkError Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/DotSdkError-Implementations","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/dotsdkerror-implementations"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/errorMessage":{"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/errormessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","role":"symbol","abstract":[],"title":"errorMessage","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/errorMessage"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/LocalizedError-Implementations":{"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/localizederror-implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"LocalizedError Implementations","kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/LocalizedError-Implementations"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error":{"url":"\/documentation\/dotnfc\/flattagstructureparser\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","kind":"symbol","abstract":[],"title":"FlatTagStructureParser.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/Error-Implementations":{"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/error-implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"Error Implementations","kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/Error-Implementations"},"doc://DotNfc/documentation/DotNfc/DotSdkError":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotsdkerror","title":"DotSdkError","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError"},"doc://DotNfc/s8SendableP":{"identifier":"doc:\/\/DotNfc\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/emptyInputData":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyInputData"}],"title":"FlatTagStructureParser.Error.emptyInputData","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/emptyInputData","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/emptyinputdata"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","op":"replace","value":"DOTNFlatTagStructureParser"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}]}]}]}