{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/init()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/init()"]}],"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"init","title":"init()","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNFlatTagStructureParser(im)init","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/init()","title":"init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/dotnfc\/flattagstructureparser\/init()"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"url":"\/documentation\/dotnfc\/flattagstructureparser","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","kind":"symbol","title":"FlatTagStructureParser","abstract":[{"text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse ","type":"text"},{"code":"OptionalDetails.content","type":"codeVoice"},{"type":"text","text":" of some documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FlatTagStructureParser"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser~1init()\/fragments"},{"op":"replace","value":"DOTNFlatTagStructureParser","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle"}]}]}