{"abstract":[{"type":"text","text":"Parse flat tag structure and return (tag, value) pairs as a dictionary."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/parse(value:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input data.","type":"text"}],"type":"paragraph"}],"name":"value"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Dictionary as a result.","type":"text"}]}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Throws","content":[{"inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"value"},{"type":"text","text":" has invalid structure."}],"type":"paragraph"}],"style":"note","type":"aside"}],"kind":"content"}],"sections":[],"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNFlatTagStructureParser(im)parseWithValue:error:","modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" : ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"parse(value:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"parseWithValue:error:"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/parse(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/parse(value:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/parse(value:)":{"navigatorTitle":[{"kind":"identifier","text":"parseWithValue:error:"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/parse(value:)","abstract":[{"text":"Parse flat tag structure and return (tag, value) pairs as a dictionary.","type":"text"}],"url":"\/documentation\/dotnfc\/flattagstructureparser\/parse(value:)","type":"topic","title":"parse(value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"]"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"url":"\/documentation\/dotnfc\/flattagstructureparser","role":"symbol","title":"FlatTagStructureParser","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"type":"codeVoice","code":"OptionalDetails.content"},{"type":"text","text":" of some documents."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlatTagStructureParser"}],"navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"parseWithValue:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"parseWithValue:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSNumber *,NSData *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"parseWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input data.","type":"text"}]}],"name":"value"},{"content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}],"name":"error"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Dictionary as a result."},{"type":"text","text":" On failure, this method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}},{"value":"parseWithValue:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser~1parse(value:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseWithValue:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser~1parse(value:)\/fragments","op":"replace"},{"value":"DOTNFlatTagStructureParser","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","op":"replace"},{"value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle","op":"replace"}]}]}