{"variants":[{"paths":["\/documentation\/dotfacecore\/wrappedfloat\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/wrappedfloat\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/value","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","title":"value","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(py)value","role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/value":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/value","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/wrappedfloat\/value"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"type":"topic","title":"WrappedFloat","url":"\/documentation\/dotfacecore\/wrappedfloat","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"value","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"value"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1value\/title"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1value\/fragments"},{"op":"replace","value":"DOTWrappedFloat","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/fragments"},{"op":"replace","value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}