{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/content"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","title":"content","platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails(py)content","navigatorTitle":[{"kind":"identifier","text":"content"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"]]},"abstract":[{"text":"Raw content.","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/optionaldetails\/content"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/optionaldetails\/content"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic","abstract":[{"text":"Result of NFC reading.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}]},"doc://DotNfc/documentation/DotNfc/OptionalDetails/content":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/content","abstract":[{"type":"text","text":"Raw content."}],"navigatorTitle":[{"kind":"identifier","text":"content"}],"role":"symbol","kind":"symbol","title":"content","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/optionaldetails\/content","type":"topic"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OptionalDetails"}],"title":"OptionalDetails","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","role":"symbol","title":"NfcTravelDocumentReader","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"content","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"content","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"content","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"value":"content","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1content\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1content\/fragments","value":[{"text":"content","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNOptionalDetails"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}