{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.backgroundColor, "},{"kind":"externalParam","text":"objectColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.objectColor, "},{"kind":"externalParam","text":"hintFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" = Defaults.hintFont, "},{"kind":"externalParam","text":"hintTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.hintTextColor, "},{"kind":"externalParam","text":"hintBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.hintBackgroundColor)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstyle\/init(backgroundcolor:objectcolor:hintfont:hinttextcolor:hintbackgroundcolor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstyle\/init(backgroundcolor:objectcolor:hintfont:hinttextcolor:hintbackgroundcolor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle\/init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"title":"init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle(im)initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessStyle/init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)":{"role":"symbol","title":"init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hintBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle\/init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstyle\/init(backgroundcolor:objectcolor:hintfont:hinttextcolor:hintbackgroundcolor:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.0.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessStyle":{"role":"symbol","title":"EyeGazeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the eye gaze liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessStyle"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"objectColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintFont:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"hintFont"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintTextColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"hintTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"hintBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"hintBackgroundColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle~1init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)\/title","value":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle~1init(backgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:objectColor:hintFont:hintTextColor:hintBackgroundColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle\/title","value":"DOTFEyeGazeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}