{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/intervalfloat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/intervalfloat"]}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"title":"IntervalFloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/init(min:max:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/max","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/min"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/isEqual(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error"]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTIntervalFloat) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalFloat"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat":{"kind":"symbol","type":"topic","title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalFloat"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","role":"symbol","url":"\/documentation\/dotfacelite\/intervalfloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/hash":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/hash","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/hash"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/isEqual(_:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/isEqual(_:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/isequal(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/intervalfloat\/error","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"title":"IntervalFloat.Error"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/max":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/max","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Maximal interval value."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"title":"max","navigatorTitle":[{"text":"max","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/max"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/min":{"kind":"symbol","title":"min","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"min"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/min","role":"symbol","url":"\/documentation\/dotfacelite\/intervalfloat\/min","navigatorTitle":[{"kind":"identifier","text":"min"}],"abstract":[{"type":"text","text":"Minimal interval value."}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/description":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/description","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/description"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.12.1","type":"text"}],"title":"DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/init(min:max:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/init(min:max:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(min:max:)","navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/init(min:max:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/max","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/min"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/init(min:max:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/isEqual(_:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTIntervalFloat","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1hash\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","value":"max","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1max\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1max\/fragments","op":"replace","value":[{"text":"max","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1min\/title","value":"min","op":"replace"},{"value":[{"text":"min","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1min\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1init(min:max:)\/title","value":"initWithMin:max:error:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat~1init(min:max:)\/fragments","op":"replace"}]}]}