{"abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/bundle","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDLocalization(cpy)bundle","symbolKind":"property","title":"bundle","role":"symbol","roleHeading":"Type Property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"bundle"}]},"variants":[{"paths":["\/documentation\/dotdocument\/localization\/bundle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/localization\/bundle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/Localization":{"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"title":"Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotdocument\/localization","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Localization/bundle":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/bundle","url":"\/documentation\/dotdocument\/localization\/bundle","abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"title":"bundle","navigatorTitle":[{"text":"bundle","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"bundle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"bundle"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bundle"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/title","op":"replace","value":"DOTDLocalization"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/fragments","op":"replace","value":[{"text":"DOTDLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDLocalization"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1bundle\/title","op":"replace","value":"bundle"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1bundle\/fragments","op":"replace","value":[{"kind":"identifier","text":"bundle"}]}]}]}