{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/quality"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Document quality attributes.","type":"text"}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument(py)quality","navigatorTitle":[{"text":"quality","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"quality","modules":[{"name":"DotDocument"}],"fragments":[{"text":"quality","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality","kind":"typeIdentifier","text":"DOTDDocumentQuality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"},{"kind":"text","text":" * "},{"kind":"identifier","text":"quality"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentdetectordocument\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument/quality":{"fragments":[{"kind":"identifier","text":"quality"}],"title":"quality","abstract":[{"type":"text","text":"Document quality attributes."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument\/quality","kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument\/quality","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","url":"\/documentation\/dotdocument\/documentquality","navigatorTitle":[{"kind":"identifier","text":"DocumentQuality"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentQuality"}],"kind":"symbol","type":"topic","title":"DocumentQuality","abstract":[{"type":"text","text":"Document quality."}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","title":"DOTDDocumentDetectorDocument","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDDocumentQuality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}