{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/initWithConfidence:position:type:quality:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetectorFinger(im)initWithConfidence:position:type:quality:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfidence:position:type:quality:","kind":"identifier"}],"title":"initWithConfidence:position:type:quality:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithConfidence:position:type:quality:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","text":"DOTFGDetectionPosition"},{"text":" *) ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","text":"DOTFGFingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality:"},{"kind":"text","text":"("},{"text":"DOTFGFingerQuality","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerQuality"},{"text":" *) ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/initwithconfidence:position:type:quality:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger":{"fragments":[{"text":"DOTFGFingerDetectorFinger","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger","title":"DOTFGFingerDetectorFinger","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DetectionPosition","abstract":[{"text":"Position of the finger in the image.","type":"text"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/detectionposition"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","kind":"symbol","abstract":[{"text":"Finger quality.","type":"text"}],"title":"FingerQuality","type":"topic","url":"\/documentation\/dotfingerscore\/fingerquality","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerQuality"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger/initWithConfidence:position:type:quality:":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/initWithConfidence:position:type:quality:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:position:type:quality:"}],"kind":"symbol","role":"symbol","title":"initWithConfidence:position:type:quality:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:type:quality:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/initwithconfidence:position:type:quality:"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","value":"DOTFGDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/title","value":"DOTFGFingerQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerQuality"}]},{"value":[{"text":"DOTFGFingerQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"text":"DOTFGFingerType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}