{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/type","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/type"]}],"abstract":[{"type":"text","text":"Type of the detected finger."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetectorFinger(py)type","symbolKind":"property","roleHeading":"Instance Property","title":"type","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTFGFingerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger":{"fragments":[{"text":"DOTFGFingerDetectorFinger","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger","title":"DOTFGFingerDetectorFinger","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger/type":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/type","fragments":[{"text":"type","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"type","abstract":[{"text":"Type of the detected finger.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/type"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFGFingerType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}