{"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"DotPalmCore"}],"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(py)description"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/rectangleint\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangleint\/description"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/description","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/description":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/description","url":"\/documentation\/dotpalmcore\/rectangleint\/description","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"description","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt","url":"\/documentation\/dotpalmcore\/rectangleint","type":"topic","title":"RectangleInt","kind":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1description\/fragments","op":"replace"},{"value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/title","op":"replace"},{"value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/fragments","op":"replace"},{"value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}