{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/rectangleint\/origin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangleint\/origin"]}],"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)origin","title":"origin","extendedModule":"DotCore","navigatorTitle":[{"kind":"identifier","text":"origin"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/origin"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt","url":"\/documentation\/dotpalmcore\/rectangleint","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"kind":"symbol","title":"RectangleInt","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","type":"topic","title":"PointInt","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/pointint","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/origin":{"role":"symbol","url":"\/documentation\/dotpalmcore\/rectangleint\/origin","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/origin","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"type":"topic","title":"origin","abstract":[],"navigatorTitle":[{"text":"origin","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"origin"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"origin"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"DOTPointInt"},{"kind":"text","text":" * "},{"kind":"identifier","text":"origin"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/title","op":"replace","value":"DOTRectangleInt"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/title","op":"replace","value":"DOTPointInt"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/fragments","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1origin\/title","op":"replace","value":"origin"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1origin\/fragments","op":"replace","value":[{"text":"origin","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}