{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfidence:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","text":"DOTDetectionPosition","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quality:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","kind":"typeIdentifier","text":"DOTFLFaceQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality"},{"kind":"text","text":" *) "},{"text":"quality","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfacedetectorface\/initwithconfidence:position:quality:"]}],"metadata":{"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace(im)initWithConfidence:position:quality:","title":"initWithConfidence:position:quality:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:position:quality:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:quality:"}],"modules":[{"name":"DotFaceLite"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace\/initWithConfidence:position:quality:"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","kind":"symbol","title":"DOTFLFaceDetectorFace","abstract":[{"text":"Detected face.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorFace"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"role":"symbol","type":"topic","title":"FaceQuality","url":"\/documentation\/dotfacelite\/facequality","abstract":[{"type":"text","text":"Face quality."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","url":"\/documentation\/dotfacelite\/detectionposition","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","abstract":[{"type":"text","text":"The position of the detected face in the image."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace/initWithConfidence:position:quality:":{"title":"initWithConfidence:position:quality:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfidence:position:quality:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace\/initWithConfidence:position:quality:","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface\/initwithconfidence:position:quality:","navigatorTitle":[{"text":"initWithConfidence:position:quality:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTFLFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments"},{"value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle"},{"value":"DOTDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments"},{"value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}