{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","text":"DOTFLFaceQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"},{"kind":"text","text":" * "},{"kind":"identifier","text":"quality"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfacedetectorface\/quality"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"quality","kind":"identifier"}],"title":"quality","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace(py)quality","navigatorTitle":[{"text":"quality","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Face quality attributes."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace\/quality","interfaceLanguage":"occ"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace/quality":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface\/quality","fragments":[{"text":"quality","kind":"identifier"}],"kind":"symbol","title":"quality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace\/quality","abstract":[{"text":"Face quality attributes.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"role":"symbol","type":"topic","title":"FaceQuality","url":"\/documentation\/dotfacelite\/facequality","abstract":[{"type":"text","text":"Face quality."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","kind":"symbol","title":"DOTFLFaceDetectorFace","abstract":[{"text":"Detected face.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorFace"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","op":"replace","value":"DOTFLFaceQuality"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceQuality"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}