{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceAutoCaptureDetectionValidator) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturedetectionvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturedetectionvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"title":"FaceAutoCaptureDetectionValidator","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"seeAlsoSections":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]}],"sections":[],"abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/identifier"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator/dependencyIdentifiers":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","required":true,"title":"dependencyIdentifiers","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator\/dependencyidentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/dependencyIdentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator/validate(faceAutoCaptureFrameParameters:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","required":true,"title":"validate(faceAutoCaptureFrameParameters:)","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator\/validate(faceautocaptureframeparameters:)","abstract":[{"type":"text","text":"Validate current frame parameters."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/validate(faceAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"title":"FaceAutoCaptureDetectionValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"navigatorTitle":[{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","title":"DevicePitchTooHighValidator","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate maximum pitch angle of the device."}]},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected face."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","role":"symbol","type":"topic","title":"SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"abstract":[{"type":"text","text":"Validates confidence of the detected face."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","title":"FaceNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceNotDetectedValidator","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"kind":"symbol","title":"BrightnessTooHighValidator","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","title":"FaceOutOfBoundsValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"type":"topic","navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator/identifier":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/identifier","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator\/identifier","required":true,"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"identifier"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"kind":"symbol","title":"SizeTooSmallValidator"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}]},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/identifier"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"generated":true,"title":"Validators"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1validate(faceAutoCaptureFrameParameters:)\/title","value":"validateWithFaceAutoCaptureFrameParameters:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","value":"DOTFLFaceAutoCaptureDetectionValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}]},{"value":"DOTFLDevicePitchTooHighValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title","op":"replace"},{"value":[{"text":"DOTFLDevicePitchTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments"},{"value":"DOTFLBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1identifier\/title","value":"identifier","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator~1identifier\/fragments"},{"op":"replace","value":"DOTFLSizeTooSmallValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}