{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"metadata":{"navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceOutOfBoundsValidator","title":"FaceOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init(minEdgeDistanceToImageShorterSideRatioThreshold:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/minEdgeDistanceToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/defaultMinEdgeDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"seeAlsoSections":[{"title":"Validators","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceOutOfBoundsValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator"]},{"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","title":"FaceOutOfBoundsValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"type":"topic","navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/defaultMinEdgeDistanceToImageShorterSideRatioThreshold":{"navigatorTitle":[{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/defaultMinEdgeDistanceToImageShorterSideRatioThreshold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/defaultminedgedistancetoimageshortersideratiothreshold","title":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","type":"topic","abstract":[{"type":"text","text":"Default threshold value."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected face."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","role":"symbol","type":"topic","title":"SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/dependencyidentifiers","kind":"symbol","title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"type":"topic"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"title":"FaceAutoCaptureDetectionValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/init()","kind":"symbol","title":"init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/init(minEdgeDistanceToImageShorterSideRatioThreshold:)":{"navigatorTitle":[{"text":"initWithMinEdgeDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init(minEdgeDistanceToImageShorterSideRatioThreshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/init(minedgedistancetoimageshortersideratiothreshold:)","title":"init(minEdgeDistanceToImageShorterSideRatioThreshold:)","type":"topic","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/minEdgeDistanceToImageShorterSideRatioThreshold":{"title":"minEdgeDistanceToImageShorterSideRatioThreshold","type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/minedgedistancetoimageshortersideratiothreshold","abstract":[{"type":"text","text":"Current margin to image side ratio threshold."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/minEdgeDistanceToImageShorterSideRatioThreshold","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator","type":"topic"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"abstract":[{"type":"text","text":"Validates confidence of the detected face."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","title":"FaceNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceNotDetectedValidator","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"kind":"symbol","title":"SizeTooSmallValidator"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"kind":"symbol","title":"BrightnessTooHighValidator","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/validate(faceAutoCaptureFrameParameters:)":{"title":"validate(faceAutoCaptureFrameParameters:)","type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/validate(faceautocaptureframeparameters:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/validate(faceAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}]},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/identifier":{"title":"identifier","type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/identifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFLFaceOutOfBoundsValidator","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/minEdgeDistanceToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/init(minEdgeDistanceToImageShorterSideRatioThreshold:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/validate(faceAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/defaultMinEdgeDistanceToImageShorterSideRatioThreshold"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"generated":true,"title":"Validators"}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFLFaceOutOfBoundsValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1defaultMinEdgeDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1defaultMinEdgeDistanceToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}]},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1dependencyIdentifiers\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","value":"DOTFLFaceAutoCaptureDetectionValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1init(minEdgeDistanceToImageShorterSideRatioThreshold:)\/title","op":"replace","value":"initWithMinEdgeDistanceToImageShorterSideRatioThreshold:error:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMinEdgeDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1init(minEdgeDistanceToImageShorterSideRatioThreshold:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1minEdgeDistanceToImageShorterSideRatioThreshold\/title","value":"minEdgeDistanceToImageShorterSideRatioThreshold","op":"replace"},{"value":[{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1minEdgeDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","op":"replace","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments"},{"op":"replace","value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]},{"op":"replace","value":"DOTFLSizeTooSmallValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","op":"replace","value":"DOTFLBrightnessTooHighValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1validate(faceAutoCaptureFrameParameters:)\/title","value":"validateWithFaceAutoCaptureFrameParameters:"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1identifier\/title","value":"identifier"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}