{"metadata":{"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","title":"LoggerLogLevel","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerLogLevel"}],"modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/debug","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/info","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/none","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/warning"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/description"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTLoggerLogLevel) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","interfaceLanguage":"swift"},"abstract":[{"text":"Available log levels.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel"]},{"paths":["\/documentation\/dotfacelite\/loggerloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/info":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/info","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"role":"symbol","title":"LoggerLogLevel.info","url":"\/documentation\/dotfacelite\/loggerloglevel\/info","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs informative events."}]},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/description":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/loggerloglevel\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/description"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/dotfacelite\/loggerloglevel\/rawrepresentable-implementations","kind":"article","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/dotfacelite\/loggerloglevel\/init(rawvalue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/init(rawValue:)"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/warning":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}],"kind":"symbol","title":"LoggerLogLevel.warning","url":"\/documentation\/dotfacelite\/loggerloglevel\/warning","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/warning","abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"type":"topic","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/SY":{"identifier":"doc:\/\/DotFaceLite\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"kind":"symbol","abstract":[{"type":"text","text":"Available log levels."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","title":"LoggerLogLevel","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","url":"\/documentation\/dotfacelite\/loggerloglevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/Equatable-Implementations":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/loggerloglevel\/equatable-implementations","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/error":{"title":"LoggerLogLevel.error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"url":"\/documentation\/dotfacelite\/loggerloglevel\/error","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/error","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/debug":{"type":"topic","abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"role":"symbol","title":"LoggerLogLevel.debug","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/debug","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/loggerloglevel\/debug"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/none":{"abstract":[{"type":"text","text":"Disables logging."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"LoggerLogLevel.none","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/none","url":"\/documentation\/dotfacelite\/loggerloglevel\/none","role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTLoggerLogLevel","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/debug","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/info","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/none","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/warning"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTLoggerLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1info\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1warning\/title","value":"DOTLoggerLogLevelWarning","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1warning\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError"},{"op":"replace","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1error\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1debug\/title","op":"replace","value":"DOTLoggerLogLevelDebug"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]},{"value":"DOTLoggerLogLevelNone","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1none\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1none\/fragments"}]}]}