{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","title":"init","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration(im)init","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration\/init"]}],"sections":[],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotFaceEyeGazeLivenessModuleConfiguration/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration\/init","url":"\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration\/init","title":"init","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceEyeGazeLivenessModuleConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","url":"\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"}]}]}