{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/camerapreviewscaletype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/camerapreviewscaletype"]}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fill","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fit"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/init(rawValue:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/native"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"metadata":{"role":"symbol","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"title":"CameraPreviewScaleType","symbolKind":"enum","modules":[{"name":"DotPalmCore"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]},"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraPreviewScaleType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"kind":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/fit":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"title":"CameraPreviewScaleType.fit","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fit","type":"topic","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/fit","abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"type":"text","text":" "},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}],"kind":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/native":{"type":"topic","kind":"symbol","title":"native","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/native","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVLayerVideoGravity","text":"AVLayerVideoGravity","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/native"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/RawRepresentable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/RawRepresentable-Implementations","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/description":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/description","abstract":[],"title":"description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/init(rawValue:)":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/fill":{"navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/fill","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fill","abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"type":"text","text":" "},{"type":"text","text":"This configuration may produce images with lower resolution (compared to "},{"type":"codeVoice","code":"fit"},{"type":"text","text":" case) during an auto capture process."}],"type":"topic","title":"CameraPreviewScaleType.fill","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}]},"doc://DotPalmCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/Equatable-Implementations":{"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/equatable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCameraPreviewScaleType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fill","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fit"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fit\/title","op":"replace","value":"DOTCameraPreviewScaleTypeFit"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fit\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fill\/title","op":"replace","value":"DOTCameraPreviewScaleTypeFill"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fill\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]}]}]}