{"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"title":"Libraries","symbolKind":"class","modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","navigatorTitle":[{"text":"Libraries","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/libraries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/libraries"]}],"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/document","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/face","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/faceLite","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/nfc","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/palm"]}],"abstract":[{"text":"Container for library configurations.","type":"text"}],"kind":"symbol","references":{"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/palm":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"title":"palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/palm","type":"topic","url":"\/documentation\/dotpalmcore\/libraries\/palm","kind":"symbol","abstract":[{"type":"text","text":"Palm library configuration."}],"navigatorTitle":[{"text":"palm","kind":"identifier"}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"title":"Libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"url":"\/documentation\/dotpalmcore\/libraries","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/nfc":{"navigatorTitle":[{"text":"nfc","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/libraries\/nfc","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/nfc","abstract":[{"type":"text","text":"NFC library configuration."}],"type":"topic","title":"nfc","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/init(document:face:faceLite:nfc:palm:)":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:)","abstract":[],"title":"init(document:face:faceLite:nfc:palm:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/document":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/libraries\/document","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/document","title":"document","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"document","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/face":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/libraries\/face","abstract":[{"type":"text","text":"Face library configuration."}],"title":"face","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/face","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"face"}]},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/faceLite":{"navigatorTitle":[{"kind":"identifier","text":"faceLite"}],"url":"\/documentation\/dotpalmcore\/libraries\/facelite","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/faceLite","abstract":[{"type":"text","text":"Face Lite library configuration."}],"type":"topic","title":"faceLite","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?"}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"Libraries","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/document","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/face","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/faceLite","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/nfc","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/palm"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:)"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1palm\/title","op":"replace","value":"palm"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1palm\/fragments","op":"replace","value":[{"kind":"identifier","text":"palm"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title","op":"replace","value":"Libraries"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle","op":"replace"},{"value":"nfc","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1nfc\/title","op":"replace"},{"value":[{"text":"nfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1nfc\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title","op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments","op":"replace"},{"value":"document","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1document\/title","op":"replace"},{"value":[{"kind":"identifier","text":"document"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1document\/fragments","op":"replace"},{"value":"face","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1face\/title","op":"replace"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1face\/fragments","op":"replace"},{"value":"faceLite","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1faceLite\/title","op":"replace"},{"value":[{"kind":"identifier","text":"faceLite"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1faceLite\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}