{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgraRawImage:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}]}],"name":"bgraRawImage"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" instance."}]}]}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"title":"create(bgraRawImage:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgraRawImage:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(bgrarawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(bgrarawimage:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.17.0","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"type":"topic","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"title":"CGImageFactory","type":"topic","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/cgimagefactory","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory/create(bgraRawImage:)":{"url":"\/documentation\/dotfacecore\/cgimagefactory\/create(bgrarawimage:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgraRawImage:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"kind":"symbol","type":"topic","title":"create(bgraRawImage:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"text":" *) ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"value":"createWithBgraRawImage:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgraRawImage:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:"}],"op":"replace"}]}]}