{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(bgrrawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(bgrrawimage:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgrRawImage","content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" instance."}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory"]]},"metadata":{"navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgrRawImage:","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","title":"create(bgrRawImage:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgrRawImage:)"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"title":"CGImageFactory","type":"topic","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/cgimagefactory","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory/create(bgrRawImage:)":{"url":"\/documentation\/dotfacecore\/cgimagefactory\/create(bgrrawimage:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgrRawImage:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"create(bgrRawImage:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.17.0","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","kind":"symbol","type":"topic","title":"BgrRawImage","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createWithBgrRawImage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier","text":"CGImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","text":"DOTBgrRawImage"},{"kind":"text","text":" *) "},{"text":"bgrRawImage","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgrRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}]},{"value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}