{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"image","roleHeading":"Instance Property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerPhotoSample(py)image","role":"symbol","fragments":[{"text":"image","kind":"identifier"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"property"},"abstract":[{"text":"Sample image.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample\/image","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerPhotoSample/image":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample\/image","abstract":[{"type":"text","text":"Sample image."}],"role":"symbol","fragments":[{"text":"image","kind":"identifier"}],"title":"image","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample\/image"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerPhotoSample":{"kind":"symbol","title":"DOTFGFingersAutoCaptureControllerPhotoSample","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample","fragments":[{"text":"DOTFGFingersAutoCaptureControllerPhotoSample","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"type":"text","text":".captureDepth"},{"type":"text","text":" event during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}]}]}