{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(bgrRawImage:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"text":" format as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with ","type":"text"},{"code":".rawBgra","type":"codeVoice"},{"text":" format.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"bgrRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with a ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"text":" format. Terminates if the passed image is not in the correct format.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"title":"createBgraRawImage(bgrRawImage:)","externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithBgrRawImage:","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(bgrrawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(bgrrawimage:)"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageFactory":{"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imagefactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"title":"ImageFactory","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"url":"\/documentation\/dotdocument\/image","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"title":"Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgraRawImage(bgrRawImage:)":{"url":"\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(bgrrawimage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(bgrRawImage:)","title":"createBgraRawImage(bgrRawImage:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createBgraRawImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createBgraRawImageWithBgrRawImage:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageFactory","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/title"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/fragments"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"},{"op":"replace","value":"createBgraRawImageWithBgrRawImage:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments"}]}]}