{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection"]}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"}],"title":"detection","role":"symbol","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"type":"topic","title":"DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"title":"detection","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class":{"kind":"symbol","abstract":[{"text":"Palm library module configuration.","type":"text"}],"title":"DotPalmLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"type":"topic","title":"DotPalmDetectionModuleConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]}]}]}