{"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"roleHeading":"Class","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","title":"MachineReadableZone","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMachineReadableZone) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/machinereadablezone"]}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td1:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td2:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td3:)"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/lines","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td1","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td2","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td3"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/isEqual(_:)"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output","generated":true}],"references":{"doc://DotDocument/documentation/DotDocument/MrzDate":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzdate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"title":"MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}]},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"type":"topic","title":"MrzElement","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/description":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/description","title":"description","url":"\/documentation\/dotdocument\/machinereadablezone\/description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/lines":{"kind":"symbol","type":"topic","title":"lines","url":"\/documentation\/dotdocument\/machinereadablezone\/lines","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/lines","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"lines","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"MRZ lines."}],"navigatorTitle":[{"text":"lines","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}]},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"title":"MrzStringPosition","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"type":"topic","title":"Td2MachineReadableZone","kind":"symbol"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/td2":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Parsed MRZ of TD2."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","text":"Td2MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td2","title":"td2","url":"\/documentation\/dotdocument\/machinereadablezone\/td2","type":"topic","navigatorTitle":[{"kind":"identifier","text":"td2"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/isEqual(_:)":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/isEqual(_:)","url":"\/documentation\/dotdocument\/machinereadablezone\/isequal(_:)","title":"isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"title":"MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/td3":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Parsed MRZ of TD3."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"td3"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td3","title":"td3","url":"\/documentation\/dotdocument\/machinereadablezone\/td3","type":"topic","navigatorTitle":[{"kind":"identifier","text":"td3"}]},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","role":"symbol","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"title":"Td1MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/td1":{"navigatorTitle":[{"text":"td1","kind":"identifier"}],"url":"\/documentation\/dotdocument\/machinereadablezone\/td1","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td1","abstract":[{"type":"text","text":"Parsed MRZ of TD1."}],"title":"td1","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"td1","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/init(lines:td3:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td3:"}],"url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td3:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td3:)","abstract":[],"title":"init(lines:td3:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"td3","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"title":"MrzNameElement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/init(lines:td1:)":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLines:td1:"}],"title":"init(lines:td1:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td1:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td1"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","text":"Td1MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td1:)"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/init(lines:td2:)":{"navigatorTitle":[{"text":"initWithLines:td2:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td2:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td2:)","abstract":[],"title":"init(lines:td2:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","text":"Td2MachineReadableZone","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}]},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotdocument\/machinereadablezone\/hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/hash","abstract":[],"title":"hash","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTMachineReadableZone","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/lines","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td1","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td2","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/td3"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td1:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td2:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td3:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTMachineReadableZone","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTMrzDate","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace","value":[{"text":"DOTMrzDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1lines\/title","op":"replace","value":"lines"},{"value":[{"kind":"identifier","text":"lines"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1lines\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace","value":"DOTTd2MachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td2\/title","value":"td2"},{"op":"replace","value":[{"text":"td2","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td2\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1isEqual(_:)\/title","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1isEqual(_:)\/fragments"},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td3\/title","op":"replace","value":"td3"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td3\/fragments","value":[{"text":"td3","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone","op":"replace"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td1\/title","value":"td1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1td1\/fragments","value":[{"text":"td1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td3:)\/title","value":"initWithLines:td3:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td3:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLines:td3:","kind":"identifier"}],"op":"replace"},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace"},{"op":"replace","value":"initWithLines:td1:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td1:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td1:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td1:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td2:)\/title","value":"initWithLines:td2:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLines:td2:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td2:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}