{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"symbolKind":"class","title":"FaceAutoCaptureQualityAttributeThresholds.Builder","roleHeading":"Class","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/init()"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/build()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/maxDevicePitchAngle(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder/sizeInterval(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)","title":"sizeInterval(_:)","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder\/sizeinterval(_:)","type":"topic"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder/maxDevicePitchAngle(_:)":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder\/maxdevicepitchangle(_:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/maxDevicePitchAngle(_:)","title":"maxDevicePitchAngle(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"type":"topic","abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder/minConfidence(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)","title":"minConfidence(_:)","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder\/minconfidence(_:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder/build()":{"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder\/build()","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/build()","abstract":[],"title":"build()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder","title":"FaceAutoCaptureQualityAttributeThresholds.Builder","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder/init()":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder\/init()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/init()","title":"init()","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFLFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}