{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceAspects"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","text":"FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","kind":"typeIdentifier","text":"FaceQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveLivenessFaceAttribute"},{"text":": ","kind":"text"},{"text":"FaceAttribute","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?, ","kind":"text"},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore0B8DetectorC0B0C10confidence8position11faceAspects0G7Quality015passiveLivenessB9Attribute22fullFrontalBgrRawImage8templateAESd_AA17DetectionPositionCAA0bH0CAA0bI0CAA0bL0CSgAA0opQ0CSgAA8TemplateCSgtcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"faceAspects","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier","text":"FaceAspects"},{"kind":"text","text":", "},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"passiveLivenessFaceAttribute"},{"kind":"text","text":": "},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":"?)","kind":"text"}],"title":"init(confidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","role":"symbol","symbolKind":"init","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:faceaspects:facequality:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:)"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition":{"title":"DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"url":"\/documentation\/dotfacecore\/detectionposition","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector/Face/init(confidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceAspects","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","text":"FaceAspects"},{"text":", ","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveLivenessFaceAttribute"},{"kind":"text","text":": "},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":"?, "},{"text":"template","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","title":"init(confidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","url":"\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:faceaspects:facequality:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:)","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector/Face":{"title":"FaceDetector.Face","abstract":[{"type":"text","text":"Detected face in the image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/faceaspects","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"type":"topic","title":"FaceAspects"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"role":"symbol","abstract":[{"type":"text","text":"Face template."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"title":"Template","url":"\/documentation\/dotfacecore\/template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacecore\/facequality","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","role":"symbol","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"title":"FaceQuality"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","kind":"symbol","title":"FaceAttribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTDetectionPosition","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace","value":"DOTFFaceAspects"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"value":[{"kind":"identifier","text":"DOTFTemplate"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}