{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden\/description"},"sections":[],"metadata":{"externalID":"s:11DotPalmCore11PlaceholderC6HiddenC11descriptionSSvp","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/placeholder\/hidden\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/placeholder","title":"Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Hidden":{"navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"abstract":[{"text":"Hidden placeholder.","type":"text"}],"title":"Placeholder.Hidden","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden","type":"topic","url":"\/documentation\/dotpalmcore\/placeholder\/hidden","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Hidden/description":{"abstract":[],"url":"\/documentation\/dotpalmcore\/placeholder\/hidden\/description","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","op":"replace","value":"DOTPPlaceholder"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]}]}]}