{"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/camerafacing"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"cameraFacing"}],"navigatorTitle":[{"text":"cameraFacing","kind":"identifier"}],"role":"symbol","title":"cameraFacing","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureConfiguration(py)cameraFacing","modules":[{"name":"DotFaceCore"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/cameraFacing"},"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"text":".front","type":"text"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration/cameraFacing":{"role":"symbol","fragments":[{"text":"cameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration\/cameraFacing","abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"text":".front","type":"text"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration\/camerafacing","title":"cameraFacing","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureConfiguration":{"title":"DOTFFaceAutoCaptureConfiguration","fragments":[{"text":"DOTFFaceAutoCaptureConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/dotffaceautocaptureconfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}