{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","text":"DOTPQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPQualityAttributeThresholds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"metadata":{"role":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"role":"symbol","title":"DOTPPalmAutoCaptureConfiguration","fragments":[{"text":"DOTPPalmAutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholds":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"role":"symbol","fragments":[{"kind":"identifier","text":"DOTPQualityAttributeThresholds"}],"url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholds","kind":"symbol","type":"topic","title":"DOTPQualityAttributeThresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","kind":"symbol","role":"symbol","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","url":"\/documentation\/dotpalmcore\/camerafacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.6.1","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}