{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"externalID":"c:@M@DotDocument@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceLiteEnabled","required":true,"modules":[{"name":"DotDocument"}],"symbolKind":"property","title":"isFaceLiteEnabled","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceliteenabled"]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceliteenabled","kind":"symbol","title":"isFaceLiteEnabled","required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","kind":"symbol","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"isFaceLiteEnabled"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title","op":"replace","value":"isFaceLiteEnabled"},{"op":"replace","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]}]}