{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/initialize(configuration:)"},"sections":[],"metadata":{"title":"initialize(configuration:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","kind":"typeIdentifier","text":"DotSdk"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)initializeWithConfiguration:error:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","kind":"typeIdentifier","text":"DotSdk"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}]}],"name":"configuration"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" fails to decode provided license or if any library fails to initialize."}]}],"name":"Throws","style":"note"}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdk\/initialize(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdk\/initialize(configuration:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","title":"DotSdkConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"text","text":"DotSdk"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotdocument\/dotsdkconfiguration"},"doc://DotDocument/documentation/DotDocument/DotSdk/initialize(configuration:)":{"url":"\/documentation\/dotdocument\/dotsdk\/initialize(configuration:)","type":"topic","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"title":"initialize(configuration:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/initialize(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","kind":"typeIdentifier","text":"DotSdk"},{"kind":"text","text":"."},{"preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://DotDocument/documentation/DotDocument/DotSdk":{"url":"\/documentation\/dotdocument\/dotsdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFingers","type":"codeVoice"},{"text":".","type":"text"}],"title":"DotSdk"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotSdk/Configuration":{"title":"DotSdk.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdk\/configuration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initializeWithConfiguration:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotSdkConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1initialize(configuration:)\/title","op":"replace","value":"initializeWithConfiguration:error:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1initialize(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]}]}]}