{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdk\/versionname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdk\/versionname"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/versionName"},"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"versionName","kind":"identifier"}],"title":"versionName","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotSdk(py)versionName","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"abstract":[{"type":"codeVoice","code":"DotSdk"},{"text":" version.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotSdk/versionName":{"title":"versionName","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/versionName","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" version."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/versionname","navigatorTitle":[{"kind":"identifier","text":"versionName"}]},"doc://DotDocument/documentation/DotDocument/DotSdk":{"url":"\/documentation\/dotdocument\/dotsdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFingers","type":"codeVoice"},{"text":".","type":"text"}],"title":"DotSdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"versionName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"versionName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1versionName\/title","op":"replace","value":"versionName"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1versionName\/fragments","op":"replace","value":[{"text":"versionName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}