{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeaturePoint\/init(feature:point:score:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"initWithFeature:point:score:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","text":"FaceFeature"},{"kind":"text","text":", "},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":", ","kind":"text"},{"text":"score","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":")","kind":"text"}],"title":"init(feature:point:score:)","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeaturePoint(im)initWithFeature:point:score:"},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/init(feature:point:score:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/init(feature:point:score:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeaturePoint"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceFeature","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"},{"kind":"text","text":", "},{"text":"point","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"score"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeaturePoint/init(feature:point:score:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:point:score:"}],"title":"init(feature:point:score:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeaturePoint\/init(feature:point:score:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","text":"FaceFeature","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"score"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facefeaturepoint\/init(feature:point:score:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","abstract":[{"type":"text","text":"Available face features."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeaturePoint":{"url":"\/documentation\/dotfacecore\/facefeaturepoint","title":"FaceFeaturePoint","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeaturePoint"}],"navigatorTitle":[{"text":"FaceFeaturePoint","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeaturePoint","role":"symbol","abstract":[{"type":"text","text":"Face feature point contains face feature, point and score."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithFeature:point:score:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFeature:point:score:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFeature:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"},{"text":") ","kind":"text"},{"text":"feature","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"point:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") "},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"score:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"text":") ","kind":"text"},{"text":"score","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeaturePoint~1init(feature:point:score:)\/title","value":"initWithFeature:point:score:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeature:point:score:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeaturePoint~1init(feature:point:score:)\/fragments"},{"value":"DOTFFaceFeature","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeaturePoint\/title","value":"DOTFFaceFeaturePoint"},{"value":[{"kind":"identifier","text":"DOTFFaceFeaturePoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeaturePoint\/fragments"}]}]}