{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped\/challengeItem"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped"]]},"metadata":{"externalID":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC09challengeH0ACvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","kind":"typeIdentifier"}],"title":"challengeItem","symbolKind":"property","modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped\/challengeitem"]}],"kind":"symbol","sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/Wrapped":{"role":"symbol","title":"MultiRangeLivenessChallengeItem.Wrapped","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/Wrapped/challengeItem":{"type":"topic","title":"challengeItem","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped\/challengeitem","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped\/challengeItem","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"role":"symbol","title":"MultiRangeLivenessChallengeItem","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem","abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}]}]}]}