{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwilldisappear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","role":"symbol","title":"viewWillDisappear(_:)","externalID":"c:@CM@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController(im)viewWillDisappear:","extendedModule":"DotFaceCore","symbolKind":"method","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/viewWillDisappear(_:)":{"type":"topic","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/viewwilldisappear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"viewWillDisappear:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/title","op":"replace","value":"viewWillDisappear:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"},{"value":"DOTFMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}