{"abstract":[{"text":"Palm library module configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class"]}],"metadata":{"title":"DotPalmLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","symbolKind":"class","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"]]},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotPalmLibraryConfigurationModules) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Modules","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"title":"detection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"role":"symbol","title":"init(detection:)","abstract":[],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/Modules-swift.class":{"title":"DotPalmLibraryConfiguration.Modules","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"abstract":[{"text":"Palm library module configuration.","type":"text"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]}]}]}