{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/init(sessiontoken:validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"], "},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = Defaults.minValidFramesInRowToStartCandidateSelection, "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = Defaults.candidateSelectionDurationMillis, "},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sessionToken","content":[{"type":"paragraph","inlineContent":[{"text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"type":"paragraph"}],"name":"validators"},{"name":"minValidFramesInRowToStartCandidateSelection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection."}]}]},{"name":"candidateSelectionDurationMillis","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Duration of candidate selection phase."}]}]},{"name":"detectionNormalizedRectangle","content":[{"inlineContent":[{"type":"text","text":"Normalized detection rectangle in an image."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error when validator dependencies are missing.","type":"text"}]}],"style":"note","name":"Throws"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)"},"sections":[],"metadata":{"externalID":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC12sessionToken10validators44minValidFramesInRowToStartCandidateSelection09candidateR14DurationMillis28detectionNormalizedRectangleAESSSg_SayAA0bcD18DetectionValidator_pGS2iAA0X6DoubleCSgtKcfc","title":"init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","roleHeading":"Initializer","symbolKind":"init","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"validators","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"text":"], ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"]]},"abstract":[{"text":"Create document auto capture controller configuration.","type":"text"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)":{"title":"init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/init(sessiontoken:validators:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/init(sessionToken:validators:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:)","abstract":[{"text":"Create document auto capture controller configuration.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validators","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DocumentAutoCaptureDetectionValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"text":"], ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","type":"topic","title":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"DocumentAutoCaptureController.Configuration","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"type":"topic","abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"title":"DocumentAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","navigatorTitle":[{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}