{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","title":"detection","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","modules":[{"name":"DotDocument"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class/detection":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"}],"abstract":[],"title":"detection","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/detection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"kind":"symbol","title":"DotFaceDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection module configuration."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Face library configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"title":"DotFaceLibraryConfiguration.Modules","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}