{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError"]]},"metadata":{"platforms":[{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"introducedAt":"10.10","deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"introducedAt":"9.0","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"2.0","deprecated":false,"name":"watchOS","unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:11DotDocument9MrzReaderC12ReadingErrorC","roleHeading":"Instance Property","role":"symbol","title":"failureReason","extendedModule":"Foundation"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/readingerror\/failurereason"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/failureReason","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError":{"navigatorTitle":[{"text":"ReadingError","kind":"identifier"}],"title":"MrzReader.ReadingError","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ReadingError","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","url":"\/documentation\/dotdocument\/mrzreader\/readingerror"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError/failureReason":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/dotdocument\/mrzreader\/readingerror\/failurereason","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/failureReason","kind":"symbol","type":"topic","title":"failureReason","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}