{"variants":[{"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Palm library module configuration."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotPalmLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"title":"DotPalmLibraryConfiguration.Modules","symbolKind":"class","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"],"title":"Instance Properties","anchor":"Instance-Properties"}],"references":{"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class":{"title":"DotPalmLibraryConfiguration.Modules","abstract":[{"type":"text","text":"Palm library module configuration."}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","abstract":[],"title":"init(detection:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"role":"symbol","title":"detection"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration","title":"DotPalmLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"role":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","kind":"symbol","type":"topic"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]}]}]}