{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Module configuration."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/modules-swift.property","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"title":"modules","navigatorTitle":[{"text":"modules","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(py)modules","symbolKind":"property","role":"symbol"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/modules-swift.property":{"abstract":[{"type":"text","text":"Module configuration."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/modules-swift.property","type":"topic","title":"modules","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.property"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration","title":"DotPalmLibraryConfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class":{"title":"DotPalmLibraryConfiguration.Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Palm library module configuration.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules","abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"modules"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"modules"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modules"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration~1modules-swift.property\/title","op":"replace","value":"modules"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration~1modules-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"modules"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]}]}]}