{"seeAlsoSections":[{"title":"Segments","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RandomSegmentsGenerator"}],"title":"RandomSegmentsGenerator","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFRandomSegmentsGenerator","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"RandomSegmentsGenerator"}]},"abstract":[{"type":"text","text":"Generates random segments for the eye gaze liveness process."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/generate(segmentCount:segmentDurationMillis:)"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/randomsegmentsgenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/randomsegmentsgenerator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFRandomSegmentsGenerator) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RandomSegmentsGenerator"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment":{"role":"symbol","title":"Segment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Segment"}],"abstract":[{"type":"text","text":"Eye gaze liveness segment representing the position on the screen which should be watched by the user for the specified duration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Segment"}],"url":"\/documentation\/dotfacecore\/segment"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SegmentImage":{"role":"symbol","title":"SegmentImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentImage"}],"abstract":[{"type":"text","text":"Captured image during the eye gaze liveness process which corresponds to the specific segment."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentImage"}],"url":"\/documentation\/dotfacecore\/segmentimage"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SegmentsGenerator":{"role":"symbol","title":"SegmentsGenerator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentsGenerator"}],"abstract":[{"type":"text","text":"Generates segments for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentsGenerator"}],"url":"\/documentation\/dotfacecore\/segmentsgenerator"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RandomSegmentsGenerator/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacecore\/randomsegmentsgenerator\/init"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RandomSegmentsGenerator/generate(segmentCount:segmentDurationMillis:)":{"role":"symbol","title":"generate(segmentCount:segmentDurationMillis:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segmentDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Generate random segments."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/generate(segmentCount:segmentDurationMillis:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}],"url":"\/documentation\/dotfacecore\/randomsegmentsgenerator\/generate(segmentcount:segmentdurationmillis:)"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RandomSegmentsGenerator":{"role":"symbol","title":"RandomSegmentsGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RandomSegmentsGenerator"}],"abstract":[{"type":"text","text":"Generates random segments for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RandomSegmentsGenerator"}],"url":"\/documentation\/dotfacecore\/randomsegmentsgenerator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFRandomSegmentsGenerator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFRandomSegmentsGenerator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFRandomSegmentsGenerator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/generate(segmentCount:segmentDurationMillis:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RandomSegmentsGenerator\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Segments","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFRandomSegmentsGenerator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/title","value":"DOTFSegment"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/fragments","value":[{"kind":"identifier","text":"DOTFSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentImage\/title","value":"DOTFSegmentImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentImage\/fragments","value":[{"kind":"identifier","text":"DOTFSegmentImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator\/title","value":"DOTFSegmentsGenerator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator\/fragments","value":[{"kind":"identifier","text":"DOTFSegmentsGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator~1generate(segmentCount:segmentDurationMillis:)\/title","value":"generateWithSegmentCount:segmentDurationMillis:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator~1generate(segmentCount:segmentDurationMillis:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator\/title","value":"DOTFRandomSegmentsGenerator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RandomSegmentsGenerator\/fragments","value":[{"kind":"identifier","text":"DOTFRandomSegmentsGenerator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}