{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/dependencyidentifiers"]},{"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooLargeValidator(py)dependencyIdentifiers","title":"dependencyIdentifiers","roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/dependencyIdentifiers":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":">","kind":"text"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/dependencyidentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","abstract":[{"type":"text","text":"Validate size of the detected face."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","title":"SizeTooLargeValidator","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.1"}],"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","role":"symbol","title":"FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dependencyIdentifiers"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSSet<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}