{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPQualityAttributeThresholds","kind":"typeIdentifier","text":"DOTPQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTCameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"placeholderType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPPlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType"},{"text":") ","kind":"text"},{"text":"placeholderType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:placeholdertype:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","modules":[{"name":"DotPalmCore"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholds":{"kind":"symbol","fragments":[{"text":"DOTPQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"type":"topic","role":"symbol","title":"DOTPQualityAttributeThresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","role":"symbol","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"title":"PlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the type of placeholder used in palm auto-capture UI."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/placeholdertype","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","role":"symbol","title":"DOTPPalmAutoCaptureConfiguration","fragments":[{"text":"DOTPPalmAutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:placeholdertype:","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"type":"topic","role":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotpalmcore\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","role":"symbol","title":"CameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","value":"DOTPPlaceholderType","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","op":"replace","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"}]}]}