{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/detectionposition\/rebased(parentrectangle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/detectionposition\/rebased(parentrectangle:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/rebased(parentRectangle:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@DotDocument@objc(cs)DOTDDetectionPosition(im)rebasedWithParentRectangle:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"title":"rebased(parentRectangle:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the document card in the image."}],"role":"symbol","url":"\/documentation\/dotdocument\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","title":"DocumentDetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/rebased(parentRectangle:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/rebased(parentRectangle:)","url":"\/documentation\/dotdocument\/detectionposition\/rebased(parentrectangle:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"kind":"symbol","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"abstract":[],"title":"rebased(parentRectangle:)"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","url":"\/documentation\/dotdocument\/rectangledouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DOTDDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":" *) ","kind":"text"},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"DOTDDetectionPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1rebased(parentRectangle:)\/fragments"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}