{"abstract":[{"type":"text","text":"Raw data group DG16."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"dg16PersonsToNotify","kind":"identifier"}],"title":"dg16PersonsToNotify","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg16PersonsToNotify","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg16personstonotify"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg16personstonotify"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg16PersonsToNotify"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg16PersonsToNotify":{"abstract":[{"type":"text","text":"Raw data group DG16."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg16PersonsToNotify","kind":"identifier"}],"title":"dg16PersonsToNotify","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg16personstonotify","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg16PersonsToNotify","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"type":"topic","abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","title":"Lds1eMrtdApplication","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1ElementaryFile"}],"navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","title":"Lds1ElementaryFile","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dg16PersonsToNotify","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dg16PersonsToNotify","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"dg16PersonsToNotify","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg16PersonsToNotify\/title"},{"value":[{"text":"dg16PersonsToNotify","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg16PersonsToNotify\/fragments"},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle"},{"value":"DOTNLds1ElementaryFile","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle"}]}]}