{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthupperedge"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthupperedge"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthUpperEdge","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mouthUpperEdge","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureMouthUpperEdge","title":"FaceFeature.mouthUpperEdge","symbolKind":"case","navigatorTitle":[{"text":"DOTFFaceFeatureMouthUpperEdge","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/mouthUpperEdge","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/mouthUpperEdge":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mouthUpperEdge","kind":"identifier"}],"title":"FaceFeature.mouthUpperEdge","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/mouthUpperEdge","url":"\/documentation\/dotfacecore\/facefeature\/mouthupperedge","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthUpperEdge"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Available face features."}],"url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceCore","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeatureMouthUpperEdge"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthUpperEdge"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureMouthUpperEdge","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1mouthUpperEdge\/title","value":"DOTFFaceFeatureMouthUpperEdge"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1mouthUpperEdge\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthUpperEdge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"op":"replace"}]}]}