{"sections":[],"abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"metadata":{"symbolKind":"property","title":"localizationDictionary","navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLocalization(cpy)localizationDictionary","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"role":"symbol","modules":[{"name":"DotFaceLite"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/localizationDictionary"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"text":"You also need to set ","type":"text"},{"code":"useLocalizationDictionary","type":"codeVoice"},{"text":" flag to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"style":"note"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/localization\/localizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/localization\/localizationdictionary"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Localization/localizationDictionary":{"title":"localizationDictionary","navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/localization\/localizationdictionary","kind":"symbol","abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/localizationDictionary","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"url":"\/documentation\/dotfacelite\/localization","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"role":"symbol","type":"topic","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.13.0","type":"text"}],"type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"localizationDictionary","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"localizationDictionary","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"text":"localizationDictionary","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"localizationDictionary","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1localizationDictionary\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1localizationDictionary\/fragments","value":[{"text":"localizationDictionary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title","value":"DOTFLLocalization","op":"replace"},{"value":[{"text":"DOTFLLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments"}]}]}