{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules\/barcode"},"sections":[],"metadata":{"role":"symbol","title":"barcode","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"barcode"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode","symbolKind":"property","fragments":[{"kind":"identifier","text":"barcode"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules\/barcode"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfigurationModules":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules","title":"DotDocumentLibraryConfigurationModules","type":"topic","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules","role":"symbol","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration","role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","type":"topic","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfigurationModules/barcode":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules\/barcode","title":"barcode","type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules\/barcode","role":"symbol","fragments":[{"text":"barcode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}]}]}