{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentimagequality\/init(brightness:sharpness:hotspotsscore:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentimagequality\/init(brightness:sharpness:hotspotsscore:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/init(brightness:sharpness:hotspotsScore:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithBrightness:sharpness:hotspotsScore:"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality(im)initWithBrightness:sharpness:hotspotsScore:","title":"init(brightness:sharpness:hotspotsScore:)","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"hotspotsScore","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/init(brightness:sharpness:hotspotsScore:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"hotspotsScore","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"title":"init(brightness:sharpness:hotspotsScore:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/init(brightness:sharpness:hotspotsScore:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBrightness:sharpness:hotspotsScore:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/documentimagequality\/init(brightness:sharpness:hotspotsscore:)","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentImageQuality"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentimagequality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","navigatorTitle":[{"kind":"identifier","text":"DocumentImageQuality"}],"role":"symbol","abstract":[{"type":"text","text":"Document image quality."}],"title":"DocumentImageQuality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBrightness:sharpness:hotspotsScore:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrightness:sharpness:hotspotsScore:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"hotspotsScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"hotspotsScore","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1init(brightness:sharpness:hotspotsScore:)\/title","value":"initWithBrightness:sharpness:hotspotsScore:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1init(brightness:sharpness:hotspotsScore:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:sharpness:hotspotsScore:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title","value":"DOTDDocumentImageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle","value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}