{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/transactionCountingToken","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Transaction counting token."}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk\/configuration\/transactioncountingtoken"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"transactionCountingToken","externalID":"s:7DotCore0A3SdkC13ConfigurationC24transactionCountingTokenSSSgvp","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"kind":"symbol","title":"DotSdk.Configuration","type":"topic","url":"\/documentation\/dotfacelite\/dotsdk\/configuration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration/transactionCountingToken":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/transactionCountingToken","abstract":[{"type":"text","text":"Transaction counting token."}],"kind":"symbol","title":"transactionCountingToken","type":"topic","url":"\/documentation\/dotfacelite\/dotsdk\/configuration\/transactioncountingtoken","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"DotSdk","type":"topic","url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}