{"sections":[],"abstract":[{"text":"Personal number.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalNumber","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"variants":[{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/personalnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/personalnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"personalNumber"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false}],"title":"personalNumber","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)personalNumber"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/personalNumber":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalNumber","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"personalNumber"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"personalNumber","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/personalnumber","abstract":[{"text":"Personal number.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","role":"symbol","navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AdditionalPersonalDetails","url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"personalNumber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"personalNumber"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"personalNumber"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"value":"personalNumber","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalNumber\/title"},{"value":[{"text":"personalNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalNumber\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace"}]}]}