{"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotSdkLicenseProxy(py)isEvaluation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"title":"isEvaluation","role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isEvaluation"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isevaluation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isevaluation"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isEvaluation"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isEvaluation":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isevaluation","navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"isEvaluation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEvaluation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isEvaluation"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","kind":"symbol","title":"DotSdkLicenseProxy","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isEvaluation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"isEvaluation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isEvaluation\/title","value":"isEvaluation"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isEvaluation\/fragments","value":[{"kind":"identifier","text":"isEvaluation"}],"op":"replace"},{"op":"replace","value":"DotSdkLicenseProxy","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace"}]}]}