{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/template\/version-swift.class"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFTemplateVersion) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Version","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"Version","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","externalID":"s:11DotFaceCore8TemplateC7VersionC","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Version","kind":"identifier"}],"roleHeading":"Class","title":"Template.Version","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"]]},"abstract":[{"type":"text","text":"Template compatibility version."}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/init(major:minor:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/major","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/minor"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"title":"Conforms To"}],"references":{"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/init(major:minor:)":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/init(major:minor:)","url":"\/documentation\/dotfacecore\/template\/version-swift.class\/init(major:minor:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"major"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"minor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"title":"init(major:minor:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/minor":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/template\/version-swift.class\/minor","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"kind":"symbol","title":"minor","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/minor"},"doc://com.innovatrics.dot.face.core/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Version"}],"title":"Template.Version","abstract":[{"text":"Template compatibility version.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Version"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","url":"\/documentation\/dotfacecore\/template\/version-swift.class"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TemplateMatcher","kind":"identifier"}],"title":"TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/major":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"major","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"major","abstract":[],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/template\/version-swift.class\/major","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/major"},"doc://com.innovatrics.dot.face.core/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"title":"Template","abstract":[{"type":"text","text":"Face template."}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Template"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","url":"\/documentation\/dotfacecore\/template"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title","op":"replace","value":"DOTFTemplateMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}],"op":"replace"}]}]}