{"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)sex","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"text":"sex","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"sex"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/sex"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/sex"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/sex","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"title":"Td3MachineReadableZone","kind":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/sex":{"type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"text":"sex","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/sex","url":"\/documentation\/dotnfc\/td3machinereadablezone\/sex","abstract":[],"role":"symbol","title":"sex"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"title":"MrzElement","kind":"symbol","url":"\/documentation\/dotnfc\/mrzelement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sex"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"sex","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sex"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"op":"replace"},{"value":"sex","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1sex\/title","op":"replace"},{"value":[{"kind":"identifier","text":"sex"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1sex\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}