{"sections":[],"abstract":[{"type":"text","text":"Current configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"modules":[{"name":"DotFaceCore"}],"title":"configuration","roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController(py)configuration","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.property"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/configuration-swift.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC","text":"Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/configuration-swift.property":{"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.property","type":"topic","title":"configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/configuration-swift.property","abstract":[{"text":"Current configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"title":"MultiRangeLivenessViewController.Configuration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"title":"MultiRangeLivenessViewController","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","type":"topic","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFMultiRangeLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","role":"symbol","title":"DOTFMultiRangeLivenessConfiguration","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"configuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","kind":"typeIdentifier","text":"DOTFMultiRangeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1configuration-swift.property\/title","op":"replace","value":"configuration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1configuration-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","value":"DOTFMultiRangeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}