{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/s5ErrorP","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/s8SendableP"]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/invalidChallengeSequenceCount"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/errorMessage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/internalError"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/DotSdkError-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/Error-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"MultiRangeLivenessViewController.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"roleHeading":"Enumeration","role":"symbol","extendedModule":"DotFaceCore","externalID":"s:11DotFaceCore32MultiRangeLivenessViewControllerC5ErrorO","symbolKind":"enum"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/LocalizedError-Implementations":{"kind":"article","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/localizederror-implementations","type":"topic","title":"LocalizedError Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/LocalizedError-Implementations"},"doc://DotFaceCore/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"kind":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","title":"MultiRangeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/invalidChallengeSequenceCount":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/invalidChallengeSequenceCount","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidChallengeSequenceCount","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/invalidchallengesequencecount","title":"MultiRangeLivenessViewController.Error.invalidChallengeSequenceCount"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/equatable-implementations","type":"topic"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/internalError":{"abstract":[],"kind":"symbol","title":"internalError","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/internalerror","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/internalError","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/DotFaceCore\/s5ErrorP"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkError":{"url":"\/documentation\/dotfacecore\/dotsdkerror","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"abstract":[],"title":"DotSdkError","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","role":"symbol"},"doc://DotFaceCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/DotFaceCore\/s8SendableP"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/errorMessage":{"title":"errorMessage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/errorMessage","abstract":[],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/errormessage","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/CustomStringConvertible-Implementations":{"abstract":[],"title":"CustomStringConvertible Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/customstringconvertible-implementations","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/CustomStringConvertible-Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/DotSdkError-Implementations":{"abstract":[],"title":"DotSdkError Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/dotsdkerror-implementations","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/DotSdkError-Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error":{"type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error","kind":"symbol","title":"MultiRangeLivenessViewController.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/Error-Implementations":{"abstract":[],"title":"Error Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/error-implementations","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/Error-Implementations"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFMultiRangeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"}]}]}