{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"MultiRangeLivenessViewController"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/init(configuration:style:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"title":"init(configuration:style:)","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC5StyleC","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController(im)initWithConfiguration:style:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC5StyleC","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Style-swift.class","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":" = .init())"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Configure the Multi-Range Liveness process.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"text":"Customize user interface.","type":"text"}],"type":"paragraph"}],"name":"style"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessStyle":{"title":"DOTFMultiRangeLivenessStyle","kind":"symbol","abstract":[{"type":"text","text":"Customization options for the Multi-Range Liveness user interface."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessStyle","fragments":[{"text":"DOTFMultiRangeLivenessStyle","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessstyle","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Style-swift.class":{"role":"symbol","abstract":[{"type":"text","text":"Customization options for the Multi-Range Liveness user interface."}],"title":"MultiRangeLivenessViewController.Style","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/style-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Style-swift.class","navigatorTitle":[{"kind":"identifier","text":"Style"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class":{"title":"MultiRangeLivenessViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"kind":"symbol","title":"DOTFMultiRangeLivenessConfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","fragments":[{"kind":"identifier","text":"DOTFMultiRangeLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"title":"MultiRangeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/init(configuration:style:)":{"title":"init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore32MultiRangeLivenessViewControllerC5StyleC"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"MultiRangeLivenessViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/init(configuration:style:)","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/init(configuration:style:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFMultiRangeLivenessConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFMultiRangeLivenessStyle","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessStyle"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Configure the Multi-Range Liveness process."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"type":"text","text":"Customize user interface."}],"type":"paragraph"}],"name":"style"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"DOTFMultiRangeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1init(configuration:style:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1init(configuration:style:)\/fragments"}]}]}