{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/stop()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/stop()","interfaceLanguage":"swift"},"abstract":[{"text":"Stop the Multi-Range Liveness process.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController(im)stop","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"title":"stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"symbolKind":"method"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","role":"symbol","title":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/stop()":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/stop()","abstract":[{"text":"Stop the Multi-Range Liveness process.","type":"text"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/stop()","title":"stop()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"stop"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"stop","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stop"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFMultiRangeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace"},{"value":"stop","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1stop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1stop()\/fragments","op":"replace"}]}]}