{"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"seeAlsoSections":[{"generated":true,"anchor":"Face-auto-capture-process","title":"Face auto capture process","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDetectionPosition) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","title":"DetectionPosition"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/center","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/sizeToImageShorterSideRatio"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/detectionposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/detectionposition"]}],"references":{"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","navigatorTitle":[{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","title":"FaceAutoCaptureFrameParameters"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}]},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition/init(center:sizeToImageShorterSideRatio:)":{"navigatorTitle":[{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/detectionposition\/init(center:sizetoimageshortersideratio:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"center","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","type":"topic","title":"init(center:sizeToImageShorterSideRatio:)","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","type":"topic","title":"MagnifEyeLivenessViewController","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI Face Auto Capture component."}]},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition/center":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/center","abstract":[{"type":"text","text":"Center of the face in the image."}],"title":"center","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"center","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/detectionposition\/center"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","kind":"symbol","role":"symbol","title":"description","url":"\/documentation\/dotfacelite\/detectionposition\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition/sizeToImageShorterSideRatio":{"navigatorTitle":[{"text":"sizeToImageShorterSideRatio","kind":"identifier"}],"title":"sizeToImageShorterSideRatio","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/sizeToImageShorterSideRatio","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Radius of the face circle represented as a ratio to the image shorter side."}],"url":"\/documentation\/dotfacelite\/detectionposition\/sizetoimageshortersideratio","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/detectionposition","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","title":"DetectionPosition","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","abstract":[{"text":"The position of the detected face in the image.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"title":"FaceAutoCaptureResult","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection","abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureDetection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTDetectionPosition"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/center","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/sizeToImageShorterSideRatio"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Face-auto-capture-process","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],"title":"Face auto capture process","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDetectionPosition"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","op":"replace","value":"DOTFLFaceAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace","value":"DOTFLFaceAutoCaptureController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/title","op":"replace","value":"initWithCenter:sizeToImageShorterSideRatio:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1center\/title","op":"replace","value":"center"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1center\/fragments","op":"replace","value":[{"text":"center","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1sizeToImageShorterSideRatio\/title","op":"replace","value":"sizeToImageShorterSideRatio"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1sizeToImageShorterSideRatio\/fragments","op":"replace","value":[{"text":"sizeToImageShorterSideRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","op":"replace","value":"DOTDetectionPosition"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/navigatorTitle","op":"replace","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","op":"replace","value":"DOTFLFaceAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace","value":"DOTFLFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]}]}]}