{"abstract":[{"type":"text","text":"Face quality."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/init(imageQuality:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/imageQuality"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/isEqual(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLFaceQuality) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/facequality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/facequality"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"kind":"symbol","metadata":{"roleHeading":"Class","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","role":"symbol","symbolKind":"class","title":"FaceQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}]},"references":{"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"isEqual(_:)","url":"\/documentation\/dotfacelite\/facequality\/isequal(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/isEqual(_:)"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face quality."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacelite\/facequality","title":"FaceQuality"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"description","url":"\/documentation\/dotfacelite\/facequality\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/description"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/imageQuality":{"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Image quality."}],"type":"topic","title":"imageQuality","url":"\/documentation\/dotfacelite\/facequality\/imagequality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/imageQuality"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/hash":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","abstract":[],"title":"hash","url":"\/documentation\/dotfacelite\/facequality\/hash","kind":"symbol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/init(imageQuality:)":{"navigatorTitle":[{"text":"initWithImageQuality:","kind":"identifier"}],"title":"init(imageQuality:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/init(imageQuality:)","abstract":[],"url":"\/documentation\/dotfacelite\/facequality\/init(imagequality:)"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFLFaceQuality"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceQuality"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/imageQuality"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/init(imageQuality:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLFaceQuality","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","op":"replace","value":"DOTFLFaceQuality"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","op":"replace","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceQuality"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1imageQuality\/title","op":"replace","value":"imageQuality"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1imageQuality\/fragments","op":"replace","value":[{"text":"imageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1init(imageQuality:)\/title","op":"replace","value":"initWithImageQuality:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1init(imageQuality:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}