{"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"roleHeading":"Class","title":"FaceAutoCaptureUiState","role":"symbol","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLFaceAutoCaptureUiState) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running"],"title":"Classes","generated":true,"anchor":"Classes"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"references":{"doc://DotFaceLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"navigatorTitle":[{"kind":"identifier","text":"Running"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running","kind":"symbol","abstract":[{"text":"Running state.","type":"text"}],"title":"FaceAutoCaptureUiState.Running"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateInitializing":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateinitializing","type":"topic","role":"symbol","fragments":[{"text":"DOTFLFaceAutoCaptureUiStateInitializing","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Initializing state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active right after the component is created for a short period of time.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateInitializing","title":"DOTFLFaceAutoCaptureUiStateInitializing"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiState/init":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistate\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiState\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","role":"symbol"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning":{"abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiStateRunning"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning","kind":"symbol","title":"DOTFLFaceAutoCaptureUiStateRunning","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning","role":"symbol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateIdle":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle","fragments":[{"text":"DOTFLFaceAutoCaptureUiStateIdle","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle","abstract":[{"text":"Idle state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active either:","type":"text"}],"role":"symbol","title":"DOTFLFaceAutoCaptureUiStateIdle"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"abstract":[{"text":"Initializing state.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Initializing","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing","title":"FaceAutoCaptureUiState.Initializing"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Idle":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/idle","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"title":"FaceAutoCaptureUiState.Idle","abstract":[{"type":"text","text":"Idle state."}],"navigatorTitle":[{"text":"Idle","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacelite\/faceautocaptureuistate","role":"symbol","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFLFaceAutoCaptureUiState"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiState\/init"],"title":"Instance Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateInitializing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning"],"title":"Inherited By"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","op":"replace","value":"DOTFLFaceAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]}]}]}