{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/backgrounduniformity"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"backgroundUniformity"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"backgroundUniformity"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules":{"type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules/backgroundUniformity":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/backgrounduniformity","fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","title":"backgroundUniformity","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceBackgroundUniformityModuleConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Face background uniformity module."}],"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfacebackgrounduniformitymoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}