{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endorsementsOrObservations","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/endorsementsorobservations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/endorsementsorobservations"]}],"metadata":{"title":"endorsementsOrObservations","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"endorsementsOrObservations","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(py)endorsementsOrObservations","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"endorsementsOrObservations"}],"modules":[{"name":"DotNfc"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/endorsementsOrObservations","interfaceLanguage":"swift"},"abstract":[{"text":"Endorsements or observations.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.7.1"}],"title":"DotNfc","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"title":"AdditionalDocumentDetails","abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/endorsementsOrObservations":{"title":"endorsementsOrObservations","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endorsementsOrObservations"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"endorsementsOrObservations","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/endorsementsorobservations","kind":"symbol","type":"topic","abstract":[{"text":"Endorsements or observations.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/endorsementsOrObservations"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"endorsementsOrObservations","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"endorsementsOrObservations"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"endorsementsOrObservations"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","op":"replace","value":"DOTNAdditionalDocumentDetails"},{"value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","op":"replace"},{"op":"replace","value":"endorsementsOrObservations","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1endorsementsOrObservations\/title"},{"value":[{"kind":"identifier","text":"endorsementsOrObservations"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1endorsementsOrObservations\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"}]}]}