{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"personalizationDeviceSerialNumber"}],"title":"personalizationDeviceSerialNumber","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(py)personalizationDeviceSerialNumber","role":"symbol","platforms":[{"beta":false,"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false}]},"abstract":[{"text":"Serial number of personalization device.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalizationDeviceSerialNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/personalizationdeviceserialnumber"]},{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/personalizationdeviceserialnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationDeviceSerialNumber"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/personalizationDeviceSerialNumber":{"title":"personalizationDeviceSerialNumber","role":"symbol","abstract":[{"type":"text","text":"Serial number of personalization device."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"personalizationDeviceSerialNumber","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/personalizationdeviceserialnumber","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationDeviceSerialNumber","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","title":"AdditionalDocumentDetails","url":"\/documentation\/dotnfc\/additionaldocumentdetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"personalizationDeviceSerialNumber"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"personalizationDeviceSerialNumber","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":"personalizationDeviceSerialNumber","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationDeviceSerialNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationDeviceSerialNumber\/fragments","value":[{"text":"personalizationDeviceSerialNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","op":"replace","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]}]}]}