{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"taxOrExitRequirements","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/taxOrExitRequirements","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/taxorexitrequirements"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/taxorexitrequirements"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Tax or exit requirements."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(py)taxOrExitRequirements","title":"taxOrExitRequirements","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"taxOrExitRequirements","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"taxOrExitRequirements"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","role":"symbol","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails","title":"AdditionalDocumentDetails","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/taxOrExitRequirements":{"title":"taxOrExitRequirements","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxOrExitRequirements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/taxOrExitRequirements","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/taxorexitrequirements","abstract":[{"text":"Tax or exit requirements.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"taxOrExitRequirements"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"taxOrExitRequirements"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"taxOrExitRequirements"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"taxOrExitRequirements","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","op":"replace","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments"},{"op":"replace","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle"},{"op":"replace","value":"taxOrExitRequirements","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1taxOrExitRequirements\/title"},{"op":"replace","value":[{"text":"taxOrExitRequirements","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1taxOrExitRequirements\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}