{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/hasallchecksumsvalid"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasAllChecksumsValid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone\/hasAllChecksumsValid","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasAllChecksumsValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"extendedModule":"DotDocument","modules":[{"name":"DotDocument"}],"title":"hasAllChecksumsValid","externalID":"s:11DotDocument22Td3MachineReadableZoneC20hasAllChecksumsValidSbvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"sections":[],"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone/hasAllChecksumsValid":{"kind":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone\/hasallchecksumsvalid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasAllChecksumsValid","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone\/hasAllChecksumsValid","type":"topic","abstract":[],"title":"hasAllChecksumsValid","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"kind":"symbol","title":"MrzReader","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"kind":"symbol","role":"symbol","title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","type":"topic","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}