{"abstract":[{"text":"Default threshold value.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/defaultMinEdgeDistanceToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/defaultminedgedistancetoimageshortersideratiothreshold"]},{"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/defaultminedgedistancetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceOutOfBoundsValidator(cpy)defaultMinEdgeDistanceToImageShorterSideRatioThreshold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","kind":"symbol","abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"title":"FaceOutOfBoundsValidator","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/defaultMinEdgeDistanceToImageShorterSideRatioThreshold":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/defaultminedgedistancetoimageshortersideratiothreshold","kind":"symbol","abstract":[{"type":"text","text":"Default threshold value."}],"navigatorTitle":[{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"title":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/defaultMinEdgeDistanceToImageShorterSideRatioThreshold"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1defaultMinEdgeDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1defaultMinEdgeDistanceToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinEdgeDistanceToImageShorterSideRatioThreshold"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"}]}]}