{"metadata":{"title":"DotPalmModuleId.detection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotPalmCore@E@DotPalmModuleId@DotPalmModuleIdDetection"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmmoduleid\/detection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmmoduleid\/detection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/detection","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/detection":{"type":"topic","title":"DotPalmModuleId.detection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/detection","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/detection","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"title":"DotPalmModuleId","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotPalmModuleIdDetection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DotPalmModuleIdDetection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId~1detection\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId~1detection\/fragments","op":"replace","value":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","op":"replace","value":"DotPalmModuleId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace"}]}]}