{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class"},{"kind":"text","text":" = .init())"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/init(modules:)"]}],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)initWithModules:","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"title":"init(modules:)"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"kind":"symbol","role":"symbol","title":"DotDocumentLibraryConfiguration","type":"topic","abstract":[{"text":"Document library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class":{"kind":"symbol","role":"symbol","title":"DotDocumentLibraryConfiguration.Modules","abstract":[{"type":"text","text":"Document library module configuration."}],"type":"topic","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/init(modules:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/init(modules:)","abstract":[],"type":"topic","title":"init(modules:)","role":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/init(modules:)","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfigurationModules":{"kind":"symbol","role":"symbol","title":"DotDocumentLibraryConfigurationModules","abstract":[{"type":"text","text":"Document library module configuration."}],"type":"topic","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithModules:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules","text":"DotDocumentLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}