{"metadata":{"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detection17expressionNeutral20backgroundUniformity15eyeGazeLiveness07passiveN012verificationAeA0ac15DetectionModuleE0C_AA0ac10ExpressionirE0CSgAA0ac10BackgroundkrE0CSgAA0ac3EyemnrE0CSgAA0ac7PassivenrE0CSgAA0ac12VerificationrE0CSgtcfc","modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}],"symbolKind":"init","title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"type":"text","text":"Face background uniformity module."}],"title":"DotFaceBackgroundUniformityModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotfacelite\/dotfacebackgrounduniformitymoduleconfiguration","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"title":"DotFaceLibraryConfiguration.Modules","type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"type":"topic","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face library configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceEyeGazeLivenessModuleConfiguration":{"type":"topic","title":"DotFaceEyeGazeLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration","url":"\/documentation\/dotfacelite\/dotfaceeyegazelivenessmoduleconfiguration","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"title":"DotFacePassiveLivenessModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Face passive liveness module.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceExpressionNeutralModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"abstract":[{"type":"text","text":"Face expression neutral module."}],"title":"DotFaceExpressionNeutralModuleConfiguration","type":"topic","url":"\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","abstract":[{"type":"text","text":"Face verification module."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"title":"DotFaceVerificationModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}],"title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceExpressionNeutralModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}