{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerImageQuality","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerquality\/init(imagequality:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerquality\/init(imagequality:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality"]]},"kind":"symbol","metadata":{"roleHeading":"Initializer","title":"init(imageQuality:)","symbolKind":"init","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerQuality(im)initWithImageQuality:","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/init(imageQuality:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerImageQuality","kind":"identifier"}],"title":"FingerImageQuality","navigatorTitle":[{"text":"FingerImageQuality","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerimagequality","kind":"symbol","abstract":[{"type":"text","text":"Image quality attributes for finger detection."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality":{"title":"FingerQuality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerQuality"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}],"abstract":[{"text":"Finger quality.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingerquality","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/init(imageQuality:)":{"title":"init(imageQuality:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality","text":"FingerImageQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithImageQuality:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/fingerquality\/init(imagequality:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/init(imageQuality:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImageQuality:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingerImageQuality","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality"},{"text":" *) ","kind":"text"},{"text":"imageQuality","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/title","value":"DOTFGFingerImageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerImageQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerImageQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/title","value":"DOTFGFingerQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1init(imageQuality:)\/title","value":"initWithImageQuality:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1init(imageQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:"}]}]}]}