{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomLeft"},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomleft"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomleft"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner@DOTFEyeGazeLivenessCornerBottomLeft","roleHeading":"Case","title":"EyeGazeLivenessCorner.bottomLeft","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerBottomLeft"}],"symbolKind":"case","role":"symbol","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"abstract":[{"type":"text","text":"Eye gaze liveness corner."}],"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","kind":"symbol","type":"topic","title":"EyeGazeLivenessCorner"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/bottomLeft":{"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomleft","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerBottomLeft"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"}],"type":"topic","kind":"symbol","title":"EyeGazeLivenessCorner.bottomLeft"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFEyeGazeLivenessCornerBottomLeft","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerBottomLeft"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFEyeGazeLivenessCornerBottomLeft","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFEyeGazeLivenessCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCorner"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/navigatorTitle","op":"replace","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomLeft\/title","value":"DOTFEyeGazeLivenessCornerBottomLeft"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomLeft\/fragments","value":[{"text":"DOTFEyeGazeLivenessCornerBottomLeft","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}