{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomright"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner@DOTFEyeGazeLivenessCornerBottomRight","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"EyeGazeLivenessCorner.bottomRight"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomRight"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"abstract":[{"type":"text","text":"Eye gaze liveness corner."}],"kind":"symbol","title":"EyeGazeLivenessCorner","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/bottomRight":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerBottomRight"}],"title":"EyeGazeLivenessCorner.bottomRight","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomRight","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomright","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"DOTFEyeGazeLivenessCornerBottomRight","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title","value":"DOTFEyeGazeLivenessCorner","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/navigatorTitle","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomRight\/title","value":"DOTFEyeGazeLivenessCornerBottomRight","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomRight\/fragments","value":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}