{"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/init(rawValue:)"},"metadata":{"title":"init(rawValue:)","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"s:11DotFaceCore21EyeGazeLivenessCornerO8rawValueACSgSi_tcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"abstract":[{"type":"text","text":"Eye gaze liveness corner."}],"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","kind":"symbol","type":"topic","title":"EyeGazeLivenessCorner"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/init(rawValue:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title","value":"DOTFEyeGazeLivenessCorner"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCorner"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/navigatorTitle","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}]}]}]}