{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topLeft","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerTopLeft","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner@DOTFEyeGazeLivenessCornerTopLeft","title":"EyeGazeLivenessCorner.topLeft","role":"symbol","roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/topleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/topleft"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.10.0","type":"text"}],"url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","kind":"symbol","title":"EyeGazeLivenessCorner","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"abstract":[{"text":"Eye gaze liveness corner.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/topLeft":{"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/topleft","abstract":[],"navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerTopLeft","kind":"identifier"}],"title":"EyeGazeLivenessCorner.topLeft","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topLeft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTFEyeGazeLivenessCornerTopLeft"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopLeft"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTFEyeGazeLivenessCornerTopLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFEyeGazeLivenessCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}]},{"value":"DOTFEyeGazeLivenessCornerTopLeft","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topLeft\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopLeft"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topLeft\/fragments"}]}]}