{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC","text":"Version","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/init(bytes:version:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/template\/init(bytes:version:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/template\/init(bytes:version:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"]]},"metadata":{"navigatorTitle":[{"text":"initWithBytes:version:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"text":"Version","preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(bytes:version:)","roleHeading":"Initializer","externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplate(im)initWithBytes:version:","symbolKind":"init","role":"symbol","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFTemplateVersion":{"type":"topic","url":"\/documentation\/dotfacecore\/dotftemplateversion","fragments":[{"kind":"identifier","text":"DOTFTemplateVersion"}],"title":"DOTFTemplateVersion","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateVersion","abstract":[{"type":"text","text":"Template compatibility version."}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"role":"symbol","abstract":[{"type":"text","text":"Face template."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"title":"Template","url":"\/documentation\/dotfacecore\/template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/init(bytes:version:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bytes","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Version","preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/template\/init(bytes:version:)","title":"init(bytes:version:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/init(bytes:version:)","type":"topic","navigatorTitle":[{"text":"initWithBytes:version:","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"title":"Template.Version","navigatorTitle":[{"text":"Version","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/template\/version-swift.class","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","type":"topic","abstract":[{"type":"text","text":"Template compatibility version."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Version","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"title":"TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithBytes:version:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBytes:version:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytes"},{"kind":"text","text":" "},{"text":"version:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplateVersion","text":"DOTFTemplateVersion","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateVersion"},{"text":" *) ","kind":"text"},{"text":"version","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"value":"initWithBytes:version:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template~1init(bytes:version:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template~1init(bytes:version:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:version:","kind":"identifier"}]},{"op":"replace","value":"DOTFTemplateMatcher","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}