{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum\/denied"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum\/denied"]}],"sections":[],"abstract":[{"text":"Chip is proved not genuine.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}]}]}],"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}],"roleHeading":"Case","externalID":"s:6DotNfc24ChipAuthenticationStatusC0E0O6deniedyA2EmF","modules":[{"name":"DotNfc"}],"title":"ChipAuthenticationStatus.Status.denied"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum"]]},"references":{"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum/denied":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum\/denied","abstract":[{"type":"text","text":"Chip is proved not genuine."}],"title":"ChipAuthenticationStatus.Status.denied","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum\/denied","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum","role":"symbol","kind":"symbol","abstract":[{"text":"Authentication status of the chip.","type":"text"}],"navigatorTitle":[{"text":"Status","kind":"identifier"}],"type":"topic","title":"ChipAuthenticationStatus.Status","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"role":"symbol","title":"ChipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNChipAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle"}]}]}