{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBgrRawImage) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"externalID":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","roleHeading":"Class","modules":[{"name":"DotDocument"}],"title":"BgrRawImage"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrrawimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrrawimage"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/init(bytesPointer:size:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/size"],"title":"Instance Properties"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage/bytesPointer":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytesPointer","url":"\/documentation\/dotdocument\/bgrrawimage\/bytespointer","abstract":[],"title":"bytesPointer"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage":{"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotdocument\/bgrrawimage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","title":"BgrRawImage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage/size":{"role":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","text":"ImageSize"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/size","url":"\/documentation\/dotdocument\/bgrrawimage\/size","abstract":[{"type":"text","text":"Image size."}],"title":"size"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage/init(bytesPointer:size:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/init(bytesPointer:size:)","url":"\/documentation\/dotdocument\/bgrrawimage\/init(bytespointer:size:)","abstract":[{"type":"text","text":"Do not use this, use "},{"code":"BgrRawImageFactory","type":"codeVoice"},{"text":" to create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"kind":"symbol","title":"init(bytesPointer:size:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"type":"topic"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage/bytes":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytes","url":"\/documentation\/dotdocument\/bgrrawimage\/bytes","abstract":[{"type":"text","text":"Raw image data."}],"kind":"symbol","title":"bytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytes"}],"type":"topic"},"doc://com.innovatrics.dot.document/@M@DotDocument@objc(pl)_RawImage":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/@M@DotDocument@objc(pl)_RawImage","title":"_RawImage"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTBgrRawImage","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/size"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage\/init(bytesPointer:size:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/@M@DotDocument@objc(pl)_RawImage"],"kind":"relationships","title":"Conforms To"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgrRawImage"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1bytesPointer\/title","value":"bytesPointer"},{"value":[{"kind":"identifier","text":"bytesPointer"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1bytesPointer\/fragments"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1size\/title","value":"size"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1size\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1init(bytesPointer:size:)\/title","op":"replace","value":"initWithBytesPointer:size:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1init(bytesPointer:size:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1bytes\/title","value":"bytes","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"}]}]}