{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","symbolKind":"class","title":"RectangleDouble"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/init(left:top:right:bottom:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/width"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/rebased(parentRectangle:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/fullRectangle"]},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/from(cgRect:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTRectangleDouble) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/rectangledouble"]}],"sections":[],"references":{"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/height":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/height","role":"symbol","abstract":[],"kind":"symbol","title":"height","url":"\/documentation\/dotdocument\/rectangledouble\/height","navigatorTitle":[{"kind":"identifier","text":"height"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/from(cgRect:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/from(cgRect:)","url":"\/documentation\/dotdocument\/rectangledouble\/from(cgrect:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"title":"from(cgRect:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/left":{"url":"\/documentation\/dotdocument\/rectangledouble\/left","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/left","type":"topic","title":"left","kind":"symbol","role":"symbol","abstract":[{"text":"Left edge.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"left"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/hash":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/rectangledouble\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","title":"hash","type":"topic","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/mirrored()":{"title":"mirrored()","role":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/mirrored()","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}]},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/init(left:top:right:bottom:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/init(left:top:right:bottom:)","url":"\/documentation\/dotdocument\/rectangledouble\/init(left:top:right:bottom:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"title":"init(left:top:right:bottom:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"left"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/rebased(parentRectangle:)":{"abstract":[],"title":"rebased(parentRectangle:)","url":"\/documentation\/dotdocument\/rectangledouble\/rebased(parentrectangle:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/rebased(parentRectangle:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"kind":"text","text":"("},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"type":"topic"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/width":{"abstract":[],"title":"width","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/width","kind":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"width","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/isEqual(_:)","url":"\/documentation\/dotdocument\/rectangledouble\/isequal(_:)","abstract":[],"type":"topic","title":"isEqual(_:)","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/cgRect":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"cgRect","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble\/cgrect","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/cgRect","title":"cgRect"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/description":{"url":"\/documentation\/dotdocument\/rectangledouble\/description","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/right":{"navigatorTitle":[{"kind":"identifier","text":"right"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/right","abstract":[{"text":"Right edge.","type":"text"}],"title":"right","url":"\/documentation\/dotdocument\/rectangledouble\/right","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/points":{"title":"points","abstract":[],"url":"\/documentation\/dotdocument\/rectangledouble\/points","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"points","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/points","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/fullRectangle":{"title":"fullRectangle","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/fullrectangle","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/fullRectangle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/bottom":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"type":"text","text":"Bottom edge."}],"title":"bottom","type":"topic","url":"\/documentation\/dotdocument\/rectangledouble\/bottom","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/bottom","navigatorTitle":[{"kind":"identifier","text":"bottom"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/top":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/top","abstract":[{"text":"Top edge.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"top","navigatorTitle":[{"kind":"identifier","text":"top"}],"kind":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/top"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTRectangleDouble","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/width"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/init(left:top:right:bottom:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/fullRectangle"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/from(cgRect:)"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTRectangleDouble"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1height\/title","value":"height","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1height\/fragments","value":[{"text":"height","kind":"identifier"}]},{"value":"fromCgRect:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1from(cgRect:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1from(cgRect:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]},{"value":"left","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1left\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1left\/fragments","value":[{"text":"left","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1hash\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1mirrored()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1mirrored()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"mirrored","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1init(left:top:right:bottom:)\/title","value":"initWithLeft:top:right:bottom:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1init(left:top:right:bottom:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1width\/title","value":"width"},{"value":[{"text":"width","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1width\/fragments","op":"replace"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"value":"cgRect","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1cgRect\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cgRect"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1cgRect\/fragments","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1description\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1right\/title","value":"right"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1right\/fragments","value":[{"text":"right","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1points\/title","value":"points","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1points\/fragments","op":"replace","value":[{"text":"points","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1fullRectangle\/title","op":"replace","value":"fullRectangle"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1fullRectangle\/fragments","op":"replace","value":[{"kind":"identifier","text":"fullRectangle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1bottom\/title","value":"bottom"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1bottom\/fragments","op":"replace","value":[{"text":"bottom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1top\/title","value":"top"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1top\/fragments","value":[{"text":"top","kind":"identifier"}],"op":"replace"}]}]}