{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugEvent(py)description","role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debugevent\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debugevent\/description"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/description","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DebugEvent/description":{"title":"description","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/description","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/debugevent\/description","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"title":"DebugEvent","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugEvent","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/debugevent","navigatorTitle":[{"kind":"identifier","text":"DebugEvent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"description","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1description\/fragments","op":"replace"},{"value":"DOTNDebugEvent","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","value":[{"kind":"identifier","text":"DOTNDebugEvent"}],"op":"replace"}]}]}