{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugEvent(py)timestamp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent"]]},"variants":[{"paths":["\/documentation\/dotnfc\/debugevent\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/debugevent\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/timestamp"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DebugEvent/timestamp":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","title":"timestamp","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/timestamp","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/debugevent\/timestamp"},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugEvent","kind":"identifier"}],"role":"symbol","title":"DebugEvent","abstract":[],"navigatorTitle":[{"text":"DebugEvent","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","type":"topic","url":"\/documentation\/dotnfc\/debugevent","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"timestamp","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"timestamp"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"timestamp","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1timestamp\/title","op":"replace"},{"value":[{"kind":"identifier","text":"timestamp"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1timestamp\/fragments","op":"replace"},{"value":"DOTNDebugEvent","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDebugEvent"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDebugEvent"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}