{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DotFingersLibraryConfigurationModules) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"roleHeading":"Class","title":"DotFingersLibraryConfiguration.Modules","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","role":"symbol"},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"],"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class":{"title":"DotFingersLibraryConfiguration.Modules","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Fingers library module configuration."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","abstract":[{"type":"text","text":"Fingers library configuration."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(detection:transformation:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"}],"title":"detection","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","role":"symbol"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","role":"symbol"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title","op":"replace","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]}]}]}