{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"roleHeading":"Case","modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","title":"DotLibraryId.document","symbolKind":"case"},"variants":[{"paths":["\/documentation\/dotdocument\/dotlibraryid\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibraryid\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"]]},"abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/document","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotLibraryId/document":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid\/document","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"title":"DotLibraryId.document","abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"text":" identifier.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/document"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotLibraryIdDocument","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1document\/title","value":"DotLibraryIdDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1document\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}