{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotlibraryid\/facelite"]},{"paths":["\/documentation\/dotdocument\/dotlibraryid\/facelite"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceLite"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/faceLite"},"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"modules":[{"name":"DotDocument"}],"title":"DotLibraryId.faceLite","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"symbolKind":"case"},"references":{"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"title":"DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotdocument\/dotlibraryid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotLibraryId/faceLite":{"role":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid\/facelite","type":"topic","abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"text":" identifier.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"title":"DotLibraryId.faceLite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"faceLite","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/faceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DotLibraryIdFaceLite","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1faceLite\/title","op":"replace","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1faceLite\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}]}]}]}