{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"]]},"metadata":{"navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"roleHeading":"Case","title":"DotLibraryId.fingers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFingers"},"variants":[{"paths":["\/documentation\/dotdocument\/dotlibraryid\/fingers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibraryid\/fingers"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/fingers","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"url":"\/documentation\/dotdocument\/dotlibraryid","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotLibraryId/fingers":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/fingers","role":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid\/fingers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DotLibraryId.fingers","abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotLibraryIdFingers","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/navigatorTitle"},{"op":"replace","value":"DotLibraryIdFingers","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1fingers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1fingers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}