{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"]}],"metadata":{"title":"transformation","roleHeading":"Instance Property","symbolKind":"property","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"kind":"symbol","title":"transformation","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration":{"kind":"symbol","title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Fingers library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfingerstransformationmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Fingers library module configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"title":"DotFingersLibraryConfiguration.Modules","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}]}]}