{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"title":"multiRangeLivenessViewControllerViewDidDisappear(_:)","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessLiteViewControllerViewDidDisappear:","navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerViewDidDisappear:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(multiRangeLivenessLiteViewControllerViewDidDisappear:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidDisappear(_:)"},"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"title":"MultiRangeLivenessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidDisappear:"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdiddisappear(_:)","title":"multiRangeLivenessViewControllerViewDidDisappear(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidDisappear(_:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"multiRangeLivenessLiteViewControllerViewDidDisappear:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewDidDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"DOTFLMultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFLMultiRangeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidDisappear(_:)\/title","value":"multiRangeLivenessLiteViewControllerViewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidDisappear:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}