{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"DotLibraryId.faceLite","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/faceLite"},"variants":[{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/facelite"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/facelite"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"faceLite","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"]]},"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"url":"\/documentation\/dotfacelite\/dotlibraryid","title":"DotLibraryId","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","abstract":[{"text":"version: 8.14.1","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/faceLite":{"url":"\/documentation\/dotfacelite\/dotlibraryid\/facelite","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"faceLite","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/faceLite","navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"title":"DotLibraryId.faceLite","type":"topic","abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1faceLite\/fragments"}]}]}