{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibraryid\/fingers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotlibraryid\/fingers"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/fingers"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFingers","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"title":"DotLibraryId.fingers","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/fingers":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotlibraryid\/fingers","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/fingers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"title":"DotLibraryId.fingers","abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"text":" identifier.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdFingers"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdFingers","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/navigatorTitle"},{"value":"DotLibraryIdFingers","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1fingers\/title"},{"value":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1fingers\/fragments"}]}]}