{"variants":[{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"DotLibraryId.palm","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdPalm","navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},"abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"text":" identifier.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/palm","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfacelite\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/palm":{"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibraryid\/palm","kind":"symbol","abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/palm","title":"DotLibraryId.palm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotLibraryIdPalm","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/navigatorTitle"},{"op":"replace","value":"DotLibraryIdPalm","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1palm\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1palm\/fragments"}]}]}