{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdk\/shared"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/shared"},"abstract":[{"type":"text","text":"Shared singleton instance."}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DotSdk(cpy)shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotSdk","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdk"}],"title":"shared","symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"shared","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk","text":"DotSdk","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdk"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk","url":"\/documentation\/dotnfc\/dotsdk","kind":"symbol","title":"DotSdk","role":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 8.2.0"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/shared":{"url":"\/documentation\/dotnfc\/dotsdk\/shared","abstract":[{"text":"Shared singleton instance.","type":"text"}],"type":"topic","role":"symbol","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/shared"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"shared","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shared"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk","text":"DotSdk","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdk"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1shared\/title","value":"shared"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}