{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/autocapture"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/autoCapture"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is:","type":"text"}]},{"type":"codeListing","syntax":null,"code":[".init(","    minValidSamplesInRowToStartCandidateSelection: 2,","    candidateSelectionDurationMillis: 2000",")"]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"kind":"symbol","metadata":{"title":"autoCapture","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC04autoE00aE00deG0Cvp","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"}],"role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"role":"symbol","title":"PalmAutoCaptureController.Configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the palm auto capture non-UI component."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/autoCapture":{"title":"autoCapture","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/autoCapture","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/autocapture","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","title":"AutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","role":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}