{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/s5ErrorP","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/s8SendableP","doc:\/\/DotDocument\/s16SendableMetatypeP"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"]]},"kind":"symbol","metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"roleHeading":"Enumeration","title":"IntervalDouble.Error","externalID":"s:7DotCore14IntervalDoubleC5ErrorO","role":"symbol","symbolKind":"enum","modules":[{"name":"DotDocument"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/intervaldouble\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/invalidBounds"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/errorMessage","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/internalError"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/DotSdkError-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Error-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"references":{"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DotSdkError":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","url":"\/documentation\/dotdocument\/dotsdkerror","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"title":"DotSdkError","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/DotSdkError-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/error\/dotsdkerror-implementations","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","role":"collectionGroup","abstract":[]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/internalError":{"url":"\/documentation\/dotdocument\/intervaldouble\/error\/internalerror","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"internalError","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/internalError"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/Error-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/error\/error-implementations","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Error-Implementations","title":"Error Implementations","role":"collectionGroup","abstract":[]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s8SendableP","title":"Swift.Sendable"},"doc://DotDocument/10Foundation14LocalizedErrorP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError"},"doc://DotDocument/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://DotDocument/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s5ErrorP","title":"Swift.Error"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/LocalizedError-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/error\/localizederror-implementations","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","role":"collectionGroup","abstract":[]},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"title":"IntervalDouble","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/invalidBounds":{"url":"\/documentation\/dotdocument\/intervaldouble\/error\/invalidbounds","abstract":[],"role":"symbol","title":"IntervalDouble.Error.invalidBounds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/invalidBounds","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBounds"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/errorMessage":{"abstract":[],"url":"\/documentation\/dotdocument\/intervaldouble\/error\/errormessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol","title":"errorMessage","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/errorMessage"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/Equatable-Implementations":{"type":"topic","url":"\/documentation\/dotdocument\/intervaldouble\/error\/equatable-implementations","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/intervaldouble\/error","abstract":[],"title":"IntervalDouble.Error","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}