{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC7isEqualySbypSgF","title":"isEqual(_:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotFaceCore"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped\/isEqual(_:)"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem","type":"topic","title":"MultiRangeLivenessChallengeItem","abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/Wrapped/isEqual(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isEqual(_:)","kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped\/isequal(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped\/isEqual(_:)","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/Wrapped":{"title":"MultiRangeLivenessChallengeItem.Wrapped","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Wrapped","kind":"identifier"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/wrapped","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/Wrapped","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}],"op":"replace"}]}]}