{"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Fingers library configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration"]}],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"],"anchor":"Classes","generated":true},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/init(modules:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/modules-swift.property"],"anchor":"Instance-Properties","generated":true}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"abstract":[{"text":"Fingers library configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/modules-swift.property":{"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}],"title":"modules","abstract":[{"text":"Module configuration.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/modules-swift.property"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/init(modules:)":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/init(modules:)","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/init(modules:)","kind":"symbol","title":"init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/init(modules:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1modules-swift.property\/title","value":"modules","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}