{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt"]]},"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)description","navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/pointint\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/pointint\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/PointInt/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/description","title":"description","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","url":"\/documentation\/dotfacelite\/pointint\/description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/PointInt":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"title":"PointInt","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt","url":"\/documentation\/dotfacelite\/pointint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/title","value":"DOTPointInt","op":"replace"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/fragments","op":"replace"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}