{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration","text":"EyeGazeLivenessConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle","text":"EyeGazeLivenessStyle"},{"kind":"text","text":" = .init()) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New instance of "},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the eye gaze liveness process."}]}]},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/create(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/create(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/create(configuration:style:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"}],"title":"create(configuration:style:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController(cm)createWithConfiguration:style:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:style:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessStyle":{"role":"symbol","title":"EyeGazeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the eye gaze liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessStyle"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration":{"role":"symbol","title":"EyeGazeLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/create(configuration:style:)":{"role":"symbol","title":"create(configuration:style:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/create(configuration:style:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:style:"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/create(configuration:style:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithConfiguration:style:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:style:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration","text":"DOTFEyeGazeLivenessConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"style:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle","text":"DOTFEyeGazeLivenessStyle"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle\/title","value":"DOTFEyeGazeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/title","value":"DOTFEyeGazeLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1create(configuration:style:)\/title","value":"createWithConfiguration:style:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1create(configuration:style:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:style:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}