{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/localizationDictionary","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"You also need to set "},{"code":"useLocalizationDictionary","type":"codeVoice"},{"type":"text","text":" flag to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"]]},"kind":"symbol","metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPLocalization(cpy)localizationDictionary","roleHeading":"Type Property","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"title":"localizationDictionary","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/localization\/localizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/localization\/localizationdictionary"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.7.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/Localization/localizationDictionary":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/localizationDictionary","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"title":"localizationDictionary","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"url":"\/documentation\/dotpalmcore\/localization\/localizationdictionary"},"doc://DotPalmCore/documentation/DotPalmCore/Localization":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotpalmcore\/localization","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"kind":"symbol","type":"topic","title":"Localization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"localizationDictionary","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"localizationDictionary","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1localizationDictionary\/fragments","op":"replace","value":[{"text":"localizationDictionary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/title","op":"replace","value":"DOTPLocalization"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPLocalization"}]}]}]}