{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)minValidSamplesInRowToStartCandidateSelection","title":"minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to ","type":"text"},{"type":"codeVoice","code":"1"},{"text":".","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","type":"topic","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/minValidSamplesInRowToStartCandidateSelection":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection","abstract":[{"text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to ","type":"text"},{"code":"1","type":"codeVoice"},{"text":".","type":"text"}],"title":"minValidSamplesInRowToStartCandidateSelection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minValidSamplesInRowToStartCandidateSelection","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle"},{"op":"replace","value":"minValidSamplesInRowToStartCandidateSelection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/fragments"}]}]}