{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement\/description","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzelement\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzelement\/description"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement(py)description","title":"description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzElement":{"url":"\/documentation\/dotdocument\/mrzelement","kind":"symbol","title":"MrzElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzElement/description":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement\/description","title":"description","url":"\/documentation\/dotdocument\/mrzelement\/description","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace","value":"DOTMrzElement"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments"},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}