{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement\/positions"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Positions of the element.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"positions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"positions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","title":"positions","navigatorTitle":[{"text":"positions","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement(py)positions","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotdocument\/mrzelement\/positions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzelement\/positions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzElement/positions":{"navigatorTitle":[{"text":"positions","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement\/positions","url":"\/documentation\/dotdocument\/mrzelement\/positions","title":"positions","kind":"symbol","abstract":[{"text":"Positions of the element.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"positions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"title":"MrzStringPosition","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotdocument\/mrzstringposition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzElement":{"title":"MrzElement","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"positions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"positions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DOTMrzStringPosition *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"positions","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement~1positions\/title","value":"positions","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement~1positions\/fragments","value":[{"text":"positions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/navigatorTitle","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/navigatorTitle","value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace"}]}]}