{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/isEqual(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/detectionposition\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/isequal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition(im)isEqual:","roleHeading":"Instance Method","role":"symbol","title":"isEqual(_:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","role":"symbol","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/isEqual(_:)":{"url":"\/documentation\/dotpalmcore\/detectionposition\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"isEqual(_:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Position of the palm in the image."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]}]}]}