{"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/points"],"generated":true}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/LengthOfEdgesCalculatorProtocol-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition"],["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"collectionGroup","title":"LengthOfEdgesCalculatorProtocol Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/lengthofedgescalculatorprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/lengthofedgescalculatorprotocol-implementations"]}],"sections":[],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DetectionPosition/points":{"navigatorTitle":[{"text":"points","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/points","abstract":[],"title":"points","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition\/points","type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/detectionposition","kind":"symbol","title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the palm in the image."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/points"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"value":"points","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition~1points\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition~1points\/fragments","value":[{"text":"points","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}