{"metadata":{"symbolKind":"method","title":"mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"}],"externalID":"c:@CM@DotPalmCore@objc(cs)DOTPDetectionPosition(im)mirrored","roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition"],["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/mirrored()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/detectionposition\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/mirrored()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/detectionposition","kind":"symbol","title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the palm in the image."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition","role":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DetectionPosition/mirrored()":{"kind":"symbol","role":"symbol","title":"mirrored()","type":"topic","url":"\/documentation\/dotpalmcore\/detectionposition\/mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition\/mirrored()","abstract":[]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mirrored"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DetectionPosition","text":"DOTPDetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition~1mirrored()\/title","value":"mirrored"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DetectionPosition~1mirrored()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]}]}]}