{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/localization\/bundle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/localization\/bundle"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"]]},"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/bundle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"bundle","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLocalization(cpy)bundle","roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"navigatorTitle":[{"kind":"identifier","text":"bundle"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/Localization/bundle":{"title":"bundle","type":"topic","url":"\/documentation\/dotfacelite\/localization\/bundle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/bundle","abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bundle"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotfacelite\/localization","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"type":"topic","title":"Localization","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Localization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bundle","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"bundle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":" * ","kind":"text"},{"text":"bundle","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1bundle\/title","op":"replace","value":"bundle"},{"value":[{"text":"bundle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1bundle\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title","value":"DOTFLLocalization","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLLocalization"}]}]}]}