{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" *) "},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration"]]},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol","title":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureConfiguration(im)initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotffacesimplecaptureconfiguration\/initwithsessiontoken:facesizeratiointerval:query:istorchenabled:camerafacing:camerapreviewscaletype:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Create the face simple capture configuration."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"text":"version: 8.4.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceSimpleCaptureConfiguration":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration","title":"DOTFFaceSimpleCaptureConfiguration","fragments":[{"text":"DOTFFaceSimpleCaptureConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Configuration options for the face simple capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotffacesimplecaptureconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"title":"CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"role":"symbol","title":"FaceDetectionQuery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}],"abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfacecore\/intervaldouble","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","role":"symbol","type":"topic","title":"CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceSimpleCaptureConfiguration/initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"title":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","type":"topic","role":"symbol","abstract":[{"text":"Create the face simple capture configuration.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:query:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotffacesimplecaptureconfiguration\/initwithsessiontoken:facesizeratiointerval:query:istorchenabled:camerafacing:camerapreviewscaletype:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"},{"op":"replace","value":"FaceDetectionQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"}]}]}