{"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/setdelegate(_:queue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/setdelegate(_:queue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/setDelegate(_:queue:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate","text":"NfcTravelDocumentReaderDelegate","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"? = .main)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Set delegate and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":" on which you want to recieve the delegate callbacks. ","type":"text"},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" and "},{"code":"queue","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"kind":"symbol","metadata":{"title":"setDelegate(_:queue:)","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader(im)setDelegate:queue:","role":"symbol","symbolKind":"method","platforms":[{"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"NfcTravelDocumentReaderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setDelegate:queue:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotNfc"}]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/setDelegate(_:queue:)":{"kind":"symbol","title":"setDelegate(_:queue:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"queue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/setDelegate(_:queue:)","navigatorTitle":[{"text":"setDelegate:queue:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/setdelegate(_:queue:)","abstract":[{"text":"Set delegate and ","type":"text"},{"code":"DispatchQueue","type":"codeVoice"},{"type":"text","text":" on which you want to recieve the delegate callbacks. "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to "},{"type":"codeVoice","code":"delegate"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"queue"},{"text":".","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReaderDelegate","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"title":"NfcTravelDocumentReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setDelegate:queue:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setDelegate:queue:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<DOTNNfcTravelDocumentReaderDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"kind":"text","text":" *) "},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"queue:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue","text":"NSObject<OS_dispatch_queue>"},{"kind":"text","text":" *) "},{"text":"queue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1setDelegate(_:queue:)\/title","value":"setDelegate:queue:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1setDelegate(_:queue:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setDelegate:queue:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","value":"DOTNNfcTravelDocumentReaderDelegate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments","value":[{"text":"DOTNNfcTravelDocumentReaderDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}