{"abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/precandidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/precandidateselection"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase@DOTFaceAutoCapturePhasePreCandidateSelection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}],"title":"FaceAutoCapturePhase.preCandidateSelection","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/preCandidateSelection"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"url":"\/documentation\/dotfacelite\/faceautocapturephase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","role":"symbol","title":"FaceAutoCapturePhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/preCandidateSelection":{"url":"\/documentation\/dotfacelite\/faceautocapturephase\/precandidateselection","role":"symbol","title":"FaceAutoCapturePhase.preCandidateSelection","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}],"kind":"symbol","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/preCandidateSelection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTFaceAutoCapturePhasePreCandidateSelection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title","value":"DOTFaceAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1preCandidateSelection\/title","value":"DOTFaceAutoCapturePhasePreCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1preCandidateSelection\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}