{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/rawrepresentable-implementations"]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/hashValue"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/hash(into:)"],"generated":true,"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/RawRepresentable-Implementations"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"]]},"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotFaceLite"}],"title":"RawRepresentable Implementations","role":"collectionGroup"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"role":"symbol","title":"FaceAutoCapturePhase","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","url":"\/documentation\/dotfacelite\/faceautocapturephase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/hash(into:)":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturephase\/hash(into:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/hash(into:)","kind":"symbol","title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/hashValue":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/hashValue","type":"topic","abstract":[],"title":"hashValue","url":"\/documentation\/dotfacelite\/faceautocapturephase\/hashvalue"}},"variantOverrides":[{"patch":[{"value":"DOTFaceAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}