{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topRight","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"topRight"}],"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"title":"topRight"},"variants":[{"paths":["\/documentation\/dotdocument\/corners\/topright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/corners\/topright"]}],"abstract":[{"text":"Top right corner point.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topRight","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/Corners":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"type":"topic","role":"symbol","title":"Corners","url":"\/documentation\/dotdocument\/corners","abstract":[{"type":"text","text":"Four detected corners in an image."}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.14.1"}],"url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Corners/topRight":{"role":"symbol","navigatorTitle":[{"text":"topRight","kind":"identifier"}],"abstract":[{"type":"text","text":"Top right corner point."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topRight","type":"topic","url":"\/documentation\/dotdocument\/corners\/topright","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"title":"topRight"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"topRight","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topRight"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"topRight","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","op":"replace","value":"DOTCorners"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topRight\/title","value":"topRight","op":"replace"},{"value":[{"text":"topRight","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topRight\/fragments","op":"replace"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}