{"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg16"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg16"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg16"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg16"}],"symbolKind":"case","title":"Lds1ElementaryFileId.dg16","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg16"}],"role":"symbol","externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg16","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"abstract":[{"type":"text","text":"File identifier for data group 16. Data group 16 contains person(s) to notify."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"role":"symbol","title":"Lds1ElementaryFileId","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg16":{"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg16","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg16","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16","kind":"identifier"}],"title":"Lds1ElementaryFileId.dg16","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg16","kind":"symbol","abstract":[{"type":"text","text":"File identifier for data group 16. Data group 16 contains person(s) to notify."}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTNLds1ElementaryFileIdDg16","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg16"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg16"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNLds1ElementaryFileId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"},{"value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle"},{"value":"DOTNLds1ElementaryFileIdDg16","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg16\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg16"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg16\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}