{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator(py)dependencyIdentifiers","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"title":"dependencyIdentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/dependencyIdentifiers":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"kind":"symbol","role":"symbol","title":"dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/dependencyidentifiers"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dependencyIdentifiers","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}]},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1dependencyIdentifiers\/title","op":"replace"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1dependencyIdentifiers\/fragments","op":"replace"}]}]}