{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator(im)initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:","navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = FingersOutOfBoundsValidator\n            .defaultMinCornerDistanceToImageShorterSideRatioThreshold, "},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = FingersNotDetectedValidator.defaultMinConfidenceThreshold) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:minconfidencethreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:minconfidencethreshold:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:minconfidencethreshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidenceThreshold:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minConfidenceThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)\/title","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:","kind":"identifier"}]}]}]}