{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minConfidenceThreshold","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"minConfidenceThreshold","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator(py)minConfidenceThreshold","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Minimum detection confidence threshold.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/minconfidencethreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/minconfidencethreshold"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/minConfidenceThreshold":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minConfidenceThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"minConfidenceThreshold","abstract":[{"text":"Minimum detection confidence threshold.","type":"text"}],"navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/minconfidencethreshold"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minConfidenceThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"minConfidenceThreshold","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minConfidenceThreshold\/title","value":"minConfidenceThreshold","op":"replace"},{"value":[{"kind":"identifier","text":"minConfidenceThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minConfidenceThreshold\/fragments"},{"value":"DOTFGFingersOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}