{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/description","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcode(py)description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","symbolKind":"property","title":"description","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/barcode\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcode\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Barcode/description":{"type":"topic","url":"\/documentation\/dotdocument\/barcode\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/description"},"doc://DotDocument/documentation/DotDocument/Barcode":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Result of barcode detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","title":"Barcode","url":"\/documentation\/dotdocument\/barcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","value":"DOTDBarcode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","value":[{"text":"DOTDBarcode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}