{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Barcode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"},{"text":".","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"init(bytes:detectionPosition:)","modules":[{"name":"DotDocument"}],"symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcode(im)initWithBytes:detectionPosition:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBytes:detectionPosition:"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/init(bytes:detectionPosition:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/init(bytes:detectionposition:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/barcode\/init(bytes:detectionposition:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/Barcode/init(bytes:detectionPosition:)":{"navigatorTitle":[{"text":"initWithBytes:detectionPosition:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/init(bytes:detectionPosition:)","url":"\/documentation\/dotdocument\/barcode\/init(bytes:detectionposition:)","title":"init(bytes:detectionPosition:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"Barcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Barcode":{"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","url":"\/documentation\/dotdocument\/barcode","title":"Barcode","kind":"symbol","abstract":[{"type":"text","text":"Result of barcode detection process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","url":"\/documentation\/dotdocument\/barcode\/detectionposition","title":"Barcode.DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithBytes:detectionPosition:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:detectionPosition:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBytes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionPosition:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition","kind":"typeIdentifier","text":"DOTDBarcodeDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionPosition"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithBytes:detectionPosition:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1init(bytes:detectionPosition:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:detectionPosition:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1init(bytes:detectionPosition:)\/fragments"},{"value":"DOTDBarcode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title"},{"value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments"},{"value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle"}]}]}