{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"Barcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcode(py)position","navigatorTitle":[{"text":"position","kind":"identifier"}],"title":"position","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/position","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/barcode\/position"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcode\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Position of the barcode in image.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","url":"\/documentation\/dotdocument\/barcode\/detectionposition","title":"Barcode.DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Barcode":{"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","url":"\/documentation\/dotdocument\/barcode","title":"Barcode","kind":"symbol","abstract":[{"type":"text","text":"Result of barcode detection process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Barcode/position":{"navigatorTitle":[{"text":"position","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/position","url":"\/documentation\/dotdocument\/barcode\/position","title":"position","kind":"symbol","abstract":[{"text":"Position of the barcode in image.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"Barcode","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument7BarcodeC17DetectionPositionC","text":"DetectionPosition","kind":"typeIdentifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"position"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"position","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition","kind":"typeIdentifier","text":"DOTDBarcodeDetectionPosition"},{"text":" * ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","op":"replace","value":"DOTDBarcode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1position\/title","op":"replace","value":"position"},{"op":"replace","value":[{"text":"position","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode~1position\/fragments"}]}]}