{"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier","text":"MagnifEyeLivenessViewControllerDelegate"},{"kind":"text","text":"?"}],"platforms":[],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController(py)delegate","title":"delegate","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/delegate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Set this delegate to handle the MagnifEye liveness events.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/delegate"},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/delegate":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/delegate","deprecated":true,"abstract":[{"text":"Set this delegate to handle the MagnifEye liveness events.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"title":"MagnifEyeLivenessViewController","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"deprecated":true,"abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","title":"MagnifEyeLivenessViewControllerDelegate","type":"topic","navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate","text":"id<DOTFMagnifEyeLivenessViewControllerDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFMagnifEyeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewControllerDelegate"}]}]}]}