{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator"]]},"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/init()"]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSharpnessTooLowValidator(im)init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"symbolKind":"init","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/init()":{"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/init()","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init()","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","abstract":[{"type":"text","text":"Initialize with default threshold."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"title":"SharpnessTooLowValidator","type":"topic","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","value":"DOTPSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}