{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/defaultthreshold"]},{"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/defaultThreshold","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default threshold."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"defaultThreshold","modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPSharpnessTooLowValidator(cpy)defaultThreshold"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/defaultThreshold":{"abstract":[{"type":"text","text":"Default threshold."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/defaultthreshold","title":"defaultThreshold","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/defaultThreshold","navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","title":"SharpnessTooLowValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","type":"topic","title":"PalmAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"defaultThreshold","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1defaultThreshold\/title","op":"replace","value":"defaultThreshold"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1defaultThreshold\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","value":"DOTPSharpnessTooLowValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments"},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"}]}]}