{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary\/configuration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary"]]},"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" configuration."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"configuration","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary(py)configuration","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"role":"symbol","symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary/configuration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary\/configuration","type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrary\/configuration","role":"symbol","kind":"symbol","title":"configuration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"url":"\/documentation\/dotfacecore\/dotfacelibrary","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library initialization."}],"title":"DotFaceLibrary","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"title":"DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Configuration of the "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"configuration","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"configuration"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary~1configuration\/title","op":"replace","value":"configuration"},{"value":[{"kind":"identifier","text":"configuration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary~1configuration\/fragments","op":"replace"},{"op":"replace","value":"DotFaceLibrary","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title"},{"value":[{"text":"DotFaceLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}