{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15eyeGazeLivenessAA0ac3Eyehi6ModuleE0CSgvp","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"eyeGazeLiveness","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotFaceLibraryConfiguration.Modules","role":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"title":"eyeGazeLiveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness","type":"topic","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","abstract":[{"text":"Face library configuration.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotFaceEyeGazeLivenessModuleConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"title":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"url":"\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]}]}]}