{"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"expressionNeutral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"verification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"?)","kind":"text"}],"title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","roleHeading":"Initializer","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detection17expressionNeutral20backgroundUniformity15eyeGazeLiveness07passiveN012verificationAeA0ac15DetectionModuleE0C_AA0ac10ExpressionirE0CSgAA0ac10BackgroundkrE0CSgAA0ac3EyemnrE0CSgAA0ac7PassivenrE0CSgAA0ac12VerificationrE0CSgtcfc","symbolKind":"init","modules":[{"name":"DotDocument"}]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"expressionNeutral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"verification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"abstract":[{"text":"Face library configuration.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"type":"topic","title":"DotFaceLibraryConfiguration.Modules","abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expressionNeutral","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"verification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","role":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotFacePassiveLivenessModuleConfiguration":{"abstract":[{"type":"text","text":"Face passive liveness module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"url":"\/documentation\/dotdocument\/dotfacepassivelivenessmoduleconfiguration","title":"DotFacePassiveLivenessModuleConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFacePassiveLivenessModuleConfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceVerificationModuleConfiguration":{"url":"\/documentation\/dotdocument\/dotfaceverificationmoduleconfiguration","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"title":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Face verification module.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceEyeGazeLivenessModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration","navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"title":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceExpressionNeutralModuleConfiguration":{"title":"DotFaceExpressionNeutralModuleConfiguration","abstract":[{"text":"Face expression neutral module.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfaceexpressionneutralmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration"},"doc://DotDocument/documentation/DotDocument/DotFaceBackgroundUniformityModuleConfiguration":{"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"title":"DotFaceBackgroundUniformityModuleConfiguration","type":"topic","url":"\/documentation\/dotdocument\/dotfacebackgrounduniformitymoduleconfiguration","role":"symbol","abstract":[{"type":"text","text":"Face background uniformity module."}]},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"abstract":[{"type":"text","text":"Face detection module configuration."}],"title":"DotFaceDetectionModuleConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle"},{"value":"DotFacePassiveLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"},{"value":"DotFaceVerificationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/title"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/navigatorTitle"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}