{"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(im)initWithX:y:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"title":"init(x:y:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"x"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/init(x:y:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/init(x:y:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble\/init(x:y:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/PointDouble/init(x:y:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/init(x:y:)","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"title":"init(x:y:)","url":"\/documentation\/dotnfc\/pointdouble\/init(x:y:)","abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"url":"\/documentation\/dotnfc\/pointdouble","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"type":"topic","title":"PointDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithX:y:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithX:y:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithX:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"x","kind":"internalParam"},{"kind":"text","text":" "},{"text":"y:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"text":"y","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1init(x:y:)\/title","value":"initWithX:y:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1init(x:y:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithX:y:"}],"op":"replace"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}