{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/compositecheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/compositecheckdigit"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/compositeCheckDigit","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotNfc"}],"title":"compositeCheckDigit","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)compositeCheckDigit"},"references":{"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"title":"MrzCheckDigit","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/mrzcheckdigit","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"kind":"symbol","title":"Td1MachineReadableZone","role":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/compositeCheckDigit":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/compositeCheckDigit","title":"compositeCheckDigit","url":"\/documentation\/dotnfc\/td1machinereadablezone\/compositecheckdigit","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"compositeCheckDigit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"compositeCheckDigit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","text":"DOTMrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/navigatorTitle","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1compositeCheckDigit\/title","value":"compositeCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1compositeCheckDigit\/fragments","value":[{"kind":"identifier","text":"compositeCheckDigit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}