{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfBirth"},"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)dateOfBirth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}],"title":"dateOfBirth","symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/dateOfBirth":{"navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone\/dateofbirth","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfBirth","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}],"title":"dateOfBirth","abstract":[],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"title":"Td1MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","url":"\/documentation\/dotnfc\/td1machinereadablezone","type":"topic","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"symbol","title":"MrzDateElementWithCheckDigit","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dateOfBirth","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"dateOfBirth"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfBirth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dateOfBirth"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfBirth\/fragments"},{"op":"replace","value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/navigatorTitle"},{"op":"replace","value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}