{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentNumber"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"}]}]}],"metadata":{"title":"documentNumber","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)documentNumber","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"variants":[{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/documentnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/documentnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"type":"topic","title":"MrzElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"title":"Td1MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","url":"\/documentation\/dotnfc\/td1machinereadablezone","type":"topic","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/documentNumber":{"title":"documentNumber","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentNumber","url":"\/documentation\/dotnfc\/td1machinereadablezone\/documentnumber","type":"topic","abstract":[],"navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentNumber","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"documentNumber"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/navigatorTitle"},{"op":"replace","value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/navigatorTitle","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentNumber\/title","value":"documentNumber","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"documentNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}