{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/name"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","kind":"typeIdentifier","text":"MrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/name"]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone(py)name","title":"name","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","text":"MrzNameElement","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","url":"\/documentation\/dotnfc\/mrznameelement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone/name":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone\/name","navigatorTitle":[{"kind":"identifier","text":"name"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/name","type":"topic","title":"name","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone":{"url":"\/documentation\/dotnfc\/td1machinereadablezone","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","type":"topic","title":"Td1MachineReadableZone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"name"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTMrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement"},{"kind":"text","text":" * "},{"text":"name","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1name\/title"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1name\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","op":"replace","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]}]}]}