{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/selectedFingerTypes","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/selectedfingertypes"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Selected finger types. These finger types have a valid image captured during the process."}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC19selectedFingerTypesSayAA0J4TypeO7WrappedCGvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped"},{"kind":"text","text":"]"}],"title":"selectedFingerTypes","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/selectedFingerTypes":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/selectedfingertypes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC"},{"kind":"text","text":"]"}],"title":"selectedFingerTypes","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/selectedFingerTypes","role":"symbol","abstract":[{"type":"text","text":"Selected finger types. These finger types have a valid image captured during the process."}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","title":"FingersAutoCaptureController.ProcessingResult","role":"symbol","abstract":[{"text":"The result returned from the processing of one image during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Wrapped":{"url":"\/documentation\/dotfingerscore\/fingertype\/wrapped","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped","title":"FingerType.Wrapped","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}