{"metadata":{"platforms":[{"introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(py)description","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/description"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/description"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/description":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/description","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"url":"\/documentation\/dotnfc\/additionaldocumentdetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"title":"AdditionalDocumentDetails","navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","kind":"symbol","abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails","op":"replace"},{"value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"}]}]}