{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/error\/helpanchor"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/helpAnchor"},"kind":"symbol","metadata":{"extendedModule":"Foundation","role":"symbol","roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:6DotNfc22FlatTagStructureParserC5ErrorO","title":"helpAnchor","modules":[{"relatedModules":["Foundation"],"name":"DotNfc"}],"symbolKind":"property","platforms":[{"introducedAt":"8.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"8.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"8.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"10.10","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser","navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}],"role":"symbol","abstract":[{"text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse ","type":"text"},{"type":"codeVoice","code":"OptionalDetails.content"},{"text":" of some documents.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","kind":"symbol","title":"FlatTagStructureParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlatTagStructureParser"}]},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/helpAnchor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/helpanchor","title":"helpAnchor","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/helpAnchor","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error":{"type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","kind":"symbol","title":"FlatTagStructureParser.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","value":"DOTNFlatTagStructureParser"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}